### ISSUE TITLE
It would be nice if CONTRIBUTING.md contained a link to test setup. 

### ISSUE THREAD

**Issue by budden** [marko-js/marko#1003]
### Description

CONTRIBUTING.md asks that I (a potential contributor) run tests before I make my pull request. I installed marko as a dependency of marko-express (it was installed by npm install), so it does not have necessary packages to run tests. I installed several by hand but then get tired :) Maybe it should be obvious, but I'm not an experiences node.js user, so it is not evident for me. 

### Why

I and other users could fix easy issues more easily. 

### Is this something you're interested in working on?

Maybe.

**Comment by jasonmacdonald** [comment]
Are you trying to contribute something to the core Marko project, or something around the Express starter example? If the former, you should check out the main Markojs project from Github, not through NPM as that is the distribution version, not the core project. If the change is in the marko-express start project, again, check out the GitHub project for that, not NPM. NPM is typically a packaged version of a project, exported specifically for consumption as an NPM package, not as a GIT repository. 

Hope that helps :)

**Comment by mlrawlings** [comment]
I think what you're looking for is [`npm link`](https://docs.npmjs.com/cli/link).  Here's how you would set things up with it:

**1. Clone and install `marko`**
```
cd ~/Desktop
git clone git@github.com:marko-js/marko.git
cd marko && npm i
```

**2. Clone and install `marko-express`**
```
cd ~/Desktop
git clone git@github.com:marko-js/marko.git
cd marko && npm i
```

**3. Link `marko` (this creates a global link to `marko`, it's like you had `npm i -g marko`, but it's running from your cloned directory)**
```
cd ~/Desktop/marko
npm link
```

**4. Link `marko` into `marko-express` (this creates a symlink in `marko-express/node_modules` to your cloned directory)**
```
cd ~/Desktop/marko-express
npm link marko
```

**5. You can now make changes in `~/Desktop/marko` and they will affect your copy of `marko-express`.**

This can be a good way to track down and fix an issue that you're only seeing in a specific project.  However, we'd also want to distill the source of the issue and create a minimal test case to commit to the Marko repo to prevent reintroducing the issue.

---

I'm not sure whether or not this info is something that should be in CONTRIBUTING or not.  I've been leaning towards keeping things short by only including information that is unique to Marko, so it's not intimidating or annoying to read.  But maybe linking out to something like [this article](https://medium.com/trisfera/the-magic-behind-npm-link-d94dcb3a81af) (one of the first google results for `npm link`) would be worth while.  Or maybe even linking to this issue.
