### ISSUE TITLE
Incorrect "<await>" tag behavior

### ISSUE THREAD

**Issue by slavik-m** [marko-js/marko#1004]
### Marko Version: 4.8.0

marko create project

### Details

Incorrect `<await>` tag behavior.
 `src/routes/test/index.marko`

```
$ var timeout = new Promise((resolve, reject) => {
  setTimeout(function() {
    resolve({
      name: "Frank"
    });
  }, 5000);
});

<site-layout>
  <@title>Test page</@title>
  <@content>
    <section>
      <h2>Test page</h2>
      <div>
        <await(data from timeout) client-reorder=true>
          <await-placeholder>
            <div>User: ...</div>
          </await-placeholder>
          <div>User: ${data.name}!</div>
        </await>
      </div>
    </section>
  </@content>
</site-layout>
```

### Expected Behavior

![nimbus-record-video-2018-02-26-20-27-42](https://user-images.githubusercontent.com/12348485/36690810-1e7bef80-1b3c-11e8-8e59-e9ddd446eefc.gif)

### Actual Behavior

![nimbus-record-video-2018-02-26-20-28-56](https://user-images.githubusercontent.com/12348485/36690945-7e9d2ec4-1b3c-11e8-9b44-2181bf010c9d.gif)

### Possible Fix

**Hot hack:** Add second `<await(data from Promise.resolve()) client-reorder=true />` tag.
```
...
      <div>
        <await(data from timeout) client-reorder=true>
          <await-placeholder>
            <div>User: ...</div>
          </await-placeholder>
          <div>User: ${data.name}!</div>
        </await>
        <await(data from Promise.resolve()) client-reorder=true />
      </div>
...
```

<details><summary>Additional Info</summary>

### Your Environment

* Environment name and version: **node.js 9.4**
* Operating System and version: **macOS High Sierra 10.13.2**
* IDE: **WebStorm 2017.2.2**

### Steps to Reproduce

1. marko create hello-world
2. create route test and `index.marko` (Code from details)
3. start server
4. go to test page
</details>

**Comment by fogarasyroland** [comment]
+1

**Comment by DylanPiercey** [comment]
I'm a bit confused by this, it seems like the `actual` is actually what I would expect.

With `client-reorder` as much content as possible is sent to the browser, like in the actual.
If there was a bug here I believe it is fixed.
