### ISSUE TITLE
server side rendering - can globals be after html

### ISSUE THREAD

**Issue by cameronbraid** [marko-js/marko#1005]
in src/components/taglib/body-transformer.js, the component-globals tag is added at the start of the body tag

```
    let componentGlobalsNode = context.createNodeForEl('component-globals');
    el.prependChild(componentGlobalsNode);
```

I would like to know if this can be changed to `appendChild` since these globals wouldn't be read until the init-components component is activated, which will happen after component-globals due to their placement

I have tested this on my project and it seems to work.  Just curious why it wasn't done this way ?  Is there something I am missing ?

The main reason I want this is that in some cases I am sending a fair bit of data via globals and I want the html rendered asap to the client.

**Comment by jasonmacdonald** [comment]
I'll have a look when I get a chance.

**Comment by DylanPiercey** [comment]
So in some cases `appendChild` would work, but this would actually break down if you are using streaming since the globals would not be there when the async content tries to initialize.
