### ISSUE TITLE
Dynamic component with javascript not being lasso'd properly when using include (found cause and includes suggestion for fix)

### ISSUE THREAD

**Issue by KB-xluo** [marko-js/marko#1006]
### Details

When including a component with javascript, the component loads fine using the taglib like so:
`<my-component/>`

However, if I want to dynamically load a component in my template like so:
```
template.stream({
myDynamicComponent: 'path/to/my-component'
});
...
<include(require(input.myDynamicComponent)) />
```
The browser's javascript console throws the following error:
```
Uncaught Error: Component not found: /my-site$1.0.0/src/pages/my-page/components/my-component.marko
    at load (registry-browser.js:31)
```
Looking at my html source code for the two methods, I notice that the taglib generates a file called my-component.marko-run.register with some $_mod statements and includes that as a <script> while the include does not. If I first run it with the taglib to generate that file, then replace it with the include and manually include the generated my-component.marko-run.register.js script, the browser error goes away.

### Expected Behavior

`<include(require('path/to/my-component'))>` has the same behavior as `<my-component/>`, loading properly with lasso

### Actual Behavior

Using the include tag does not properly create the `my-component.marko-run.register.js` file causing a browser error and any component javascript to not run.

### Possible Fix

add in logic to create and include as part of <lasso-body/> the `my-component.marko-run.register.js` script

<details><summary>Additional Info</summary>

### Your Environment

* Environment name and version (e.g. Chrome 39, node.js 5.4):
* Operating System and version (desktop or mobile):
* Link to your project:

### Steps to Reproduce

1. make a component with javascript
2. try to include it in a separate template
3. use lasso to package app
4. watch it fail with an error in the browser console

### Stack Trace

Uncaught Error: Component not found: /my-site$1.0.0/src/pages/my-page/components/my-component.marko
    at load (registry-browser.js:31)
    at getComponentClass (registry-browser.js:47)
    at Object.createComponent [as ___createComponent] (registry-browser.js:64)
    at Function.ComponentDef.___deserialize (ComponentDef.js:116)
    at init-components-browser.js:209
    at Array.forEach (<anonymous>)
    at Object.initServerRendered [as concat] (init-components-browser.js:208)
    at account:63
    at account:63

</details>

**Comment by KB-xluo** [comment]
Slightly unrelated, there's another script file that doesnt get picked up automatically when using <include>

`/static/my-site$1.0.0/src/pages/my-page/components/my-component.marko.js` (basically the same file as above without the `-run.register.js` suffix but i was able to get it to load by adding in the browser.json file `{"path": "./player/components/my-component.marko", "if-flag": "my-component"}` for each of the possible components that could potentially be slotted in there. If it's possible for the dynamic component to be picked up automatically instead of requiring this extra step, that would be nice too.

**Comment by mlrawlings** [comment]
@KB-xluo Marko picks up and adds the registration code for any components that it can discover statically at compile time.  When passing dynamic components, it obviously can't do this.

But components templates do include the code to register themselves when required so if the template is run, it will register itself.  You should be able to add `"run": true` to the `browser.json` entry for your component to get it to register itself.

I'm going to close this, but if you have more questions we can talk here and reopen if necessary.
