### ISSUE TITLE
...attr has strange behaviour when returning object from function

### ISSUE THREAD

**Issue by steebchen** [marko-js/marko#1008]
### Details

I have a function which returns an object with e.g. an href attribute:
```
link rel="stylesheet" ...out.global.asset('/css/style.css')
```
.asset returns `{ href: 'foo/bar' }`

### Expected Behavior

Should output:
```
<link rel="stylesheet" href="foo/bar.css">
```

### Actual Behavior

Outputs:
```
<link>
```

### Possible Fix

However, the following workaround works:
```
$ var c = out.global.asset('/css/style.css')
link rel="stylesheet" ...c
```

It results in
`<link rel="stylesheet" href="foo/bar">`

<details><summary>Additional Info</summary>

### Your Environment

* Environment name and version (e.g. Chrome 39, node.js 5.4): serverside, node v8.3.0
* Operating System and version (desktop or mobile):
* Link to your project:

### Steps to Reproduce

1. 
2. 
3. 
4.

**Comment by mlrawlings** [comment]
My best guess is this is getting picked up as an attribute argument like `<div if(true)>` or `<li for(x in y)>` and not being handled correctly.
