### ISSUE TITLE
Question - how do I transform an attribute into a function

### ISSUE THREAD

**Issue by cameronbraid** [marko-js/marko#1026]
I wish to be able to rewrite `a/@href` attributes at runtime based on other data in the global context.  So I would like to write a marko transformer that turns the following 

```
<a href='https://example.com'>example</a>
```

into

```
<a href=require("../URLRewriter.js")('https://example.com', out)>example</a>
```

Or is there an example core tag that would include similar code that I could look at ?

**Comment by mlrawlings** [comment]
Sorry this is several months later... It would look something like this: 

`marko.json`: register a transformer for all `<a>` tags.  
```json
{
  "<a>" : {
    "transformer": "./path/to/transformer.js"
  }
}
```
> Note this only affects `<a>` tags in templates that can "see" this config file.  It will not affect tags from installed dependencies, etc.  We don't currently support global tags.  See https://github.com/marko-js/marko/issues/379


`transformer.js`: gets passed the current node (the `<a>` tag) and the compile context
```js
const urlHelperPath = require.resolve('./URLRewriter.js');

module.exports = function (el, context) {
  const href = el.getAttributeValue('href');
  const builder = context.builder;
  if (href) {
    const relativeHelperPath = context.getRequirePath(urlHelperPath);
    const helper = builder.require(relativeHelperPath);
    el.setAttributeValue('href', builder.functionCall(helper, [href, builder.identifierOut()]));
  }
}
```

We definitely need docs around the compiler api, but looking at the methods available in the following files will get you a long way:
- [src/compiler/Builder.js](https://github.com/marko-js/marko/blob/master/src/compiler/Builder.js) (`context.builder`)
- [src/compiler/CompileContext.js](https://github.com/marko-js/marko/blob/master/src/compiler/CompileContext.js) (`context`)
- [src/compiler/ast/HtmlElement/index.js](https://github.com/marko-js/marko/blob/master/src/compiler/ast/HtmlElement/index.js) (base class for `el`)
- [src/compiler/ast/Node.js](https://github.com/marko-js/marko/blob/master/src/compiler/ast/Node.js) (base class for HTMLElement and all other AST Nodes - all methods also available on `el`)
