### ISSUE TITLE
It would be great if Marko could use the <for> tag to iterate over array like objects

### ISSUE THREAD

**Issue by cameronbraid** [marko-js/marko#1036]
Currently the <for (x in arrayLike | status-var=loop)> tag works with array like objects - for example mobx observable array (https://mobx.js.org/refguide/array.html)

However the standard <for (x in arrayLike)> tag explicitly checks for Array.isArray which prevents the tag from being used for array like objects

I've implemented a PR with tests https://github.com/marko-js/marko/pull/1035 if this is something you would consider

**Comment by DylanPiercey** [comment]
This was implemented in https://github.com/marko-js/marko/pull/1238
