### ISSUE TITLE
My Global design (.less) is not being loaded into the page.

### ISSUE THREAD

**Issue by BashiAly** [marko-js/marko#1042]
### Details

Do i need to import anything? I have added a .less file in src directory.

**Comment by austinkelleher** [comment]
If you're using Lasso, you will need to use the `lasso-less` plugin: https://github.com/lasso-js/lasso-less. If you're using Webpack: https://github.com/webpack-contrib/less-loader

**Comment by BashiAly** [comment]
Thanks
