### ISSUE TITLE
How to add Jquery into project?

### ISSUE THREAD

**Issue by BashiAly** [marko-js/marko#1045]
### Details
I have installed the jquery using npm and then created an App.js in project and imported jquery there.

But its showing me error while using _import_, that it is an unexpected identifier.

**Comment by mauricionr** [comment]
I'm using brunchjs

**Comment by mlrawlings** [comment]
Support for ES Modules (`import`/`export`) is still pretty limited in JS land.  You can either set up babel in your project or switch to Common JS (`require`) which has native support in node and is supported by all major bundlers ([see here](https://www.npmjs.com/package/jquery#browserifywebpack)).

You could also look into [experimental esm support in node](https://nodejs.org/api/esm.html) plus a build tool like webpack or rollup that supports esm.

In `.marko` files, the `import` syntax is handled by the Marko compiler, so it's fine to use there without any other build tools.

I'm going to close this issue, but if you have more questions related to module systems, you can ask here.  And feel free to open another issue if you have any other questions.
