### ISSUE TITLE
Document third-party library integration

### ISSUE THREAD

**Issue by janat08** [marko-js/marko#1050]
### Description

There's short explanation that hird party library insertion point belongs in onMounted hook, and I saw changelog explaining that marko will avoid touching random elements.

### Why

third party libraries are unavoidable, and are key to adoption of a library.

### Possible Implementation & Open Questions

is library build on proxies at which point it becomes incompatible in very involved third-party libraries only, and given that you use virtual DOM I suspect that's fairly unlikely.

### Is this something you're interested in working on?

no

**Comment by DylanPiercey** [comment]
Hey @janat08,

Thanks for creating the issue, I agree there is lots of work to do here. We have documented some third party integrations on the Marko website and are open to contributions to add more.
