### ISSUE TITLE
what would be the right way to integrate marko.js with keystone.js?

### ISSUE THREAD

**Issue by mnksingh** [marko-js/marko#1053]
Currently keystone js has an option for to use custom templating engine

I need to make a performant ui with capabilities like marko js 
Since there is a different implementation of keystone and marko as in keystone we set engine's configuration beforehand and if we have pass any values to custom engine there i have several options like marko, marko/express, etc. Also i need to use markoExpress as middleware.

There are also different ways to call marko like through res.render/view.render/view.marko/res.marko

I didn't found any specific documentation related to this, maybe i am not using it correctly, maybe i don't enough knowledge.
But i would really appreciate closure .

**Comment by mlrawlings** [comment]
There are a bunch of ways to render a template.  Sorry for the confusion!

This article explains why we recommend bypassing the view engine for express:
https://strongloop.com/strongblog/bypassing-express-view-rendering-for-speed-and-modularity/

`res.marko` actually does the same thing as above but passes `res.locals`, sets the `content-type`, etc.  If you're using `express` I'd recommend that route.

I have used keystone in the past for a small project, but I don't remember how tied to the view engine it is and if you'd be fighting with it to bypass the view engine.  Marko is supported by [consolidate](https://github.com/tj/consolidate.js/) to use as an express view engine, but it comes with the down-sides mentioned in the article.  Depending on your application, this might be acceptable.
