### ISSUE TITLE
add option to store compiled sources under a different root path

### ISSUE THREAD

**Issue by ahmadnassri** [marko-js/marko#106]
unless i'm missing something, it seems all compiled files are created in the same directory / path as the template sources.

this means having additional complex rules for `.gitignore` in cases where `.marko` is not used as the extension!

would be a lot simpler to store all compiled files (under the same directory tree) starting a temp root path, that can be easily cleared / deleted as needed, and can be simply ignored from the project/repository version control.

**Comment by patrick-steele-idem** [comment]
Hi @ahmadnassri, the Marko compiler puts the compiled templates next to the original template because the Node.js module loader is context aware and we want the stack traces to match up with location that the Node.js module loader associates with the loaded compiled template. That is, the location of the JS module on disk matters since it impacts how `require`'d modules are resolved. Currently, we calculate all of the relative paths based on the original template location on disk and we therefore put the compiled template module next to the original template file. While we could place the compiled template at a different location on disk, we would need to change how the relative `require` paths are generated. Also, at a minimum, each module in the application would need to have its own parallel directory tree for compiled templates so that the required Node.js modules would be resolved relative to the module that contains the template. Something like the following:

```
my-app/
    .marko-compiled/
        foo/
            template.marko.js
        bar/
            template.marko.js
    foo/
        template.marko
    bar/
        template.marko
    node_modules/
        my-installed-module/
            .marko-compiled/
                foo/
                    template.marko.js
                bar/
                    template.marko.js
            foo/
                template.marko
            bar/
                template.marko
```

However, I would be concerned about the impact on usability if we move compiled templates to a parallel directory tree. There were also be other impacts on usability that would need to be explored. I don't want to dismiss your suggestion, but unfortunately it is not as simple as changing where the compiled template gets stored on disk.

**Comment by ahmadnassri** [comment]
> the Marko compiler puts the compiled templates next to the original template because the Node.js module loader is context aware and we want the stack traces to match up with location that the Node.js module loader associates with the loaded compiled template

fully agree with this *(just wanted to be clear)*

> While we could place the compiled template at a different location on disk, we would need to change how the relative require paths are generated. 

I have not looked at the internals *- yet -*, but in theory, should be done in such a way that changing the `cwd` or `root` would be sufficient. 

your example is exactly what I'm interested in. but I would also add that each module (and module maintainer, whether internal or external) should be free to determine the best setup for that module.

I'm guessing your basing your use-case on a hierarchy of modules used within one system, but the moment you go out of the scope of the one system then the module wouldn't know where to look for its compiled templates.

so it's best to keep the separation between modules to ensure true portability of the module itself.

that of course would become complicated if you're doing template dependencies between modules, but rather than solve that problem a better pattern would be to have only the main / root module be responsible for compiling, and if there are dependant module templates, they are simply pointed to, and the compiled output is stored elsewhere.

###### example

for this module, the package maintainer chooses to store in a folder `.marko-compiled-location-a`, this is only relevant when that module is used on its own.
```
my-installed-module/
    .marko-compiled-location-a/
        foo/
            template.marko.js
        bar/
            template.marko.js
    foo/
        template.marko
    bar/
        template.marko
```

but when the module is used as a dependency of another system, the dependant chooses where the final compiled files should live:

```
my-app/
    .marko-compiled/
        foo/
            template.marko.js
        bar/
            template.marko.js
        .marko-dependants/
            foo/
                template.marko.js
            bar/
                template.marko.js
    foo/
        template.marko
    bar/
        template.marko
    node_modules/
        my-installed-module/
            foo/
                template.marko
            bar/
                template.marko
```

again, not sure what the best path design here would be, but, with the current setup, it makes it very noisy (for simple usage like static site building) and cumbersome with server-side live systems, especially if you're doing live reloading of the application, your template changes may not get refreshed.

**Comment by patrick-steele-idem** [comment]
Hey @ahmadnassri, we added an option to disable writing compiled templates to disk:

```javascript
require('marko/compiler').defaultOptions.writeToDisk = false; 
```
Please see issue #150 and commit 370ac4b3ab2adc078b0b1c79f8f58186cd8074e9.

If that is an acceptable solution then I would like to close this issue. Please let me know. Thanks.


Does that resolve this issue?

**Comment by ahmadnassri** [comment]
yes indeed this does satisfy the ask here ... 

wish there was a cleaner way to set this option though ..

**Comment by patrick-steele-idem** [comment]
Do you have an recommendation for a cleaner way to set the option? We can always adjust.

**Comment by ahmadnassri** [comment]
I have to play around with it more first ... I'm thinking this should be done on the main include:

```js
var marko = require('marko')
marko.compiler({
  ...
})
```

or 

```js
marko.compilerConfig = {
  ...
}
```

**Comment by adammcarth** [comment]
@ahmadnassri If you're using Express JS, there could be a cleaner way to define configuration with an API similar to what I've proposed in #165. If there was a Marko Express plugin, when initializing the engine you could pass configuration options to Marko similar to how defined them above...

```javascript
var Marko = require("marko-express"); // example lib name
app.engine("marko", Marko({ writeToDisk: false }));
app.set("view engine", "marko");
```

**Comment by ahmadnassri** [comment]
not using express for this particular project (It's a static site builder, no server required)
