### ISSUE TITLE
AdonisJS view template engine

### ISSUE THREAD

**Issue by LucaGabi** [marko-js/marko#1063]
### Description
AdonisJS view template engine with MarkoJS

(I have something not with adonisjs: https://gitlab.com/gabiluca.mx.gitlab/tsmvc.git)

### Why
It is grate as a template engine SSR and CSR

### Is this something you're interested in working on?
Yes

**Comment by mlrawlings** [comment]
Looks interesting! If you end up creating an integration, feel free to send a PR to add details to this page: https://markojs.com/docs/server-integrations-other-overview/
