### ISSUE TITLE
getComponent(key) returns null after transcluding component input change

### ISSUE THREAD

**Issue by cameronbraid** [marko-js/marko#1087]
### Marko Version: 4.12.1

Will provide a failing test case and PR once I get an issue number

index.marko
```
class {
}
<Wrapper key='wrapper'>
    <Item key='item'/>
</>
```

Wrapper.marko
```
class {
    onCreate() {
        this.state = {
            updated: false,
        }
    }
}
<div.Wrapper>
    <include(input.renderBody)/>
</>
```

Item.marko
```
class {
}
<div.Item/>
```

test.js
```
var expect = require("chai").expect;

module.exports = function(helpers) {
    let app = helpers.mount(require.resolve("./index"));

    var item = app.getComponent("item")
    expect(item).to.be.an('object')

    var wrapper = app.getComponent("wrapper")

//truncated

    // input update
    wrapper.input = {} 
    wrapper.update()
    item = app.getComponent("item")

// fails on next line
    expect(item).to.be.an('object') 
    
};

```

**Comment by mlrawlings** [comment]
I think this is expected behavior.  The wrapper receives the transcluded content on the `input` object, so when `input` is set to `{}`, the transcluded content is no longer available to wrapper, it doesn't render it, and when the `app` component tries to get it, it's not there.

Did this work at some point in the past? Are you facing an issue now because of this?

**Comment by cameronbraid** [comment]
You are right.  That was a silly thing for me to do !  That will teach me for working late at night.

Im actually trying to isolate an issue with upgrading from 4.11.4.  Which results in me getting  lots of dom exceptions 

```
Uncaught TypeError: Cannot read property 'nextSibling' of null
    at Component.___forEachNode (Component.js?2cba:542)
    at Component.___detach (Component.js?2cba:533)
    at morphChildren (index.js?8192:329)
```

Sorry - Lets close this PR and issue.
