### ISSUE TITLE
Component.js:489 Uncaught TypeError

### ISSUE THREAD

**Issue by basickarl** [marko-js/marko#1090]
`"marko": "^4.12.1",`

```
Component.js:489 Uncaught TypeError
    at Component.___rerender (Component.js:489)
    at Component.update (Component.js:452)
    at updateComponents (update-manager.js:44)
    at updateUnbatchedComponents (update-manager.js:16)
    at nextTick-browser.js:18
```

main-app component
index.marko
`<app-list key="list" count=state.count/>`
component.js
```
    onCreate(input, out) {
        console.log('onCreate', input);
        this.state = input.state;
        this.state.count = 0;
    },
```

app-list component
index.marko
```
<div>${input.count}</div>
```

In the main-app component-browser.js I add an element to an array in the state object:
`this.state.count++;`

This forces the state to change which triggers the child component app-list to re-render since we are inputting the main-app state object into it, and that is where I get the error.

What else do you need?

**Comment by DylanPiercey** [comment]
@basickarl by using `component-browser` you are opting into [split components](https://markojs.com/docs/components/#split-components) which do not support client side rerendering. If you would like to re-render your component in the browser you will need to use `component.js` instead.

**Comment by basickarl** [comment]
@DylanPiercey Thank you for the quick answer! Keep up the good work, I remember when marko only had a 1000 stars or so on GitHub. 6000 now, keep it up!
