### ISSUE TITLE
What if I don't want to use Atom?

### ISSUE THREAD

**Issue by LoganDark** [marko-js/marko#1092]
Atom has all this fancy support, hyperclick, autocomplete, blah blah...

Well, Atom is slow and bulky, and I don't use it. Even Sublime Text is better. My editor of choice is WebStorm, and your support for it is almost nonexistent. Seriously... syntax highlighting? That's it?

Atom has all this special support and none of the better editors have anything more than an acknowledgement. It's like you're saying "we know about these, but we're not going to support them."

Feel free to close this issue as soon or as late as you want, but hopefully, this can stay open as a 'feature request' for better support. I'd like to hear your thoughts on this. I'd also like Marko support in my fucking IDE where I do all my work, tyvm

**Comment by DylanPiercey** [comment]
Just to add to @jasonmacdonald's answer there is currently active development on a [language-server](https://langserver.org) which could eventually make the IntelliJ integration much better so keep an eye on that.

I also personally recommend VSCode, it offers similar functionality to webstorm on top of having slightly better Marko support (currently atom still has the best Marko support but we are working to get to parity with VSCode).
