### ISSUE TITLE
Scoped Variables are not being passed correctly to transcluded content

### ISSUE THREAD

**Issue by nthibert** [marko-js/marko#1096]
### Details

Currently I have a tag that looks like this:
`"<page>": {
        "renderer": "./src/index.marko",
        "@site": "object",
        "@page": "object",
        "@class": "string", 
        "vars": ["site", "page"]
    }`

I want the site and page attributes to be passed down into my transcluded content. Currently what is happening is that site and page are being set to the second argument of the renderBody as an object that has site and page. The 3 argument of renderBody is undefined. 

<img width="590" alt="renderbody" src="https://user-images.githubusercontent.com/4306927/43215530-6504e0ea-900a-11e8-8d1d-5f562d0ba213.png">
<img width="841" alt="output" src="https://user-images.githubusercontent.com/4306927/43215533-680b5fee-900a-11e8-9a52-df4eea5c3abd.png">

### Expected Behavior

Expect `site` and `page` to be their own individual variables for the transcluded content. 

### Actual Behavior

`site` and `page` are combined into one object and passed to the renderBody as the first name of the scoped vars list. 

### Possible Fix

I haven't dug into this, but thinking it might be something to do with an apply or call method. Just need to make sure the variables are separated and not joined into 1 object

<details><summary>Additional Info</summary>

### Your Environment

- Environment name and version (e.g. Chrome 39, node.js 5.4): Chrome 67.0.3396.99, node.js 8.6.0
- Operating System and version (desktop or mobile): Mac 10.13.6 Desktop

</details>

**Comment by mlrawlings** [comment]
The `vars` property in `marko.json` allows you to add additional parameters to the renderBody function as can be seen in your screenshot:

```js
function renderBody(out, site, page) { /* ... */ }
```

I'm not sure exactly how you're passing the data, but it's probably something along the lines of 

```marko
<include(input.renderBody) site=x page=y/>
```

In this case the call to renderBody would look something like `renderBody(out, { site:x, page:y })`.  Marko doesn't do anything special with the parameters.

In order to pass multiple parameters, you can use:

```marko
<include(input.renderBody, x, y)/>
```

Which will result in a call similar to  `renderBody(out, x, y)`.

**Comment by nthibert** [comment]
@mlrawlings I'm sorry for not showing you my full implementation. I'm currently using the "newer" feature dynamic tags. 
`<${input.renderBody} site=site page=page>`. 

I'm not sure if this changes your answer, though I guess my question would be, how do we use the vars attribute in marko.json with dynamic tags?

**Comment by mlrawlings** [comment]
Ah.  The `<${dynamic}>` tag does not support passing multiple parameters.  This will likely change in the future, but we need to figure out what that looks like.

Also, we've not documented it yet, but the [tag parameters](https://github.com/marko-js/marko/pull/1076) feature is intended to replace the `vars` property in `marko.json`.  This is currently behind a "flag" (see the pr for more info).  Tag parameters makes the introduction of these variables into the tag body more explicit and gives the user of the component the ability to name the parameters however they like.  It also allows destructuring the parameters:

```marko
<lcp-page({ site, page })>

</lcp-page>
```

This works in tandem with the dynamic tag just as you're using it:
```marko
<${input.renderBody} site=site page=page>
```
