### ISSUE TITLE
Dynamic svg elements not mounted correctly

### ISSUE THREAD

**Issue by Hafas** [marko-js/marko#1098]
### Details

In my project I use fontawesome's svg api to render their icons and I noticed an issue with their icons whenever I (re)render them on the client.

When using their api we then receive an array in the following format:

    [
      {
        "tag": <tagname>,
        "attributes": <object of attributes>,
        "children": <array in the same format>
      }
    ]

So I created a simple marko-component that accepts such an object and renders the icon:

    <macro fa (elements)>
      <for (element in elements)>
        $ const { tag, attributes, children } = element;
        <${tag} ...attributes>
          <fa (children)/>
        </>
      </for>
    </macro>
    
    <fa (input.icon)/>

### Expected Behavior

The icon should be rendered.

### Actual Behavior

The icon will only be rendered if the markup comes from the server.
If the client renders or rerenders it, it disappears.

### Possible Fix

On the client, marko is supposed to use `createElementNS` instead of `createElement`. This apparently does not happen, when using dynamic tags.

<details><summary>Additional Info</summary>

### Steps to Reproduce

Try to render the following template. Only 2 out of the 4 check marks are rendered.

    class {
      onCreate () {
        this.state = {
          hidden: true
        };
      }
      onMount () {
        this.state.hidden = false;
      }
    }

    
    <macro fa (elements)>
      <for (element in elements)>
        $ const { tag, attributes, children } = element;
        <${tag} ...attributes>
          <fa (children)/>
        </>
      </for>
    </macro>

    
    <macro fa-fixed (elements)>
      <for (element in elements)>
        $ const { tag, attributes, children } = element;
        <if (tag === "svg")>
          <svg ...attributes>
            <fa-fixed (children)/>
          </svg>
        </if>
        <else-if (tag === "path")>
          <path ...attributes>
            <fa-fixed (children)/>
          </path>
        </else-if>
        <else>
          <${tag} ...attributes>
            <fa-fixed (children)/>
          </>
        </else>
      </for>
    </macro>

    // this is the object that fontawesome's svg library returns
    $ const checkCircle = [
      {
        "tag": "svg",
        "attributes": {
          "aria-hidden": "true",
          "data-prefix": "fas",
          "data-icon": "check-circle",
          "class": "svg-inline--fa fa-check-circle fa-w-16",
          "role": "img",
          "xmlns": "http://www.w3.org/2000/svg",
          "viewBox": "0 0 512 512"
        },
        "children": [
          {
            "tag": "path",
            "attributes": {
              "fill": "currentColor",
              "d": "M504 256c0 136.967-111.033 248-248 248S8 392.967 8 256 119.033 8 256 8s248 111.033 248 248zM227.314 387.314l184-184c6.248-6.248 6.248-16.379 0-22.627l-22.627-22.627c-6.248-6.249-16.379-6.249-22.628 0L216 308.118l-70.059-70.059c-6.248-6.248-16.379-6.248-22.628 0l-22.627 22.627c-6.248 6.248-6.248 16.379 0 22.627l104 104c6.249 6.249 16.379 6.249 22.628.001z"
            }
          }
        ]
      }
    ];

    <macro my-frame (color)>
      <p style={ color }>Below, there should be a ${color} check mark.</p>
      <div style={ width: "100px", height: "100px", border: "1px solid black", color }>
        <include(renderBody)/>
      </div>
    </macro>

    
    <html>
      <body>

        
        <my-frame ("red")>
          <if (!state.hidden)>
            <fa (checkCircle)/>
          </if>
        </my-frame>

        
        <my-frame ("green")>
          <if (!state.hidden)>
            <fa-fixed (checkCircle)/>
          </if>
        </my-frame>

        
        <my-frame ("blue")>
          <fa (checkCircle)/>
        </my-frame>

        
        <my-frame ("violet")>
          <fa-fixed (checkCircle)/>
        </my-frame>
      </body>
    </html>

</details>

**Comment by DylanPiercey** [comment]
Should be fixed in 4.17.0 😄
