### ISSUE TITLE
Taglib Discovery - allow configuration of folders to use for discovery

### ISSUE THREAD

**Issue by kristianmandrup** [marko-js/marko#110]
Please add a way to programmatically add specific folders to perform `Taglib Discovery` in order not to be forced to rely on node default search strategy. Something like:

`marko.taglibs.discovery([myTaglibsPath, myOtherTaglibsPath, ...]);`

Thanks :)

**Comment by patrick-steele-idem** [comment]
Hi @kristianmandrup, can you please provide more details on your use case and why you need this feature? I think that will allow is to provide a better solution to your problem.

Also, we want to make ensure that templates still compile through the command line compiler and other tools. If application code must first register taglibs as you described then that would mean that other tools would not work as expected unless they also some how loaded your application code to register the additional taglibs.

On a related note, Marko does support the ability for a taglib to import another taglib (here's a link to the [relevant code in loader-taglib.js](https://github.com/marko-js/marko/blob/156f04ed3537b3e1d0561f87a3353ac7e0c1f543/compiler/taglibs/taglib-loader/loader-taglib.js#L138)). Not sure if that would solve your problem though.

Please provide more details on your use case. Thanks!

**Comment by kristianmandrup** [comment]
Thanks :) Trying to make sense of this...

Various "clever" ways for using taglibs:

```js
{
    "<my-hello>": {
        "renderer": "./hello-renderer",
        "@name": "string"
    }
}
```

Importing other taglibs :)

```js
taglibImports: function(imports) {
    // The "taglib-imports" property allows another taglib to be imported
    // into this taglib so that the tags defined in the imported taglib
    // will be part of this taglib.
    //
    // NOTE: If a taglib import refers to a package.json file then we read
    //       the package.json file and automatically import *all* of the
    //       taglibs from the installed modules found in the "dependencies"
    //       section
```

The "normal" way

`importPath = resolveFrom(dirname, dependencyName + '/marko-taglib.json')`

Trying to combine local with global/shared taglibs

```js
{
  tagsDir: './my-tags',
  taglibImports: ['../../package.json']
}
```

// package.json
```js
{
  dependencies: {
    // how does the import expect to find taglibs from external module??
    // what are the conventions in this case!?
    'my-global-taglib': 'x',
    ...
  }
}
```

Another proposal - direct require (why traverse all dependencies?)

```js
{
  tagsDir: './my-tags',
  // refers to a package in my package.json
  // why not require module directly? (ie. not local since not prefixed by ./ )
  taglibImports: ['my-global-taglib', 'my-other-shared-taglib-module']
}
```

**Comment by kristianmandrup** [comment]
Hi, 

I'm trying to use the `taglib-import` feature as I really need it now. I think I understand the `package.json` mechanism, but not sure about the `else` part, line `176`. What should be at `./_global/components/menu` for this to work? I assume resolveFrom it just a special wrapper for node `require` using `curImport` as the base path?

```js
else
  importPath = resolveFrom(dirname, curImport);
  taglib.addImport(importPath);
```

```json
{
    "tags-dir": ".components",
    "taglib-imports": [
      "./components/menu",
      ...
    ]
}
```

My target file structure

```sh
/components
  /my-comp
  /menu
    /other-comp
```

**Comment by kristianmandrup** [comment]
I got it, must be `"./components/menu/marko-taglib.json"`, however why not assume that by default given a path without it? At least it works for me now. So cool :)
