### ISSUE TITLE
State with dynamic tabs

### ISSUE THREAD

**Issue by nthibert** [marko-js/marko#1139]
### Details

I am working with dynamic tags doing a conditional statement to determine the tag. On runtime everything works as expect. Though it seems to break when the condition is tied to the state. Then when the state changes it throws an error. Here is an example of the code.

```
class {

    onCreate(){
        this.state = {
            flip: true
        }
    }

    onButtonClicked(){
        this.setState({flip: !this.state.flip});
    }
}


<${state.flip ? "div" : "span"} />
<button on-click("onButtonClicked")>Flip</button>
```

### Expected Behavior

I expect when I flip the tag with the state property, it doesn't throw an error and changes to the appropriate tag

### Actual Behavior

I get an error when I change the state.
![screen shot 2018-10-01 at 11 05 06 am](https://user-images.githubusercontent.com/4306927/46297161-ffe16680-c569-11e8-9a11-234d91ce1489.png)

### Your Environment

- Chrome 69, node.js 8.6.0
- macOs Mojave Version: 10.14

**Comment by jasonmacdonald** [comment]
I worked with Nate to resolve this. The issue was the use of a split component, where the template was not available to handle the re-render. Closing.
