### ISSUE TITLE
Marko loader does not load the correct generated .marko.js file from disk

### ISSUE THREAD

**Issue by mketo** [marko-js/marko#1159]
### Details

I'm using marko loader (Marko.load()) to load templates but generated files does not load properly.

Generated *.marko.js file is not loaded. Tries to load *.js (without marko.) files instead and that does not match the generated file that "doLoad" function creates.

If you have a .marko and a .js file in the same directory, and the .js file includes **code** for your own project, marko will load the .js file and that file is not a generated .marko.js file.

Example, original file: **about.marko**. Generated file: **about.marko.js**. File trying to get loaded: **about.js**.

### Expected Behavior

Load *.marko.js files and not *.js files.

### Actual Behavior

Loads *.js files.

### Possible Fix

~~~~
--- src/loader/index-default.js.orig	2018-10-27 11:19:39.907452000 +0000
+++ src/loader/index-default.js	2018-10-27 11:40:35.136133000 +0000
@@ -17,7 +17,7 @@
             return require(templatePath);
         } else if (parsed.ext === ".marko") {
             // Check if precompiled js file already exists.
-            const jsFilePath = nodePath.join(parsed.dir, parsed.name + ".js");
+            const jsFilePath = templatePath + '.js';
             let foundPrecompiled = false;

             try {
~~~~

### Your Environment

Centos 7 docker running Node v8.12.0

**Comment by DylanPiercey** [comment]
Fixed by https://github.com/marko-js/marko/pull/1426
