### ISSUE TITLE
How to access flash messages within template?

### ISSUE THREAD

**Issue by dtrikannad** [marko-js/marko#116]
Hello team,

I was wondering if there is any way to access messages set with flash using the following api.

```javascript
req.flash('success', 'Account Created Successfully!');
```

is it `${flash}`? or something else within a `.marko` file?

Thank you.

Deep

**Comment by patrick-steele-idem** [comment]
Hi @dtrikannad,

I'm assuming you are using the [flash](https://github.com/expressjs/flash) module for Express. I've not used that module, but according to the documentation the flash messages are stored in the `res.locals.flash` variable and they are an array in the following form:

```json
{
    "type": "info",
    "message": "message"
}
```

I would recommend just passing the flash messages to your page template as part of the template data similar to the following:

```javascript
var template = require('./template.marko');

app.get('/', function(req, res) {
    template.render({
            flashMessages: res.locals.flash
        }, res);
});
```

And then in your template:

```xml
<ul>
    <li for="flashMessage in data.flashMessages">
        <b>Type:</b> ${flashMessage.type}<br>
        <b>Message:</b> ${flashMessage.message}
    </li>
</ul>
```

I hope that answers your question.

**Comment by dtrikannad** [comment]
Thank you! That worked!!

Now I have a debug question. I am getting a 500 error when trying to do the following:

`<require module="../private_libraries/globals_v1.js" var="globals"/>`
`<if test="!globals.isEmpty(data.messages)">Not Empty</if>`

where data.messages is being passed in as the flashMessage. isEmpty is a function that runs through that object to make sure nothing is contained in that data.messages object, but I'm getting a 500.

Any ideas on how to resolve and/or better yet, debug that 500? there are no messages that get spit out besides the 500 error result.

Thank you.

Deep

**Comment by patrick-steele-idem** [comment]
Hi @dtrikannad, glad that solved your problem. Do you have a stack trace with your 500 error? Marko doesn't have any `try...catch` blocks so any exception is just going to bubble up. If you are not seeing a proper stack trace in your logs then I think there are issues with how your server is configured and that is going to cause more problems for you in the future. Did you you add your own uncaught exception handler (e.g. 'process.on('uncaughtException', function(err) { ... })`);? Are you using promises (promises catch exceptions and will silently eat them in some circumstances)?

If you are desperate you can do the following:

```xml
{% try { %}
<require module="../private_libraries/globals_v1.js" var="globals"/>
<if test="!globals.isEmpty(data.messages)">Not Empty</if>
{% } catch(e) { console.error(e); } %}
```

(using embedded scripts is not recommended!)

I hope that helps

**Comment by patrick-steele-idem** [comment]
Hi @dtrikannad, I'm going to close this issue, but if you are still facing issues related to debugging then feel free to comment here or open another Github issue.

**Comment by crash85** [comment]
Hello Patryk, will comment here because I have a related question.
What if the flash messages are sent before a
```
res.redirect('/');
```
?

In this case how can I pass the parameter to the .marko layout since I am not calling the render method?

**Comment by patrick-steele-idem** [comment]
Hey @crash85, the "flash messages" are stored in a session that persists across redirects. See:
 https://github.com/expressjs/flash/blob/92fd748feb60c9a277622ce75ef7091735796af9/index.js#L6-L8

As an addendum to my earlier response, whenever you pass flash messages to the template to be rendered you should just also clear out flash messages from the session:

```javascript
var template = require('./template.marko');

app.get('/', function(req, res) {
    var flashMessages = res.locals.flash;
    if (flashMessages) {
        flashMessages = res.locals.flash.concat([]); // Clone the flash messages before clearing
        res.locals.flash.length = 0; // Remove all of the elements from the flash messages stored in the session
    }  

    template.render({
            flashMessages: res.locals.flash
        }, res);
});
```

I don't use sessions in my app and I don't use the `flash` module, but that should work for you.
