### ISSUE TITLE
self-ref library not playing well with marko.json

### ISSUE THREAD

**Issue by basickarl** [marko-js/marko#1164]
```
"require-self-ref": "^2.0.1"
"marko": "^4.13.8",
```

Error:
`Error: Unable to load taglib ([/Users/km/dev/pcap-reader/web/application/frontend/marko.json]): Error: Error while applying option of "tags-dir". Cause: Error: ENOENT: no such file or directory, scandir '/Users/km/dev/pcap-reader/web/application/frontend/~/application/frontend/components/smart'`

marko.json:
```
{
    "tags-dir": "~/application/frontend/components/smart"
}
```

I'd like to use the self-ref library inside the marko.json file (as I do with browser.json files). It looks like it doesn't apply for the marko.json file?

**Comment by DylanPiercey** [comment]
Since the `marko.json` file can be analyzed by multiple tools I don't think it makes sense to add support for changing the path resolution like this. For example it would break editor support, and potentially break bundlers, even though it may work on the node side.
