### ISSUE TITLE
Problems importing tags using npm link

### ISSUE THREAD

**Issue by hedefalk** [marko-js/marko#1167]
### Details

I'm trying to use a common lib with tags supporting two different projects that are developed in parallell. I'm using npm link symlinks to support that workflow.

### Expected Behavior
I was expecting I could put a marko.json in a taglib project, import it, npm link and it would work.

### Actual Behavior
On a tag that is under the npm-linked library, event handlers aren't called on DOM-events.

<details><summary>Additional Info</summary>

I've tried putting the same exact source component under the importing project and then everything works fine. If I'm diffing the output js between these two, there are differences like these:

```

-var marko_template = module.exports = __webpack_require__(/*! marko/src/vdom */ "../kb-frontend/node_modules/marko/src/vdom.js").t(),
-    components_helpers = __webpack_require__(/*! marko/src/components/helpers */ "../kb-frontend/node_modules/marko/src/components/helpers-browser.js"),
+var marko_template = module.exports = __webpack_require__(/*! marko/src/vdom */ "./node_modules/marko/src/vdom.js").t(),
+    components_helpers = __webpack_require__(/*! marko/src/components/helpers */ "./node_modules/marko/src/components/helpers-browser.js"),
     marko_registerComponent = components_helpers.rc,
-    marko_componentType = marko_registerComponent("/kb-frontend$18.10.5/src/marko/components/kb-link/index.marko", function () {
+    marko_componentType = marko_registerComponent("/kb-admin$1.0.0/src/marko/components/admin-link/index.marko", function () {
   return module.exports;
 }),
-    marko_component = __webpack_require__(/*! ./component */ "../kb-frontend/src/marko/components/kb-link/component.js"),
+    marko_component = __webpack_require__(/*! ./component */ "./src/marko/components/admin-link/component.js"),
     marko_renderer = components_helpers.r,
     marko_defineComponent = components_helpers.c,
-    marko_helpers = __webpack_require__(/*! marko/src/runtime/vdom/helpers */ "../kb-frontend/node_modules/marko/src/runtime/vdom/helpers.js"),
+    marko_helpers = __webpack_require__(/*! marko/src/runtime/vdom/helpers */ "./node_modules/marko/src/runtime/vdom/helpers.js"),
     marko_loadTag = marko_helpers.t,
-    include_tag = marko_loadTag(__webpack_require__(/*! marko/src/taglibs/core/include-tag */ "../kb-frontend/node_modules/marko/src/taglibs/core/include-tag.js")),
+    include_tag = marko_loadTag(__webpack_require__(/*! marko/src/taglibs/core/include-tag */ "./node_modules/marko/src/taglibs/core/include-tag.js")),
     marko_attrs = marko_helpers.as;

```
Does this mean they are using different instances of marko runtimes? I'm doing a "resolutions"- to fix the marko version in package.json, but that doesn't help.

### Your Environment
osx, marko-loader, webpack-serve.

</details>

**Comment by DylanPiercey** [comment]
In order for a linked tag to work you need to have it listed in your package.json (https://markojs.com/docs/custom-tags/#using-tags-from-npm), then you can remove it after you unlink. I’m thinking maybe we should re-evaluate this though to see if we can make the experience more seamless for linked Marko tags.

**Comment by DylanPiercey** [comment]
Oh yes you are right. Sorry I didn’t read the full issue but as you say it is pulling in two runtimes which isn’t going to work. This is something we should address though.

**Comment by hedefalk** [comment]
@DylanPiercey Hm, I'm trying to understand here. At one point I had issues with using a community library that also includes _a_ marko:

https://github.com/jesse1983/marko-router5/issues/5

It seemed I could at that point get around it by using package.json resolutions:

```
"resolutions": {
    "marko": "4.13.8"
  },
```

forcing only one marko version which seemed to also make it only one _instance_ in normal cases (root marko folder in node_modules tree). But it seems that the way the marko-loader or something works, even if it's only one version (and maybe only one physical folder in node_modules) there will be more than once instance because of how the require-thingies are registered? And it's stateful so everything breaks then. Is that a correct analysis? :)

What is then the recommended way to try to create a taglib module? Does peer dependency to marko help?

**Comment by DylanPiercey** [comment]
Yeah that makes sense. I agree it should be documented and would accept a PR for that. I’d like to see what we can do on our end though to make this automatic.
