### ISSUE TITLE
How asynchronous synchronization is achieved

### ISSUE THREAD

**Issue by QinZonger** [marko-js/marko#1170]
### Possible Fix

<details><summary>Additional Info</summary>

### Your Environment

- Environment name and version (e.g. Chrome 39, node.js 5.4):
- Operating System and version (desktop or mobile):
- Link to your project:

### Steps to Reproduce

1.  first...
2.
3.
4.

### Stack Trace

</details>

**Comment by mlrawlings** [comment]
It's an old article, but pretty much everything still applies: https://www.ebayinc.com/stories/blogs/tech/async-fragments-rediscovering-progressive-html-rendering-with-marko/
