### ISSUE TITLE
Is possible skip Warning Deprecated Messages on compile a .marko file?

### ISSUE THREAD

**Issue by jesse1983** [marko-js/marko#1240]
Is there any option on compile a .marko file?

**Comment by DylanPiercey** [comment]
Skipping deprecation messages, in general, would mean that users are not aware of the things that may break in their app.
We've taken some steps to reduce the number of warnings. Notably, any warnings coming from `node_modules` now only log once.

Also, these warnings are setup to only log in development mode, running your app in `NODE_ENV=test` or anything else would also hide them.
