### ISSUE TITLE
w-body for tag body content

### ISSUE THREAD

**Issue by kristianmandrup** [marko-js/marko#125]
In the `marko-widget` docs, you use the following to indicate the placeholder for contained body content:

`<span w-body></span>`

"used to determine the nested external content that is to be injected into the body of the UI component (to support transclusion). The actual injection point is determined by the `w-body` attribute."

Can I use this for regular tags as well? If so, please document use in this project as well ;)
What is a valid attribute value for `w-body` if one must be provided for whatever reason?

**Comment by kristianmandrup** [comment]
Answer from https://github.com/marko-js/marko-widgets

If it helps, an attribute with no value is equivalent to an attribute with a value of an empty string:

`<span w-body></span> === <span w-body=""></span>`

The purpose of the `w-body` attribute is to support transclusion. If the user of a custom tag nested content inside the custom tag then that content will get injected into the output HTML relative to the `w-body` marker. In addition, if the widget rerenders then the body content will be preserved (since that content is external to the widget). For example, below is the usage of a custom tag with nested content:

```html
<my-awesome-component>
    This is nested content that will be injected into the `w-body` element.
</my-awesome-component>
```

**Comment by patrick-steele-idem** [comment]
Was that a question and then an answer to your own question? :)

Should I close this issue, or do you think we need to improve the docs for `renderBody(out)` as it relates to Marko?: https://github.com/marko-js/marko#tag-renderer

**Comment by kristianmandrup** [comment]
Yeah, was a way to add docs via a FAQ entry using an issue :P

Please make a note in tag-renderer section that the `w-body` attribute can be used in the marko template for the same effect as `renderBody(out)`. That would connect the dots I think. 
Thanks :)

**Comment by tindli** [comment]
@kristianmandrup please see the PR if it fits your needs....
