### ISSUE TITLE
Please put old docs back at https://markojs.com/docs/getting-started/

### ISSUE THREAD

**Issue by cameronbraid** [marko-js/marko#1263]
We still use the older syntax <for(i in array)> and would get value in being able to read the old docs at https://markojs.com/docs/getting-started/  Currently only version 3.x and 4.15.1 is available.

**Comment by DylanPiercey** [comment]
I understand it will take a bit of time to get everyone on to the new syntax. In the interim you can always view the old docs via the [GitHub interface](https://github.com/marko-js/marko/tree/v4.14.25/docs) and if you are specifically looking for getting started it is here https://github.com/marko-js/marko/blob/v4.14.25/docs/getting-started.md.

There is also an automated migration available for all the recent changes. You can migrate existing files using the [marko migrate](https://github.com/marko-js/cli/blob/master/packages/migrate/README.md) cli.

I don't think it's worth while to show the outdated documentation on the website when it is still viewable via GitHub.
