### ISSUE TITLE
Is support for HTTP2 in the roadmap?

### ISSUE THREAD

**Issue by StarpTech** [marko-js/marko#1273]
### Description

Marko heavily relies on asynchronous rendering and streaming. It use HTTP1 [`Chunked transfer encoding`](https://en.wikipedia.org/wiki/Chunked_transfer_encoding) to respond chunks out of the order which are then assembled on client side. With [HTTP2](https://hpbn.co/http2) we can use more efficient mechanism like [`server-push`](https://hpbn.co/http2/#server-push), [`Stream Prioritization`](https://hpbn.co/http2/#stream-prioritization)

In-depth explanation: https://www.ebayinc.com/stories/blogs/tech/async-fragments-rediscovering-progressive-html-rendering-with-marko/

### Browser support
https://caniuse.com/#feat=http2

**Comment by ianvonholt** [comment]
I'm actually pretty interested in getting something with HTTP2 up and running with MarkoJS since Chunked Transfer Encoding is forbidden with HTTP/2.

**Comment by tigt** [comment]
While HTTP/2 does forbid `Transfer-Encoding: chunked`, [it still can stream partial responses, just like chunked TE](https://stackoverflow.com/a/29487781/2522637).

**Comment by DylanPiercey** [comment]
The current render apis expose an async iterator that you can use to take the html chunks flushed by Marko and do whatever you want with them.
