### ISSUE TITLE
Spread operator is not usable in component class

### ISSUE THREAD

**Issue by ccinelli** [marko-js/marko#1281]
### Details

```
class {
   onCreate(input){
      return {...input, a: 3}
   }
}
```

It does not work in the `class` inside a `.marko` file.

### Expected Behavior

Spread operator should work: `...`

### Actual Behavior

It complains that `...` is not expected

### Possible Fix

A workaround is to use the `lasso-babel-transform` and move the `class` in `component.js`

**Comment by dominikstoetter** [comment]
this is most likely caused by a outdated runtime. rest/spread is a feature not present until node `8.6.0`.

If you target browsers that don't fully support ES2015 you want to transform then anyway.

**Comment by DylanPiercey** [comment]
This is now fixed in Marko 5.
