### ISSUE TITLE
The "Methods" link in the "this.els" section in class-component.md is broken

### ISSUE THREAD

**Issue by melquan** [marko-js/marko#1287]
### Details

The "Methods" link in the "this.els" section in class-component.md is broken.

![image](https://user-images.githubusercontent.com/19419138/54317792-68188780-45a1-11e9-8fe8-ce3cf8cf8254.png)

### Expected Behavior

The link should go to https://markojs.com/docs/class-components/#getelkey-index

### Actual Behavior

The link goes to https://markojs.com/docs/components/#getelkey-index.

### Possible Fix

Update the URL to just `#getelkey-index` since it's on the same page.

**Comment by mlrawlings** [comment]
Fixed by #1288.  Thanks!  We'll publish an update to the site soon.
