### ISSUE TITLE
Marko destroys hydrated page with a rerender on client side

### ISSUE THREAD

**Issue by StarpTech** [marko-js/marko#1291]
### Marko Version: 14.5.2

As titled. I have a stateful component (empty class) with a `<i18n/>` component which use [i18n](https://www.i18next.com/) as utility. When the page is hydrated on the client, it will be rerendered. This rerender destroys all my translated strings and results in empty strings because the utility isn't available on client side. Is marko not able to check if the DOM really needs to be rerendered? The template isn't connected to any state.

Another example:

Imagine the scenarion with translations or with a component which only serves as a controller to delegate events to other components. Right now, due to the behaviour that the template is always rerendered on client-side all my prerendered values are destroyed. This force me to provide a isomorphic solution for everything. Also no-update has no effect. How do you handle this?

There is compatibility tag `<marko no-browser-rerender />` which disable the rerender on client-side but I can't use it because then the `onCreate` isn't fired anymore on client-side and I can't handle component events in it.

**Comment by StarpTech** [comment]
Marko supports hydration only on component level and based on the changes of two renderings. There isn't a concept of in-place updates of node values (text, attributes) which weren't change since the server DOM. This means that any stateful component has to provide client und browser implementations and since any child component of a stateful will be serialized to the client too, we also have to care about them as well.

**Comment by ianvonholt** [comment]
I'm not sure if this is related, but I've been having a lot of state hydration problems with split components recently. Specifically, states defined within onCreate, on the server, will not be accessible on the browser for actual rendering. 

I'll see if I can't get a reproducible example up to illustrate.

**Comment by StarpTech** [comment]
@ianvonholt this sounds like a different problem. Please create a seperate issue.
