### ISSUE TITLE
How to escape tags with nested syntax

### ISSUE THREAD

**Issue by jlopezxs** [marko-js/marko#1297]
We are building sitemaps with marko with SSR and now we have a lot of warnings because we need to use tags like: <g:id>, <g:description>, <g:link> ...
Any method to scape it? We add them to marko-tag.json and the output is ok but the warning stills there

**Marko Version: 4.16.1**

**Detail**
```
WARNING!!
The "<my-tag:nested>" tagName syntax is deprecated. Please use the "<@nested>" tagName syntax instead. See: https://github.com/marko-js/marko/wiki/Deprecation:-legacy-nested-tag
  at client/views/sitemaps/sitemap.marko:47:8
```

**Comment by jlopezxs** [comment]
We found a bit dirty method. Encapsulating all the component between **---** to render as text https://markojs.com/docs/concise/#text
```
---
<?xml version="1.0" encoding="UTF-8"?>
<sitemapindex xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">
  <for|item| of=items>
    <item>
      <g:id>${item.id}</g:id>
      <g:title>${item.title}</g:title>
      <g:description>${item.description}</g:description>
    </sitemap>
  </for>
</sitemapindex>
---
```

**Comment by tigt** [comment]
Oh, that’s awesome! I’ll use that until I can get my PR for #1367 working

**Comment by DylanPiercey** [comment]
This warning is gone in Marko 5 and the recommendation is to declare these in the `marko.json` files as you've done.
