### ISSUE TITLE
DevX: Compiler point to a HTML tag when there is a token error in the JS in the template

### ISSUE THREAD

**Issue by ccinelli** [marko-js/marko#1331]
### Marko Version: 4.16.0

<img width="619" src="https://user-images.githubusercontent.com/38021940/57809067-99d0da80-7719-11e9-84f6-366bf78299d7.png">

### Details

Error:
```
Missing ending "div" tag at line 6 col 0
```

Code:
```
class {
  onCreate() {
  }
}

<div>

  $ const a =23s2; // What? 
</div>
```

### Expected Behavior

The error should point to the line with the incorrect token (`23s2`).

### Actual Behavior

`Missing ending "div" tag at line 6 col 0`. This pretty much the same code in #1330 I just added a comment... 

### Steps to Reproduce

Copy the code in https://markojs.com/try-online

**Comment by DylanPiercey** [comment]
This particular issue was due to an error in parsing comments which was resolve here: marko-js/htmljs-parser#71
