### ISSUE TITLE
lasso outputDir config being ignored by bundler?

### ISSUE THREAD

**Issue by sandro-pasquali** [marko-js/marko#1389]
├─┬ lasso@3.3.0
│ └── marko@4.18.10  

Hello, using Lasso w/ Marko to SSR components.

With the following config:
```
require('lasso').configure({
    plugins: [
        'lasso-marko'
    ],
    outputDir: "some/path/compiled",
    bundlingEnabled: true,
    minify: true,
    fingerprintsEnabled: false
});
```
...the compiled bundle of my component (say 'main.js') is correctly placed in `/some/path/compiled/main.js`

However, in the browser I continue to see network requests for `/static/main.js` (which doesn't exist...)

I'd rather not be forced to create a `static/` folder (which I tried and it works!)...is there a setting somewhere else that I've missed?

latest OSX, node 11.5

Thanks...except for this bit lasso/marko is super smooth to implement.

**Comment by DylanPiercey** [comment]
`outputDir` simply controls where the files are written to disk. To change where they are requested from you need to use the `urlPrefix` option, see https://github.com/lasso-js/lasso#default-configuration.

Also the lasso repo is a better place for lasso specific issues (https://github.com/lasso-js/lasso/issues) 😄.
