### ISSUE TITLE
Concatenating :scoped identifiers?

### ISSUE THREAD

**Issue by tigt** [marko-js/marko#1391]
I want to implement [the “input is part of its own label” pattern for `aria-labelledby`](https://developer.mozilla.org/en-US/docs/Web/Accessibility/ARIA/forms/Multipart_labels) using `:scoped` attribute values:

```marko
<label id:scoped="a">
  Show all results from the last 
  <input value=30 id:scoped="b" aria-labelledby:scoped="a b"> 
  days.
</label>
```

### Expected Behavior

The resulting `aria-labelledby` attribute should space-separate the two scoped `id`s as its value:

```html
<label id="c118-a">Show all results from the last
    <input value="30" id="c118-b" aria-labelledby="c118-a c118-b">days.</label>
```

### Actual Behavior

Instead, something kind of strange happens:

```html
<label id="c118-a">Show all results from the last
    <input value="30" id="c118-b" aria-labelledby="c118-a b">days.</label>
```

**Comment by tigt** [comment]
This would also be relevant for other attributes that accept a list of identifier tokens:

* `<label>`’s `for` attribute
* `aria-describedby`
* `aria-controls`
* `aria-flowto`
* `aria-owns`

**Comment by DylanPiercey** [comment]
This should be solved by the new `<id>` tag in the [tags-api-preview](https://github.com/marko-js/tags-api-preview).
