### ISSUE TITLE
De-dupe taglibs by module name

### ISSUE THREAD

**Issue by sendlo** [marko-js/marko#140]
Per email thread:

We probably need to look into a better way to prevent the same taglib from being loaded multiple times, but currently the Marko compiler walks up the directory tree to find taglibs and will happily load the "same" taglib multiple times if it is found multiple times in the search path. The marko-widgets taglib being loaded multiple times is causing the same template to be transformed multiple times and that is resulting in unexpected behavior. De-duping taglibs by module name would solve the problem.

**Comment by vidya-lingineni** [comment]
+1 facing the same issue

**Comment by patrick-steele-idem** [comment]
New version published with fix: `marko@2.7.24`

**Comment by patrick-steele-idem** [comment]
Thanks for reporting the problem!

**Comment by patrick-steele-idem** [comment]
De-duping is not happening if the found taglibs are coming from the cache...
