### ISSUE TITLE
Also have node_modules/ taglibs default to `./components`?

### ISSUE THREAD

**Issue by tigt** [marko-js/marko#1401]
### Details

When using a Marko project in a root project, components will automatically be discovered at `./components`.

When using a custom taglib from `node_modules/`, the compiler requires `"tags-dir"` to be defined.

### Expected Behavior

I assumed as long as `marko.json` existed, the autoloader would reuse the `./components` convention.

### Possible Fix

Either this difference should be more clearly documented, OR

The autoloader should also have a default of `.components` if `"tags-dir"` isn’t defined. I’d much prefer this option.

### Steps to Reproduce

https://github.com/tigt/marko-cant-import-internal-package-repro

### Stack Trace

```sh
Error: An error occurred while trying to compile template at path "~/repo/src/components/SiteHead/components/SiteSearch/SiteSearch.marko". Error(s) in template:
    1) [src/components/SiteHead/components/SiteSearch/SiteSearch.marko:8:4] Unrecognized tag: Button - More details: https://github.com/marko-js/marko/wiki/Error:-Unrecognized-Tag
```

**Comment by DylanPiercey** [comment]
In this case are you hoping to avoid having a `marko.json` at all? If so we currently use that as one of the heuristics for if we should scan a module for components.

**Comment by tigt** [comment]
No, I had a `marko.json` with a taglib ID already. I was genuinely surprised Marko didn’t assume `components/` with it, as it seemed logical that it would use the default autodiscovery behavior it does everywhere else.

**Comment by DylanPiercey** [comment]
I agree. We should make this change.

**Comment by DylanPiercey** [comment]
Thinking this through a bit more, this would actually be a breaking change.

Also I think in a lot of cases packages may opt for something like `./src/components` and so maybe this is not a sane default?

**Comment by tigt** [comment]
I would be fine if it gave an error message saying “it looks like you’re trying to use these components, but you have to use an explicit `tags-dir`”. I was confused for a while with the generic Unrecognized tag error.

**Comment by DylanPiercey** [comment]
I think that's something we could do. Basically if a `marko.json` does not register any tags we could maybe log a warning.

**Comment by DylanPiercey** [comment]
Thinking through this more I don't think it's worth doing.

We can't really have a default since we recommend precompiling in some setups and so components are in eg a `dist`.
Also having a warning in if you haven't specified tags in the `marko.json` seems strange because I'm not sure why you'd even create the `marko.json` if not to export tags.
