### ISSUE TITLE
Bind event to component after rendering

### ISSUE THREAD

**Issue by Teddy95** [marko-js/marko#1402]
Hey :)

Is it possible to bind an event listener to a component, after it's rendered client side?
For example, I have the following code in my `.marko`-file:

```marko
var component = require('../components/my-component')
var componentRendered = component.renderSync({}).appendTo(domElement)
```

In this code the component isn't included via tag, so the default way don't work:

```marko
<my-component on-event('do-something') />
```

Thank you :)

**Comment by tigt** [comment]
You probably want to register the event listener inside [the `onMount()` lifecycle method](https://markojs.com/docs/class-components/#onmount) (and remove it on `onDestroy()`).

**Comment by Teddy95** [comment]
Yes, but how can I do that? The component which should bind to an event listener is rendered on the onMount lifecycle. I've tested it with the addEventListener function but without success.

**Comment by DylanPiercey** [comment]
@Teddy95 after rendering in the browser you get access to a [RenderResult](https://markojs.com/docs/rendering/#renderresult). On this you can call [getComponent](https://markojs.com/docs/rendering/#getcomponent) to get the top level component instance, then add events as you would any other component instance (`component.on('eventName', handler)`).

For example:

```marko
var renderResult = component.renderSync({});
renderResult.appendTo(domElement);

var component = renderResult.getComponent();

component.on('do-something', () => { ... });
```
