### ISSUE TITLE
Event listener options

### ISSUE THREAD

**Issue by tigt** [marko-js/marko#1408]
## Description

It’s a shame that to use all the features of browser event handlers, one has to drop out of the happy path syntax and manually initialize/clean up listeners in the `class` — especially if the component would not be stateful otherwise.

## Why

* `passive: true` is crucial for smooth scrolling for pages with `touch*`/`wheel` handlers — see #1404
* Sometimes, the capturing phase of events is necessary (especially with focus-ish events)
* Marko already has the `once` option with `once-eventName`, so that’s cool

It also seems likely that `addEventListener()` will gain more options as the Web platform advances.

## Possible Implementation & Open Questions

The first thing that jumped to my mind was a second argument to event attributes:

```marko
<button on-click=(handler, { …options })>
```

But I can see how the wrapping parentheses are undesirable. It could also look like this with a `handler` prop, which surprisingly has precedent on the Web platform:

```marko
<button on-click={ handler: handlerFn, passive: true, once: true }>
```

## Is this something you're interested in working on?

Yes

**Comment by DylanPiercey** [comment]
Current recommendation is to keep it simple and setup the event handler manually if you need extra args.

This is made nicer in Marko 6 thanks to improved lifecycle colocation and the builtin abort signal (`$signal`)
```marko
<button/btn>...</>
<script>
  btn().addEventListener("click", () => { ... }, { passive: true, once: true, signal: $signal });
</script>
```
