### ISSUE TITLE
Globals and utility functions for custom tags? 

### ISSUE THREAD

**Issue by kristianmandrup** [marko-js/marko#141]
I was wondering if it is possible to load custom functions or even set one or more globals, such as `lodash` or `underscore` before "running" all the custom tags, in order to make these globals available for tags to use if needed (load once, use anywhere). 

Must be a very common use case ;) 
Thanks. 

In my case, I would like the following to be generally available for many of my tags:

```js
String.prototype.capitalizeFirst = function() {
    return this.charAt(0).toUpperCase() + this.slice(1);
}
```

**Comment by patrick-steele-idem** [comment]
Hi @kristianmandrup, I think that would be independent of Marko. In your application's main script (on either the server or client) you could run code to do what you are asking. In the Marko templates your expressions are just JavaScript so there would be no problem there.

However, I would recommend not using globals and to instead use `require` to import any JavaScript modules into your templates or other JavaScript code. Also, people might not be happy if you monkey patch the prototypes for core JavaScript types (unless they are polyfills).

Let me know if you still think that there is something that can be done to solve your common use case :)

**Comment by kristianmandrup** [comment]
Hi Patrick, thanks for your response. I was just curious if there was a way. Kind of like a base class or decorator for all renderers to leverage common functionality. So far I've been using `require` but can feel like duplication and I like to keep my prod code super slim and DRY. 
I guess I will just introduce a "compile step" of some sort to prepend or inject whatever code I want according to some global rules...

**Comment by patrick-steele-idem** [comment]
Hey @kristianmandrup. I'm going to go ahead and close this issue since you can make changes on your side to meet your needs. I don't think `marko` should be introducing any globals or making it easier to introduce globals. I think it is better to stick with the CommonJS way of importing dependencies using `require`. Let me know if you have any thoughts or suggestions. Thanks.
