### ISSUE TITLE
Filters in MarkoJS

### ISSUE THREAD

**Issue by slidenerd** [marko-js/marko#1416]
### Description

Filters let you add other languages inside marko templates. Idea is borrowed directly from Pug Filters https://pugjs.org/language/filters.html

### Why

If I want to link to a dynamically generated app.js file with a chunkhash which is the result of a Webpack build step, currently it doesnt seem possible to do so

### Possible Implementation & Open Questions

The example shown at the bottom of the PugJS documentation seems to be a solid case

**Comment by mlrawlings** [comment]
I think components give you the same level of expressiveness.

For the [custom filter example](https://pugjs.org/language/filters.html#custom-filters), you could write a component like this
```marko
<if(input.addStart)Start</if>
<${input.renderBody}/>
<if(input.addEnd)End</if>
```
and usage:
```marko
<my-component add-start=true add-end=false>
  Component
  Body
</my-component>
```

For the Markdown example, you'd need to use Marko's compiler api.  You can tell a component to parse its body not as HTML, but [as text instead](https://github.com/marko-js-samples/ui-components-playground/blob/master/components/app-markdown/marko-tag.json#L2).  Then you can pass that text to a markdown compiler.  We have a [markdown component](https://markojs.com/try-online/?file=%2Fui-components-playground%2Fcomponents%2Fapp-markdown) in the online playground.

```marko
  
<app-markdown>
  ## This is Markdown

  ---

  - A
  - B
  - C
</app-markdown>
```

---

> I want to link to a dynamically generated app.js file with a chunkhash which is the result of a Webpack build step, currently it doesnt seem possible to do so

I'm not sure I'm understanding you correctly, but it sound like you want to inline the contents of the app.js into a script tag?  If so, something like this would work (assuming this component is only rendered on the server):

```marko
import { readFileSync } from "fs";

<script>
  $!{readFileSync(`./path/to/app.${input.hash}.js`)}
</script>
```

Though I wouldn't recommend inlining a bundle into the HTML like this.  Have you checked out the [`@marko/webpack`](https://github.com/marko-js/webpack) plugin?  It handles getting your assets into the html for you.
