### ISSUE TITLE
Is there a location where I can place static files?

### ISSUE THREAD

**Issue by ryanmjacobs** [marko-js/marko#1419]
Sorry if this question has been answered somewhere else... I really looked everywhere, but I couldn't find an answer.

Is there a location where I can place static files that will be served by Marko? For example `src/static` or `src/public`.

Worst case, I can copy them over to `./dist/` after running `npm run build`.

---

Also, is this related? I see this output from `npm start` a lot:
```json
...
  outputDir: /home/ryan/w/2.0/frontend/src/.cache/static
  staticUrlPrefix: /static/
...
```

**Comment by ryanmjacobs** [comment]
I ended up going with this code in my `project.js`. Seems to work fine... Is this idiomatic?

```javascript
// project.js
const fs   = require("fs");
const exec = require("child_process").exec;

module.exports = require("marko-starter").projectConfig({
  name: "redacted",
  beforeStartServer: copy_static_files,
  afterBuild: copy_static_files
});

function copy_static_files() {
  exec("mkdir -p ./.cache/static ./dist/static");
  exec("cp -rv static ./.cache/"); // covers `npm start`
  exec("cp -rv static ./dist/");   // covers `npm run build`
}
```

**Comment by DylanPiercey** [comment]
`marko-starter` has been deprecated and a new tool (`@marko/serve`) is now the recommended config-less setup for Marko. (https://github.com/marko-js/cli/tree/master/packages/serve)

Assets are automatically managed, you can either `import` them, or if they are referenced via a tag like `<img src="./path-to-image.png">` it is handled for you as well.
