### ISSUE TITLE
Please add unless conditional

### ISSUE THREAD

**Issue by kristianmandrup** [marko-js/marko#142]
Would help clean up conditionals a lot :) 

`if='!loop.isLast()'` is kinda ugly and hard to notice those `!` exclamation marks.

```jade
  for(each='item in data.list; status-var=loop"' if='data.list')
    ui-button(attrs='item')
    div(class='or' if='data.or' data-text='$data.or' unless='loop.isLast()')
```

**Comment by philidem** [comment]
That wouldn't be hard to implement but I always find `unless` confusing when reading CoffeeScript code. I'm sure I could get use to it though.

**Comment by kristianmandrup** [comment]
My PR has been merged! Thanks guys :)
