### ISSUE TITLE
Can't pass an Event Listener as a Dynamic Attribute

### ISSUE THREAD

**Issue by lvmasterrj** [marko-js/marko#1421]
### Details

I'm writing a form and for the fields I'm using a component that will render the fields and will handle the validation of them.

The problem is that when I pass the fields attributes, I cannot pass an Event Listener for the field, for it's validation.

*** FORM ***
```marko
$ const fieldsdata= [
   {
    atrrs: {
     id:'exampleEmail',
     type: 'email',      
     on-change : 'check'
    }
  },
.
.
.
]

<fieldscomponent fields=fieldsdata/>
```

*** FIELDS COMPONENT
```marko
<for|field| of=input.fields>
   <input ...field.attrs>
</for>
```

**Comment by tigt** [comment]
In the provided code, you're passing an object named `atrrs`, but the fields component is looking for `attrs`.

Additionally, I believe you need to quote the property name `on-change`, as it contains a hyphen.

**Comment by lvmasterrj** [comment]
Sorry, these ```atrrs``` and ```attrs``` were a typo here, not in the code.

And I already tried quote the property name but it just renders it as a normal attribute, like ```<input attribute="property">```, in my case: ```<input on-change="check">```.

Also tried passing as a string, instead of an object, getting two errors:

MIGRATION
The "${attributes}" is deprecated. Please use "...attributes" modifier instead

WARNING!!
"Passing a string as dynamic attributes ('<div ${string}>' or '<div ...string>') is deprecated, use an object instead."

**Comment by tigt** [comment]
Hm, I’m out of my depth then. You may need a maintainer to answer this question.

**Comment by tigt** [comment]
Sorry for how late this is, but I think the problem is that custom tags can’t listen for native events (even ones that bubble) and vice-versa. [The docs page for Events](https://markojs.com/docs/events/) really could make that clearer.

**Comment by DylanPiercey** [comment]
Currently in Marko 4/5 you've got to explicitly re-emit events that you want to be available to the parent.

With the [tags-api-preview](https://github.com/marko-js/tags-api-preview) events are now just functions passed down through the template which works with `...spreadAttrs` as you've tried.
