### ISSUE TITLE
Marko doesn't support babel plugins using lasso-babel-transform?

### ISSUE THREAD

**Issue by pcanella** [marko-js/marko#1450]
### Details

After adding a plugin to my `.babelrc` file, I don't seem to be able to use the functionality in `index.marko` single component files. I was able to use it on non-Marko server side `.js` files with no issue, but with any sort of Marko file, it breaks. Here's my `lasso-config.json` file:

```json
"babelOptions": {
    "presets": [
        "@babel/preset-env"
    ],
    "plugins": [
        "@babel/plugin-proposal-optional-chaining"
    ]
}
```

Am I forced to use `component.js` files or something for my plugins, rather than lasso looking at the `index.marko.js` file and properly babel transforming? 

### Expected Behavior
Marko should see the babel plugin and transform as necessary

### Actual Behavior
When using the syntax the babel plugin rectifies, I get

```
 const plugs = input.model?.features?.plugs;
                            ^

SyntaxError: Unexpected token .
```

### Your Environment

- Environment name and version: Node 10.15.3
- Operating System and version (desktop or mobile): MacOS Mojave, Chrome, etc.
- Link to your project: n/a (personal project)

### Steps to Reproduce

- install any babel plugin as shown above
- Try to add that functionality to a single file `index.marko`
- See it break

**Comment by Yejielw** [comment]
did you find a fix for this ?

**Comment by pcanella** [comment]
@Yejielw uhhh, well... I switched my entire side project to NextJS + React + Webpack because I was over all the issues with Lasso/Marko/Babel and almost no support/documentation for it.
