### ISSUE TITLE
Marko results in render error when there is an extra space after tags in ebayui-core components

### ISSUE THREAD

**Issue by BhavinPatel04** [marko-js/marko#1451]
### Details
Marko results in a render error when there is an extra space after the tags in ebayui-core component.

#### Error:
````
Error "Error: Render error. Exception: TypeError: Cannot read property 'w' of null
````
I got this error when I was using the ebayui-core components 

### Expected Behavior

Should not result in render error

### Actual Behavior

Results in the above error and stops the page from completing rendering

### Your Environment

- Environment name and version (e.g. Chrome 39, node.js 5.4): Chrome 76, NodeJS 10.16.0
- Operating System and version (desktop or mobile): Desktop

### Steps to Reproduce
Use below HTML:
````
<ebay-tab>
    <ebay-tab-heading>Tab 1</ebay-tab-heading>
    <ebay-tab-panel>Panel 3</ebay-tab-panel> 
</ebay-tab>
````
Note: There is an extra space after `</ebay-tab-panel>`

### Stack Trace

````
Error "Error: Render error. Exception: TypeError: Cannot read property 'w' of null
    at index.marko.js:79:17
    at forEachHelper (node_modules/marko/src/runtime/helpers.js:108:17)
    at Object.renderBody (index.marko.js:36:9)
    at mergeNestedTags (node_modules/marko/src/runtime/helper-mergeNestedTags.js:9:15)
    at render (index.marko.js:31:16)
    at Template.renderer (node_modules/marko/src/runtime/components/renderer.js:227:9)
...........
````

</details>

**Comment by DylanPiercey** [comment]
This issue is fixed with newer versions of ebayui since they no longer use `transforms` to achieve their API.
