### ISSUE TITLE
onMount() is not being called (Marko 4.18.24)

### ISSUE THREAD

**Issue by lbertoncello** [marko-js/marko#1452]
onMount() function is not being called in Marko 4.18.24. When I run my page, it only shows 'URL:'. You can see the code below.

```
class {
  onCreate() {
    this.state = {
      url: '',
    }
  }
  onMount() {
    /*
    this.state.url = window.location.href
    console.log(window.location)
    console.log(window.location.href)
    */
    console.log('Test')
    this.state.url = 'test'
  }
}

<html>
  <head></head>
  <body>
    <p>URL: ${state.url}</p>
  </body>
</html>
```
Is this really a bug or I did something wrong?

**Comment by DylanPiercey** [comment]
Sorry for taking so long to reply to this issue.

What are you using to bundle the Marko templates? `onMount` will only be called if you've configured Marko with a bundler such as Webpack, Lasso or rollup. You can see existing examples here: https://github.com/marko-js/examples

If this is a bug and not a configuration issue please feel free to let me know on this issue 😄.
