### ISSUE TITLE
Performance - use JSON.parse while sending the json to browser.

### ISSUE THREAD

**Issue by pajaydev** [marko-js/marko#1457]
### Description

From recent talks from v8 team, we know that `JSON.parse approach is much faster compared to the JavaScript object literal. JSON.parse() is much faster than JavaScript evaluation`. I got inspiration from the below article to make this change
https://v8.dev/blog/cost-of-javascript-2019#json

### Why

This may be effective when you use handful of stateful components in your marko app and marko ships those to the browser. In the above case, browser takes time to parse and compile JS, I have made a small comparison with a sample JSON file in my machine. Below are the results

#### Before changes
<img width="1417" alt="Screen Shot 2019-12-01 at 9 31 29 PM" src="https://user-images.githubusercontent.com/21375014/69934518-fa8ded80-1486-11ea-9494-dfc8b147ee93.png">

#### After changes
<img width="1417" alt="Screen Shot 2019-12-01 at 9 31 16 PM" src="https://user-images.githubusercontent.com/21375014/69934525-fe217480-1486-11ea-8ab0-e18927aea9d9.png">

### Possible Implementation & Open Questions
We know that marko uses `warp10` internally to serialize the data while sending it to browser. We can make this change as suggested below in this file https://github.com/marko-js/marko/blob/master/src/runtime/components/index.js#L188

```javascript
      componentGlobalKey +
        "=(window." +
        componentGlobalKey +
        "||[]).concat(JSON.parse(" +
        JSON.stringify(safeJSON(warp10.stringify(renderedComponents))) +
        "))||" +
        componentGlobalKey
```

Kindly share any thoughts, concerns or feedback.

CC: @DylanPiercey @mlrawlings 

### Is this something you're interested in working on?

Yes

**Comment by tigt** [comment]
Related: https://github.com/marko-js/warp10/issues/2

**Comment by tigt** [comment]
Slightly related: it should be safe to replace the `Array#concat()` call in your suggested code with `Array#push()`, right? 2 less characters, but more importantly it won’t return a newly-copied array.

**Comment by DylanPiercey** [comment]
@tigt after Marko initializes it actually replaces the global key with an object which has a `concat` method. Since the scripts generated also assign to the global, we also return the `concat` object from the `concat`.

See here: https://github.com/marko-js/marko/blob/master/src/runtime/components/init-components-browser.js#L275

**Comment by DylanPiercey** [comment]
Overall the impact of this in benchmarking seemed to be minimal and there are benefits to our JS based serialization approach (deduping, smaller runtime, more data types, etc).
