### ISSUE TITLE
Isn't work with koa-router

### ISSUE THREAD

**Issue by sakurayang** [marko-js/marko#1462]
### Details

I'm use koa with koa-router and marko to build a RESTful website. But it doesn't render correctly

This is my route part of index.js
```js
const Koa = require("koa");
const Router = require('koa-router');
const router = new Router();
const app = new Koa();
require("marko/node-require")
const index = require("./src/components/index/index.marko");
router.get('/', ctx => {
    ctx.type = "text/html";
    ctx.body = index.stream({
        name: "Test"
    });
})
app.use(router.routes())
    .use(router.allowedMethods());
const port = 9990;
app.listen(port, () => console.log(`Website already run on ${port}`));
```
The index.marko
```marko
<h1>${input.name}</h1>
```  
But when I run `node index.js` for test, I get nothing in my bowser. And I run `curl localhost:9990`, then I get this ...
![curl](https://user-images.githubusercontent.com/11017232/70591608-ac5cb500-1c11-11ea-9610-e761c25482a0.png)
...and httpie was
![httpie](https://user-images.githubusercontent.com/11017232/70591649-c7c7c000-1c11-11ea-8735-47a8f3ea4cb7.png)

I also try `ctx.body=index.renderSync({name:"Test"})` and other way but nothing change

### Environment
- Linux 4.4.0-18362-Microsoft run in WSL with Windows 10
- node: v12.13.1

package.json
```json
"dependencies": {
    "koa": "^2.11.0",
    "koa-router": "^7.4.0",
    "koa-static": "^5.0.0",
    "marko": "^4.18.28"
  }
```
</details>

**Comment by sakurayang** [comment]
The guide function `app.use(...)` is work so I think it may a middleware so I try `router.use('/' , ...)` 
But it also nothing change

**Comment by tigt** [comment]
What does the `index.marko` file become if you run it manually through [the `marko compile` CLI command](https://github.com/marko-js/cli/blob/master/packages/compile/README.md)?

**Comment by DylanPiercey** [comment]
I've recently updated the lasso-koa example (https://github.com/marko-js/examples/blob/master/examples/lasso-koa/src/server.js) which appears to be working
