### ISSUE TITLE
Serving compiled templates

### ISSUE THREAD

**Issue by xtremespb** [marko-js/marko#1467]
Hello all!

I'm developing a content management system called Zoia which is using Marko as an user space engine to render pages. That's working awesome and I'm using an isomorphic solution to create both client and server pages.

The problem is that all design templates need to be "compiled" directly to a bundle so if user wants to use his own he will need to rebuild the whole package. Is there a way I can use a "second" bundle with templates somehow, or maybe another way: how can I compile a Marko template and serve both HTML and JS of a template? Currently when I'm sending a compiled result of Marko template I only get HTML code without JS.

**Comment by tigt** [comment]
Can you publish any of the code you’re using? Specifically, how you’re compiling and sending Marko templates.

**Comment by xtremespb** [comment]
Yes, sure. That's how I'm rendering templates:

```javascript
import template from './template.marko';
const render = (await template.render({
  content: 'Some sample content',
}));
const html = render.out.stream.str;
```

The `html` output contains only HTML code of compiled template. But as the code is being pre-built by webpack, a generated HTML file contains links to JS files which do all the reactive magic of Marko.

I would like to understand how can I get a "JS" part directly when rendering an HTML, e.g. something like `render.out.js`.

**Comment by tigt** [comment]
So you’re looking to get the associated JavaScript (and/or CSS) files associated with a Marko component? You’ll probably have to call the Marko compiler differently to do so. If using [`marko-cli`’s `compile` package](https://github.com/marko-js/cli/blob/master/packages/compile/README.md):

```sh
marko compile --browser ./components/my-component.marko
```

That said, I’ve only ever done this implicitly via the Webpack plugin. The Marko devs should have more to say about this.

**Comment by DylanPiercey** [comment]
With `marko@5` there is improved support for the cli that it ships with `markoc`. You can use `markoc` to precompile templates, and if you are using `marko/node-require` it will prefer to pick up the precompiled versions.

You can see the docs for `markoc` by running

```
node ./node_modules/.bin/markoc -h
```

Otherwise, the compilation is meant to happen at runtime or at the bundler level.
