### ISSUE TITLE
On global helpers

### ISSUE THREAD

**Issue by taecilla** [marko-js/marko#149]
Hi:

I know that Marko "avoids evil global variables and global helpers", but I think I have a situation where they could be useful:

I'm using Marko in a Koa app. This app uses koa-locale which provides two methods: `this.__(key)`, which looks for the translated text by key, and `this.__getLocale()` which returns the selected language from URL, cookie, HTTP header, sub-domain, etc. So, I have a layout like this one:

    <!doctype html>
    <html lang="${out.global.__getLocale()}">
        <head>
            <meta charset="utf-8"/>
            <meta content="width=device-width" name="viewport"/>
            <link rel="stylesheet" href="styles.css"/>
            <title>${out.global.title}</title>
        </head>
        <body>
            <layout-placeholder name="content"/>
        </body>
    </html>

With a view like:

    <layout-use template="./boilerplate.marko">
        <layout-put into="content">
            <h1>${out.global.__('Welcome!')}</h1>
        </layout-put>
    </layout-use>

And I use them as follow:

    this.response.body = require('../templates/index.marko').renderSync({
        $global: {
            __: this.__.bind(this),
            __getLocale: this.__getLocale.bind(this),
            title: this.__('Welcome!')
        }
    })

Of course, I don't want to pass `this.__()` and `this.__getLocale()` in every router, so I'm wondering if there is a better way to accomplish this.

**Comment by patrick-steele-idem** [comment]
At eBay we are using a very similar approach to handle localization. However, instead of adding additional methods to `out.global` we just pass the `out` object to various helper methods. For example:

```javascript
var locale = getLocale(out);
```

If you are rendering to an HTTP response directly using `template.render({...}, res)` then you can access the underlying response stream and the request object by doing the following:

```javascript
var res = out.stream;
var req = res.req; // Works for Express, not sure if it works for Koa
var locale = getLocaleFromRequest(req);
```

NOTE: For Koa you can render directly to the HTTP response stream by doing the following:

```javascript
app.use(function *() {
  template.render({...}, this.res)
}); 
```

I don't use Koa so I am going by what @jlarsson said in the following issue: https://github.com/marko-js/marko/pull/144

The benefit of this approach is that the developer does not have to explicitly use the `$global` property to add things to `out.global`. The disadvantage is that this approach won't work if you are not rendering directly to an HTTP response stream.

Does the approach described above work for you?

**Comment by patrick-steele-idem** [comment]
Also, you could create a custom compile-time tag to introduce a new JavaScript i18n variable in your template. For example:

```xml
<i18n-var name="i18n"/>

<layout-use template="./boilerplate.marko">
    <layout-put into="content">
        <h1>${i18n.__('Welcome!')}</h1>
    </layout-put>
</layout-use>
```

I think that approach is cleaner. We have a similar taglib for our eBay apps.

**Comment by taecilla** [comment]
Currently I'm using `.renderSync()` just because I'm learning Marko. I plan to start rendering to an HTTP response directly. In any case I think my problem is that koa-locale does its work automatically.
In the first case, if I understand well, you pass the complete output to a helper that replaces some text with its translated version. As far as I know I can't do that because `__(key)` only receives the key to be replaced.

In the second case you are referring to require a JavaScript module, aren't you?

    <require module="./util" var="util" />

The problem with that is that koa-locale receives the app instance as an argument and I don't see a way to do that inside a .marko file.

That's why I was wondering if there's is a a way to pass helpers to the compiled `__helpers` object, maybe before calling `.install()`.

**Comment by patrick-steele-idem** [comment]
Hi @taecilla, sometimes it is just easier to explain in code, so I created a sample app to hopefully make things clearer about what I am proposing. Please check out the following app:

https://github.com/marko-js-samples/marko-koa-i18n

Key notes:

- Enable the `koa-i18n` middleware in your main `server.js` file and add some locales
- Just put `i18n` object into the `out.global` property when you render the page template:

```javascript
this.response.body = require('./template.marko').renderSync({
    $global: {
        i18n: this.i18n
    }
});
```

- Use the `<i18n-var>` tag to add a new JavaScript `i18n` var to your template at compilation time whose value will be `out.global.i18n`

- In your template you can then do the following:

```xml
<i18n-var/>
${i18n.__('hello', data.name)}
```

Does that look like a clean solution to you?

**Comment by yomed** [comment]
@patrick-steele-idem thanks for the transformer example!

**Comment by taecilla** [comment]
Hi again @patrick-steele-idem,

Thanks for your example, it makes things clearer, but you are still passing `i18n` to `$global` every time you render a template and that's why I'm trying to avoid because I'm pretty sure I will do that everywhere. Anyway I think it's just a minor drawback.

**Comment by patrick-steele-idem** [comment]
Hi @taecilla, I only passed in `i18n` using `$global` because you were *not* rendering directly to the HTTP response stream. If you were to do the following:

```javascript
template.render({ ... }, this.response);
```

Then you could access the `i18n` variable as shown below:

```javascript
var response = out.stream;
var koaContext = response.ctx;
var i18n = koaContext.i18n;
console.log(i18n.__('howAreYou'));
```

The easiest way to automatically associate a template rendering with a request/response is to render directly to `this.response`. Alternatively, you could create your own Koa plugin that introduces a `this.renderTemplate(template, templateData)` method for rendering the top-level page template:

```javascript
module.exports = function *() {
    this.renderTemplate(template, { name: 'Frank' });
};
```

Your Koa plugin could then auto-populate any globals into the template data object.

There's alternatives to avoid having to explicitly pass in `$global` everywhere :)

**Comment by Globik** [comment]
Here must be some middleware for koa. Some thing like this:
https://gist.github.com/Globik/d612dce121de3e1cd996

**Comment by tropperstyle** [comment]
@patrick-steele-idem I like your proposal of `i18n-var` so I tried to move it into my `tags-dir` without success:

`Error: Error while handling properties for /app/src/marko-taglib.json: Error while applying option of "tags-dir". Cause: Error: Invalid tag file: /app/src/components/i18n-var/marko-tag.json. Neither a renderer or a template was found for tag.`

marko-tag.json
```
{
    "@name": "identifier",
    "transformer": "./transformer.js"
}
```
This is the same definition [here](https://github.com/marko-js-samples/marko-koa-i18n/blob/master/src/marko-taglib.json#L3) - so shouldn't it work the same?

**Comment by patrick-steele-idem** [comment]
Hey @tropperstyle, it looks like a bad validation check at the following line:
https://github.com/marko-js/marko/blob/56d23b07bdc4ca2a20ebce868a3982277c97c618/compiler/taglibs/taglib-loader/scanTagsDir.js#L89

That line should probably be updated to not throw an error if the tag has a transformer:

```javascript
if (!tagDef.renderer && !tagDef.template && !tagDef.transformer) {
```

Do you want to try it out locally and send a PR if it solves your problem?

Thanks,
Patrick

**Comment by patrick-steele-idem** [comment]
Hey @taecilla, I'm just going through issues to do some housecleaning. I'm going to go ahead and close this issue, but if this is still an issue/question please feel free to add more comments. Thanks.

**Comment by taecilla** [comment]
Hi @patrick-steele-idem. Sorry for the delay and thanks for the input. Just for future reference in case someone has the same doubt: In the end I followed @Globik's advice. I have developed two projects using Koa and Marko in this way and I'm pretty happy with the result.

**Comment by Globik** [comment]
@markschmid  you can wrap any globals into the middleware and assign it  to req.app.locals
Somthing like

var context={};
Object.assign(context,req.app.locals,ops)
