### ISSUE TITLE
keyup stopped working

### ISSUE THREAD

**Issue by rwg726** [marko-js/marko#1492]
### Details

keyup code is no longer being called 

```marko
class {

  onCreate(){
    this.state = {
      val: "",
    }
  }

  keyup(event) {
    let val = this.getEl('filter').value;
    this.getEl('filter').value = val;
    this.emit("filtered", val);
  }
}

form class="filter" onsubmit="return false;" autocomplete="off"
  label class="block" for="cFilter"
      -- Filter list
  input on-keyup("keyup") key="filter" no-update class="filter-input block" type="text" name="cFilter" id="cFilter" placeholder="Type here ..."
  span class="counter block" data-filter-counter
    -- ${input.count} results
```

### Expected Behavior

Keyup should be called when user types in input box

### Actual Behavior

keyup is not getting called

### Possible Fix

no idea - does work in 4.18.35

<details><summary>Additional Info</summary>

### Your Environment

node 12.14.1

### Steps to Reproduce

sorry don't have standalone example
</details>

**Comment by rwg726** [comment]
so maybe related to our use of no-update ?

**Comment by DylanPiercey** [comment]
@rwg726 thanks for reporting the issue. We recently did some changes to improve `no-update` in some cases, however there were a couple of regressions which are now fixed in [`4.18.40`](https://github.com/marko-js/marko/blob/master/CHANGELOG.md#41840). Could you try upgrading and see if the issue persists?

**Comment by rwg726** [comment]
Hi,
same problem on 4.18.40 I'm afraid - I'm new to marko - but I have our expert in tomorrow - might well not be marko - thanks

**Comment by DylanPiercey** [comment]
Alright, thanks for checking. I will try to set aside some time today to reproduce the issue with the above code.

**Comment by rwg726** [comment]
thanks for closing - our dev says the error is elsewhere!
