### ISSUE TITLE
Compiled templates in /tmp/ throw error "Error: Cannot find module 'marko'".

### ISSUE THREAD

**Issue by Bouncr** [marko-js/marko#150]
I'm trying to get marko work for me in amazon AWS Lambda.
As Lambda gives the process limited writing rights, I can only write to /tmp/ and compiled templates throw error "Error: Cannot find module 'marko'". With http://markojs.com/docs/marko/compiler/ I can get the whole CommonJS module -output into a variable but how do I run it straight from there? Would be awesome to get the whole compiled html output of the template to a buffer/string. Thanks!

**Comment by patrick-steele-idem** [comment]
New version published: `marko@2.7.25`

Here's what you can do to prevent compiled templates from being written to disk:

First install the latest version of marko:

```bash
npm install marko@marko@^2.7.25
```

Then in your main script change the default compiler options to disable writing compiled templates to disk:

```javascript
require('marko/compiler').defaultOptions.writeToDisk = false; 
```

Thanks for reporting the issue. Let us know if you run into any other problems.
