### ISSUE TITLE
for-loop issues

### ISSUE THREAD

**Issue by ricagurgel** [marko-js/marko#1508]
### Details

this is not my real code, this is only a test.

I trying to do a simple string concatenation inside a for loop, to make a 6 digit random color. But it's impossible

it's seem to be variables inside for loop is not global, and everything generated inside for-loop cant be use belong template

### How to fix
make for-loop global

<details><summary>Additional Info</summary>

node 12/10, chrome, mac os x or ubuntu

### code example:
$ const colors = ["5","6","7","8","9","A","B","C","D","E"]
$ var color = "#"
$ var colorb = "aa"
$ var color = color+colorb
<for|i| from=1 to=6>
    $ var bb = colors[i]   
	$ var color = color+bb
    <p>${bb} - ${color}</p>
</for>
<ul>
<li style={ color: color }>
        ${color}
</li>
</ul>
![Captura de Tela 2020-02-23 às 16 07 21](https://user-images.githubusercontent.com/7705137/75118195-bd389680-5656-11ea-9187-458f18f13094.png)

</details>

**Comment by ricagurgel** [comment]
![Captura de Tela 2020-02-23 às 16 07 21](https://user-images.githubusercontent.com/7705137/75118208-d6414780-5656-11ea-9962-4d75fa60ec6b.png)

**Comment by DylanPiercey** [comment]
Loops in Marko are run in a new function scope (think of them like `.map`, `.filter`, `.reduce` instead of a traditional `for (...) {` loop.

In the above if you avoid shadowing the `color` variable you will not have an issue. eg:

```marko
$ const colors = ["5","6","7","8","9","A","B","C","D","E"]
$ var color = "#"
$ var colorb = "aa"
$ var color = color+colorb
<for|i| from=1 to=6>
  $ var bb = colors[i]
  $ color = color+bb
  <p>${bb} - ${color}</p>
</for>
```
