### ISSUE TITLE
Spread operator used in HTML tag makes interpreter treat attributes and change its names

### ISSUE THREAD

**Issue by javierlatorrep** [marko-js/marko#1529]
### Details

Having a component component.marko that prints an svg... 
```
$ const { className = "whatever", ...props } = input;

<svg
  class=className
  viewBox="0 0 100 19"
  ...props
>
...
</svg>
```

### Expected Behavior

The HTML output without props should be 
```
<svg
  class="whatever"
  viewBox="0 0 100 19"
>

```
### Actual Behavior

viewBox -> view-box

```
<svg
  class="whatever"
  view-box="0 0 100 19"
>

```
### Your Environment

- Chrome 80.0.3987.132
- macOS Mojave 10.14.5 (Desktop)

I've tryed using marko.json to avoid this behaviour but I've not been able to make it work

**Comment by DylanPiercey** [comment]
Fixed in `4.19.6`. Thanks for raising the issue!
