### ISSUE TITLE
Marko's handling of <template> tag results in stale templates

### ISSUE THREAD

**Issue by atsepkov** [marko-js/marko#1547]
### Details

Wrap some updating marko-generated content inside `<template>` tag. Attempt to reference this content later via JavaScript (`document.getElementById(idOfTemplate).innerHTML`). It's possible that other properties/methods are also affected, not just innerhHTML/innerText). The content will receive the first update, but not subsequent ones (tested in Chrome and Firefox).

### Expected Behavior

Content receives all updates, not just the first one.

### Actual Behavior

Upon further inspection, it looks like the issue may be with browser handling `<template>` element differently. After a while I realized that the DOM tree is showing 2 child elements for marko-generated `<template>` instead of the one that should be.

### Possible Fix

Per HTMLTemplateElement spec (https://developer.mozilla.org/en-US/docs/Web/API/HTMLTemplateElement), it looks like this element wraps the content in an additional `DocumentFragment` element, which seems to be ignored by Marko but not the DOM. It looks like Marko is creating another child under this element, DOM's methods ignore this 2nd child, Marko ignores the 1st child. A possible workaround for this currently is to use `template.children[1].innerHTML` instead of `template.innerHTML`. Ideally the 2 elements should get consolidated, but I'm not an expert in Marko so not sure if the cleaner solution is for Marko to keep replacing the first child (DocumentFragment) with its own content or learn to update the subtree withing the DocumentFragment itself. When looking at this wrapping, `<iframe>` element comes to mind, which similarly wraps `contentDocument` property (seems like the same idea except that it's a `Document` instead of `DocumentFragment`.

<details><summary>Additional Info</summary>

### Your Environment

- Tested on Chrome 80.0.3987.116 and Firefox 75.0
- Linux (Ubuntu 19.10)

### Steps to Reproduce

Simple example:

```
class {
  onCreate() {
    this.state = { counter: 0 }
  }

  update() {
    this.state.counter++;
  }

  onUpdate() {
    document.getElementById('myIframe').srcdoc = document.getElementById('myTemplate').innerHTML;
  }
}

<div>
  <template id="myTemplate">
    <div>${state.counter}</div>
  </template>
  <iframe id="myIframe">
  <button on-click('update') />
</div>
```

### Stack Trace

N/A

</details>

**Comment by tigt** [comment]
Original conversation: https://gitter.im/marko-js/marko?at=5e93b36a9316f34b8d9992bf

**Comment by DylanPiercey** [comment]
I think adding support for updating template element content is outside of Marko's scope.
Marko is primarily intended for updating live DOM. The other thing Is you can't easily serialize the `innerHTML` from this template since it will not come with any event handlers or anything setup.
