### ISSUE TITLE
Inline javascript is executing on the server

### ISSUE THREAD

**Issue by retrohacker** [marko-js/marko#1553]
### Details

When I inline javascript in my templates, I see it execute during compilation.

```marko
$ console.log("hai")

<html><body>Hello World</body></html>
```

### Expected Behavior

Should see `hai` in the browser's console

### Actual Behavior

I see `hai` in the server logs during compilation.

<details><summary>Additional Info</summary>

### Your Environment

- Environment name and version (e.g. Chrome 39, node.js 5.4): Firefox 75.0 64-bit v10.20.1
- Operating System and version (desktop or mobile): Debian 10 - Linux 4.19.98-1

### Steps to Reproduce

1.  `marko create test`
2.  Open `src/index.marko` and add `$ console.log("hai")`
3.  `cd test && npm start`
4.  Load page in browser

### Stack Trace

```text
> test@1.0.0 start /home/retrohacker/Development/test
> marko-starter server

[browser-refresh] Watching: /home/retrohacker/Development/test
[browser-refresh] Ignore rule: # OS
[browser-refresh] Ignore rule: *.swp
[browser-refresh] Ignore rule: .DS_Store
[browser-refresh] Ignore rule: # Editor Configs
[browser-refresh] Ignore rule: .idea
[browser-refresh] Ignore rule: .vscode
[browser-refresh] Ignore rule: *.sublime*
[browser-refresh] Ignore rule: # Generated Files
[browser-refresh] Ignore rule: dist
[browser-refresh] Ignore rule: .cache
[browser-refresh] Ignore rule: coverage
[browser-refresh] Ignore rule: .nyc-output
[browser-refresh] Ignore rule: *.marko.js
[browser-refresh] Ignore rule: .marko-cli
[browser-refresh] Ignore rule: .marko-devtools
[browser-refresh] Ignore rule: # NPM
[browser-refresh] Ignore rule: node_modules
[browser-refresh] App started (pid: 11655)
[marko-starter plugins] Installed plugin: lasso
[marko-starter plugins] Installed plugin: generic-http-server

NOTICE
The module [@lasso/marko-taglib] is using deprecated features.
Run with process.env.SHOW_MODULE_COMPLAINS=1 to see all warnings.

[marko-starter marko-starter-demo] Starting server...
[marko-starter marko-starter-demo] 
CONFIGURATION:
  name: marko-starter-demo
  routePathPrefix: /
  version: 0.0.0
  dir: /home/retrohacker/Development/test
  buildNumber: 0
  colors: true
  minify: (not set)
  minifyCss: (not set)
  minifyJs: (not set)
  fingerPrintsEnabled: (not set)
  production: false
  flags: (not set)
  outputDir: /home/retrohacker/Development/test/.cache/static
  staticUrlPrefix: /static/
  plugins: (not set)
  lassoConfig: (not set)
  httpPort: 8080
  sslCert: (not set)
  sslKey: (not set)
  routeNotFound: (not set)
[marko-starter marko-starter-demo lasso] Configured default lasso
[marko-starter marko-starter-demo http-server] [route] OPTIONS /static/**
[marko-starter marko-starter-demo http-server] [route] GET     /static/**
[marko-starter marko-starter-demo http-server] [route] GET     /
[marko-starter marko-starter-demo http-server] [route] GET     /hello/:name
[marko-starter marko-starter-demo http-server] [route] GET     /layouts
[marko-starter marko-starter-demo http-server] LISTENING ON: http://localhost:8080
[browser-refresh] Server is ready. Watching files for changes.
[marko-starter marko-starter-demo http-server request] GET /
[marko-starter marko-starter-demo] Building page /...
hai
[marko-starter marko-starter-demo] Finished building page /
```
</details>

**Comment by mlrawlings** [comment]
This log comes [right before](https://github.com/marko-js/marko-starter/blob/b80b4eabe8fcf51a30ee360148285f7b989fef3d/src/util/buildRoute.js#L22) rendering the page.
```
[marko-starter marko-starter-demo] Building page /...
```

That log might be a bit misleading: it's not actually logging during compilation, but during rendering.  Since the template is initially rendered on the server, seeing the log in the node console is expected.

Only components that can actually update or have client-logic are sent to the browser.  The heuristic used to determine this is whether the component uses `class {}`, `component.js` or `component-browser.js`.  This is why you don't see the log in the browser.

If you wanted to see the log in the browser only, you could do this instead:
```marko
class {
  onMount() {
    console.log("hai");
  }
}

<html><body>Hello World</body></html>
```

**Comment by retrohacker** [comment]
Thanks for the quick reply :heart:

> That log might be a bit misleading: it's not actually logging during compilation, but during rendering. Since the template is initially rendered on the server, seeing the log in the node console is expected.

:exploding_head:
