### ISSUE TITLE
Unable to use modules w/ spread operator

### ISSUE THREAD

**Issue by retrohacker** [marko-js/marko#1567]
### Details

`index.marko`

```
class {
  onCreate() {
  }
  onMount() {
    const ky = require('ky/universal')
  }
}

<h1>hai world</h1>
```

This results in:

```
[marko-starter marko-starter-demo] Building page /...
[marko-starter marko-starter-demo] Error building page /. Error: Error: Error: Failed to walk dependency [marko-hydrate: path=".../src/index.marko"]. Dependency chain: [marko-hydrate: path=".../src/index.marko"]. Cause: Error: Failed to walk dependency [marko-dependencies: path=".../src/index.marko"]. Dependency chain: [marko-hydrate: path=".../src/index.marko"] → [marko-dependencies: path="...src/index.marko"]. Cause: Error: Failed to walk dependency [marko-dependencies: path=".../src/components/landing-layout/index.marko"]. Dependency chain: [marko-hydrate: path=".../website/src/index.marko"] → [marko-dependencies: path=".../src/index.marko"] → [marko-dependencies: path=".../src/components/landing-layout/index.marko"]. Cause: Error: Failed to walk dependency [marko-dependencies: path=".../src/components/layout/index.marko"]. Dependency chain: [marko-hydrate: path=".../src/index.marko"] → [marko-dependencies: path=".../src/index.marko"] → [marko-dependencies: path=".../src/components/landing-layout/index.marko"] → [marko-dependencies: path=".../src/components/layout/index.marko"]. Cause: Error: Failed to walk dependency [require: .../src/components/layout/index.marko.register.js]. Dependency chain: [marko-hydrate: path=".../src/index.marko"] → [marko-dependencies: path=".../website/src/index.marko"] → [marko-dependencies: path=".../src/components/landing-layout/index.marko"] → [marko-dependencies: path=".../src/components/layout/index.marko"] → [require: .../src/components/layout/index.marko.register.js]. Cause: Error: Failed to walk dependency [require: ./]. Dependency chain: [marko-hydrate: path=".../src/index.marko"] → [marko-dependencies: path=".../src/index.marko"] → [marko-dependencies: path=".../src/components/landing-layout/index.marko"] → [marko-dependencies: path=".../src/components/layout/index.marko"] → [require: .../src/components/layout/index.marko.register.js] → [require: ./]. Cause: Error: Failed to walk dependency [require: ky/umd]. Dependency chain: [marko-hydrate: path=".../src/index.marko"] → [marko-dependencies: path=".../src/index.marko"] → [marko-dependencies: path=".../src/components/landing-layout/index.marko"] → [marko-dependencies: path=".../src/components/layout/index.marko"] → [require: .../src/components/layout/index.marko.register.js] → [require: ./] → [require: ky/umd]. Cause: SyntaxError: node_modules/ky/umd.js(73,21): Unexpected token ...
  71 |                                  }
  72 | 
> 73 |                                  returnValue = {...returnValue, [key]: value};
     |                                                 ^
  74 |                          }
  75 |                  }
  76 |          }
    at module.exports (.../node_modules/raptor-util/createError.js:7:50)
    at walkDependency (.../node_modules/lasso/src/dependency-walker.js:123:23)
    at process._tickCallback (internal/process/next_tick.js:68:7
```

When using the config:

```js
const marko = require("marko-starter");
marko.plugins(['marko-starter-babel']);
module.exports = marko.projectConfig({
  name: "marko-starter-demo"
});
```

<details><summary>Additional Info</summary>

### Your Environment

- Environment name and version (e.g. Chrome 39, node.js 5.4):
- Operating System and version (desktop or mobile):
- Link to your project:

### Steps to Reproduce

1.  first...
2.
3.
4.

### Stack Trace

</details>

**Comment by DylanPiercey** [comment]
@retrohacker it looks like the issue is that babel is not being loaded and lasso by default does not understand the `...spread` inside objects. https://github.com/marko-js/marko-starter-babel should allow you to add `babel` along side `preset-env` which should make this work.

Having said all that, we are getting closer to beginning to phase out `marko-starter` with our simpler `webpack` based setup that currently ships with `marko-cli` (https://github.com/marko-js/cli).

Specifically you should check out the [`serve`](https://github.com/marko-js/cli/blob/master/packages/serve/README.md) and [`build`](https://github.com/marko-js/cli/blob/master/packages/build/README.md) commands. It's a bit rough around the edges but we are hoping to give it the polish it needs in the coming weeks and we're happy to help with any issues!

**Comment by retrohacker** [comment]
Heya! I appreciate the quick response!

I've run into some problems trying to get `marko serve` to work. I'm struggling to understand what you mean by

> should allow you to add babel along side preset-env which should make this work.

The readme in that repo just shows adding it to the plugins for marko-starter.

**Comment by retrohacker** [comment]
Doing a bit of digging, I don't see an opportunity to pass configuration down into the plugin:

https://github.com/marko-js/marko-starter/blob/master/src/plugin-manager.js#L41

**Comment by retrohacker** [comment]
Ah, it's pulled by the plugin:

https://github.com/marko-js/marko-starter-babel/blob/master/index.js#L31

**Comment by retrohacker** [comment]
Ahhh, it looks like fashion-model looks for `babelConfig` key on the `projectConfig` object. Making progress I think!

**Comment by retrohacker** [comment]
Cool, it looks like transpiling is now working, but there is a version mismatch between `@babel/preset-env` and the `babel-core` that ships w/ `lasso-babel-transform`.

It looks like `babel-core` has moved to `@babel/core`.

**Comment by retrohacker** [comment]
Cool beans. So after: https://github.com/marko-js/marko-starter-babel/pull/2

To support the latest syntax you need to:

```sh
$ npm install --save @babel/core @babel/preset-env marko-starter-babel
```

And update the `project.js` file to:

```js
module.exports = require("marko-starter").projectConfig({
  name: "marko-starter-demo", // Optional, but added here for demo purposes
  plugins: ["marko-starter-babel"],
  babelConfig: {
    babelOptions: {
      presets: [
        ["@babel/preset-env"]
      ]
    },
    extensions: [".js"]
  }
});
```

**Comment by DylanPiercey** [comment]
Sounds like you've got this all set up, great!

I'll also mention that if you do switch to `@marko/serve` as I mentioned in https://github.com/marko-js/marko/issues/1452#issuecomment-582149223, it comes with babel built-in and so you should be able to just move your `babelOptions` object into a `babel.config.js` file and it would work out of the box.
