### ISSUE TITLE
Repeated attribute tag has inconsistent target property name

### ISSUE THREAD

**Issue by cynthiahhc** [marko-js/marko#1571]
### Details

For the `<option-description>` , it is supposed to be `optionDescription` as an input after compiling. However, it is showing as `option-description`. It compiled correctly if `<option-description>` removed the <for> tag

If I put `<option-description>` under `<for>` to loop through all the description, it would show `option-description` as an input. However, if I removed `<for>` and typed out `<option-description>` one by one, the input will be `optionDescription` which can be rendered correctly.

```json
{
        "@option-content <option-content>[]": {
            "@option-key": "string"
        },
        "@option-description <option-description>[]": {
            "@option-key": "string"
        }
}
```

### Expected Behavior

It should compile to the same input name no matter if there is a `<for>` wrapped around it.

### Actual Behavior

It compiles different under `<for>`

<details><summary>Additional Info</summary>

### Your Environment

- Environment name and version (e.g. Chrome 39, node.js 5.4): node 10.19.0
- Operating System and version (desktop or mobile): desktop
</details>

**Comment by DylanPiercey** [comment]
Fixed via #2115
