### ISSUE TITLE
dynamic class fontawesome not working

### ISSUE THREAD

**Issue by marcstreeter** [marko-js/marko#1575]
### Details

So I wish to display an icon based on details that should be present server side.  Whenever I attempt to display dynamic icons though it acts as if it hasn't loaded the assets/fonts necessary.

### Expected Behavior

I expect this to render icons available server side.

### Actual Behavior

when any dynamic behavior is present it does not render the icon

### Possible Fix

I'm new to Marko - probably is a misunderstanding that I have failed to locate in the documentation.

<details><summary>Additional Info</summary>

### Your Environment
I wonder if this is at all related to https://github.com/marko-js/marko/issues/1098

### Steps to Reproduce
```
            <for|artifact, idy| of=artifacts>
            <a href=artifact.url class:no-update="panel-block">
              <span class="panel-icon">
                <i class=`fas fa-${fileIconMap[artifact.type] || 'file'}` aria-hidden="true"></i>
              </span>
              ${artifact.name}
            </a>
            </for>
```

so the line `<i class="fas fa-${..../"></i>` is where I'm having the problem. If I put a hardcoded string it loads properly. If I try to dynamically apply a string it acts as if it hasn't loaded those font awesome icons.

### Stack Trace

</details>

**Comment by tigt** [comment]
Does it work if you use the dynamic `class` syntax like this?

```marko
<i class=['fas', `fa-${fileIconMap[artifact.type] || 'file'}`]></i>
```

**Comment by marcstreeter** [comment]
using the before syntax and the dynamic `class` syntax both produce
![image](https://user-images.githubusercontent.com/5916490/84819813-3ed57b00-afde-11ea-9ceb-ffd34f835232.png)

the icon's still don't display though ¯\_(ツ)_/¯

**Comment by marcstreeter** [comment]
ok so I took away the `...` bit completely and did it outside of the template and it's happy again.  Thank you for giving me some ideas.

**Comment by marcstreeter** [comment]
well, I take that back. It's not working still.  I got it working by doing this:

```
artifacts = [
            {
              name: 'poodle.txt',
              type: 'txt',
              icon: 'fa-text',
            },
            {
              name: 'contis.bat',
              type: 'bat',
              icon: 'fa-book',
            },
            {
              name: 'fontain.gz',
              type: 'gz',
              icon: 'fa-file',
            },
            {
              name: 'odurin.txt',
              type: 'txt',
              icon: 'fa-file-archive'
            },
          ]
```
but those just represent some trash variables. When I finally moved in the code that will generate that array it still doesn't want to load the icons... I thought, maybe it was my use of interpolated strings so I removed that. Any dynamic icons break this setup.

**Comment by marcstreeter** [comment]
to be clear, removing string interpolation didn't help.

**Comment by DylanPiercey** [comment]
@marcstreeter how are you loading the fonts/icons? Are you sure they are loaded in the browser?

**Comment by marcstreeter** [comment]
@DylanPiercey after dealing with another bug that was very similar to this - I believe it is not Marko but rather how we are loading our fonts and icons (just as you've mentioned). Closing

**Comment by DylanPiercey** [comment]
Thanks for the update @marcstreeter 🙂
