### ISSUE TITLE
High Performance Java Rendering Library

### ISSUE THREAD

**Issue by sirinath** [marko-js/marko#1582]
### Description

Is it possible to provide a high-performance Java serverside rendering library so it can be used when the server-side is not NodeJS?

### Why

Server-side may not always be NodeJS.

Users using other web frameworks other than Node can benefit.

**Comment by cameronbraid** [comment]
You may wish to see if you use markojs in https://www.graalvm.org/

**Comment by cameronbraid** [comment]
You can always use something like https://vertx.io/ or https://moleculer.services/ to run markojs rendering system out of process using a rpc layer.

**Comment by DylanPiercey** [comment]
I think @cameronbraid answered this well. We don't currently have any plans to officially support using Marko templates within a Java app.
