### ISSUE TITLE
body-only-if deprecated - replacement is inadequate

### ISSUE THREAD

**Issue by cameronbraid** [marko-js/marko#1619]
marko 4.23.9

I am getting this deprecation warning

```
#17 261.8 MIGRATION
#17 261.8 The "body-only-if(x)" tag is deprecated. Please use "<${test ? null : tag>" instead. See: https://github.com/marko-js/marko/wiki/Deprecation:-body‐only‐if
```

The issue is that using the proposed syntax produces and error.

example, I use the following deprecated, but working, syntax :
```
        <ToolTip body-only-if(tooltipHtml)>
            <@tooltip>$!{tooltipHtml}</@tooltip>
            <div>Some Content that always shows</div>
        </>
```

When I migrate to the following I get an error that  `<@tooltip>` cannot be used outside a custom tag - in the case where `tooltipHtml` is null

```
        <${tooltipHtml && "ToolTip"}>
            <@tooltip>$!{tooltipHtml}</@tooltip>
            <div>Some Content that always shows</div>
        </>
```

Also the `body-only-if` is a much neater and easier to read syntax :)

**Comment by mlrawlings** [comment]
The dynamic tag syntax will render a DOM element instead of a Marko Component when a string is passed, which is why you see the error about `<@tooltip>` being used outside a custom tag.  You'll need to import the tag when it's used with the dynamic tag syntax so you're passing a component rather than a string.

```marko
import ToolTip from "<ToolTip>";

<${tooltipHtml && ToolTip}>
     <@tooltip>$!{tooltipHtml}</@tooltip>
     <div>Some Content that always shows</div>
</>
```
