### ISSUE TITLE
renderToString bug

### ISSUE THREAD

**Issue by tevel** [marko-js/marko#1621]
Create new component with two files:

index.marko:

`<span ${component.model.aaa}></span>`

component.js:

```
module.exports = class {
    onCreate(input) {
        this.model = {aaa = 'bbb’};
    }
};
```

Render this component by using renderToString()

Expected results: <span aaa=bbb></span>
Actual results: <spanaaa=bbb></span>

"marko": "^4.23.9",

Workaround: change index.marko:
`<span bugFixPleaseDontRemove ${component.model.aaa}></span>`

Actual results: <span aaa=bbb></span>

**Comment by DylanPiercey** [comment]
The dynamic attribute syntax is deprecated. Also with that syntax you are required to add the spacing yourself, eg `” bbb”`.

Please switch to the modern spread attribute syntax which does not have this issue. https://markojs.com/docs/syntax/#dynamic-attributes

```marko
<span ...component.model.aaa></span>
```

**Comment by tevel** [comment]
cool, thank you!
