### ISSUE TITLE
Add a load option forceRecompile to force loader recompile template instead of using cache

### ISSUE THREAD

**Issue by lanyusan** [marko-js/marko#1624]
### Description

Support property `forceRecompile` of `options` argument  of marko loader `function load(templatePath, templateSrc, options) ` and update loader code to check if the property, `forceRecompile` is set to `true` , then recompile template,  i.e. `if( options && options.forceRecompile) recompile else useCache` 

### Why

I have a project that in a safe environment, internal web authors would use a web editor to edit marko template, primarily look and feel, static html and some basic template functions, save the content, then a preview server of marko engine would load the updated template from web, recompile it and generate preview.

Now the current marko loader always checks cache by file path and name and load compiled template if the template file was already compiled before even if the template file has been modified. So updated template **wouldn't** be rendered when refreshing preview page.

My use case is a production server for marko template authors to edit templates through web editor and update preview by refreshing preview page. So it is **NOT** an option to use `browser-refresh`. 

My preview server knows if a marko tempate at remote location has been modified. It would retrieve it and then force marko loader to recompile the marko template when user refresh preview page if this feature is implemented.

### Possible Implementation & Open Questions

Update loader functions to check `options` argument's `forceRecompile` property and skip loading from cache if set true.

### Is this something you're interested in working on?

**I have developed and tested it and would be happy to submit a PR.**

**Comment by DylanPiercey** [comment]
I think my main issue with this is that in a lot of cases when you load a compiled template, many other templates get loaded as well. I think a simpler approach here would just be to manually invalidate the require cache. You can run something like this:

```js
for (const file in require.cache) {
  if (file.endsWith(".marko")) {
      delete require.cache[file];
  }
}
```
