### ISSUE TITLE
Docs/Upgrade is outdated

### ISSUE THREAD

**Issue by Enteleform** [marko-js/marko#1629]
The [`https://markojs.com/docs/getting-started`](https://markojs.com/docs/getting-started) documentation version defaults to `5.0.0-next.39`.

[`Guides / Marko 4 upgrade`](https://marko-v4.github.io/docs/marko-4-upgrade/) has information detailing the migration process from `3.x` to `4.x`, which seems to be an artifact of the `4.21.9` documentation.

The `5.0.0-next.39` documentation should detail the migration process from `4.x` to `5.x`.

**Comment by DylanPiercey** [comment]
https://markojs.com/docs/marko-5-upgrade/
