### ISSUE TITLE
Mention isomorphism in readme

### ISSUE THREAD

**Issue by wheresrhys** [marko-js/marko#163]
Would be useful to be able to tell from reading the first paragraph of the readme whether mark is server, client side or both. I guess it's both, but if it was mentioned I would feel more confident trying marko out

**Comment by patrick-steele-idem** [comment]
Good catch. Marko is isomorphic and works on the server (Node.js) and in any browser. You will need a JavaScript module bundler (browserify, [Lasso.js](https://travis-ci.org/lasso-js/lasso), etc.) to transport the compiled templates to the browser and everything will work exactly as it does on the server. I'll update the README and website to make this clear. Thanks for letting us know.

**Comment by patrick-steele-idem** [comment]
Website updated. Please let us know if you see any other issues with the website or docs. Thanks again.

**Comment by wheresrhys** [comment]
Excellent - thanks. So far, after 1 evening, I'm a big marko fan - the most comprehensible compiled templates I've ever come across - great for debugging

**Comment by patrick-steele-idem** [comment]
Great. Thanks for the feedback, @wheresrhys!
