### ISSUE TITLE
ZOIA Content Management System built on top of Marko

### ISSUE THREAD

**Issue by xtremespb** [marko-js/marko#1639]
### Description

Hi guys, I would like to introduce my CMS which is built on top of Node, Marko, Fastify, MongoDB and Bulma: [ZOIA](https://github.com/xtremespb/zoia).

It supports internationalization and server-side rendering out of the box and already has a lot of features so you'll be able to build your website or service with ease.

### Why

Because Marko is awesome and you'll certainly need a good example before you'll start using it.

Actually that's the biggest benefit.

### Possible Implementation & Open Questions

Check out the [live demo](https://demo.zoiajs.org/) (built on top of the latest master version of ZOIA, currently I'm trying to implement CI/CD). Use "admin"/"password to log in, feel free to go directly to the [Admin Panel](https://demo.zoiajs.org/admin).

There are still many open questions and topics to discuss.

### Is this something you're interested in working on?

The project is open source and licensed under the MIT license. Please feel free to contribute.

**Comment by DylanPiercey** [comment]
@xtremespb I'm going to close this one. If you like though it'd be great to share this in the #i-made-this channel on our discord!
