### ISSUE TITLE
Is it possible to add js and less file to the components/taglibs?

### ISSUE THREAD

**Issue by leonli** [marko-js/marko#164]
@patrick-steele-idem Is it possible to add js and less file to the components/taglibs? 

I've tried `<lasso-page name="hello" package-path="./browser.json"/>` and someway similar to it, I found that only one `lasso-page` tag would be work. 

is that a possible way to get `lasso` and `marko taglib` working together to support the dependencies which would be required by the component/taglib itself?

**Comment by patrick-steele-idem** [comment]
Hey @leonli, sorry for the delayed response, but better late than never...

What I found works well is to also require non-JavaScript module dependencies in your component's `index.js` file as shown in the following code:
https://github.com/marko-js-samples/ui-components-playground/blob/63cf6d30928d28060d293bbae1c171f598adc506/src/components/app-button/index.js#L1

Also, if you put a `browser.json` next to an included JavaScript module then it will automatically be processed and all of the referenced client-side dependencies will be included.

That way, if the UI component is sent to the browser then the required CSS will also be included. Also, all of the required client-side dependencies for nested UI component's will be included automatically when you bundle up the root UI component.

Does that answer your question or do you have another more specific suggestion on how to improve how CSS dependencies are included.

**Comment by patrick-steele-idem** [comment]
Hey @leonli, I'm just going through issues to do some housecleaning. I'm going to go ahead and close this issue, but if this is still an issue/question please feel free to add more comments. Thanks.

**Comment by leonli** [comment]
@patrick-steele-idem sure
