### ISSUE TITLE
Marko Beautify is not working on VS Code anymore

### ISSUE THREAD

**Issue by xtremespb** [marko-js/marko#1655]
The [Marko Beautify](https://marketplace.visualstudio.com/items?itemName=buster.marko-beautify&ssr=false#qna) plugin is not working with VS Code anymore.

I think that's something what's related to the Marko 5:

```
Error: Cannot find module 'marko/src\compiler\CodeWriter'
Require stack:
- c:\Users\mmatveev\Documents\Git\zoia\src\modules\core\web\images\noop.js
```

**Comment by DylanPiercey** [comment]
@xtremespb I just refactored and updated the Marko vscode plugin to use the latest vscode apis and it seems to have fixed the issue for me. I've released a new version of the package that should be available shortly. If you could try that out and let me know if that fixed your issue that'd be great!

**Comment by DylanPiercey** [comment]
Should be fixed now.
