### ISSUE TITLE
Lasso-express example doesn't support async/await

### ISSUE THREAD

**Issue by DavidBernal** [marko-js/marko#1662]
### Marko Version: ^5.0.0

```
├─┬ lasso@3.4.0
│ └── marko@4.23.14 
└── marko@5.1.17 
```
### Details

Create lasso-express example app:
```
npx @marko/create
```
Select lasso-express on selector.

Open `server.js` and add a new middleware with async. 

### Expected Behavior

Should works normally

### Actual Behavior

Throws an babel error about generators

### Possible Fix

I try to add node12 as preset on babel config file, but then throw a new error. :-/

Also, is lasso best option to SSR? Webpack example works correctly.

**Comment by DylanPiercey** [comment]
https://github.com/marko-js/examples/blob/master/examples/lasso-express/babel.config.js#L2

Should probably change to:

```js
  presets: [["@babel/preset-env", { targets: { node: "current" } }]]
```

Could you test that out?

**Comment by DylanPiercey** [comment]
I'll also add that we are currently recommended using our webpack setup for new apps (see https://github.com/marko-js/examples/tree/master/examples/webpack-express) or `npx @marko/create --template webpack-express`

**Comment by DavidBernal** [comment]
@DylanPiercey with your change it works. Thank you. I will try webpack version with more detail :)

**Comment by DylanPiercey** [comment]
Awesome :). I'll update the lasso examples accordingly.

**Comment by DylanPiercey** [comment]
Fixed!
