### ISSUE TITLE
Unquoted HTML attribute values sometimes contain equal signs, which is invalid HTML

### ISSUE THREAD

**Issue by msendlakowski** [marko-js/marko#1671]
### Marko Version: x.x.x
4.23.11

### Details

If you create a template with a dom node that contains an attribute whose value contains an equal sign, the attribute value should be in quotes. 

### Expected Behavior
```
<a href="test?a=b">test</a>
```

### Actual Behavior

```
<a href=test?a=b>test</a>
```

### Your Environment

This was pointed out during an a11y audit. 

### Steps to Reproduce

1.  Create a template that sets a url string like "https://www.ebay.com?a=b" to a variable
2.  Set that variable on the href of a link: `<a href=myVariable>test</a>`
3. Render the template and the attribute value will not be wrapped in quotes
4.

### Stack Trace

</details>

**Comment by taylor-hunt-kr** [comment]
Can confirm this also makes security scan tools freak out with the trailing `==` Base64 padding on `integrity` attributes

**Comment by vwong** [comment]
This issue is still present in Marko 5.19.0.
While not technically valid HTML, browsers (and presumably bots too) seem to parse it fine.
Would be nice to have it fixed though...

**Comment by DylanPiercey** [comment]
This is something we are open to changing but in general our goal has been to output standards compliant html that is as small as possible. In this case [according to the spec](https://html.spec.whatwg.org/#:~:text=This%20is%20an%20unexpected%2Dcharacter%2Din%2Dunquoted%2Dattribute%2Dvalue%20parse%20error.%20Treat%20it%20as%20per%20the%20%22anything%20else%22%20entry%20below.) the `=` will cause the parser to go into an error state, but non the less treat the character as a part of the attribute value.
