### ISSUE TITLE
NectarJS & AssemblyScript compatibility

### ISSUE THREAD

**Issue by sirinath** [marko-js/marko#1680]
Is it possible to test and maintain compatibility with [NectarJS](https://github.com/NectarJS/nectarjs) & [AssemblyScript](https://www.assemblyscript.org/)

**Comment by DylanPiercey** [comment]
These are not tools we are actively using and I'm not sure what specific support would be required. We're happy to help with any integration if the scope is relatively limited though or if it is heavily requested.

For now I believe this is out of scope though.
