### ISSUE TITLE
Add documentation for "template-data" and "c-input" attributes

### ISSUE THREAD

**Issue by patrick-steele-idem** [marko-js/marko#17]
Example:

```html
<some-component c-input="{ message: 'Hello World' }"/>
```

_src/components/some-component/renderer.js:_

```javascript
module.exports = function render(input, out) {
   var message = input.message; // 'Hello World'
}
```

"template-data" is similar, but it only works for includes. Only one should be documented for consistency.

**Comment by kristianmandrup** [comment]
Yes please :)

**Comment by patrick-steele-idem** [comment]
FYI, in Marko v3 we are moving to the following syntax:

```xml
<some-component({message: 'Hello World' })/>
<some-component(data.someObject)/>
```

Will keep issue open because we still need to update the docs.
