### ISSUE TITLE
onMount is called twice on a page load. 

### ISSUE THREAD

**Issue by treeder** [marko-js/marko#1705]
### Details

onMount called twice. 

### Expected Behavior

onMount called once.

### Actual Behavior

onMount called twice.

### Steps to Reproduce

Make a component with `index.marko`, can have anything in it and a `component-browser.js` with:

```
module.exports = class {
    onMount() {
        console.log("onMount");

    }
    onUpdate() {
        console.log("onUpdate");
    }
}
```

onMount is logged twice.

**Comment by DylanPiercey** [comment]
@treeder are you able to share a simplified reproduction repo?
