### ISSUE TITLE
TypeScript: Support types in Marko's parser

### ISSUE THREAD

**Issue by ryansolid** [marko-js/marko#1707]

**Comment by vovanrew** [comment]
Hey @ryansolid. Is there a way to overcome the following typescript error when loading .marko files?
e.g I have `import indexTemplate from "./views/index.marko";`

And receive the following error on `tsc` output:
`Cannot find module './views/index.marko' or its corresponding type declarations.`

**Comment by ryansolid** [comment]
You can probably set of a declaration file that just ignores them for now like people do with .css types etc.. I haven't tried this myself for marko files but something this:
```ts
declare module '*.marko' {
    const src: any;
    export default src;
}
```
