### ISSUE TITLE
Marko Serve (Must/Should Do's)

### ISSUE THREAD

**Issue by ryansolid** [marko-js/marko#1710]
- [ ] Support routing in Windows
- [ ] Robots.txt sitemap.xml favicon.ico support 
- [ ] Compress (gzip/brotli) the html response
- [ ] Show an error message when doing a static build and the path could not be found
- [ ] Support for custom 404 and other error pages
- [ ] Error when a custom browserlist would yield multiple bundles
- [ ] Custom bundle config

**Comment by DylanPiercey** [comment]
Superseded by [@marko/run](https://github.com/marko-js/run)
