### ISSUE TITLE
EcmaScript 2015-style imports

### ISSUE THREAD

**Issue by patrick-steele-idem** [marko-js/marko#172]
# New syntax

ES6-style imports:

```xml
<module-imports>
import { reverse } from "./helpers";
import foo from "./foo";
</module-imports>

Hello ${reverse('Frank')}
```

Generated JavaScript code:

```javascript
var reverse = require('./helpers').reverse;
var foo = require('./foo');
```

# Old syntax

```xml
<require module="./helpers" var="helpers"/>
<var name="reverse" value="helpers.reverse"/>
<require module="./foo" var="foo"/>
```

**Comment by BryceEWatson** [comment]
@patrick-steele-idem, are there any examples of what the test file `include-nested-content.marko` would look like?

**Comment by patrick-steele-idem** [comment]
Deferring this feature. CommonJS syntax works well enough as an alternative:

```xml
<script marko-init>
var reverse = require('./helpers').reverse;
var foo = require('./foo');
</module-imports>

Hello ${reverse('Frank')}
```

**Comment by patrick-steele-idem** [comment]
Nothing is preventing `import` from being used within `<script marko-init>`. Closing issue... No change is needed.

**Comment by mlrawlings** [comment]
Thoughts on this? https://github.com/mlrawlings/marko-import-tag/
