### ISSUE TITLE
Cannot use Marko with Typescript/Express

### ISSUE THREAD

**Issue by acrodrig** [marko-js/marko#1737]
### Details

When I try to run:

```
this.app.use(markoExpress());
```

I get "ReferenceError: markoExpress is not defined". I looked into the types in the package "@types/marko" but there is no `markoExpress` for me to import. Please help.

### Expected Behavior

It should not throw a `ReferenceError.`

### Actual Behavior

I get "ReferenceError: markoExpress is not defined"

### Possible Fix

Add correct/full types to "@types/marko" package?

### Your Environment

Node 16.1.0

### Steps to Reproduce

Any express/typescript application trying to use marko middleware.

**Comment by amardeep** [comment]
Works for me with
```
import markoMiddleware from '@marko/express';
...
app.use(markoMiddleware());
```
