### ISSUE TITLE
Module build failed, cannot resolve components

### ISSUE THREAD

**Issue by MiloCasagrande** [marko-js/marko#1740]
### Marko Version: 5.15.9

```
├─┬ @marko/express@1.0.0
│ └── marko@5.15.9 deduped
├─┬ @marko/webpack@9.0.3
│ └── marko@5.15.9 deduped
└─┬ marko@5.15.9
  └─┬ @marko/translator-default@5.15.9
    └── marko@5.15.9 deduped
```

### Details

Trying to build my project with `marko@5.15.9` results in some build errors.
I have a `error.marko` page  (without a Component), inside `src/pages/` that is imported and used as a template for errors handling in my `index.js` file:

```javascript
import ErrorPage from './pages/error.marko';

app.use((err, req, res, next) => {
 res.marko(ErrorPage);
});
```

This is the error I get:

```
ERROR in ./src/pages/error.marko?browser-entry
Module build failed (from ./node_modules/@marko/webpack/dist/loader/index.js):
Error: /dashboard/src/pages/error.marko: ENOENT: no such file or directory, open '/dashboard/src/components/components/app-gtm/index.marko'
    at Object.openSync (node:fs:585:3)
    at Object.readFileSync (node:fs:453:35)
    at CacheBackend.provideSync (/dashboard/node_modules/webpack/node_modules/enhanced-resolve/lib/CachedInputFileSystem.js:233:32)
    at loadFileForImport (/dashboard/node_modules/@marko/babel-utils/dist/tags.js:194:8)
    at /dashboard/node_modules/@marko/translator-default/dist/util/add-dependencies.js:90:58
    at resolveIfMissing (/dashboard/node_modules/@marko/translator-default/dist/util/add-dependencies.js:185:7)
    at addHydrateDeps (/dashboard/node_modules/@marko/translator-default/dist/util/add-dependencies.js:89:9)
    at /dashboard/node_modules/@marko/translator-default/dist/util/add-dependencies.js:90:9
    at resolveIfMissing (/dashboard/node_modules/@marko/translator-default/dist/util/add-dependencies.js:185:7)
    at addHydrateDeps (/dashboard/node_modules/@marko/translator-default/dist/util/add-dependencies.js:89:9)
```

The interesting part is this line:

`Error: /dashboard/src/pages/error.marko: ENOENT: no such file or directory, open '/dashboard/src/components/components/app-gtm/index.marko'`

I'm not sure why the path there is built with `src/components/components`. I have a `marko.json` file like:
```json
{
  "tags-dir": [
    "./src/components",
    "node_modules"
  ]
}
```

Using `"./src"` for `tags-dir` doesn't change anything.

This was working with `marko@5.15.5`.

If I change that `error.marko` into its own directory structure with `template.marko` and `index.js` files, the error goes away.

It might just that I was using the wrong approach of importing the template and this is the expected behaviour.

<details><summary>Additional Info</summary>

### Your Environment

- nodejs 16.8.0
- macOS 11.5.2

</details>

**Comment by tigt** [comment]
Does anything change if you add a trailing slash to the value of `tags-dir`? Even just a different error message?

**Comment by DylanPiercey** [comment]
@MiloCasagrande could you try two things:

1. Remove the `node_modules` from the `tags-dir`, it should not be necessary and could cause some strange behavior (`node_modules` are handled specially).

2. Upgrade to `marko@5.15.10`, there was a regression in `5.15.9` that may have been related

**Comment by MiloCasagrande** [comment]
> @MiloCasagrande could you try two things:
> 
>     1. Remove the `node_modules` from the `tags-dir`, it should not be necessary and could cause some strange behavior (`node_modules` are handled specially).
> 
>     2. Upgrade to `marko@5.15.10`, there was a regression in `5.15.9` that may have been related

Removed `node_modules` and updated to `5.15.10` and the error is gone, all is working fine now.
Thanks!

**Comment by MiloCasagrande** [comment]
> Does anything change if you add a trailing slash to the value of `tags-dir`? Even just a different error message?

I tried, but nothing changed (with `5.15.9`).
