### ISSUE TITLE
CSS generated file does not included on page header

### ISSUE THREAD

**Issue by keuller** [marko-js/marko#1741]
### Details

I've defined a `style` inside `index.marko` page file, but CSS classes does not applied into HTML page. Inspecting the generated HTML file on head section any link tag was inserted, but CSS file is generated. 

### Expected Behavior

The CSS styles must be applied on generated HTML file.

This is the page code.

```
<app-layout title="Home">
    <h2> Home </h2>

    <br/>

    <h3>Counter</h3>
    <div.box>
        <span.counter>${state.count}</span>

        <div>
            <button.btn on-click("inc")> + </button>
            <button.btn on-click("dec")> - </button>
        </div>
    </div>

    <h3>People</>
    <div.box>
        <ul>
        <for|person| of=state.people>
            <li key=person.id> ${person.name} </li>
        </for>
        </ul>
    </div>

</app-layout>

style {
    div.box {
        display:flex;
        background: #CCC99A;
        padding: 10px 7px;
        width:100%;
    }
    .counter {
        display: block;
        font-size: 2rem;
    }
    button.btn {
        padding: 5px 5px;
        font-size: 15px;
        width: 3rem;
    }
}
```

### Your Environment

- OS: Linux Manjaro
- Environment name and version: Firefox 91, Chrome 93, node.js v14.17.3
- Operating System and version: Desktop

### Stack Trace

It is the header page section generated by Marko.

```html
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <meta name="description" content="Demo app">
  <title>Home</title>
</head>
```

AS we can see at network tab the CSS file is generated by the server.

![demo-view-marko](https://user-images.githubusercontent.com/2074316/132553462-8f56dad7-4e96-4315-b065-31783dfa6fd6.png)

**Comment by DylanPiercey** [comment]
@keuller I'm assuming this is a webpack app?

In the network panel you shared it does show a stylesheet being loaded, but you are saying it's not in the HTML somehow?
Could you try `rm -rf ./node_modules/.cache` to clear the webpack cache just to be safe?

**Comment by keuller** [comment]
@DylanPiercey yes, it is webpack app. Exactly, stylesheet are being loaded, but it's not in HTML file.
So I already removed the whole `node_modules` and re-install all dependencies, but it does not works.

**Comment by DylanPiercey** [comment]
@keuller given the html output you shared above I believe the issue may be related to https://github.com/marko-js/marko/wiki/Error:-Stateful-components-cannot-contain-html,-head,-or-body-tags

**Comment by keuller** [comment]
@DylanPiercey Even though my page does not contains any of those tags (html, head nor body). There is an issue related with stateful component. I have converted my component to stateless and CSS was applied correctly.

![marko-statefull-bug](https://user-images.githubusercontent.com/2074316/132561325-42464467-0771-4d4b-b4f6-99f70d01f54a.png)

But I think it is a serious bug on Marko's rendering process or is there some workaround to render styles in stateful components? Based on Marko docs it is very straightforward to apply styles on components regardless if it is stateless or stateful. What do you think?

**Comment by xtremespb** [comment]
I can confirm this issue exists since the times I've started using Marko. Easy to reproduce: if a "root" component does contain any state logic, e.g. component.js, no CSS is being rendered.
As a workaround, I'm using an "entry point" workaround like this: [take a look on GitHub](https://github.com/xtremespb/zoia/tree/master/src/modules/users/web/users) .

**Comment by DylanPiercey** [comment]
@keuller if the solution @xtremespb mentioned, then either directly or indirectly server only tags (eg `html`, `head`, `body`) are being included in the browser. If that is the case, it is a known issue and @xtremespb's solution is the recommended one.
