### ISSUE TITLE
Forward event from children to parent

### ISSUE THREAD

**Issue by cc-ebay** [marko-js/marko#1757]
### Description

It would be good to have some syntactic sugar to forward the event up. 

### Why

Since in **marko.js** the custom events do not automatically bubble up, it would be great not having to waste time writing a boilerplate function to just do:
```javascript
onMyEventOnChild(param1, param2, param3) { 
   this.emit('myEvent' , param1, param2, param3);
}
```

### Possible Implementation & Open Questions
I have seen people adding `"emit"` directly inside `on-*` but unfortunately you are not able to retrieve the parameters of the event.
```marko
<input type="email" name=input.name on-change("emit", "email-change", { email: ???event.target.value })/>
```
In this case  we wanted to massage the data and `event` is not accessible. But ideally if there is no massaging of parameters we should be able to write something like: 
```javascript
<my-child-component on-my-event("pass-through")/>
```

That should be equivalent to:

_my-component-in-the-middle.marko_

```marko
class {
  handleMyEvent(...args) {
      this.emit("myEvent", ...args);
  }
}

<my-child-component on-my-event("handleMyEvent")/>
```

### Is this something you're interested in working on?

I do not know enough about marko internals

**Comment by DylanPiercey** [comment]
FWIW in Marko 6 (and the [tags api preview](https://github.com/marko-js/tags-api-preview)) we've moved away from directly attaching event listeners to instead pass functions around similar to other frameworks. This means that you can spread input/attributes and have the event handlers propagate to the child as well.

A long while ago we also talked about a potential way to allow bubbling events in the current system, something like:

```marko

// same as onClick("emit", "click")
<input bubble:click/>

// same as onClick("emit", "input-click")
<input bubble:click="input-click"/>

// no current equivalent. allow the parent to attach event handlers to the input directly.
<input bubble:*/>

// no current equivalent. allow parent to attach event handlers to input directly, but only ones prefixed with (in this case) "input"
// eg from the parent onInputClick("...")
<input bubble:*="input"/>
```

**Comment by DylanPiercey** [comment]
We do not currently plan to change this behavior in the class api. The Marko 6 tags api supports event handlers passed as input which resolves the issue.
