### ISSUE TITLE
marko/vite/unocss fixture

### ISSUE THREAD

**Issue by electroheadfx** [marko-js/marko#1763]
### Description

Anyone is interested to make any template for marko/vite with unocss ?

https://github.com/antfu/unocss
> The instant on-demand atomic CSS engine.

### Why

For work with the speed of templating with the new atomic design engine
speed of light together with vite.

### Possible Implementation & Open Questions

Here the place to post the fixture for uno:
https://github.com/antfu/unocss/tree/main/test/fixtures

### Is this something you're interested in working on?

Yes

**Comment by DylanPiercey** [comment]
Any integrations we appreciate from the community but this integration isn't something the core team currently has planned.
