### ISSUE TITLE
Adding Class Breaks Styles

### ISSUE THREAD

**Issue by kkjdaniel** [marko-js/marko#1764]
### Marko Version: x.x.x

v5.17.9

@marko/build: 4.2.3
@marko/serve: 4.2.3

### Details

Using the Marko Starter App, as soon as I create a single file component and add a `class {}` to it, the component immediately stops rendering `style {}`. It outputs the mark-up but with none of the styles? It does work however work when using multi-file components.

### Expected Behavior

Should still render with styles applied in a single component.

### Actual Behavior

Renders without styling. It does work still when using multi-file components.

### Your Environment

Windows 10, Desktop
Node v16.13.1

### Steps to Reproduce

1. Create a `.marko` file
2. Add markup, styles and a class.
3. Notice the styles are not applied.

### Stack Trace

None.

**Comment by sgwicks** [comment]
I'm also experiencing this issue:

marko v5.21.1
@marko/build v4.2.5
@marko/serve v4.2.5

Ubuntu 20.04.4 LTS
node v18.1.0

`<style>` tags within the HTML still work fine

It still seems to generate the css and the stylesheet, it just isn't applying the stylesheet to the component

**Comment by sgwicks** [comment]
Experimenting with this some more, it's to do with the app-layout wrapper. Something about it generating a body tag makes it break any component further down the tree when that component uses `class{}`

**Comment by tigt** [comment]
Ah yeah, that’s a known footgun — [Error: Stateful components cannot contain html, head, or body tags](https://github.com/marko-js/marko/wiki/Error:-Stateful-components-cannot-contain-html,-head,-or-body-tags)
