### ISSUE TITLE
Slow view import after upgrade to version 5

### ISSUE THREAD

**Issue by kvandenhaute** [marko-js/marko#1772]
### Details

We have a custom build process where we compile Marko views and render them on request with specific input data. After doing the upgrade to version 5.19.0 (coming from 4.24.2) we noticed that the importing of the compiled Marko views took at least 4-5 times the normal time.

### Expected Behavior

The time to import the compiled Marko view should be around the same time (or faster) in version 5.

### Actual Behavior

The time to import the compiled Marko view is at least 4-5 times slower in version 5.

### Your Environment

- node 14.17.0
- macOS Big Sur 11.3.1

### Steps to Reproduce

**Implementation @ 4.24.2**

```javascript
import Marko from 'marko/src/compiler';

const contents = Marko.compileFile('pathToMarkoFile');
```

```javascript
import { performance } from 'perf_hooks';

const startTime = performance.now();
const compiledView = await import('pathToCompiledMarkoFile').then(result => result.default);
const endTime = performance.now();

console.log(`${(endTime - startTime).toFixed(2)}ms`);

const html = compiledView.renderToString({ key: 'value' });
```

**Implementation @ 5.19.0**

```javascript
import { compileFileSync } from '@marko/compiler';
import fs from 'fs';

const contents = compileFileSync('pathToMarkoFile', {
    modules: 'cjs',
    fileSystem: fs
}).code;
```

```javascript
import { performance } from 'perf_hooks';

const startTime = performance.now();
const compiledView = await import('pathToCompiledMarkoFile').then(result => result.default);
const endTime = performance.now();

console.log(`${(endTime - startTime).toFixed(2)}ms`);

const html = compiledView.renderToString({ key: 'value' });
```

</details>

**Comment by DylanPiercey** [comment]
The compiler perf has been improved some however the v5 compiler will always be "slower" than the v4 compiler because of it's "child template analysis" (ie it looks at multiple templates in a single compilation).
