### ISSUE TITLE
dynamic tagname jumplink on syntax.md ReadME loads a 404

### ISSUE THREAD

**Issue by TheSethness** [marko-js/marko#1773]
### Marko Version: x.x.x

I see it on the https://markojs.com/docs/syntax wiki page. 

### Details

Was trying to hit a jump link in the wiki and got a 404 for the [dynamic tag name syntax](#dynamic-tagname) markdown. 
### Expected Behavior
Expected to jump to the dynamic tagname section of the page.

### Actual Behavior

loaded a 404 for a different page because it added "" around the jumplink. 
https://markojs.com/docs/syntax/%22#dynamic-tagname%22
### Possible Fix
change link to relative domain-level link.
eg: [dynamic tag name syntax](./syntax.md#dynamic-tagname)

### Your Environment
Mac OS Big Sur 11.4 Chrome Version 91.0.4472.114 (Official Build) (x86_64) desktop
or Safari 14.1.1 desktop

### Steps to Reproduce
Load https://markojs.com/docs/syntax/

**Comment by tigt** [comment]
Fixed by #1774
