### ISSUE TITLE
inline and centered math equations and defined variables

### ISSUE THREAD

**Issue by jrmarcum** [marko-js/marko#1778]
Is there a way to create latex/Katex/TeX equations inline in the markdown? I would also like to be able to include defined variables added to the equations. Similar to the attached jupyter notebook using the display function after the data input cell. This js frame work seems perfect for this type of programming.

[PCAMethodForRectangularTanks.zip](https://github.com/marko-js/marko/files/8219124/PCAMethodForRectangularTanks.zip)

**Comment by DylanPiercey** [comment]
I'm afraid to click the link above and I think the question itself is likely not exactly Marko specific.
