### ISSUE TITLE
Marko v3: include tag

### ISSUE THREAD

**Issue by patrick-steele-idem** [marko-js/marko#178]
NOTE: New syntax not finalized.

# New Syntax

```xml
<include("./include-target.marko") name='Frank' count=20/>
<include("./include-target.marko", {name: 'Frank', count: 20})/>
<include("./include-nested-content.marko") name="Frank" count=20>
    Have a 
    <b>
        wonderful
    </b>
    day!
</include>
```

NOTE: When body content is provided, a special `data.renderBody = function(out) { ... }` function should be added to the template data for the target template. 

# Old Syntax

```xml
<include template="./include-target.marko" name="${'Frank'}" count="20"/>
<include template="./include-target.marko" name="Frank" count="${20}"/>
<include template="./include-target.marko" template-data="{name: 'Frank', count: 20}"/>
<include template="./include-nested-content.marko" name="Frank" count="${20}">
    Have a 
    <b>
        wonderful
    </b>
    day!
</include>
```

**Comment by BryceEWatson** [comment]
What do you think about keeping the template-data attribute in the new syntax? I like the new simplified syntax as well, I just wonder if template-data might be more intuitive for some?

**Comment by patrick-steele-idem** [comment]
In general, I think we should avoid having two ways to do the same thing. I don't like that `template-data` would be a special attribute so I am in favor of only allowing template data to be the second argument inside the `<include(path, templateData)>` tag.

@philidem What do you think?

**Comment by BryceEWatson** [comment]
@patrick-steele-idem, are there any examples of what the test file include-nested-content.marko would look like?

**Comment by patrick-steele-idem** [comment]
Not yet @BryceEWatson, but I can add some code. Nested content should always be passed in as a `data.renderBody(out)` method.

**Comment by patrick-steele-idem** [comment]
@BryceEWatson I went ahead and implemented support for `<include>` since I needed to move on to migration testing. Please review the code (commit: https://github.com/marko-js/marko/commit/a3d76a367842fd2171f481c1b8d4c72f12ac5a31) and let me know if you see any issues. Thanks for your help earlier.
