### ISSUE TITLE
mouseenter and mouseleave seem to bubble

### ISSUE THREAD

**Issue by tws2000** [marko-js/marko#1780]
### Details

When mouseenter and mouseleave are attached to an element, they seem to be firing when the mouse moves over child elements.

### Expected Behavior

mouseenter and mouseleave do not fire when mouse moves over child elements.

### Actual Behavior

mouseenter and mouseleave are firing when mouse moves over child elements.

### Your Environment

- Environment name and version (e.g. Chrome 39, node.js 5.4): Chrome 99.0.4844.83 
- Operating System and version (desktop or mobile): macOs Big Sur 11.6.1

### Steps to Reproduce
Marko playground example:
https://markojs.com/playground/#NobwRAdghgtgpmAXGAlhAJnAHgOhlAJwGsB7MAGjAAcoAXACyTAHo1Nd9izKBjEiWnAFMeAGygBnCQAIQAHQjTptEgHNVouAGESokgQAUASlkKl5vhAm1pcUdIC8y+igk5VcWgFFRBgOTwEACufkYA3GbmtqI4YpISADKutDgq6pr+fHoEoRGK0gC+CkUQCgA86CgAbpFxUg5yYIFBjZFEcACeDU1CLWCR-AC0MCRBEnBCgoaNaRrauvqNRgMQw6PjdnBQVXAGM2pzOtlLAHwKkRXVJ2VQ0vQEcABm3QDEjScAEnZ6ZcxQ18xKlUzvlLsCbncHs9Gm8wCcAOr6UToX7-X5AkHoq7nCBlawdTQgvC9Uz5ABGUB4RFUBFGGEGWX0iGkLx4bLySho6EqEFUzIAzAAGKhYPIlYnBaQnaRA0lKSoSKjiDrMtCiNBwQZkvRUjnSLk8vnSACMwtFkU4qjQzNNIr1ZP0mAINpF0gkuhQ6DFCliCwIcukFKpNLp6AZfuZDy9xXKzHxhLABQAukA

**Comment by DylanPiercey** [comment]
Fix released in `marko@5.20.1`
