### ISSUE TITLE
Compile error: @tags must be within a custom element

### ISSUE THREAD

**Issue by redonkulus** [marko-js/marko#1788]
### Details

When compiling templates in v5, the following error occurs (not present in v4):

```
Failed to compile "foo.marko". Error: SyntaxError: foo.marko(27,6): @tags must be within a custom element.
```

### Expected Behavior

No compile time error.

### Actual Behavior

The error mentioned above.

### Possible Fix

Debugging with @DylanPiercey, turns out a danging comma on a dynamic tag cased this issue. Note, this same code in v4 did not produce this error. Additionally, a similar project on v5, with the same syntx did not cause this issue either. 

```marko
<${Page}, ...input>
```

Removing the `,` resolved the compile bug.

<details><summary>Additional Info</summary>

### Your Environment

- Environment name and version (e.g. Chrome 39, node.js 5.4): node v14.18.1
- Operating System and version (desktop or mobile): mac / desktop
- Link to your project:

### Steps to Reproduce

The command executed and the stack trace are available here:
https://gist.github.com/redonkulus/aeb803a18e9e8c00d4cc2fac076aa254

</details>

**Comment by DylanPiercey** [comment]
Trailing commas after the tag name are now ignored in htmljs parser.
