### ISSUE TITLE
Marko v3: Nested attributes

### ISSUE THREAD

**Issue by patrick-steele-idem** [marko-js/marko#180]
NOTE: the new syntax requires some more discussion.

# New Syntax

```xml
<test-popover>
    <@title>Popover Title</@title>
    <@content>Popover Content</@content>
    
    Link Text
</test-popover>
```

# Old Syntax

```xml
<test-popover>
    <attr name="title">Popover Title</attr>
    <attr name="content">Popover Content</attr>
    
    Link Text
</test-popover>
```

**Comment by patrick-steele-idem** [comment]
I propose we drop this feature from Marko as it is confusing and it doesn't add much value. Also, it is currently not documented on markojs.com so if anyone is using it, it would be minimal. Nested tags offer a better alternative in cases where rendered HTML markup needs to be passed around as input to another tag.

**Comment by philidem** [comment]
I've never had a need for this feature and if I needed rich HTML content provided to a custom tag then I would have implemented a nested tag as you suggested (and not used attribute). I'm ok with dropping this as a feature until we have a stronger use case.

**Comment by philidem** [comment]
Are you also suggesting that we drop the old `<attr>` tag? I'm not using that either but was wondering.

**Comment by patrick-steele-idem** [comment]
Yes, dropping nested `<attr>` as well and there will be no support for nested attributes. I'm going to go ahead and close this issue and drop this feature from Marko v3. Thanks for the feedback.
