### ISSUE TITLE
How to handle 3rd party node_modules

### ISSUE THREAD

**Issue by elverskog** [marko-js/marko#1817]
I don't see anything in the docs on how to import 3rd party node modules. 
Is there anything?

I'm trying to integrate pouchdb-browser via an import and am running into various build errors (depending on the version, source and approach I take). I also tried some sparse/blank modules to test (`module.exports = null` or `export default null`), 
But with those also get errors, usually per the type of export I get.
`Error: ES Modules may not assign module.exports or exports.*, Use ESM export syntax, instead: ./app.js`

I can only get `require` to work.

_Before I go too far nosing around or contact pouchdb, do you have recommendations or guidelines?_

I'm only looking to bundle it for the front-end of course.
For now (just to play around)  I am importing pouchdb via an old fashioned script tag,  accessing it via window and pushing it into my app on user action (if you have any tips on how to handle this hack better and/or how to push it back into the app on reload that would be great!)

fyi - I also get an error "self cannot be found" where pouchdb tries to use set-immediate-shim. 
I seem to be able to bypass this error as a bypass circuit with a simple `if` but then I get the errors above.

**Comment by DylanPiercey** [comment]
@elverskog Marko doesn't impact the loading of 3rd party modules, besides loading other Marko files [as described here](https://markojs.com/docs/custom-tags/#using-tags-from-npm). This is entirely dependent on the bundler.

If you could create a reproduction and share the exact error, stack trace and what tools your are using I may be able to help though.

**Comment by elverskog** [comment]
@DylanPiercey  Agh. It was conflicting module import/export styles that was doing it. Needed a walk :)
I seem to have it mostly wired up now.

I had earlier tried to convert the main app.js to ESM style but ran into some problems, per how to handle "new" (I don't usually use that style). I then needed to of course ESM import app.js's module, wherever it was used.

_Thanks for responding so quickly!_

Ahem...3 more quick (hopefully) questions if you have a sec:
1. The sample todo app uses the CommonJS styles predominantly, is there a reason and should I be wary of ESM in Marko?
2. I'm checking `window` to avoid initiating a pouch DB in node (and getting adapter errors). Is there a Marko standard way to check environment (or does the need to check signal a structural problem)?
3. My next major step is to pull (or sync) data from couchdb (which pouchdb-browser will sync with) and then push that into the SSR. I'll try to get pouchdb installed/running in node, in which case my life will be simpler. _But if I need to make HTTP calls to couch (or any other data source), would that require integrating another server (koa etc)?_
