### ISSUE TITLE
<return> with marko-tag.json

### ISSUE THREAD

**Issue by Hen2609** [marko-js/marko#1822]
### Details

Tried to add `<return>` tag to the component but I got the following error: 
![image](https://user-images.githubusercontent.com/24863531/178110996-11bd3837-1a96-4015-a44b-f72c59176961.png)
---
this the tag json file: 
![image](https://user-images.githubusercontent.com/24863531/178111014-6eb3fe3d-09e0-42d2-9f84-1342a9357c5a.png)

**Comment by Hen2609** [comment]
wrong repo :(

**Comment by tigt** [comment]
Just in case somebody’s looking at this in the future, issue was reopened at https://github.com/marko-js/tags-api-preview/issues/24
