### ISSUE TITLE
<await client-reorder> not compatible with tight CSP rules.

### ISSUE THREAD

**Issue by vwong** [marko-js/marko#1835]
### Description

`<await() client-reorder/>` is incompatible with tight Content-Security-Policies, specifically ones that block `unsafe-inline`.

### Why

I want to be able to lock down my CSP, but then I can't use `client-reorder`.

### Possible Implementation & Open Questions

With client-reordering, the replacement is streamed as a div like the following, (and then subsequently put into the right spot with JS).

```
<div id="af0" style="display:none"> ... </div>
```

An alternate way of representing this, without breaking CSP is:
```
<style nonce="abc123">
  #af0 { display: none }
</style>
<div id="af0"> ... </div>
```

### Is this something you're interested in working on?

I wish I could, but don't know enough about it.

**Comment by DylanPiercey** [comment]
@vwong this is a good point, we should address it and I like your solve there. If you're interested in taking a shot at it, the relevant code is here: https://github.com/marko-js/marko/blob/main/packages/marko/src/core-tags/core/await/reorderer-renderer.js#L60

**Comment by vwong** [comment]
Hmm. Doesn't look hard at all. I'll create a PR.
