### ISSUE TITLE
<noscript> interferes with stateful components that also contains  body content

### ISSUE THREAD

**Issue by vwong** [marko-js/marko#1847]
### Details

Under the conditions specified in the title, the server renders the HTML as expected, but subsequent client-side hydration destroys the body contents.

This seems to be a problem only with production builds; development mode is fine.

### Expected Behavior

Body content (eg, server-only components) remains in the client, despite re-rendering.

### Actual Behavior

Body content disappears when re-rendered in the client. Changing `<noscript>` to `<${"noscript"}>` provides a workaround.

### Steps to Reproduce

See example reproduction in https://github.com/vwong/marko-noscript-bug

**Comment by tigt** [comment]
Initial invesigation in the Discord shows this has some surprising traits:

- It doesn’t seem to happen in development mode (explicit or implicit)

- It’s not exclusive to `<noscript>` — it happens with any 2 static roots in a file, like this:

  ```marko
  <div><span>static content</span></div>

  <div>
    <${input.renderBody}/>
  </div>
  ```

- It happens in Marko 4 and 5

We’re currently discussing how best to fix it.

**Comment by vwong** [comment]
Interesting. Feel free to rename the issue to better describe the problem.
