### ISSUE TITLE
Compiler should Parse tags on notifyFinish instead of onopentag

### ISSUE THREAD

**Issue by BryceEWatson** [marko-js/marko#185]
While working on issue https://github.com/marko-js/marko/issues/169 I noticed that the HtmlElement node for the var tag never contained the proper body nodes.
Example:
```
<var x=1 y=7 z=x+10 unusedVar>
  ${x}
  ${y}
  ${z}
HELLO WORLD
</var>
```
Would return the following body node:
```
body: 
   ArrayContainer {
     node: 
      { type: 'HtmlElement',
        tagName: 'var',
        attributes: [Object],
        argument: undefined,
        body: [Circular] },
     array: [] }
```
Notice that the body is Circular, it points to the parent tag node.
The onopentag event does not have access to any body information since it has not finished reading the tag yet. However, I can see that the event object passed into the `notifyFinish(event)` listener in `/compiler/HtmlJsParser.js`, does contain all body nodes, along with the attributes from the start tag.

event object:
```
[ ElementNode {
    event: { type: 'opentag', tagName: 'var', attributes: [Object], pos: 0 },
    children: 
     [ [Object],
       [Object] ],
    tagName: 'var',
    closetagEvent: { type: 'closetag', tagName: 'var' } } ]
```
I propose that we move the parsing logic from the `Parser.js` `handleStartElement` function, and move it into a new `handleEndElement` function. `handleEndElement` can then parse the tag signature, as well as the body elements.

**Comment by patrick-steele-idem** [comment]
I'll see if I can reproduce in a new unit test and provide an update soon. Thanks for providing all of the details.

**Comment by patrick-steele-idem** [comment]
I added a test and I get the following error when parsing the template you provided:

```
AssertionError: Node does not support child nodes: { type: 'Vars',
  kind: 'var',
  declarations:
   [ HtmlAttribute {
       name: 'x',
       value: [Object],
       argument: undefined,
       def: undefined },
     HtmlAttribute {
       name: 'y',
       value: [Object],
       argument: undefined,
       def: undefined },
     HtmlAttribute { name: 'z', value: 'x+10', argument: undefined, def: undefined },
     HtmlAttribute {
       name: 'unusedvar',
       value: undefined,
       argument: undefined,
       def: undefined } ] }
```

That looks like the correct behavior to me. I updated the `Vars` AST node to support body content, by adding a `body` property that is a `Container` and everything is parsing correctly. I'll push the code that I used for testing so that you can verify.

**Comment by patrick-steele-idem** [comment]
Changes pushed. Make sure you are merging in the latest code on the `htmljs-parser` branch. See the following commit for more details: https://github.com/marko-js/marko/commit/90fb80b71f739af6fbb6ddde6d054d6696e26ae6
