### ISSUE TITLE
dx barriers to entry tags api preview gripes suggestions

### ISSUE THREAD

**Issue by leoj3n** [marko-js/marko#1858]
### `--template` flag does not work.

https://twitter.com/MarkoDevTeam/status/1420431542485012485

> Or get started with:
> npm init marko --template tags-api

this command proposes a dialog to the user to select "Default starter app"

TODO: Twitter post should be ammended to read like that:

> Or get started with:
> npm init marko@latest -- --template tags-api

~~probably will need to see if fix can be made in https://github.com/marko-js/cli~~
also notice suggesting a slight difference to command here:
https://github.com/marko-js/cli/tree/main/packages/create#npm
`npm init @marko myapp --template webpack` notice the `@marko` instead of just `marko`
EDIT: proposed changes here https://github.com/marko-js/cli/pull/214

### Example code errors

so after `--template tags-api` fails causing regular marko5 app user may go ahead and `npm install @marko/tags-api-preview` then they may try copy/paste example from readme at https://github.com/marko-js/tags-api-preview#example ~~which will fail to compile at which point developer user might say screw it~~
EDIT: proposed changes here https://github.com/marko-js/tags-api-preview/pull/29

### Consider specifying `@latest`:

```console
npm init marko@latest --template ...
```
just assuming that `@latest` could help if someone somehow has outdated marko
NOTE: primarily a suggestion for the Twitter post and/or blog type posts

### More examples

regarding: https://github.com/marko-js/tags-api-preview
TODO: mention using `npm init marko -- --template tags-api` command to create a new project
TODO: point to https://github.com/marko-js/examples/tree/master/examples/tags-api-guide as well

regarding: https://dev.to/ryansolid/introducing-the-marko-tags-api-preview-37o4
TODO: cannot copy/paste code examples as they are all images... perhaps at least provide try online links like for initial count example... could perhaps be added to examples repo as a set of examples similar to the tags-api-guide set of examples
TODO: mention using `npm init marko@latest -- --template tags-api` command to create a new project

**Comment by DylanPiercey** [comment]
Appreciate the callout. We'll look into smoothing those things out. PR's welcome of course 😄

**Comment by leoj3n** [comment]
Linking related issue https://github.com/marko-js/cli/issues/213

**Comment by leoj3n** [comment]
@DylanPiercey looking like the primary issues with A) the readme example needing to be updated to be `<let/count=0/>` and B) with the npm command needing to look like `npm init marko -- --template tags-api` should take a minute to solve; think probably do what needs to be done asap since it will make a big difference for people trying to play with tags-api coming from twitter post etc.

**Comment by leoj3n** [comment]
<img width="807" alt="image" src="https://user-images.githubusercontent.com/990216/194223811-e666ab2c-0b29-451a-b69b-c817b32e09ab.png">

**Comment by leoj3n** [comment]
<img width="402" alt="image" src="https://user-images.githubusercontent.com/990216/194223901-9f1e4d40-a4c7-40f9-95eb-662061c26de5.png">

**Comment by leoj3n** [comment]
- Default Attribute
  - https://markojs.com/try-online/?gist=4ff21c1e8917b687b4bbb67d883179e6
- Attribute Method Shorthands
  - https://markojs.com/try-online/?gist=ab09ef5a31f2a8d610cc14f355d01825
- Tag Variables
  - https://markojs.com/try-online/?gist=4bbb70bb2e7085cab377c0820a40760b

(wip)

**Comment by DylanPiercey** [comment]
Thanks for your work and feedback here.
I should point out that we will be working on a rework of our documentation once the tags api / Marko 6 is in official beta and outside of the preview.

**Comment by DylanPiercey** [comment]
WIP docs over here for now! https://github.com/marko-js/website/tree/next/src/routes/docs
