### ISSUE TITLE
no-update causing run error on built/dist - preserve-tag is not supported resolving ES modules

### ISSUE THREAD

**Issue by elverskog** [marko-js/marko#1864]
### Details

@DylanPiercey asked me to file this as a bug. 
I get an run error on start (no request needed to trigger the error) when using the `no-update` tag.
It builds fine but gives the below error when running the built code (start script).
It works when running the dev script.

### Expected Behavior

I expect the server to be able to start and for the markup element that has that tag to not hydrate client side.

### Actual Behavior

I get the below error

### Your Environment

Site based off vite/fastify example
Linux 6.0.2-arch1-1
node.js v19.0.0

  "dependencies": {
    "@fastify/compress": "^6.1.0",
    "@fastify/formbody": "^7.3.0",
    "@fastify/multipart": "^7.2.0",
    "@fastify/secure-session": "^5.2.0",
    "@fastify/static": "^6.4.1",
    "@marko-tags/context": "^2.2.2",
    "@marko/fastify": "^1.1.1",
    "events": "^3.3.0",
    "fastify": "^4.7.0",
    "fastify-plugin": "^4.2.1",
    "luxon": "^3.0.4",
    "npm": "^8.19.2",
    "pump": "^3.0.0"
  },
  "devDependencies": {
    "@marko/compiler": "^5.22.8",
    "@marko/jest": "^5.0.0",
    "@marko/testing-library": "^6.1.2",
    "@marko/vite": "^2.3.9",
    "cross-env": "^7.0.3",
    "jsdom": "^20.0.1",
    "pino-pretty": "^9.1.1",
    "postcss-load-config": "^4.0.1",
    "postcss-nesting": "^10.2.0",
    "postcss-plugin": "^1.0.0",
    "session-file-store": "^1.5.0",
    "supertest": "^6.3.1",
    "vite": "^3.1.6",
    "vitest": "^0.24.3"
  },

### Steps to Reproduce

1. Use the vite/fastify example
2. Create a page in a directory
3. On that page, use the no-update tag on an element that is rendering an attribute dynamically
4. In my case <button-styled no-update type="submit" size="small" label=state.language.labelSubmit />
5. Build
6. Run/Start

Please let me know if you need to provide a sample repo.

### Stack Trace

node:internal/process/promises:289
            triggerUncaughtException(err, true /* fromPromise */);
            ^

Error [ERR_UNSUPPORTED_DIR_IMPORT]: Directory import '/home/xyz/code/xyz/xyz-marko/node_modules/marko/dist/core-tags/components/preserve-tag' is not supported resolving ES modules imported from /home/xyz/code/xyz/xyz-marko/dist/assets/listing-create.page.e09c02f6.js
Did you mean to import marko/node_modules/marko/dist/core-tags/components/preserve-tag/index.js?
    at __node_internal_captureLargerStackTrace (node:internal/errors:484:5)
    at new NodeError (node:internal/errors:393:5)
    at finalizeResolution (node:internal/modules/esm/resolve:253:17)
    at moduleResolve (node:internal/modules/esm/resolve:850:10)
    at defaultResolve (node:internal/modules/esm/resolve:1058:11)
    at nextResolve (node:internal/modules/esm/loader:161:28)
    at ESMLoader.resolve (node:internal/modules/esm/loader:829:30)
    at ESMLoader.getModuleJob (node:internal/modules/esm/loader:412:18)
    at ModuleWrap.<anonymous> (node:internal/modules/esm/module_job:76:40)
    at link (node:internal/modules/esm/module_job:75:36) {

</details>

**Comment by DylanPiercey** [comment]
This was resolved at some point but we forgot to close this issue 😓
