### ISSUE TITLE
An idea for the footer of Markojs.com (URLs to people's pages…)

### ISSUE THREAD

**Issue by Nikolice** [marko-js/marko#1872]
### Description

I saw contributors at [markojs.com](https://markojs.com/) – but in no reach.

### Why

[Microsoft's «Visual Studio Code» main page](https://code.visualstudio.com/) has Twitter.

### Possible Implementation & Open Questions

Inside the `<div class="home-community__contributors">` could be “anchors”.

Maybe, some additional functionality can be added? – e.g. a “pop-up” (on hover) with an image and name.

### Is this something you're interested in working on?

Yes, it is.

**Comment by tigt** [comment]
We currently [automatically get that contributor information](https://github.com/marko-js/website/blob/c0975fb74c94fdb433b74c42ff3325357e5a84b1/src/pages/docs/%5Bname%5D/components/contributors/get-contributors.js) from GitHub’s API. That only provides us the URL of their GitHub profile, unfortunately, but it does show their elsewhere-on-the-web URLs on those profiles?

For example, the Contributors HTML on [the Getting Started docs page](https://markojs.com/docs/getting-started/) looks like:

```html
<div class="contributors">
  <a href="https://github.com/DylanPiercey" class="contributor">
    <img src="https://avatars.githubusercontent.com/u/4985201?v=4" alt="" class="photo">
    <span class="name">DylanPiercey</span>
  </a>
  <a href="https://github.com/mlrawlings" class="contributor">
    <img src="https://avatars.githubusercontent.com/u/1958812?v=4" alt="" class="photo">
    <span class="name">mlrawlings</span>
  </a>
  <a href="https://github.com/marko-js/marko/blob/main/packages/marko/docs/getting-started.md" class="contributor you">
    <div class="photo"><span class="icon">+</span></div>
    <span class="name">You?</span>
  </a>
</div>
```

What page were you not seeing anchors on?

**Comment by Nikolice** [comment]
> What page were you not seeing anchors on?

The [main page](https://markojs.com/)… I just see “a wall” of photos-&-pictures (of contributors) under the “Join the Community”. And it is **not** in the “footer” (my mistake), but within the *last* `<section>` of `<main>`: inside its `<div class="home-community__contributors">`… That `<div>` – contains just `<img>`s (which – are **not** wrapped in `<a>`s); however, these `<img>`s **do** *contain* URLs of GitHub-profiles, within their `src`-attribute!

At the same time – I *do* see “active” (anchored?) images (of contributors) on the [«Getting Started»-docs page](https://markojs.com/docs/getting-started/).

<hr>

… Finally – [here](https://github.com/marko-js/website/blob/c0975fb74c94fdb433b74c42ff3325357e5a84b1/src/pages/index/components/home-community/index.marko) is the place to update the code!

It's here:
> <for|contributor| of=body>

**Comment by Nikolice** [comment]
It seems, I posted this issue on a wrong place: «marko-js/marko» instead of «marko-js/website».
