### ISSUE TITLE
similar tag like dangerouslySetInnerHTML

### ISSUE THREAD

**Issue by xd-dw** [marko-js/marko#1874]
is there in Marko a similar tag like dangerouslySetInnerHTML in react so that i can dynamically render html text as html?
eg.
`<div dangerouslySetInnerHTML={{ __html: rawHTMLAsText }}></div>`
where rawHTMLAsText=`<em>Process</em> is <em>not</em> <em>defined</em>`

**Comment by DylanPiercey** [comment]
You use `$!{EXPRESSION}` to interpolate in unescaped text content (you don't need a tag for this).

See https://markojs.com/docs/syntax/#dynamic-text
