### ISSUE TITLE
Why me?

### ISSUE THREAD

**Issue by markoj3s** [marko-js/marko#1906]
Hi guys~

Can someone please tell me why you guys decided to honor me by naming this project after my name? :upside_down_face:

Cheers~
Marko

PS: Sorry for disturbing, just found that funny to see my name in a JS Library (being myself a JS/TS developer) :smile:

**Comment by DylanPiercey** [comment]
It's a sign! Hope you enjoy, Marko 😉.

Also if you didn't guess Marko was picked because it's close to **mark**up, a big focus for us!

**Comment by markoj3s** [comment]
Thanks for sharing the origin of the name, makes sense :)
