### ISSUE TITLE
Find way to securely load and run templates within sandbox

### ISSUE THREAD

**Issue by philidem** [marko-js/marko#192]
Several people have asked about the security implications of allowing end-users to edit Marko templates. I too have wished for this ability but have held off allowing it because it is currently unsafe. We should assess the options for loading and running templates within a sandbox. Examples of unsafe template code includes scriptlets (e.g. `{% process.exit(1) %}`) and JavaScript expressions (e.g. `<div if="process.exit(1)">`). Also, the CommonJS/Node.js `require` function is currently exposed to the template which would allow the template to access the module cache (this is dangerous).

Two ideas have been proposed to support this:
1. Use the Node.js built-in `vm` module to load and run Marko templates within a sandbox
2. Staticly analyze the Marko template source code to find unsafe code and prevent compilation or provide whitelist of tags and features that can be used in sandbox mode

Personally, I think option `2` (static analysis) would be too error-prone but it is worth exploring.

**Comment by AminaG** [comment]
I need it, so I believe I can implement this feature.
I can make fork, pull test, develop  & pull request.

Before I am going deeply in the source code, can you give me some direction where you think is the best place to implement it? (links to files&lines&functions will be appreciated)

**Comment by patrick-steele-idem** [comment]
Hey @AminaG what option are you leaning towards (sandbox or static code analysis)?

**Comment by patrick-steele-idem** [comment]
One thing not mentioned by @philidem is that the `out` could leak potentially sensitive objects if you are not careful. For example, if you render to the HTTP response stream in an Express app then you could do the following:

```javascript
var res = out.stream;
var app = res.app;
// User now has a reference to the Express app instance
```

This can be avoided if you don't render directly to the HTTP response. For example:

```javascript
template.stream(templateData).pipe(res);
```

You also have to be careful with data stored in `out.global` (see: http://markojs.com/docs/marko/language-guide/#global-properties).

Just wanted to make note of these subtle but important details for future reference.

**Comment by AminaG** [comment]
I prefer sandbox via vm or vm2 (https://github.com/patriksimek/vm2).
Regular VM, of node can make the entire process not responding `while (true) {}`.

**Comment by AminaG** [comment]
static code analysis never can be perfect, and in case of break, it is a backdoor to entire server. That why we must choose sandbox:
https://nodejs.org/api/vm.html
https://github.com/patriksimek/vm2

**Comment by philidem** [comment]
I think vm2 spawns a new process which is a good option for most security.
What if we used web worker? They might have sufficient isolation as well.

**Comment by patrick-steele-idem** [comment]
I'm also leaning towards the sandbox (at least for now). Fortunately, the runtime for marko is tiny. All template loading happens in the following two functions: https://github.com/marko-js/marko/blob/de673d362e993263a926bf40d34f018aa6320ccf/runtime/loader.js#L33-L69

Once you have the source, you will need to load the source in a separate sandbox and you will need to provide your own pseudo globals: `require`, `module`, `__dirname`, `__filename`

The sandbox will not have the Node.js module loading system but you will need to shim in a fake module loading system for marko to work.

**Comment by AminaG** [comment]
We only talking about server side. web worker, is mostly for client side.

**Comment by patrick-steele-idem** [comment]
I'm not convinced vm2 is completely needed, but out-of-process rendering of templates is possible (rendering will have to be async).

**Comment by AminaG** [comment]
Out-of-process will make all global not works. It is break-change. Can we do that kind of break change to Marko?

**Comment by AminaG** [comment]
Just to clarify. For securing client side, all we need to do is use XSS library. (https://www.npmjs.com/package/xss). We are only talking about securing server side code executing

**Comment by AminaG** [comment]
I believe that to not break current code using global variables, we have to add it as an option.
Maybe like this:
```
require('marko').load(src,{secure:true})
```
http://markojs.com/docs/marko/javascript-api/#loadtemplatepath-templatesrc-options--template

**Comment by patrick-steele-idem** [comment]
Marko doesn't depend on any globals.

You would just need to load the marko runtime in the separate process. However, it is challenging to load the marko runtime without the Node.js module loading system. For that reason, I think it is better to use an in-process sandbox and have the runtime be loaded outside the sandbox, but to have the template be loaded within the sandbox. If you want to try and load marko without a module loading system in a separate process then that will definitely be the safest, but it, again, it will be more challenging without the Node.js module loading system.

**Comment by philidem** [comment]
I think the JavaScript API should provide a sandbox option and if true then
behavior can be different due to the additional constraints. I don't think
we have to worry about globals not working on sandbox. Also the global data
could be stranded and sent to other process.

**Comment by patrick-steele-idem** [comment]
Yes, that is a good suggestion @AminaG :

```javascript
var template = require('marko').load(src,{secure:true})
template.render(templateData, stream)
```

**Comment by AminaG** [comment]
The problem is that maybe there are user that now using templates, that running insecure code, but this is what they want. We cannot make break change to community project.

**Comment by patrick-steele-idem** [comment]
@AminaG this definitely can't be a breaking change. The "sandbox" functionality should be an opt-in only and that option should only be recognized on the server.

**Comment by AminaG** [comment]
we can simply use child_process.spawn (or fork), and send data between the process.

A question There is any timeout for async function loading in Marko? 
We don't want that a template that contain a infinite loop, will work forever.

**Comment by AminaG** [comment]
@patrick-steele-idem . That what I mean it will be opt-in only

**Comment by patrick-steele-idem** [comment]
Looking more closely at vm2 I see that there is support for a Node.js module loading system. That makes vm2 more applealing.

**Comment by patrick-steele-idem** [comment]
@AminaG There are timeouts, but they are only for async timeouts (not CPU bound loops).

**Comment by AminaG** [comment]
So, we have to add timeout, (default: 1 min)
```
require('marko').load(src,{secure:/* true/false  */, timeout: /*in ms*/ }
```

**Comment by AminaG** [comment]
Maybe the timeout need to be in the render function (not at template loading time)

**Comment by patrick-steele-idem** [comment]
My recommendation is to go forward with [vm2](https://github.com/patriksimek/vm2), but to allow the sandbox to be more pluggable and flexible. It is better if `marko` does not have a direct dependency on `vm2`. Something more like the following:

```javascript
var NodeVM = require('vm2').NodeVM;

var options = {
    console: 'inherit',
    sandbox: {},
    require: true,
    requireExternal: true,
    requireNative: ['marko', 'marko-async', 'marko-layout'],
    requireRoot : "./"
};


var sandbox = new NodeVM(options);

var template = require('marko').load(templatePath, {
  sandbox: sandbox
});

template.render(templateData, ...);
```

Timeout only makes sense for the render method, but that is not supported for vm2. You would have to use an out-of-process solution for that.

**Comment by AminaG** [comment]
It is supported for vm2. 
`options={timeout:1000}`

**Comment by patrick-steele-idem** [comment]
Just realized that vm2 doesn't allow you to whitelist external modules (only native modules)... Really??

**Comment by patrick-steele-idem** [comment]
From the docs:

> IMPORTANT: Timeout is only effective on code you run trough run. Timeout is NOT effective on any method returned by VM.
> IMPORTANT: Timeout is not effective for NodeVM so it is not immune to while (true) {} or similar evil.

Therefore, timeout would not be effective for the `template.render()` method.

**Comment by AminaG** [comment]
Maybe it is possible to add modules to VM2 context using the sandbox option, instead of requiring it:
```
sandbox={marko: require('...'), `marko-async`:require('marko-async')}
```
What do you think/

**Comment by patrick-steele-idem** [comment]
> Maybe it is possible to add modules to VM2 context using the sandbox option, instead of requiring it:

That's possible, but it would mean that the templates would need to be compiled differently if they are loaded sandbox mode. It's worth exploring.

**Comment by AminaG** [comment]
You can do
```
vm.call('setTimeout(function(){process.exit()},60000)')
```
It will and the vm after 1 minute.

**Comment by philidem** [comment]
My guess is that everything in the vm2 sandbox has to be serializable since
it gets sent to other process but maybe I'm wrong.

**Comment by patrick-steele-idem** [comment]
Hey @philidem, I think you misread. The vm2 sandbox is in the same process.

**Comment by patrick-steele-idem** [comment]
> vm.call('setTimeout(function(){process.exit()},60000)')

I don't see how that helps. Also, `process.exit` won't be available in the sandbox :)

**Comment by AminaG** [comment]
Anyway Maybe it be easier to implement it simply, using `child_process.spawn` that run native vm module.

and not be depended on other modules. vm2 not giving as so much.

I think, that child_process can give us, secure way of running things, and vm module, can give as "javascript from text " compiler.

In short:
1. We will create a short JS file, that render templates in native vm.
2. We will run this js file, in spawned process.

**Comment by patrick-steele-idem** [comment]
vm2 is not a lot of code. May be worth forking and improving to add support for whitelisted external modules. Basically, for any required module file, search up the directory tree to find the parent package name and check if that particular package has been whitelisted.

Only problem (for me at least) is that vm2 is written using CoffeeScript...

**Comment by AminaG** [comment]
Maybe try add the creator of vm2, to the conversion...

**Comment by patrick-steele-idem** [comment]
Actually, after giving it some more thought, vm2 is probably good as-is. As long as the native Node.js modules (`fs`, `process`, etc.) are blocked then I suppose there really is no security risk. I can see the reasoning for only supporting whitelisting of native Node.js modules.

**Comment by AminaG** [comment]
The problem is, that today, I can use helper, with extenal data.

var y=3
templateDat={
my_helper:function (x) {return x*y}
}

If we use vm2, or out-of-process rendering, the `y` variable will not available.

**Comment by patrick-steele-idem** [comment]
Actually, I take that back, a non-native module might have a native binary built from C++ that could be an attack vector. I suspect that those those non-native binaries would still be allowed to be loaded when using vm2, but I could be wrong.

**Comment by patrick-steele-idem** [comment]
If you go with the out-of-process solution, then, yes, the template data needs to be serializable to JSON. vm2 is in-process so I don't think passing in helper functions or using data from closures is a problem.

**Comment by patrick-steele-idem** [comment]
I recommend trying out vm2 further. If we run into limitations, we can always improve vm2, but I still think vm2 is in the best direction.

**Comment by AminaG** [comment]
So, there is any solution how to to stop vm2, in case of infinite loop

**Comment by patrick-steele-idem** [comment]
@AminaG 

> So, there is any solution how to to stop vm2, in case of infinite loop

Yes, you need to invoke the `template.render()` method using the `vm.runInThisContext(code, { timeout: 999 })` method or `script.runInContext(contextifiedSandbox, { timeout: 999 })`. Using the latter is recommended since it can be used to execute a precompiled script (i.e., faster). See: https://nodejs.org/api/vm.html#vm_new_vm_script_code_options

**Comment by mlrawlings** [comment]
This is not a concern for the core marko project.  If someone wants to create a module to wrap marko and sandbox it that would be great.
