### ISSUE TITLE
Bug: broken link in CONTRIBUTING.md

### ISSUE THREAD

**Issue by lucasgonze** [marko-js/marko#1931]
### Marko Version: x.x.x

4.25.5

### Details

https://github.com/marko-js/marko/blob/main/.github/CONTRIBUTING.md contains the following markdown:

`Prior to merging your PR, you will need to sign the [JS Foundation CLA](https://cla.js.foundation/marko-js/marko).
`

On clicking the link I got a "Server Not Found" error "We can’t connect to the server at cla.js.foundation"

### Expected Behavior

Link should be on a real domain

### Actual Behavior

Server not found

**Comment by DylanPiercey** [comment]
Thanks for the callout, fixed now!
