### ISSUE TITLE
bug: no such script in packages.json

### ISSUE THREAD

**Issue by lucasgonze** [marko-js/marko#1932]
### Marko Version: x.x.x

5.25.5

### Details

I have a PR to contribute so I'm running through the guidelines at https://github.com/marko-js/marko/blob/main/.github/CONTRIBUTING.md. The documentation appears to be out of sync with the actual script.

<img width="824" alt="image" src="https://user-images.githubusercontent.com/111581/232629471-1fdeacac-c7f3-49a9-90ea-a057cd024019.png">

On doing `npm run test-coverage`, I get an error.

### Expected Behavior

The script should run.

### Actual Behavior

<img width="736" alt="image" src="https://user-images.githubusercontent.com/111581/232629592-08569e66-c84b-42cc-a8ee-9d3b2c3e7177.png">

### Possible Fix

<details><summary>Either the script should exist in package.json or the documentation should be updated. I suspect the correct markdown would be:</summary></details>

```
Before submitting your PR, make sure that all new and previous tests pass and that [coverage](https://codecov.io/gh/marko-js/marko) has not decreased:

`npm run test`
```

**Comment by DylanPiercey** [comment]
Thanks for the callout, fixed now!
