### ISSUE TITLE
TypeScript: Passing Attributes to Body Content Will Loose Type

### ISSUE THREAD

**Issue by sangxxh** [marko-js/marko#1989]
### Marko Version: 

5.26.4, 5.28.1

### Details

I have this example file:

```marko
export interface Input {
  heading: Marko.Renderable;
  content: Marko.Renderable;
}

<body>
  <${input.heading} data="Marko"/> // <---------- HOVER OVER data
  <hr>
  <${input.content}/>
</body>
```

Hover over data will show `"data": string` which is good:

![image](https://github.com/marko-js/marko/assets/11912225/273f3e22-9726-429a-bf4e-507543c3001f)

But in the usage, `data` is now of type `any`:

```marko
// +page.marko
    <layout>
      <@heading|{ data }|> // <--------- data is expected to be of type `string`
        <h1>Hello ${data}</h1>
      </@heading>
      <@content>
        <p>...</p>
      </@content>
    </layout>
```

![image](https://github.com/marko-js/marko/assets/11912225/7e9ad9b0-fb2d-460f-a6c5-a6bd179dcabd)

**Comment by DylanPiercey** [comment]
@sangxxh the correct typing here would to use a `Marko.AttrTag` and a `Marko.Body` type with parameters, in this case:

```
export interface Input {
  heading: Marko.AttrTag<{
    renderBody: Marko.Body<[{ data: TYPE_OF_DATA }]>
  }>;
  content: Marko.Renderable;
}
```

**Comment by sangxxh** [comment]
> @sangxxh the correct typing here would to use a `Marko.AttrTag` and a `Marko.Body` type with parameters, in this case:
> 
> ```
> export interface Input {
>   heading: Marko.AttrTag<{
>     renderBody: Marko.Body<[{ data: TYPE_OF_DATA }]>
>   }>;
>   content: Marko.Renderable;
> }
> ```

That will still raise TypeScript error on my end though:

```marko
export interface Input {
  heading: Marko.AttrTag<{
    renderBody: Marko.Body<
      [
        {
          data: string;
        }
      ]
    >;
  }>;
  content: Marko.Renderable;
}

<body>
  <${input.heading} data="Marko"/>
                                ^^^ 
                                Argument of type '{ data: string; }' is not assignable to parameter of type 'Directives & { value: [{ data: string; }]; }'.
                                Object literal may only specify known properties, and '"data"' does not exist in type 'Directives & { value: [{ data: string; }]; }'.
  <hr>
  <${input.content}/>
</body>
```

This will erase the TypeScript error but breaks the app because `data` is not assigned.

```marko
<body>
  <${input.heading} value=[{ data: "Marko" }]/>
  <hr>
  <${input.content}/>
</body>
```

**Comment by DylanPiercey** [comment]
@sangxxh the issue here is actually because of a change between Marko class api and tags api.

When providing tag parameters, the best thing to do is use the unambiguous syntax in each api. For class api it's this:
```marko
<${input.heading}({ data: "marko" })/>
```

In tags api its this:
```marko
<${input.heading}=[{ data: "marko" }]/>
```
