### ISSUE TITLE
Static functions or arrow functions do not work on components without a class statement

### ISSUE THREAD

**Issue by AndresBarreto-code** [marko-js/marko#2029]
### Details

It seems we need to include a `class {}` statement if we want to use Event handling. I have created two components, both components use `buttons` elements with `on-click` method, however, one should include a class statement so the events run. I have created the following repo to reproduce it.

See:
https://github.com/AndresBarreto-code/marko-components

### Expected Behavior

The following component does not work:
```
static function handleClick() {
  alert("Component 1 Clicked by static function!");
}
<button on-click(handleClick)>
  Click static function
</button>
```

But the following component does work:
```
class {}
static function handleClick() {
  alert("Component 1 Clicked by static function!");
}
<button on-click(handleClick)>
  Click static function
</button>
```

### Actual Behavior

We expected both components to work. We expected to use Event handling without a class statement.

### Your Environment

- Chrome 115.0.5790.173, node v18.15.0.
- Windows 11.

### Steps to Reproduce

1. Clone the repo linked: https://github.com/AndresBarreto-code/marko-components
2. Run the repo.

**Comment by DylanPiercey** [comment]
This is supported after https://github.com/marko-js/marko/pull/2214
