### ISSUE TITLE
How does routing work?

### ISSUE THREAD

**Issue by RapidOwl** [marko-js/marko#2030]
I can't find any reference to routes or routing in the docs. The starter project I got when running the `npx` command only has an index page with `+page.marko`.

* What's the syntax?
* Is there support for wildcards/parameters?
* How does `+layout` work? Can I have multiple layouts? Can I nest them?
* What do the `+`'s in front of other files mean?

**Comment by DylanPiercey** [comment]
The default starter uses @marko/run. You can see it's documentation over here: https://github.com/marko-js/run

Eventually we will incorporate those docs into the main documentation on the website.

**Comment by RapidOwl** [comment]
Thanks for pointing me in the right direction!
