### ISSUE TITLE
`Marko is not defined` when index.marko imports module from component.ts

### ISSUE THREAD

**Issue by bill-min** [marko-js/marko#2091]
### Details

In any component, if you have:

index.marko
```MARKO
import { MY_ENUM } from "./component.ts"

<div>
  ${MY_ENUM.TEST}
</div>
```

component.ts
```TS
export interface Input {}

export enum MY_ENUM {
  TEST
}

export default class extends Marko.Component<Input> {}
```

It will cause error `Marko is not defined`. This happens to me when running storybook (with vite).

### Expected Behavior

Should work without error.

### Actual Behavior

`Marko is not defined`

### Possible Fix

<details><summary>Additional Info</summary>

### Your Environment

- Environment name and version (e.g. Chrome 39, node.js 5.4):
- Operating System and version (desktop or mobile):
- Link to your project:

### Steps to Reproduce

1.  first...
2.
3.
4.

### Stack Trace

</details>

**Comment by bill-min** [comment]
Will do when I get a chance

**Comment by DylanPiercey** [comment]
Closing for now.
