### ISSUE TITLE
Support Color Highlighting for Marko files in Sublime.

### ISSUE THREAD

**Issue by pedramphp** [marko-js/marko#22]
the Html color highlighting is not good enough for marko template files in Sublime, it will be great if we can create one for Marko templates

**Comment by patrick-steele-idem** [comment]
Syntax highlighting for Marko templates in Sublime would be great. Personally, I switched to from Sublime to Atom and am happier with Atom. I don't remember the exact method for creating a new language file for Sublime, but here is the grammar file that I created for Atom:
https://github.com/raptorjs/atom-language-marko/blob/master/grammars/marko.cson

I'm sure it is possible to write a tool that converts the Atom grammar into a Sublime grammar, but it is not something that I have time to do right now. I think it would be great if someone from the community could contribute Sublime support.

**Comment by merwan7** [comment]
Hey guys, I just started working w/ Marko recently and found thread.

I've ported your Atom grammar file to a Sublime/Textmate format.  I've also ported the snippets as sublime completions.  Should be handy for us ST fans.

https://github.com/merwan7/sublime-marko

I've currently got a PR to get this into the Package Control default channel.  Will update the readme once it gets merged.

**Comment by patrick-steele-idem** [comment]
That's awesome, @merwan7... thank you for the contribution! Do you mind submitting a PR to marko to add `sublime-marko` to the [Tools](https://github.com/marko-js/marko#tools) section in the marko `README.md` file?

Out of curiosity, how did you go about converting the Atom grammar file to work for Sublime? Was there an existing tool that you used? 

Thanks again!

**Comment by merwan7** [comment]
@patrick-steele-idem. Sure thing!  I will update that section as soon as it's added to the package control channel.

I couldn't find a tool to convert the grammars in that direction (atom->tm) so I wrote a little script which I am still working on, actually (will add to github soon).  There was some manual effort involved, too :)

**Comment by patrick-steele-idem** [comment]
Just closing old issues... Syntax highlighting in Sublime now works for Marko thanks to the PR submitted by @merwan7 that was merged: https://github.com/wbond/package_control_channel/pull/4652

**Comment by pcanella** [comment]
Not to toot my own horn here, but I ported @merwan7's Sublime syntax package to VS Code :). For anyone needing this, check it out here:
https://github.com/pcanella/vscode-marko
