### ISSUE TITLE
w-onclick attribute doesn't recognize events on touch devices

### ISSUE THREAD

**Issue by pcanella** [marko-js/marko#221]
Hi all,

It seems that after a few different implementations of basic w-onClick, it does not work on mobile or tablet devices at all; the event/function attached to it simply does not fire at all. I'm not really sure what else to put here, other than to try it yourself and see the issue firsthand :+1:

**Comment by yomed** [comment]
This probably relates to how mobile browsers detect clickable elements. For example, iOS Safari has some quirks:
https://developer.apple.com/library/ios/documentation/AppleApplications/Reference/SafariWebContent/HandlingEvents/HandlingEvents.html
http://www.quirksmode.org/blog/archives/2014/02/mouse_event_bub.html

I wonder if marko-widgets should try to handle this at all.

**Comment by patrick-steele-idem** [comment]
This is the first time I have heard about this, but I have not had to a lot of development for mobile. Without actually trying to reproduce, it would appear that @yomed is right and that maybe Safari is not recognizing the elements as clickable and is not bothering to emit an `onclick` event. Here is the relevant section in the Safari developer docs:
https://developer.apple.com/library/ios/documentation/AppleApplications/Reference/SafariWebContent/HandlingEvents/HandlingEvents.html#//apple_ref/doc/uid/TP40006511-SW6

It appears that a workaround might be to attach a dummy `onclick` handler:

```html
<span onclick="void(0)">...</span>
```

@pcanella or @yomed can either of you verify the dummy `onclick` workaround?

We actually make the decision at compile-time on whether or not to use event delegation or direct event listeners based on the event type: https://github.com/marko-js/marko-widgets/blob/526a04f46bcdbd292a46572c34fdb1b4a305bc08/taglib/TransformHelper/handleWidgetEvents.js#L123-L137

We could special case the `click` event and add code to do a direct event listener in mobile Safari and rely on event delegation in all other browsers.

If more details can be provided then we can definitely look into some possible fixes. Thanks for reporting the problem.

**Comment by nickcolley** [comment]
Related: https://github.com/facebook/react/issues/134

**Comment by mindeavor** [comment]
For the record, adding `onclick: pointer;` to the style of your element causes Safari to trigger a click event when you touch it on mobile.

**Comment by pcanella** [comment]
Just an update here: I ran into this on Marko V4 as well, but just installed [FastClick](https://github.com/ftlabs/fastclick) to fix it on iOS. Will try the `onclick: pointer` and add to CSS or something.
