### ISSUE TITLE
Provide ability to import custom tags

### ISSUE THREAD

**Issue by patrick-steele-idem** [marko-js/marko#227]
Here's one proposal:

``` xml
<import-tag "component-a" as componentA>
<import-tag "component-b" as componentB>

<invoke-tag(foo ? componentA : componentB) name="Frank" count=30/>
<invoke-tag(foo ? componentA : componentB, { name: 'Frank', count: 30 })/>
```

The `<import-tag>` tag would import another tag _renderer function_ at compile time and the tag rendering function would be accessible using the provided variable.

The following would also work:

``` xml
<import-tag "component-a" as componentA>
<import-tag "component-b" as componentB>

<invoke (foo ? componentA : componentB)({ name: 'Frank', count: 30 }, out)/>
```

In either case, the compiled code would be probably be similar to the following:

``` javascript
function create(__helpers) {
  var str = __helpers.s,
      empty = __helpers.e,
      notEmpty = __helpers.ne,
      escapeXml = __helpers.x,
      __loadTag = __helpers.t,
      componentA = __loadTag(require("../component-a/renderer")),
      componentB = __loadTag(require("../component-B/renderer"));

  return function render(data, out) {
    (foo ? componentA : componentB)({
      name: "World",
      count: 30
    }, out);
  };
}

(module.exports = require("marko").c(__filename)).c(create);
```

Thoughts? Suggestions? Concerns?

**Comment by patrick-steele-idem** [comment]
@yomed @tindli @philidem Thoughts?

**Comment by tindli** [comment]
Cool concept @patrick-steele-idem 

I think it greatly improves the expressiveness of Marko templates.
Love the idea that you can make a very generic template more 
specific by importing it into another template and giving it an alias!
So yeah, I would love to have them.

Just some thoughts:
1. Function wise, nothing is added - basically one could do the same
by simply using the name of the custom tag as it has been done until know (probably surrounded
by a `<if>` clause) - the dependencies would be resolved by lasso and the compiled 
code for both templates would be available in the client package...
The difference here is compile time; right? - anything else to differentiate (probably from a user perspective)?
2. Is there a specific reason not to use a syntax like:
`<import-tag componentA="component-a">`

Great concept!

**Comment by yomed** [comment]
In my case I have 15 components which I want to call dynamically. When there were only a few components, just using `<if>` works fine. But with a large list, it becomes pretty tedious. I don't think this is too far out of an edge case, since we are encouraging the use of lots of small components.

So I ended up invoking renderers directly and then passing them through a `<dynamic-tag>` component, which cleans up the `marko` files quite a bit, but also leaves implementation to the user (handling templates, renderers, widgets without ids, widgets with ids, etc., all of which marko should already know how to do). But applying that case here, I'm not sure this new feature helps too much. It would mean 15 lines of importing components directly by name.

Can we ever resolve the tags later to be fully dynamic?
```
<import-tags "data.tags" as data.names>

<for each="name in names">
    <invoke-tag(name, { name: 'Frank', count: 30 })/>
</for>
```

**Comment by mlrawlings** [comment]
I think we could implement this and #172 with a similar syntax:

```xml
<import(<tag-name> from './component')/>
```

Then just use it:
```xml
<tag-name/>
```

And for es2015 style inputs (#172):

```xml
<import({ dedupe } from './utils')/>
```

And they'd look slightly nicer without the argument parentheses:
```xml
<import <tag-name> from './component'/>
<import { dedupe } from './utils'/>
```

**Comment by philidem** [comment]
@mlrawlings I like your suggestion of using `<...>` to denote tag name and `{...}` to denote module. Hopefully it's not too clever but I'd use this feature!

**Comment by mlrawlings** [comment]
@philidem I've been playing with the parsing, from here it should be pretty trival to generate the necessary AST nodes: https://tonicdev.com/mlrawlings/573b709ca492941100e1140e

**Comment by scttdavs** [comment]
As Yoni mentioned, the real value in this is to have something like:

```html
<for(card in model.cards)>
  <${card.name} model=card />
</for>
```
I would think the name could be resolved and the component found from the `marko.json` file. Are there any major issues with that I'm missing?

**Comment by patrick-steele-idem** [comment]
@scttdavs Resolving a custom tag is relatively "expensive" and requires reading from the file system and require calls really need to be analyzable via static code analysis so that things will work with a JavaScript module bundler. For the completely dynamic use case, it's best to use `<invoke>` and to just pass in the component renderer for each component.

**Comment by patrick-steele-idem** [comment]
Closing this issue in favor of extending `<include>` to support rendering components/custom tags: [Issue #139: Allow dynamic custom tags to be used with `<include>`](https://github.com/marko-js/marko/issues/139)
