### ISSUE TITLE
Broken prettier plugin

### ISSUE THREAD

**Issue by vwong** [marko-js/marko#2276]
### Details

Recent change in Marko broke the Marko prettier plugin.

### Expected Behavior

Expect following code to successfully pass prettier
```
<lifecycle onMount() {
  console.log("boo");
}/>
```

### Actual Behavior

Prettier reformats code to look like [sic]:
```
<lifecycle onMount() {
  >

}/>
```

### Possible Fix

Likely https://github.com/marko-js/marko/commit/5cea7d65ead9b58d7d7d244078d279d561fd3ea7 broke it

Previous version 5.35.8 works correctly

**Comment by DylanPiercey** [comment]
Will take a look, thanks for the report!
