### ISSUE TITLE
Archiving the Marko Project

### ISSUE THREAD

**Issue by bensternthal** [marko-js/marko#2302]
The OpenJS Foundation is proposing that the Marko project be [archived](https://github.com/openjs-foundation/cross-project-council/blob/main/PROJECT_PROGRESSION.md#archived). 

This is due to us being unable to reach the maintainers via email for many months.

Note the final decision on archiving is made via CPC consensus and with the approval of the maintainers of the project.

If folks believe this project should not be archived please comment in this thread. 

Thank you!

**Comment by DylanPiercey** [comment]
@bensternthal this project is still under active development.
I don't believe I, or anyone else on the Marko team, have received any recent notifications from you all about this.

Possibly you have incorrect or out of date contact info?

**Comment by bensternthal** [comment]
@DylanPiercey You’re absolutely right—our information is probably outdated. To avoid sharing any personally identifiable information (PII) publicly, feel free to email me directly at bsternthal@linuxfoundation.org. We can coordinate to ensure the contact details are up to date.

Also, we have no intention of archiving any projects that remain active. So we can close this out as invalid :)

**Comment by DylanPiercey** [comment]
I'll reach out!
