### ISSUE TITLE
Cannot get Marko to work with Nestjs app

### ISSUE THREAD

**Issue by anapeksha** [marko-js/marko#2305]
Any idea how to implement marko templates in a Nestjs project?

Currently I am using handlebars as the templating engine, but I am looking to use Markojs as templating engine for Nestjs.

**Comment by LuLaValva** [comment]
I haven't looked too far into NestJS, but it looks like you can use alternative renderers by changing settings with `setViewEngine` from [this section of the NestJS docs](https://docs.nestjs.com/techniques/mvc).

To render Marko files, you can use [these rendering methods](https://markojs.com/docs/rendering/#rendering).

Let us know if you find a straightforward way to integrate Marko with NestJS! This would be great to document.

**Comment by anapeksha** [comment]
Got it! That's helpful, thanks
