### ISSUE TITLE
Marko v3: handling reserved javascript keywords

### ISSUE THREAD

**Issue by yomed** [marko-js/marko#237]
In one of my projects, I use `short` and `long` for property names in objects (I didn't realize these were technically reserved). It turns out that these fail in Marko v3 when used as `${data.short} and ${data.long}` in a template. It's worth noting that this is server-only since I'm not using marko widgets in this case.

Apparently, these two keywords, along with a host of others, are no longer reserved as of ES5. So if that's all it is I'm happy to submit a quick PR to update https://github.com/marko-js/marko/blob/master/compiler/util/javaScriptReservedWords.js to the ES5 list. Just wanted to check if there were any concerns in doing that, or if you prefer to keep pre-ES5 list.

If this is intentional (and that we're also intentionally disallowing property names as reserved keywords for IE8 support in case the template goes to the browser), maybe we should have an option to disable such behavior.

**Comment by philidem** [comment]
I would be in favor of using the official reserved words for ES5 and beyond. However, maybe we should add a warning to discourage their usage and maybe also add an option to disable the warning? We could rely on a environment property as quick hack (which would require smaller code change).

For example, something like `MARKO_DISABLE_RESERVED_WORD_WARNING=true ./build.sh` (disable the warning and launch the build).

**Comment by patrick-steele-idem** [comment]
That would be a bug if reserved words are not being allowed as property names. The intention was to only not allow reserved words as variable names:

```javascript
// Should not be allowed:
var short = 'foo';

// The following should be fine though:
data.short = 'foo';
```

I'll add a test case to see if I can reproduce. If I am not able to reproduce I'll probably ask for more details.
