### ISSUE TITLE
custom tags should default to single template file

### ISSUE THREAD

**Issue by yomed** [marko-js/marko#239]
Somewhat related to #235, what do you think about defaulting to a template file without the name `template.marko` if it is the only one in that directory level?

Currently I avoid naming my templates `template.marko` because file navigation is much quicker if I name it after the component. So my component naming tends to have some duplication (`component.marko` `component.js` `component.less`) but allows me to easily jump to files without having to type `component/template.marko` in navigation commands.

However, I end up having to copy paste tons of `index.js` files like so:
```js
'use strict';

var template = require('./component.marko');

module.exports = function render(input, out) {
    template.render(input, out);
};
```

It would be nice if marko could discover these automatically since it is the only template there anyway.

**Comment by philidem** [comment]
@yomed do your component files also live in a directory that matches the same name?

For example, do you have something like:
`my-widget/my-widget.marko`
`my-widget/my-widget.less`
`my-widget/my-widget.js`

I'm wondering if we should add one more convention that will check for `*.marko` file that has a filename (ignoring the extension) that matches the component directory?

Alternatively, maybe we can read this setting from the `marko.json` file (or `marko-taglib.json in v2)? Similar to how the directory that will be scanned to find components can be configured.

I use to name my component files similar to your convention but then I decided to embrace the Marko convention since it does have some nice benefits.

Specifically, I like these benefits of the standard convention:

- Easy to copy & paste a directory to "clone" an existing component (don't have to rename the individual files)
- The convention does help keep Marko projects similar to each other and each component has similar files.

The downside is that you might need to type a little extra into your IDE's search box when searching for file.

That said, I don't think we ever wanted Marko Widgets to be _too_ opinionated so I think we could consider allowing an alternative convention.

I would be interested to hear thoughts from others.

**Comment by yomed** [comment]
Yep, that's exactly what I do. So in my case, matching the directory name would be enough. I actually only follow this convention for my own personal projects. For larger projects with more people, I follow the standard convention for the reasons you mentioned - while suffering through slower file navigation.

It's fairly simple to work around this, but I think it would be nice if marko was slightly less opinionated on file names. Looking for `template.marko`, then `dir-name.marko`, before finally looking through the templates in the directory, might be a nice way to optimize for the primary cases. I guess it depends how much magic we want vs. config.

**Comment by patrick-steele-idem** [comment]
You can create a `marko-tag.json` file with the following:

```json
{
  "template": "./my-component.marko"
}
```

With that said, I am curious as to why you think there is less typing when navigating in your IDE. For example, in Atom or Sublime if I want to open a template file for a UI component I start typing a portion of the component name followed by a few letters in "template" or "marko" and then it will quickly take me to the template belong to a specific component (thanks to fuzzy matching). For example:
![screen shot 2016-02-28 at 8 05 29 pm](https://cloud.githubusercontent.com/assets/978214/13384825/d05606ca-de56-11e5-9e08-8958d7f2f1ae.png)

The only con that I am aware when not repeating the directory name is that Atom still doesn't differentiate the file correctly when there are multiple files with the same basename opened. I opened up an issue against Atom that is worth checking out: https://github.com/atom/atom/issues/7345#issuecomment-113577006

Also, there are good reasons to keep the main file named `index.js` so won't it look strange to have one file named `my-component.marko` and another named `index.js`? Also, repeating the directory name is not DRY and has all of the issues that @philidem mentioned.

Making the convention more flexible to allow a repeated directory name would introduce more file system checks so I would rather not go that route. We could, in theory, introduce a new setting that could be put in the `marko.json` file at the root of the project to change the convention or to allow a custom user resolver.

With that said, there are benefits to have more consistency within the community. For example, we would like to introduce more developer tools to scaffold out new UI components and we would only want to support one convention. How attached are you to repeating the directory name in each of the nested files? Like @philidem, I also started out with the repeated directory name in nested files, but I switched and I would never go back.

**Comment by yomed** [comment]
That's true on the first point. Since about half my components have renderers and half have templates, I set them all up as renderers for "consistency," although it could really go either way. 

When I used Atom, I did notice that the fuzzy autocomplete was pretty good. But for a bunch of other reasons, I've gone back to Webstorm for now. Webstorm isn't as good with directory matching and I would to type `full-directory-name/t` to get to the template.

Regarding the `js` naming - my own personal convention is to use marko defaults when needed on the server like `index.js` `renderer.js`, but to use component name for client side js - `component.js`. You're right that having a lot of index files is a bit awkward considering my other file names, but that's more part of node.js than Marko. This convention does help me differentiate server/client a bit better.

On the last point, I'm not sure. I think as long as Webstorm autocomplete stays the way it is, it is significantly faster for me to keep my current naming conventions. If I move back to Atom, then the point is moot. Sucks to make IDE-specific decisions, but I just really hate typing out long directory names, and the other benefits of Webstorm over Atom (in my opinion) keep me there.

**Comment by yomed** [comment]
Wanted to add that in playing around with this some more, you do have to type the `/` but not the entire folder names in Webstorm. So it's not quite as bad. I still think some flexibility might be nice here regardless.

**Comment by yomed** [comment]
I've since moved to generic file names in components (and haven't had any issues with quick navigation in VS Code). We can close this, unless you were still considering expanding auto-discovery.

**Comment by andresilvasantos** [comment]
Sorry for re-opening this issue.

@patrick-steele-idem and @philidem you gave very good reasons for this to be implemented the way it is. But still, it's hard to work with files all named the same.

I feel really lost when I'm focused coding and I try to change to the footer file for example and I look above to the open file tabs in Atom and I just see index.marko. It's so confusing that some times I just forget the name of the file I was looking for and I have to type a name for fuzzy matching or go to the sidebar and scroll among all files and folders. And that really breaks the workflow.

Tried this, but it didn't work: 

> You can create a marko-tag.json file with the following:

```
{
  "template": "./my-component.marko"
}
```
