### ISSUE TITLE
Dynamic nested tags

### ISSUE THREAD

**Issue by aselvaraj** [marko-js/marko#249]
I am building a reusable component "data grid" using marko templates.

The component renders set of passed data in html `<table>`. The component internally supports couple of cell renderers which injects content inside `<td>`.
1. Text - for displaying paragraph of text/ list of links
2. Image - for displaying an image

I would also like to allow clients to configure custom cell renderers if you they choose to implement something on their own.

I don't see a way to invoke templates dynamically. As expected `<include>`  directly invokes the template and don't execute the renderer.

Am I missing something?

 **P.S:** I am using marko-v2 and this component is server side rendered.

**Comment by patrick-steele-idem** [comment]
The user of the "data grid" component can pass a `renderer(input, out)` function associated with a UI component to the "data grid" component for use as a cell renderer:

_In JavaScript_

```javascript
var cellRenderer = require('src/components/app-my-component').renderer;
```

```
<app-data-grid cell-renderer="data.cellRenderer"/>
```

Within the template for the "data grid" component, the cell renderer can be invoked similar to the following:

```xml
<tr>
  <td>
    <invoke function="data.cellRenderer({ ... }, out})"/>
  </td>
</tr>
```

Let me know if that doesn't answer your question.

**Comment by aselvaraj** [comment]
:+1: 

Thanks @patrick-steele-idem.

**Comment by patrick-steele-idem** [comment]
We'll be simplifying this as part of Marko v4: https://github.com/marko-js/marko/issues/139

Closing this issue.

**Comment by aselvaraj** [comment]
👍 Looking forward to Marko v4.
