### ISSUE TITLE
Output of render should be Promise-compatible

### ISSUE THREAD

**Issue by DylanPiercey** [marko-js/marko#251]
Currently rendering a template returns an `AsyncWriter`, it would be handy though if when a callback is omitted that templates render function returned a promise.

``` js
var template = require("template.marko");

template.render({ hello: "world" })
    .then(function (html) { ... })
    .catch(function (err) { ... });
```

If you're using promises already it makes using marko a bit easier.

**Comment by GenaANTGOfficial** [comment]
You can use temporarily **bluebird** module.

```
let Promise = require('bluebird');
let EntryCommentsMarkup = require('./views/EntryComments.marko');
Promise.promisifyAll(EntryCommentsMarkup);
```

then in routing we invoke **renderAsync** method:

```
app.get('/example', function(req, res) {
    let Data = { ... };
    return EntryCommentsMarkup.renderAsync(Data);
});
```

**Comment by patrick-steele-idem** [comment]
/CC @philidem @mlrawlings 

I would like to see a method that returns a promise, but I would prefer to avoid a breaking change. The purpose of returning the `AsyncWriter` instance was to be compatible with the `EventEmitter` API (`on`, `once`, `emit`, etc.) that `AsyncWriter` implements. For example:

```javascript
template.render({ hello: "world" })
    .on('foo', function(e) {
        
    })
    .on('error', function(e) {
        
    })
    .on('finish', function() {
        
    })
```

What are your all thoughts on utilizing the native promise implementation to provide a new `renderAsync` method?:

```javascript
var template = require("template.marko");

template.renderAsync({ hello: "world" })
    .then(function (html) { ... })
    .catch(function (err) { ... });
```

**Comment by mlrawlings** [comment]
I'd rather modify `async-writer` to be a [thenable](https://promisesaplus.com/) by adding `.then` and `.catch`

I've seen other libraries such as [`superagent`](http://visionmedia.github.io/superagent/) and [`mongoose`](http://mongoosejs.com/docs/promises.html) implement a promise-like interface that plays well with anything that is duck-typing rather than looking at `instanceof Promise` (which is most everything due to things like `bluebird` and `q`).  

It would support both
```js
template.render({ hello:"world" })
    .then(function (html) { ... })
    .catch(function (err) { ... });
```
and
```js
template.render({ hello:"world" })
    .on('error', function(e) { ... })
    .on('finish', function() { ... })
```
And with async/await you'd be able to do:

```js
var html = await template.render({ hello:"world" })
```

We could also implement a `.promise` function (or some other name) that returns a true `Promise` for cases where it is needed.

**Comment by patrick-steele-idem** [comment]
I like the suggestion to implement the `then` and `catch` methods on the `AsyncWriter` instance. Let's go forward with that approach.

**Comment by patrick-steele-idem** [comment]
FYI: it should be sufficient to add the `then()` and `catch()` methods to [OutMixins.js](https://github.com/marko-js/marko/blob/master/runtime/OutMixins.js) since those mixins are added to both `AsyncStream` and `AsyncVDOMBuilder`

**Comment by patrick-steele-idem** [comment]
NOTE: We want to follow the rules for having a consistent rendering API: https://github.com/marko-js/marko/issues/389

That is:

```javascript
template.render({})
    .then(function(out) {
        out.appendTo(document.body);
    });
```

**Comment by Hesulan** [comment]
A bit late, just throwing this out there: The Promises/A+ specification requires that if the result is an `object` or `function` with a `then` method, it *must* be treated as a "thenable". In other words, this solution is explicitly permitted by the specification, and any `Promise` library which doesn't handle this correctly is - by definition - "broken". That's all, carry on. :)
