### ISSUE TITLE
w-body not available in macro

### ISSUE THREAD

**Issue by tbashor** [marko-js/marko#253]
In some of the custom elements I've written, I want to use different root elements based on the context. I want to put `w-bind` on these root elements. The content inside these root elements is the same across variations and I would like to use a macro to avoid repetition. However, when I try to use `w-body` in the macro, I get an error saying that w-body can only be used inside a element with w-bind. This prohibits my ability to use a macro to render the content.

What is the best way to pass a rendered body to the macro?

**Comment by mlrawlings** [comment]
```xml
<!-- you're doing something like this: -->

<macro myMacro(label)>
    <h1>${label}</h1>
    <div w-body/>
</macro>

<div w-bind if(data.rootTagName === 'div')>
    <myMacro label="Hello World"/>
</div>
<span w-bind if(data.rootTagName === 'span')>
    <myMacro label="Hello World"/>
</span>
<p w-bind else>
    <myMacro label="Hello World"/>
</p>

<!-- try this instead: -->

<${data.rootTagName} w-bind>
    <h1>${label}</h1>
    <div w-body/>
</>
```

**Comment by patrick-steele-idem** [comment]
I also investigated this issue and while I think we could make it work, it would complicate the code for an edge case. The workaround that @mlrawlings suggested above should work so I'm going to go ahead and close this issue.

**Comment by tbashor** [comment]
Thanks for the suggestion. I'll try it.

**Comment by tbashor** [comment]
@mlrawlings I tried the technique you suggested and the element renders correctly. However, the new element is not bound. 

With this template:
```
<${data.tag} class=data.classes w-bind >
  <div class="content">
    <invoke data.renderBody(out) />
    <div class="sub header" if(data.subheader)>${data.subheader}</div>
  </div>
</>
```

I get:
```
<h2 class="ui-heading" w-bind>
<div class="content">My Header</div>
</h2>
```

And when I use `w-body` instead of `<invoke data.renderBody(out) />` I still get a compile error complaining about w-body without w-bind.

Let me know if I missed something that enabled the suggestion to work.

**Comment by patrick-steele-idem** [comment]
Hey @tbashor, there was a bug in Marko that prevented the Marko Widgets compile-time transformers from working on tags with a custom tag name. This has been fixed:  https://github.com/marko-js/marko/blob/master/CHANGELOG.md#374

Please let me know if you still see issues. Thanks!

**Comment by tbashor** [comment]
Works like a charm. Thanks!
