### ISSUE TITLE
Can you not include one custom tag in another?

### ISSUE THREAD

**Issue by jasonmacdonald** [marko-js/marko#259]
I'm trying to do something very simple but I can't seem to get it to work. I have a basic template like this...

`<div>
   <customTag></customTag>
</div>`

And in custom tag's template I include another custom tag...

`<div>
    <customTag2></customTag2>
</div>`

And then finally, customTag2's template simply renders.

`I'm custom tag 2`

When I render all this, I end up with 

`<div>
   <div>
      <customTag2></customTag2>
   </div>
</div>`

It never renders customTag2. And I know the tag lib is found becuase if I go to my main template and include both custom tags, they both render, but not if they are nested. 

Am I doing something wrong? Or is including one custom tag in another's template not supported? Do I have to do the Parent/Child thing? I'd rather not since the child tag is intended to be used in many places.

**Comment by patrick-steele-idem** [comment]
Could you provide more details on the directory structure? It looks like `<customTag2>` is not being discovered relative to the location of the `customTag/template.marko`. Are `<customTag>` and `<customTag2>` registered in the same package. Where is your `marko.json` relative to `customTag/template.marko` and `customTag2/template.marko`?

**Comment by jasonmacdonald** [comment]
Sure, it's a pretty simple set-up.

- tags
    - CustomTag1
        - template.marko
    - CustomTag2
        - temaple.marko
- template
    - MainTample.marko
- Index.js
- marko.json


Here, the index file is rendering the ./template/mainTemplate.marko. The marko.json is as follows

`{
    "tags-dir": "./tags/"
}`

**Comment by patrick-steele-idem** [comment]
That does look pretty simple. The names of the custom tags are case-sensitive. If the directory name is "CustomTag2" then the custom tag will be `<CustomTag2/>`. Is that possibly the reason that `<customTag2>` is not being found?

**Comment by jasonmacdonald** [comment]
No, sorry that's just my bad typing here. I fixed the above example.

**Comment by patrick-steele-idem** [comment]
I'm not able to reproduce using the following sample app:
https://github.com/patrick-steele-idem/marko-issue-259

Do you see any differences between your app and the sample app I created?

**Comment by jasonmacdonald** [comment]
You are right, that works. It must be something with my set-up. I'll close this for now since it is possible and try to figure out where I messed up. :) Thanks for all the help!
