### ISSUE TITLE
Escaping dollar within html attribute results in syntax error

### ISSUE THREAD

**Issue by christensson** [marko-js/marko#263]
Howto reproduce:
1. Open the online "try-out" "Simple" example at http://markojs.com/try-online/ 
2. Modify the line 3rd line to add an attribute
`<li data-bind="\$foo" for(color in data.colors)>`
3. The expected output for the above is `<li data-bind="$foo">` but instead a syntax error occurs.

It works if the dollar-sign isn't escaped at all.
`<li data-bind="$foo" for(color in data.colors)>`

In marko-js pre v3 this worked as expected...

**Comment by patrick-steele-idem** [comment]
Hey @christensson, in Marko v3 we dropped support for `$<var_name>` (without the curly braces). Therefore, you don't need to escape the `$`, but does seem odd that having `\$` in the attribute is causing a syntax error. I'm looking into it. Thanks for reporting the problem.

**Comment by christensson** [comment]
Worth to mention is that the migration tool translates attr="\$foo" into attr="\\$foo" which is not what is expected...

**Comment by patrick-steele-idem** [comment]
Ok, I took a closer look. It's not actually a bug in Marko. The right-hand side of an attribute is parsed as  a JavaScript expression and the string definition must follow the rules for defining a JavaScript string.

If you run the following code in your JavaScript console you will see the same error:

```javascript
JSON.parse('"\\$foo"');

// Output in Chrome/V8: SyntaxError: Unexpected token $(…)
// Output in Firefox: SyntaxError: JSON.parse: bad escaped character at line 1 column 3 of the JSON data
```

With that said, I think we can improve the error message and we definitely need to fix `marko-migrate`. I'll keep working on on this. Thanks again.

**Comment by patrick-steele-idem** [comment]
By the way, if you want to fix your template you should update it to the following:

```xml
<li data-bind="\\$foo" for(color in data.colors)>
```

(with JavaScript, you need to escape the `\` if you want it to show up in the output)

I'm still working on updating `marko-migrate`, but I have improved the error message produced by the parser.

**Comment by christensson** [comment]
The migration script translates \$foo into double \ $foo

Since I'm using knockout js some special variables need to be prefixed with $, luke $parent and such. In this case the output needs to be attr="$parent" without any \

**Comment by patrick-steele-idem** [comment]
I see. I will update `marko-migrate` to ensure the following:

Input Marko v2 template:

```xml
<div class="\$foo"></div>
```

Output Marko v3 template:

```xml
<div class="$foo"/>
```

Thanks for clarifying.

**Comment by patrick-steele-idem** [comment]
Still investigating and adding more tests. It appears there might be some other issues that I need to resolve.

**Comment by patrick-steele-idem** [comment]
Took a little more thought than expected, but the `marko-migrate` script has been updated to properly handle backslash characters in front of placeholders. If you would like to try the migration again, please install the latest version of `marko-migrate`:

```bash
npm install marko-migrate@^1.0.13 --global
```

Please let me know if you still see issues. Thanks!

**Comment by christensson** [comment]
Great, I will try it out in a couple of days!

**Comment by christensson** [comment]
Thanks, the solution worked!
