### ISSUE TITLE
Strange issue with rendering template

### ISSUE THREAD

**Issue by Bluejay47** [marko-js/marko#265]
This is my template:

```
<!DOCTYPE html>
    <html lang="en"> 
        <head>
            <title>Estimake.co</title>
            <include template="./partials/includes.marko" />
            <link rel="stylesheet" type="text/css" href="editProject.css">
            <script src="editProject.js" type="text/javascript"></script>
        </head>
        <body>
            <include("./partials/menu.marko", data)/>
            <include("./partials/footer.marko")/>
        </body>
    </html>
```

This is what I am getting when the template is rendered in v3.

`<﻿<!DOCTYPE html>><html lang="en"> <head> <title>Estimake.co</title> ... </body> </html></﻿<!DOCTYPE>`

Any idea why I have the 'strangeness' with the DOCTYPE?

**Comment by patrick-steele-idem** [comment]
@Bluejay47 when I try to compile your exact template I get the following error:

```
An error occurred while trying to compile template at path ".../template.marko". Error(s) in template:
1) [.../template.marko:2:4] Line has extra indentation at the beginning
```

Which is what I would expect. The `<html>` tag should not be indented. The following compiles with no issue:

```xml
<!DOCTYPE html>
<html lang="en">
    <head>
        <title>Estimake.co</title>
        <include template="./partials/includes.marko" />
        <link rel="stylesheet" type="text/css" href="editProject.css">
        <script src="editProject.js" type="text/javascript"></script>
    </head>
    <body>
        <include("./partials/menu.marko", data)/>
        <include("./partials/footer.marko")/>
    </body>
</html>
```

Please let me know if I am missing anything.

**Comment by Bluejay47** [comment]
Ok, thanks. I tried yours and got the same issue 

'<﻿<!DOCTYPE html>></﻿<!DOCTYPE><html lang="en">'

but there must be something wrong with my installation, because apparently the original file should not have even compiled.

I take it from your answer that with 3.0 indention is now significant like with the Jade engine even with the HTML approach?

**Comment by patrick-steele-idem** [comment]
Indentation only matters for top-level HTML elements. Once you are within an HTML tag, the indentation does not matter as long as you are not using the concise syntax.

Do you mind messaging me on Gitter to help debug your issue? I am not able to reproduce. https://gitter.im/patrick-steele-idem

**Comment by Bluejay47** [comment]
Let me play around with my installation first. I won't to make sure I am not doing something stupid before I bug you about it. I am not sure how the first template compiled given the error in indention.

Thanks for your quick response.
