### ISSUE TITLE
Compiler fails when using w-preserve-attrs on a custom tag

### ISSUE THREAD

**Issue by 1N50MN14** [marko-js/marko#269]
Example:

`<mywidget w-preserve-attrs="style,class" />`

Will result in the template compiler throwing the following error:

```javascript
/webapp/node_modules/lasso/lib/dependency-walker.js dependency.getPackageManifest failed: Error: An error occurred while trying to compile template at path "/webapp/src/code/components/cover-profile/index.marko". Error(s) in template:
1) [src/code/components/cover-profile/index.marko:25:8] Unsupported attribute of "data-w-preserve-attrs" found on the <tinput> custom tag.

    at Compiler.compile (/webapp/node_modules/marko/compiler/Compiler.js:124:25)
    at /webapp/node_modules/marko/compiler/index.js:84:41
    at tryToString (fs.js:414:3)
    at FSReqWrap.readFileAfterClose [as oncomplete] (fs.js:401:12)
```

**Comment by patrick-steele-idem** [comment]
@1N50MN14 The `w-preserve-attrs` attribute only works on standard HTML elements (not custom elements). You should, instead, be adding the `w-preserve-attrs` attribute to the root HTML element in the template for the `<mywidget>` UI component. Please let me know if that does or does not solve your problem.

**Comment by patrick-steele-idem** [comment]
I believe this is a non-issue so closing. Please reopen if I am mistaken. Thanks.
