### ISSUE TITLE
Typo in Widget-State Doc

### ISSUE THREAD

**Issue by CestDiego** [marko-js/marko#271]
I am not sure what is this supposed to be: http://markojs.com/docs/marko-widgets/get-started/#widget-state

in the `getTemplateData` function there is an assignment to nothing to `style`:

```
getTemplateData: function(state, input) {
        var style = ;
 
        return {
            name: state.name,
            color: state.selected ? 'yellow' : 'transparent'
        };
    },
```

**Comment by patrick-steele-idem** [comment]
Thanks for reporting the problem @CestDiego. That would be a typo. In the upper right of the page you will see a "Improve this page" link. That will take you to the source markdown file if you want to clean it up. I would just remove the `var style = ;` line. If you don't have time to send a PR please let me know, but a PR would be greatly appreciated. Thanks again!

**Comment by CestDiego** [comment]
https://github.com/marko-js/marko-widgets/pull/132 done
