### ISSUE TITLE
WebStorm plugin with advanced features

### ISSUE THREAD

**Issue by patrick-steele-idem** [marko-js/marko#272]
I'm opening this issue to gauge the community's interest in a WebStorm plugin with advanced features that may include the following:
- [ ] Smart autocompletion for custom tags and standard HTML tags
- [ ] Smart autocompletion for tag attributes based on tag schema files
- [ ] Pretty printing with syntax switcher
- [ ] Block commenting
- [ ] Click to go to tag definition
- [ ] UI component generator
- [ ] Anything else?

The more developers that are interested will help us make a stronger case for investing in this functionality.

Related issues:
- [Atom plugin](https://github.com/marko-js/marko/issues/273)

(I'll open a similar Github issue for Sublime Text and Visual Studio Code)

**Comment by yomed** [comment]
The only item from that list that I've found myself actively missing is "click to go to tag definition" (i.e. jump to custom tag template file) but the others would be great too!

**Comment by darkwebdev** [comment]
Many fullstack engineers use IntelliJ, so such a plugin would definitely make sense.

**Comment by jsumners** [comment]
Autocompletion of `${data.something}` would be great. Hopefully the tag attributes would autocomplete layout elements.

**Comment by wmossman** [comment]
Yes please! Also a default widget component files generator via right-click would be nice.

**Comment by patrick-steele-idem** [comment]
> Also a default widget component files generator via right-click would be nice.

Great suggestion. I'll update the description to include that. Thanks!

**Comment by yask123** [comment]
Any update on this?

**Comment by mlrawlings** [comment]
@yask123 So far, most of our tooling effort has been focused around the atom editor (see #273).  We've not got WebStorm on our roadmap right now, and we don't have a lot of expertise with the java-based IntelliJ plugin system.  

Our hope is that a developer that is familiar with the WebStorm ecosystem could look at the atom implementation to add support for WebStorm.

**Comment by davidmoshal** [comment]
Official website lists Webstorm integration, but link points to textmate:

http://markojs.com/docs/editor-plugins/

**Comment by mlrawlings** [comment]
@davidmoshal Thanks for pointing this out, I believe that _is_ intentional as we don't have a true webstorm integration, but webstorm [can import tmbundles](https://www.jetbrains.com/help/webstorm/2016.3/importing-textmate-bundles.html).  We should definitely make this clearer on that page.

**Comment by jsumners** [comment]
Given the complexity of implementing this, anyone interested in such a plugin should also login to JetBrains's issue tracker and vote for the issue https://youtrack.jetbrains.com/issue/WEB-20821

**Comment by davidmoshal** [comment]
Done

**Comment by mlrawlings** [comment]
We're not going to devote resources to this anytime soon.  We'd like to support a language server (#859) moving forwards, however WebStorm will need to support that as well: https://youtrack.jetbrains.com/issue/IDEABKL-7409
