### ISSUE TITLE
Concise syntax document: inline tags

### ISSUE THREAD

**Issue by bitinn** [marko-js/marko#277]
I am using Jade doc as a reference at the moment, they suggest using html tag directly for inline tags, does marko recommend the same strategy or does it have a better solution? eg.

```
p - hello there, <strong>username</strong>.
```

A demo on http://markojs.com/try-online/ would help. Currently the only demo with inline tags are using macro. I think it's an overkill to do this with macro.

**Comment by bitinn** [comment]
Ah interesting, so whitespace demo does sort of address my question, not quite sure what `---` stands for though.

http://markojs.com/try-online/#Whitespace_Simple

**Comment by bitinn** [comment]
Closing this as the answer is:

```
p
  - hello there,
  strong - username
  - .
```

**Comment by patrick-steele-idem** [comment]
Hey @bitinn, sorry for not being able to respond earlier. We definitely need to add better docs for the new syntax (we have plans to do this very soon). FYi, all of the following are equivalent:

```xml
p - hello there, <strong>username</strong>.
```

```xml
p
  - hello there, <strong>username</strong>.
```

```xml
p
  ---
  hello there, <strong>username</strong>.
  ---
```

```xml
p
  - hello there,
  strong - username
  - .
```

There are four ways to enter into HTML parsing mode:

**Option 1. HTML tag:**
```
<div>
  [this will be parsed as HTML]
</div>
```

**Option 2. HTML line after tag/attributes:**
```
div - [this will be parsed as HTML]
```

**Option 3. Single line HTML block:**
```
div
  - [this will be parsed as HTML]
```

**Option 4. Multiline, delimited HTML block:**
```
div
  ---
  [this will be parsed
  as HTML]
  ---
```

Sorry this wasn't explained better in the docs. Please let me know if you have any other questions. Also, please join us on Gitter if you haven't already: https://gitter.im/marko-js/marko
