### ISSUE TITLE
How can insert <br> (or <p>) tag?

### ISSUE THREAD

**Issue by taecilla** [marko-js/marko#279]
Hi,

I have a project where part of the content is inserted on a database using a CMS. That content sometimes have paragraphs. I tried to replace `\\n` (and others) with `<br>`, but then Marko replaces the `<` whit `&lt;` for security reasons I guess. How can I avoid that at least with some tags?

**Comment by davidenq** [comment]
For example:

**_data_**
```json
{
    "name": "<br>Markojs"
}
```

**_marko template hello.marko_**
```html
- Hello ${data.name}!
<span>Other text</span>
```

**_output html_**
```
Hello &lt;br>Markojs! <span>Other text</span>
```
> Hello &lt;br>Markojs! Other text

By default, all special HTML characters will be escaped in dynamic text to prevent Cross-site Scripting (XSS) Attacks. To disable HTML escaping, you can use $! as shown in the following sample code:
**_data_**
```json
{
    "name": "<br>Markojs"
}
```

**_marko template hello.marko_**
```html
- Hello $!{data.name}!
<span>Other text</span>
```

**_output html_**
```
Hello
<br>Markojs! <span>Other text</span>
```
>Hello
Markojs! Other text

Ref: [Language Guide // Marko](http://markojs.com/docs/marko/language-guide/#text-replacement)

**Comment by taecilla** [comment]
Thanks a lot, I remembered to have read it somewhere but I couldn't find it.

**Comment by patrick-steele-idem** [comment]
Thanks for the question @taecilla and thanks for the reply @davidenq! It sounds like the question was answered so I'm closing the issue.
