### ISSUE TITLE
Compiled template not updating.

### ISSUE THREAD

**Issue by cantoine** [marko-js/marko#295]
I'm probably doing something really stupid but with the following code I can't get Marko to recompile the template when I make a change directly to the template file. Can anyone tell me what mistake I'm making?

    'use strict';
    process.env.MARKO_CLEAN = true;
    require('marko/node-require').install();

    require('marko/compiler').defaultOptions.checkUpToDate = true;
    require('marko/compiler').defaultOptions.writeToDisk = true;
    require('marko/compiler').defaultOptions.preserveWhitespace = true;
    require('marko/compiler').defaultOptions.assumeUpToDate = false;

    const Hapi = require('hapi');
    const server = new Hapi.Server();

    server.connection({ port: 4000 });

    server.start((err) => {
        if (err) {
            throw err;
        }
        console.log('Server running at:', server.info.uri);
    });

    server.route({
        method: 'GET',
        path: '/',
        handler: function (request, reply) {
            var template = require('./template.marko');
            
            console.log('Render Template');
            template.render({ name: 'Frank', count: 30 }, function(err, output) {
                    if (err) {
                        console.error('Rendering failed');
                        return;
                    }

                    return reply(output);
                }
            );
        }
    });

**Comment by patrick-steele-idem** [comment]
Hey @cantoine, loaded templates are stored in the Node.js require cache. Marko supports hot reloading functionality, but you need to provide a file watcher or use [browser-refresh](https://github.com/patrick-steele-idem/browser-refresh). I recommend taking a look at `browser-refresh`, you will get hot reloading for free on the server and in the browser if you launch your app using `browser-refresh`. If you don't want to use `browser-refresh`, please see the following sample app:

https://github.com/marko-js-samples/marko-hot-reload

Please let me know if you still have questions.

**Comment by cantoine** [comment]
@patrick-steele-idem perfect! Thanks a ton, I knew I had to be missing something. I'm not sure how I missed the hot-reload options.
