### ISSUE TITLE
async-fragment-tag-transformer.js being loaded by PhantomJS

### ISSUE THREAD

**Issue by abiyasa** [marko-js/marko#304]
I was running karma + PhantomJS on some Marko Widgets with async-fragments, I got the following error:

```
Running "karma:test" (karma) task
     Saving optimization output to: ./.test/static
START:
PhantomJS 2.1.1 (Mac OS X 0.0.0) ERROR
  SyntaxError: Unexpected token '>'
  at /Users/isuhardi/works/feproject/.test/static/index/marko$3.4.4/taglibs/async/async-fragment-tag-transformer.js:28
```

This is due to arrow syntax at async-fragment-tag-transformer, which PhantomJS cannot run due to lack of ES6 support.

**Comment by patrick-steele-idem** [comment]
Thanks for reporting the problem. New version published with fix: `marko@3.4.5`

Please let me know if you still see any issues. Thanks!
