### ISSUE TITLE
w-onClick handler doesn't work during progressive rendering

### ISSUE THREAD

**Issue by darkwebdev** [marko-js/marko#311]
So I used a progressive rendering demo and changed `addEventListener` to `w-onClick`. Now header widget reacts on clicks only after rendering is finished. Problem appeared after upgrading Marko 2 to 3.

Demo here: https://marko-progressive-bug.herokuapp.com

Forked repo to show a bug: https://github.com/darkwebdev/marko-progressive-rendering

Commit with changes: https://github.com/darkwebdev/marko-progressive-rendering/commit/afe5c03567b77b641d54404ee2eac7243b417661

**Comment by patrick-steele-idem** [comment]
Hey @darkwebdev, just wanted to say that I haven't had a chance to investigate since I was out of the office this past week. I hope to investigate this a little later this week. Thanks for reporting the problem and thanks for your patience!

**Comment by patrick-steele-idem** [comment]
Fixed. See: https://github.com/marko-js/marko-widgets/issues/153

Thanks for reporting the problem!
