### ISSUE TITLE
alt attribute with empty string should be allowed

### ISSUE THREAD

**Issue by yomed** [marko-js/marko#327]
The `alt` attribute has a few scenarios where it should be an empty string, particularly when used on decorative images: https://developers.whatwg.org/embedded-content-1.html#a-purely-decorative-image-that-doesn%27t-add-any-information

In marko v3, rendering `<img alt="">` will become `<img alt>`. Haven't checked the exact output in v2, but I believe the issue is there too. Is there a workaround to get empty strings to show up? I imagine there might be similar cases out there for other attributes, but maintaining a list of exceptions would be unfortunate.

**Comment by patrick-steele-idem** [comment]
/CC @philidem @mlrawlings 

Not ideal, but you can using a space character: `<img alt=" ">`

With that said, I think we should revisit the rules for rendering attribute value. I think the following would be more appropriate...

Giving the following template:

```xml
<img alt=someExpression/>
```

| someExpression                   | Current                      | Proposed          |
|----------------------------------|------------------------------|-------------------|
| `undefined` / `null` / `false` | `<img>`                        | `<img>` (no change) |
| `true` | `<img alt>`                        | `<img alt> (no change)` |
| `''` | `<img>`                        | `<img alt="">` |

While this would be a change, I am not sure it would actually break anything. Thoughts?

**Comment by yomed** [comment]
There are probably cases where people rely on empty string not rendering the attribute, as in `<div class=${data.someClass}>` when `data.someClass` is an empty string. Technically it wouldn't break anything to have it output as `<div class="">`, but that's probably worse off then before. Maybe it's worth it to maintain the exceptions?

**Comment by mlrawlings** [comment]
@patrick-steele-idem I'd lean towards your table rather than creating a list of exceptions.

I was just testing and I think we've got some weird behavior...

`<img alt="">` becomes `<img alt>`

but

`<img alt=data.alt>` becomes `<img>` if `data.alt === ''`

This is weird, but also means that we could probably leave `alt=""` untouched if it's a string literal and keep the current behavior if it's a variable that contains an empty string as its value (if we want to).  Or maybe we should make it consistent...

@yomed Out of curiosity, is there any reason why you couldn't forgo the `alt` attribute and use `role="presentation"` or `aria-hidden`?  And does `alt` behave differently than `alt=""`?

**Comment by yomed** [comment]
@mlrawlings This came up in a PR recently where using an a single space alt was the best solution we could come up with, but stood out as a clear hack. Apparently alt is "required no matter what" (probably due to screen reader behavior?) which then leads to weird cases where the official suggestion is to have `alt=""`.

**Comment by mlrawlings** [comment]
@yomed If you ask me, even `alt=""` is kinda a hack used to stop the screen reader from reading out the url to the image.  But `role="presentation"` or `aria-hidden` explicitly tell the screen reader to ignore it because it's for presentational purposes only.  

In any case, we should probably fix this.

**Comment by yomed** [comment]
But it's an officially sanctioned hack! 😆

**Comment by patrick-steele-idem** [comment]
I'm in favor of updating Marko to follow the proposed table above as part of a minor release. The chances of actually breaking anything are extremely low since the worst case is that there will be an attribute with empty quotes when there was no attribute before. Any objections?

**Comment by yomed** [comment]
I'm not sure, in that case I think I'd personally prefer leaving it as-is. Empty string is a nice shortcut to avoid rendering an attribute, and it's only wrong in this one case.

**Comment by mlrawlings** [comment]
@yomed I don't know that this is a definitive test, but here's what WAVE has to say:
http://wave.webaim.org/report#/http://output.jsbin.com/majejevelu

It would seem that `alt` and `alt=""` are equivalent.  I've also seen recommendations for an image to "be given empty/null alternative text", although they go on to show `alt=""` in examples.

@patrick-steele-idem What are your thoughts on leaving the current behavior for variables and leaving the empty string when it's specified as a string literal?

Although, it might be useful to have the behavior from the table if you're generating a list of images from something like:
```js
[{ src="/1.png" alt="something"}, { src:"2.png", alt="" }]
```
Though I'd say chances are pretty good that given a list of images like this, they should all have `alt` content or should all have an empty/null `alt`.

**Comment by patrick-steele-idem** [comment]
> @patrick-steele-idem What are your thoughts on leaving the current behavior for variables and leaving the empty string when it's specified as a string literal?

I would want things to be consistent regardless of whether or not the attribute value is a literal value or a dynamic expression.
