### ISSUE TITLE
Does not throw error for invalid browser.json

### ISSUE THREAD

**Issue by aniruddh-a** [marko-js/marko#331]
Marko is not showing any error related to unexpected characters / invalid JSON config.

Invalid json config - browser.json :

`[
 {
            "type": "js",
            "url": "https://cdnjs.cloudflare.com/ajax/libs/select2/4.0.3/js/select2.min.js"
        },
]`

Error shown after some time : 

`Error: Async fragment failed (lasso-slot:head). Exception: Error: Async fragment (lasso-slot:head) timed out after 30000ms`

I believe a parsing error can be thrown right away if browser.json or any other config file is invalid and marko is unable to parse such file.

**Comment by patrick-steele-idem** [comment]
@aniruddh-a this looks like an issue with Lasso and not Marko. Do you mind moving this issue over to https://github.com/lasso-js/lasso and providing more details on your lasso version? Thanks!

**Comment by mlrawlings** [comment]
Lasso issue: https://github.com/lasso-js/lasso/issues/155
