### ISSUE TITLE
defineRenderer for marko

### ISSUE THREAD

**Issue by jpattishall** [marko-js/marko#344]
### Description
Currently marko-widgets allows to define a UI component's renderer as `require('marko-widgets').defineRenderer({...});`. I would like to propose a similar, but simpler:

`require('marko').defineRenderer({...});`

### Context
Building our project, we've defined custom taglibs that export the simplest "components" to more complex components. For simple componets (server-rendered only, no state, little to no client behavior), our approach to custom taglibs has been to export in index.js a function that takes an `input` and then calls template.render.

```
module.exports = function(input, out) {
    template.render(input, out);
}
```
Unlike defineRenderer, this does not export a `render` function similar to defineRenderer. We could set `exports.render` or use `createRenderFunc` from `raptor-renderer`, however I would like to propose a `defineRenderer` in `marko`, with similar (but much simpler) life cycle events.

```
module.exports = require('marko').defineRenderer({
    template: require('./template.marko'),
    getTemplateData: function (input) {
        input.time = Date.now();
        return input;
    }
});
```
The added benefit (and why this beats `exports.render` or `createRenderFunc`) is that if the simple component takes on a more, complex role, adding `-widgets` + any extra lifecycle event methods is straightforward and painless.

Thanks!

**Comment by yomed** [comment]
👍  I always thought this API difference between marko and marko-widgets was a bit strange.

**Comment by pcanella** [comment]
👍  totally agree here.

**Comment by patrick-steele-idem** [comment]
Actual usage will be the following:

```javascript
var defineRenderer = require('marko/defineRenderer');

module.exports = defineRenderer({
	template: require('./template.marko'),
	getTemplateData: function(input) {
		var firstName = input.firstName;
		var lastName = input.lastName;

		return {
			fullName: firstName + ' ' + lastName
		};
	}
})
```

NOTE: `defineRenderer` should be required as a sub-module (`require('marko/defineRenderer')`). This was done to avoid adding any extra weight to the main `marko` runtime.
