### ISSUE TITLE
Deprecate `empty`/`notEmpty` in Marko v3

### ISSUE THREAD

**Issue by patrick-steele-idem** [marko-js/marko#357]
The builtin `empty`/`notEmpty` helpers will be removed in Marko v4 and will be deprecated in v3 (with console warning).

If still needed, these helpers can still explicitly be imported:

```html
<script marko-init>
var empty = require('marko/helpers/empty');
var notEmpty = require('marko/helpers/notEmpty');
</script>
```

Alternatively, you can simply check the array length or ensure that a string is not "falsey".

# Why?

The `empty`/`notEmpty` helpers were automatically being added to every compiled template. While they can be helpful, we feel it is better if the developer explicitly imports only the exact helpers that your code depends on for improved modularity. Also, when adding support for [inline marko templates](https://github.com/marko-js/marko/issues/349) we found that these `empty`/`notEmpty` helpers could conflict with other JavaScript code since all static code/imports are added at the top of the JavaScript file.

**Comment by briceburg** [comment]
Is it possible to see a workaround for this outside of 
```js
<script marko-init>
var empty = require('marko/helpers/empty');
var notEmpty = require('marko/helpers/notEmpty');
</script>
``` ? Would be nice to add to the docs

**Comment by patrick-steele-idem** [comment]
@briceburg I suppose one possibility would be to introduce a new option in `marko.json` to opt-in for the `empty`/`notEmpty` helpers, but I don't think it is a good idea to go there. Personally, I would just use `<if(data.commits && data.commits.length)>` instead of a helper. If you have any other thoughts or ideas please share.
