### ISSUE TITLE
Koa: stream deprecated?

### ISSUE THREAD

**Issue by basickarl** [marko-js/marko#359]
http://markojs.com/docs/marko/koa/

```
require('marko/node-require').install();
 
var koa = require('koa');
 
var app = koa();
 
app.use(function *() {
    this.body = template.stream({
            name: 'Frank',
            count: 30,
            colors: ['red', 'green', 'blue']
        });
});
 
app.listen(8080);
```

However it states at http://markojs.com/docs/marko/javascript-api/#streamtemplatepath-templatedata--streamreadable

```
stream(templatePath, templateData) : stream.Readable
Deprecated. Do not use.
```

So, use stream or not? Feels like you guys should have one place for information on usage. This is confusing!

**Comment by basickarl** [comment]
Apologize.

http://markojs.com/docs/marko/javascript-api/#streamtemplatedata--streamreadable

Was looking at the wrong method!

**Comment by patrick-steele-idem** [comment]
No worries. I still think it was confusing since the docs say that they are deprecated, but we don't say why or which method should be used instead. I'll fix this to avoid confusing others. Thanks for opening the issue.
