### ISSUE TITLE
Question: About License

### ISSUE THREAD

**Issue by fundon** [marko-js/marko#362]
I want a package, just dependent on marko and not modify it.
Is it ok under MIT for package?

**Comment by patrick-steele-idem** [comment]
Hey @fundon. marko uses the [Apache 2.0](http://www.apache.org/licenses/LICENSE-2.0) license. I'm not a lawyer, but if you are just depending on marko (and not modifying it) then you don't need to do anything. Any distribution of marko need to include a copy of the license (which will be the case if you  are installing from npm or directly from Github).

If that doesn't answer your question then please let me know, but I am going to go ahead and close the issue.

**Comment by fundon** [comment]
Thanks.
So, It's ok under MIT.

**Comment by patrick-steele-idem** [comment]
@fundon yes. as long as you are not modifying and redistributing marko then it doesn't matter what the license is for your project.

**Comment by fundon** [comment]
Cool! Thank you! 🍻
