### ISSUE TITLE
Auto hot reload for any extensions provided when installing the Node.js require hook

### ISSUE THREAD

**Issue by jlarsson** [marko-js/marko#363]
### Context

Support for XML templates in _.marko.xml_ files have some (quite good) support in runtime and tools but hot reloading remains unsupported.
### Possible Fix

Currently, the code in https://github.com/marko-js/marko/blob/master/hot-reload/index.js#L136 looks like 

```
if (path.endsWith('.marko') || path.endsWith('.marko.html')) {
            // Uncache just the modified template
            delete require.cache[path];
            delete require.cache[path + '.js'];
        }
```

A fix could be 

```
if (path.endsWith('.marko') || path.endsWith('.marko.html') || path.endsWith('.marko.xml')) {
```

**Comment by patrick-steele-idem** [comment]
I think what needs to happen here is that in addition to `.marko` and `.marko.html`, we should also look for any extensions that were registered via `require('marko/node-require').install()`.

For example:

```javascript
require('marko/node-require').install({ extension: '.marko' });
require('marko/node-require').install({ extension: '.marko-xml' });
require('marko/node-require').install({ extension: '.foo' });
```

We should check to see if the path ends with `.marko`, `.marko-xml` and `.foo`.

Thoughts? Would you be interested in working on this @jlarsson?

**Comment by jlarsson** [comment]
This is a though problem since we are restricted to what `require()` CAN do and not what we WANT to do.

Personally, I favor composite extensions such as `.marko.html` and `.marko.xml` since they essientially still are html and xml and thus wont break my tooling (lint, syntax hl etc).
`require()` on the other hand has no sympathy for composites and will treat `.marko.xml` as any `.xml`.

Some observations:
- a replacement api for `require('./some.marko')` isnt feasible, since `require()` is the only viable api that has the much needed implicit dependency to the module variable `__dirname` required for resolving the full path.
- hot reloading in marko is actually more of a _hot unloading_ (https://github.com/nodejs/node/blob/ebc8c37f70a84a64851b440493f3441eb9f70fdb/lib/module.js#L436)

So, a possible solution to this is to alter the semantics of install.

Consider
```
install({
	extension: '.marko.xml'
})
```

- Make the implementation of `require('marko/hot-reload').handleFileModified(<path>)` aware of the full extension, `.marko.xml`.
- Alter the `require.extensions` mapping using the effective extension, in this case `.xml` (https://github.com/marko-js/marko/blob/master/node-require.js#L76)

My guess is that this is an addition rather than a breaking change since composite extensions currently has no effect (at least not the intended) on `install()`.

Unfortunately, I have little time for this at the moment, mainly since I work full hours in windows environments which doesnt support symlinks used in the tests.

@patrick-steele-idem , let me come back on this, perhaps I dust of my old McBookPro in the weekend...
