### ISSUE TITLE
Custom root path for views

### ISSUE THREAD

**Issue by fundon** [marko-js/marko#364]
### Description
Sometimes, we want to use `require('marko/node-require').install(options)` to the third-part package.

But it will set the views dir to package's dir. so should need an option to set root path.

**Comment by patrick-steele-idem** [comment]
I don't quite follow. Marko templates are resolved and loaded through the Node.js module loading system just like normal JavaScript modules. There's no "views dir" and there is no root path when using marko directly. Can you provide more details and code to illustrate the problem you are seeing?

**Comment by fundon** [comment]
## example
https://github.com/trekjs/views/blob/master/packages/marko/index.js
```js
/**
 * Install marko
 *
 * @param {Object} options
 */

function install (options) {
  require('marko/node-require').install(options)
}

/**
 * Stream render view
 *
 * @param {String} view
 * @param {Object} state
 * @return {Stream}
 */

function render (view, state) {
  return require(view).stream(state)
}

module.exports = {

  install,

  render

}
```
https://github.com/trekjs/examples/blob/next/template-marko/app.js
```js
const path = require('path')

const Engine = require('trek-engine')

const marko = require('trek-view-marko')

marko.install()

const app = new Engine()

app.use(({ res }) => {
  res.send(200, marko.render(path.join(__dirname, './index.marko'), { name: 'Trek Engine' }))
})

app.run(3000)
```

**Comment by mlrawlings** [comment]
As Patrick said, we use node's module resolution to handle finding the template.  If you really wanted to have a views directory, you could roll something yourself using the `require('marko').load()` function which expects a fully resolved filesystem path.  In our examples re use `require.resolve` to get that path, but there's nothing stopping you from resolving it relative to some views directory, but that would all happen outside the scope of Marko.   Maybe something along the lines of [this](https://gist.github.com/mlrawlings/d92b5c1d89abefbba66e2d8af5c47eef).

However, I would recommend having your `render` function take the loaded template as a parameter:

```js
var template = require('./index.marko')

app.use(({ res }) => {
  res.send(200, marko.render(template, { name: 'Trek Engine' }))
})
```

We do something similar in the [`marko/express`](https://github.com/marko-js/marko/blob/master/express.js) submodule to provide the [`res.marko`](http://markojs.com/docs/marko/express/) method.

**Comment by fundon** [comment]
> Maybe something along the lines of this.

Nice work. Thanks.


> However, I would recommend having your render function take the loaded template as a parameter:

If we have many templates (> 15 pages) that not good way.
