### ISSUE TITLE
Suggestion: Change the name of atom marko packages to be more search friendly

### ISSUE THREAD

**Issue by BryceEWatson** [marko-js/marko#367]
The current marko atom packages should use a more unique identifier in their package names.
When searching for "marko" in atom the packages appear in this order:
- language-marko (5th in list)
- autocomplete-marko (17th)
- hyperclick-marko (23rd)

This makes it difficult to find all available marko packages in a single search.

### Solution

Change the package name from `marko` to something like `markojs` or `marko-js` to make it easier to find all of the packages.

Thanks!

**Comment by patrick-steele-idem** [comment]
I think changing the name of the package will disrupt things too much. Also, we merged the functionality of `autocomplete-marko` and `hyperclick-marko` into the main [language-marko](https://atom.io/packages/language-marko) package. It's unfortunate that the search results for `marko` are in such a bad order, but I'm not sure there is much we can do about that right now. I did add keywords to the `package.json` so hopefully that will help: https://github.com/marko-js/atom-language-marko/commit/9e5976ed29daca646b251c6a86f06992341e7284
