### ISSUE TITLE
Question: Custom Attributes on existing HTML tags

### ISSUE THREAD

**Issue by jasonmacdonald** [marko-js/marko#369]
Sorry if this is answered somewhere (I couldn't find it), but can you do custom attributes without creating a custom tag? I'm curious if we can do something similar to what Angular has where you can create directives for attributes, not just tags.

As an example, lets say I wanted to provide an alternate "src" attribute (my-src) for the img tag so I could rewrite the URL before rendering. Is this possible? Or do I have to write a custom image tag and handle the src attribute that way? The docs weren't clear on this point. They mention custom tags AND attributes, but I only see examples for tags.

BTW, I'm currently using the component directory set-up, not a marko.json.

**Comment by patrick-steele-idem** [comment]
Marko supports custom attributes on standard HTML tags. You would need to write a compile-time transform to process those custom attributes. It's not hard, but it is definitely more in the "advanced usage" category. A compile-time transform can also process standard HTML attributes if you choose.

Here's some relevant docs that show an example of a transform processing a custom `if` attribute: http://markojs.com/docs/marko/compiler/advanced/#transform-stage

Sometimes it is easier to explain in code so I will push a sample app that will hopefully make things clear. I'll provide an update here soon.

**Comment by jasonmacdonald** [comment]
Thanks for the quick response, appreciate it. I'll have a look at the link you provided.

**Comment by patrick-steele-idem** [comment]
Hey @jasonmacdonald, it took a little longer because I got pulled into some other things, but here is a project that I hope clarifies how to handle custom attributes: https://github.com/marko-js-samples/marko-custom-attributes 

I'm going to go ahead and close this issue, but if you would like more details please feel free to post comments here.

**Comment by jasonmacdonald** [comment]
Thanks, Patrick! I'll need to digest this a bit but it's much appreciated! I assume that you must use a marko.json to accomplish this, instead of the components directory?
