### ISSUE TITLE
Injected tags

### ISSUE THREAD

**Issue by mlrawlings** [marko-js/marko#377]
### Description

This is kinda a rough idea I've been throwing around in my head for a while now and figured I should put it out there:  I'd like Marko to provide a way to automatically inject a custom tag at the end of a page.
### Context

There's a number of tags in our ecosystem (some of these eBay specific) that we end up having users add to their layout templates right before the closing `</body>` tag.  Often users will forget to add one an wonder why something isn't working.

``` xml
<body>
    ...
    <await-reorderer/>
    <lasso-body/>
    <init-widgets/>
    <gh-footer/>
    <gh-body-js/>
    <tracking-cookies/>
    <tracking-images/>
    <tracking-body />
    <browser-refresh/>
    <site-speed-bottom/>
</body>
```
### Conciderations

Tags could already implement something basic by hooking into the closing body tag, but it's possible someone renders a template without a `<body>` tag.  Google even [recommends](https://google.github.io/styleguide/htmlcssguide.xml?showone=Optional_Tags#Optional_Tags) to omit it.  Ideally, the insertion point for these tags would be just before `</body>` or, if that's not found, at the end of the top level template.

Async is also something that needs to be considered.  

> Example: In the case of `<init-widgets/>`, we would only want to include it on the page if there are widgets on the page.  But it could be that the only widget is in an `<await>` block and therefore we don't know that we need to init widgets until that block is executed.

Finally, some tags (like `<init-widgets/>`) require that the javascript has been loaded before them.  And it's likely that a tag to insert that javascript (like `<lasso-body/>`) would also be using this system to insert itself.  So perhaps we need some system of priority.  Or tags could choose between append/prepend.

**Comment by mlrawlings** [comment]
It would also be ideal if we could do this without adding code to every generated template.

**Comment by Hesulan** [comment]
It seems to me that some of those tags might be simpler than others. Like you said, `<init-widgets/>` may not recognize widgets within an `<await>` tag (though I have a couple thoughts on how it might). Others, like `<browser-refresh/>`, could simply attach themselves to the compiler (or perhaps even the renderer) and append/prepend themselves unconditionally. Ordering and precedence shouldn't affect those much, but that's something we would still need to figure out eventually.

> Side note: I just noticed that the content of `<await(...) client-reorder>` ends up in `<head>` if it's the first document element; in other words, `<!DOCTYPE html><await(foo from Promise.resolve('foo')) client-reorder>${foo}</await>bar<await-reorderer/>` produces `<html><head>foo</head><body>bar</body></html>` instead of `<html><body>foobar</body></html>`. It's an uncommon edge-case, but something to be aware of if excluding the `<body>` tag, and possibly a bug in `<await-reorderer/>`.

**Comment by DylanPiercey** [comment]
This was implemented as the (currently semi private) `<_flush_here_and_after_>` tag (https://github.com/marko-js/rollup/blob/main/components/rollup.marko#L4)
