### ISSUE TITLE
Increased scope for taglib discovery

### ISSUE THREAD

**Issue by mlrawlings** [marko-js/marko#379]
Currently, the process for [discovering taglibs](http://markojs.com/docs/marko/custom-taglibs/#taglib-discovery) is determined per template by the following:
1. search for `marko.json` in the same directory as the template, and then in each parent directory up to the project root (until a `package.json` is found).
2. for each dependency in the `package.json`, search for a `marko.json` at the package root.

This provides encapsulation as each template can only be modified by taglibs in its own package and packages it directly depends on.  It also provides consistent behavior no matter how the `node_modules` directory structure ends up due to dependency flattening of `npm@3` or `yarn`. :+1:

However there are cases where it could be useful to have global taglibs that are discovered by **every** template.  Here's a few ideas:
- A security transform that puts a [`nonce`](https://developer.mozilla.org/en-US/docs/Web/Security/CSP/CSP_policy_directives#strict-dynamic) attribute on all inline script tags
- A asset management transform that allows relative paths to be specified for resources (ex. `<img src="./foo.png"/>`) and includes the resolved file in the build.
- etc.

**Comment by patrick-steele-idem** [comment]
@mlrawlings Any thoughts on how to register global taglibs?

**Comment by mlrawlings** [comment]
I have few thoughts on this:

**1**. Add methods to force inclusion of a directory or package:
```js
require('marko/compiler').taglibFinder.includeDir(dirPath);
// Where 'dirPath' is an absolute path to the folder containing marko.json 
 
require('marko/compiler').taglibFinder.includePackage(packageName);
// Where 'packageName' is the name of the node_module containing marko.json 
```
I don't particularly like this because I'm not a fan on having the application compile templates differently than the command-line tool, test, etc.  This becomes a source of hard-to-find problems.

**2**. Keep searching up after finding a `package.json` and load parent's packages' taglibs as well.   This would make the global behavior the default, though not truly global as taglibs would trickle down, but not up.   I could potentially see some unwanted behavior with this approach, but the top level would always be in control of what was added in, so it might not be so bad.  Another issue is dependency flattening.  One dependency might be a dependency of another but they could be siblings in the directory structure due to flattening.  This could lead to unexpected behavior.

**3**. Allow taglibs to specify a `"global":true` option in `marko.json`.  For discovery purposes (and sanity?)  only top level dependencies (those directly depended on by the main application) would be able to register global transforms, renderers, etc.  If the top level application wanted to register a global transform, it would be required to do so in a `marko.json` at the root of the package.  The only challenge with this would be determining the root application.  We could potentially do something with searching up to the root of the filesystem and the highest directory with a `package.json` is assumed to be the app root.  Or we could use `process.cwd()` as a heuristic. 

Option 3 is looking the best at this point, but I'm open to other suggestions.

**Comment by neuronetio** [comment]
`require('marko/compiler').taglibFinder.includeDir(dirPath);` 
would be nice feature
I have many directories inside my project folder that have `package.json` inside because i need them to have individual node_modules inside and for other reasons as well

now I cannot bubble to main project folder and make some components available across all directories

there is `taglibLookup.registerTaglib` but seems to work only in node environment :/ (in webpack doesn't seem to work)

**Comment by DylanPiercey** [comment]
You can now register global transforms/migrators.
