### ISSUE TITLE
Bug on jQuery Proxy when w-id contains dash/hyphen

### ISSUE THREAD

**Issue by abiyasa** [marko-js/marko#391]
## Bug Report

Bug on jQuery Proxy when w-id contains dash/hyphen

### Context

When trying to get nested element using the the format `$(# + widgetId)`, it does not return the right element if the widgetId contains dash/hyphen (e.g 'submit-button').

### Expected Behavior

`widget.$('#submit-button’)` should return nested widget with `w-id="submit-button”`

### Actual Behavior

`widget.$('#submit-button’)` does NOT return nested widget with `w-id="submit-button”`. It could return undefined or nested widget with `w-id="submit”`

### Possible Fix

It could be regex at idRegExp at Widget.js, or it could just limitation of widget id (need to be documented about this) 

<details><summary>Additional Info</summary>

### Your Environment

* Version used: latest on master branch (commit 21a43c010a75ca06857598f49ea3368b3e33c3c2) & v6.4.x
* Environment name and version (e.g. Chrome 39, node.js 5.4): Chrome, Node 4.2.x
* Operating System and version (desktop or mobile): desktop
* Link to your project: https://github.com/abiyasa/marko/tree/bug-on-nested-widget-id

### Steps to Reproduce

1. See the test file from [https://github.com/abiyasa/marko/tree/bug-on-nested-widget-id](https://github.com/abiyasa/marko/commit/097c411db00e607195ce56bb1ba1f407be5d1ffe)
2. Checkout folder `/marko/test/autotests/widgets-browser/widget-jQuery-proxy/test.js`
3. Run test & see the failing test

### Stack Trace

</details>

**Comment by patrick-steele-idem** [comment]
Looks like a problem with the regular expression used to parse out the ID: https://github.com/marko-js/marko/blob/21a43c010a75ca06857598f49ea3368b3e33c3c2/widgets/Widget.js#L36

Would you be interested in working on a fix @abiyasa?

Thanks for opening in the issue and providing the test case!

**Comment by abiyasa** [comment]
Thanks for the quick reply. I thought so too about the regex, just not sure if it's intended.

Sure, I can work on a fix. Glad I could help :-)
