### ISSUE TITLE
Deprecate w-id/w-for attributes

### ISSUE THREAD

**Issue by mlrawlings** [marko-js/marko#394]
The `w-id` attribute was used to obtain references using `this.getEl(refId)`. `w-id` has been replaced with the `ref` attribute.

Renaming these attributes for clarity and because we want to remove references to `marko-widgets`.

`w-id` → `ref`
`w-for` → `for-ref` 

> I like this because it's more clear that this `for-ref` will create `for` that points to the `id` generated by `ref`

**Old:**

```html
<input type="text" w-id="name" />
```

**New:**
```html
<input type="text" ref="name" />
```

Similarly, `w-for` has been been replaced with `for-ref`:

**Old:**

```html
<label w-for="name">Name</label>
<input type="text" w-id="name" />
```

**New:**
```html
<label for-ref="name">Name</label>
<input type="text" ref="name" />
```

**Comment by charlieduong94** [comment]
If no one has started working on this, I can take this one up.

**Comment by patrick-steele-idem** [comment]
@charlieduong94 That would be great if you could take this issue. I invited you as a collaborator so that I can assign this issue to you. You can click the following link to accept: https://github.com/marko-js/marko/invitations

Thanks!

**Comment by charlieduong94** [comment]
PR #427

**Comment by patrick-steele-idem** [comment]
Work completed. Closing issue. Thanks @charlieduong94 !
