### ISSUE TITLE
Make w-bind attribute completely optional

### ISSUE THREAD

**Issue by mlrawlings** [marko-js/marko#395]
In the case of scanned taglibs, we can detect that a custom tag is a component with client-side functionality if it has a `widget.js` or `component.js` in the same directory.

In this case we could make the `w-bind` attribute optional.  

Unless we take on #393, there is only support for one element to be bound to a component, so we would expect that there would only be one top level element in the template to be bound.

If there is more than one, we could either:
- throw an error
- bind the first element only (maybe log a warning?)

**Comment by patrick-steele-idem** [comment]
I'll take this one since it ties into supporting binding a single widget to multiple top-level elements (https://github.com/marko-js/marko/issues/393)
