### ISSUE TITLE
New lifecycle methods

### ISSUE THREAD

**Issue by mlrawlings** [marko-js/marko#396]
### `onInput(input)`
Replaces `getInitialInput`, `getInitialState`, and `getWidgetConfig`.

Instead of having 3 different methods that run when input is received, we'll just have one.  

```js
onInput(input) {
    this.state = { count:input.initialCount };
    this.initialCount = input.initialCount;
}
reset() {
    this.setState('count', this.initialCount);
}
increment() {
    this.setState('count', this.state.count+1);
}
```

If you have values that should cause a re-render when they change, then put them in `this.state`, otherwise you can just attach them to the `this` object.  The widget in `onInput` will be a lightweight widget.

When rendering on the server, the state and any other values attached to this will be serialized and sent to the client and rehydrated on the widget.

### `onMount()`
Replaces `init` which is only called on the client after the component mounts.  `onMount` is clearer about what is happening.

The only difference beside the name is that `widgetConfig` is not passed as an attribute because any "config" values have already been set on the widget instance by `onInput`.

**Comment by patrick-steele-idem** [comment]
I propose we also use `onInput(input)` to replace `getTemplateData()` by allowing `onInput(input)` to `return` the template data:

**Old:**

```js
{
    onInput(input) {
        this.state = {
            name: 'Frank',
            birthday: Date(2000, 12, 24)
        }
    },
    getTemplateData(state, input) {
        return {
            age: calculateAge(state.birthday) // Only need to pass values derived
                                              // from the state to the template.
        }
    }
    ...
}
```

**New:**

```js
{
    onInput(input) {
        this.state = {
            name: 'Frank',
            birthday: Date(2000, 12, 24)
        }
        return {
            age: calculateAge(state.birthday) // Only need to pass values derived
                                              // from the state to the template.          
        }
    }
    ...
}
```

This makes sense because you can assign state and properties to the widget instance, but `onInput(input)` can also be used to transform the input data to what is needed for the next stage (i.e. rendering the template). If `onInput(input)` returns `undefined` then the input data will be passed to the template.

**Comment by artlantis** [comment]
There is a typo problem in the document. At "New widget lifecycle methods" section, new and old (onInput) samples should switch each other.
