### ISSUE TITLE
Deprecate <script marko-init>

### ISSUE THREAD

**Issue by mlrawlings** [marko-js/marko#397]
### Background: why `<script marko-init>` exists

For the most part, all of your template ends up in a render function

A template like this:
```xml
<var name="World"/>
<div>Hello ${name}</div>
```
compiles to something like the following (oversimplified) output js:
```js
function render(data, out) {
    var name = 'World';
    out.w('<div>Hello'+name+'</div>');
}

module.exports = new Template(render);
```

But there are times when you might want to add initialization code outside the `render()` function so that it doesn't run everytime the template renders, only when the template is first required.

So `<script marko-init>` has fulfilled this need.

### Why we want to change

A template like this:
```html
<script marko-init>
    var format = require('format');
</script>
<var name="World"/>
<div>Hello ${format(name)}</div>
```
compiles to something like the following (oversimplified) output js:
```js
var format = require('format');

function render(data, out) {
    var name = 'World';
    out.w('<div>Hello'+format(name)+'</div>');
}

module.exports = new Template(render);
```

A `<script>` tag usually puts code into the output html, but in this case, we're highjacking it because of the `marko-init` attribute and using the code as part of the render logic.

We actually already have a construct that is meant to add arbitrary javascript in template render logic: [scriptlets](https://github.com/marko-js/marko/blob/21a43c010a75ca06857598f49ea3368b3e33c3c2/docs/what-is-new-marko-v3.md#scriptlets).

But scriptlets, like most other things, run within the context of the `render` method.

### The proposal

By default, scriptlets, `<var>`, `<assign>`, etc. would continue to run within the context of the render method, but we will introduce a new tag: `<render>`.

A template like this:
```html
<var format=require('format')/>
<render>
    <var name='World'/>
    <div>Hello ${format(name)}</div>
</render>
```
compiles to something like the following (oversimplified) output js:
```js
var format = require('format');

function render(data, out) {
    var name = 'World';
    out.w('<div>Hello'+format(name)+'</div>');
}

module.exports = new Template(render);
```

Now the structure of the template matches up fairly well with the structure of the output js. :+1:

Obviously anything outside of `<render>` would not be allowed to write to `out` as `out` wouldn't be in scope.  We should detect this and throw an error at compile time.

**Comment by patrick-steele-idem** [comment]
I definitely have some concern around having to wrap all the template code just to introduce some JavaScript initialization code. With that said, it doesn't look as bad with the concise syntax:

```html
var format=require('format')

render
    var name='World'
    <div>Hello ${format(name)}</div>
```

You could even make it look like a method by adding parens and possibly a `data` param:

```xml
var format=require('format')

render(data)
    var name='World'
    <div>Hello ${format(name)}</div>
```

And finally, that could allow for ES6 argument destructuring:

```xml
var format=require('format')

render({name})
    <div>Hello ${format(name)}</div>
```

**Comment by scttdavs** [comment]
I agree with wrapping everything in a `<render>` not being so great. Would that be required, or optional, only if you need code generated out of the context of the render function?

If the goal is to deprecate `<script marko-init>` with the already established expectation of a `<script>` tag, why not add a new tag called `<init>`, or something else?

```html
<init>
    var format = require('format');
</init>

<var name='World'/>
<div>Hello ${format(name)}</div>
```
or
```html
<init>
    <var format=require('format')/>
</init>

<var name='World'/>
<div>Hello ${format(name)}</div>
```

**Comment by Hesulan** [comment]
For the purpose of hoisting `require()` calls out of the `render` function, the new `<import>` tag *should* handle that (see: ECMAScript's top level requirement for `import` statements). I know that's not the only use for `<script marko-init>`, but thought I should throw that out there.

Regarding `<render>` and `<init>`, why not both? `<init>` could simply be a drop-in replacement for `<script marko-init>`, while `<render>` would be optional, and if present would refactor the output in the way you described.

I get the feeling that the `<render>` tag might take a while to get working correctly, but `<init>` should be quick and easy to add (and looks much nicer and more easily recognizable than `<script marko-init>`, at least in my opinion).

**Comment by mlrawlings** [comment]
@Hesulan The `<import>` tag does hoist outside the `render` function, see the [import-tag test](https://github.com/marko-js/marko/tree/master/test/autotests/compiler/import-tag) and its [expected output](https://github.com/marko-js/marko/blob/master/test/autotests/compiler/import-tag/expected.js).

Importing modules is a big reason `<script marko-init>` was needed (just look at every example in this thread), but you might need to do something like this:

```html
<import { createFormatter } from "./format"/>
<var format=createFormatter({ lang:'en' })/>

<render(data)>
    <var name='World'/>
    <div>Hello ${format(name)}</div>
</render>
```


```js
import { createFormatter } from "./format";
var format = createFormatter({ lang:'en' });

render(data)
    var name = 'World';

    <div>Hello ${format(name)}</div>
```

I think the actual implementation of `<render>` would internally rely on the equivalent of the suggested `<init>` tag.   You'd loop over each top level element and if you found a `<render>` tag, you'd move all the other top-level elements into an `<init>` tag.  The `<init>` tag would then generate the code for its children and instead of putting that code in the render method it would place it towards the top of the file.  The question is should this `<init>` tag be an internal thing or should it be exposed as an alternative?

@patrick-steele-idem You've talked about requiring the parens on `<render>` and maybe that makes sense.  But we should also require an actual argument there: the name of the `data` variable.

Wrapping the whole template in `<render(data)>` would leave things as they are now.  `<render()>` would be invalid.

As for the `<init>` name, would `<load>` make more sense?  If you're not using the require hook, you would call `marko.load('./template.marko')` and that's the point at which this init/load code is run.

_Almost_ makes me want to do something like `<on-load>` and `<on-render>`, but let's not.

**Comment by mlrawlings** [comment]
Closed via https://github.com/marko-js/marko/commit/2980546f7c3309ec11a268ea0d4a801506c4ab6b
