### ISSUE TITLE
Introduce `state` as a local variable

### ISSUE THREAD

**Issue by mlrawlings** [marko-js/marko#400]
We can modify the compilation so that in addition to the `data` variable that is available to templates, a `state` variable would also be available for component templates.

**component.js**:
```js
export default {
   onInput(input) {
      this.state = { count:0 };
   },
   incrementCount() {
      this.setState('count', this.state.count+1);
   }
}
```

**template.js**:
```xml
<div>
    The current count is ${state.count}
    <button onClick('incrementCount')>+</button>
</div>
```

This may remove the need for `getTemplateData`... thoughts?

**Comment by philidem** [comment]
This will be very helpful and I would use this feature immediately.
