### ISSUE TITLE
Allow spaces between attribute names and values

### ISSUE THREAD

**Issue by patrick-steele-idem** [marko-js/marko#403]
The following is currently not allowed since there are spaces around the `=` character:

```xml
<div class = "foo" />
```

However this would be valid HTML.   We want to support this as part of Marko v4. 

See also: [htmljs-parser#41](https://github.com/philidem/htmljs-parser/issues/41)

**Comment by mlrawlings** [comment]
We also want to support this?
```html
<var sum = 1 + 2 />
```

Related: [htmljs-parser#37](https://github.com/philidem/htmljs-parser/pull/37)

**Comment by patrick-steele-idem** [comment]
Fixed with upgrade to `htmljs-parser@^2`
