### ISSUE TITLE
Introduce the `<import>` tag for ES6 imports

### ISSUE THREAD

**Issue by patrick-steele-idem** [marko-js/marko#404]
```xml
<import helpers from "./helpers"/>
- Total: ${helpers.formatCurrency(data.total))

// Concise syntax:
import helpers from "./helpers"
- Total: ${helpers.formatCurrency(data.total))
```

The `<import>` should follow the same rules as an ES6 import and the imports should be moved to the top of the compiled template.

Open questions:
- Should marko transpile the ES6 import code to CommonJS require?

(As a side note, I'm going to continue to call it ES6 instead of ES2015.)

**Comment by mlrawlings** [comment]
I'll get to this at some point, but if someone wants to beat me to it, here's a starting point:
https://runkit.com/mlrawlings/573b709ca492941100e1140e

**Comment by scttdavs** [comment]
@mlrawlings could you explain more the expected behavior/output of `import { foo as <foo> } from './foo'`? I believe I have the other scenarios working so far, this one is remaining however.

**Comment by patrick-steele-idem** [comment]
Given the following:

```javascript
import { bar as barAlias } from './foo'
```

The output should be similar to the following:

```javascript
var fooModule = require('./foo');
var barAlias = fooModule.bar;
```

**Comment by scttdavs** [comment]
In the current parser `import { foo as <foo> } from './foo'` would output with a field `isTag: true`. What does it mean to import as tag?

**Comment by patrick-steele-idem** [comment]
I'm guessing that was related to some experimental idea of importing a tag, but is no longer applicable. Please confirm @mlrawlings.

**Comment by mlrawlings** [comment]
Yes.  That was experimental.  The work done on `<include>` means we don't really need that anymore.

/cc @scttdavs

**Comment by mlrawlings** [comment]
To clarify, `importToAssignments` should be used, not `importToAssignmentsWithTags`

**Comment by scttdavs** [comment]
;) yeah I saw that. I have it all working. Will try to polish it up and
open a PR sometime this weekend hopefully.
