### ISSUE TITLE
Introduce the `<function>` tag for declaring JavaScript functions

### ISSUE THREAD

**Issue by patrick-steele-idem** [marko-js/marko#405]
```xml
function formatCurrency(value) {
  return '$' + value.toFixed();
}

render()
  <div>Total: ${formatCurrency(10}</div>
```

**Comment by philidem** [comment]
I'm not a fan of the `render()` call in sample above

**Comment by philidem** [comment]
Also, we will probably need to support functions that get instantiated once and functions that are declared inline (so that you can better utilize function closure for accessing local variables).
