### ISSUE TITLE
Automatically watch widget state object for changes

### ISSUE THREAD

**Issue by patrick-steele-idem** [marko-js/marko#406]
Currently, all changes to a widget state must go though the `setState()` method. For example:

```javascript
this.setState('count', this.state.count + 1);
```

This approach requires the user to write more code and it can be problematic. For example, the following would _not_ work as expected even though it would be an easy mistake:

```javascript
this.setState('count', ++this.state.count);
```

What we want to support is the following:

```javascript
this.state.count++;
```

Newer browsers support [JavaScript proxies](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Proxy) that allow libraries to watch for changes to properties on an object via proxy traps. For IE (IE9+), `Object.defineProperty()` can be used to attach getters and setters for all of the properties with the only caveat that all properties must be known upfront. It is reasonable to require that all state properties be set upfront. In addition, to prevent problems from not showing up in older browsers we can use `Object.freeze()` (IE9+) to prevent new properties from being added.

We could also optionally allow the complete set of state properties (with default values) to be statically defined declaratively upfront as part of the component definition:

_component.js:_

```javascript
exports default {
    state: {
        name: '(no name)',
        count: 0
    }
}
```

Finally, for performance reasons we could lazily define a reusable `class` type for each widget once we know the set of properties. For example, once we determine that a widget has `count` and `name` state properties then we could generate the more efficient object for reading and setting state properties by adding getters and setters on the prototype:

```javascript
class MyWidgetState {
    constructor(rawState, widget) {
        this.rawState = rawState;
        this.widget = widget;
    }

    get count() {
        return this.rawState.count;
    }

    set count(value) {
        this.widget.setState('count', value);
    }
    
    get name() {
        return this.rawState.name;
    }

    set name(value) {
        this.widget.setState('name', value);
    }
}
```

NOTE:

- We will continue to maintain backwards compatibility and allow `this.setState(...)`
- the raw/unwrapped/unproxied state object should be stored in a private `this.__state` variable (or similar)
- `this.setState()` should interact directly with the raw state
- We only want to support a shallow watch of the state object for performance reasons.
- An application state container with immutable state is still recommended for managing application state.
- When serializing state we would need to serialize `undefined` properties as `null` so that they are serialized as part of the state object
- There should be no impact on code that runs on the server

**Comment by mlrawlings** [comment]
### "When serializing state we would need to serialize undefined properties as null so that they are serialized as part of the state object"

Easy enough:
```js
JSON.stringify({ foo:undefined }, (x, y) => { return y === undefined ? null : y })
```

### "We only want to support a shallow watch of the state object for performance reasons."

I'm somewhat of the opinion that we need to go all the way down, or not do this at all.

Given a nested structure on the state:
```js
export default {
    state: {
        person: {
            name:'(no name)'
            age:3
        },
        items:[]
    }
}
```

I'm guessing people's first instinct will be to do this:
```js
birthday(present) {
    this.state.person.age++;
    this.state.items.push(present);
}
```

With this proposal they'll have to do this:
```js
birthday(present) {
    this.state.person = Object.assign({}, this.state.person, { age:this.state.person.age+1 });
    this.state.items = this.state.items.concat(present);
}
```

With spread operators, it's certainly cleaner, and while I kinda like this, I worry that it's confusing.
```js
birthday(present) {
    this.state.person = { ...this.state.person, age:this.state.person.age+1 };
    this.state.items = [ ...this.state.items, present ];
}
```



If we don't want to go all the way down, perhaps there could be some value in providing a state objects with functions to handle nested immutable data?
```js
birthday(present) {
    this.state.increment('person.age');
    // this.state.increment('person.age', 1);
    // this.state.set('person.age', this.state.person.age+1);
    // this.state.set('person.age', (age) => age+1);
    this.state.appendTo('items', present);
    // this.state.set('items', (items) => items.concat(present));
}
```
