### ISSUE TITLE
Deprecate w-preserve/w-preserve-if/w-preserve-body/w-preserve-body-if

### ISSUE THREAD

**Issue by patrick-steele-idem** [marko-js/marko#419]
`w-preserve` → `no-update`

**Old:**
```html
<div w-preserve>
    ...
</div>
```

**New:**
```html
<div no-update>
    ...
</div>
```

**Comment by austinkelleher** [comment]
What about `w-preserve-body`, `w-preserve-if`, `w-preserve-body-if`? Should we change those to `no-update-...`?

**Comment by patrick-steele-idem** [comment]
Yes, @austinkelleher, those should be included. I updated the issue title to reflect that. We kept `w-preserve-attrs` as a separate Github issue (https://github.com/marko-js/marko/issues/422) because it is a little more involved since it is not a simple rename.

Would you be interested in taking this one @austinkelleher ?

**Comment by austinkelleher** [comment]
Yeah sure. Assign me.
