### ISSUE TITLE
Add separate in-depth documentation for creating custom taglibs

### ISSUE THREAD

**Issue by patrick-steele-idem** [marko-js/marko#42]
Topics to include:
- Creating nested tags using the following:
  - `body-function`
  - `import-var`
- Compile-time transformers
- Compile-time nodes
- Tag renderers
- `marko-taglib.json` and `marko-tag.json`

**Comment by kristianmandrup** [comment]
Please, please please :) Anything we can do to help. Any sample repo to use as reference?
Cheers!

**Comment by patrick-steele-idem** [comment]
The Marko compile-time API is getting a much-needed refactoring with Marko v3. The plan is to finally provide docs for how to extend Marko at compile-time with Marko v3.

**Comment by mlrawlings** [comment]
Docs for creating custom tags have been added here: http://markojs.com/docs/custom-tags/

We still need docs for compile-time transforms (see #100).
