### ISSUE TITLE
Deprecate `w-bind`

### ISSUE THREAD

**Issue by patrick-steele-idem** [marko-js/marko#421]
`w-bind` → `widget` or `component`

See also #393 #395 #399 

__Update:__ we decided to remove `w-bind` and alternatives completely. If you want to bind a widget to the DOM nodes you need to name the file `widget.js`, `component.js` or embed an inline `<script>` tag in the template with a `module.exports`/`export default`.

**Comment by Hesulan** [comment]
Is there another way to achieve the same result? I can think of a few cases where it would be useful, though perhaps not strictly necessary, to be able to explicitly bind a widget file path. One example would be #514 - is there an alternative, or would that functionality no longer be possible?

**Comment by austinkelleher** [comment]
@Hesulan We decided to not allow that anymore

**Comment by patrick-steele-idem** [comment]
@Hesulan The problem with `<widget-types/>` was that all possible widgets ended up being bundled up by the JavaScript module bundler. The better alternative is to have a single widget that can delegate out to a particular widget implementation or to conditionally remap the JavaScript widget module to the correct module at bundling time. Lasso supports conditional remaps (see `requireRemap` in https://github.com/lasso-js/lasso#nodejs-style-module-support). There are better workarounds and deprecating `w-bind`/`<widget-types>` simplifies Marko and simplifies documentation. I hope that clarifies.

**Comment by Hesulan** [comment]
@patrick-steele-idem Ah, that does clarify. Thanks! Probably a good idea to mention those alternatives somewhere in the v3-v4 upgrade docs, and maybe a few examples to make refactoring easier.

**Comment by drewfish** [comment]
In marko@4.0.0-rc.17 it appears that in `onMount()`, `this.el` is the first element and `this.els` is all top-level elements (when there are multiple top-level elements).
