### ISSUE TITLE
Deprecate `w-preserve-attrs`

### ISSUE THREAD

**Issue by patrick-steele-idem** [marko-js/marko#422]
`w-preserve-attrs` → `<input style:no-update=”” title:no-update>`

**Old:**
```html
<div style="color:#09c" w-preserve-attrs="style">
    ...
</div>
```

**New:**
```html
<div style:no-update="color:#09c">
    ...
</div>
```

**Comment by austinkelleher** [comment]
I can take this one.

/cc @mlrawlings

**Comment by austinkelleher** [comment]
This would be an unlikely case, but do you think we should consolidate `w-preserve-attrs` and `:no-update` if both are present? We will of course log a deprecation warning when `w-preserve-attrs` is used regardless.

```html
<div style:no-update="color:#09c" class="test" w-preserve-attrs="class">
...
</div>
```

```html
<!-- Doesn't matter that it's listed under `class:no-update` and `w-preserve-attrs`. -->
<div style:no-update="color:#09c" class:no-update="test" w-preserve-attrs="class">
...
</div>
```

**Comment by austinkelleher** [comment]
I'm personally leaning toward consolidating because they will function the same anyway.

**Comment by mlrawlings** [comment]
@austinkelleher I think consolidation makes the most sense as well.  Ideally, this would be done in such a way that the code for `w-preserve-attrs` can easily be removed in the future.

**Comment by mlrawlings** [comment]
FYI, I've added a new method to do deprecations from the compiler that tracks the node and line:column in the original template code.

```js
context.deprecate('deprecation warning text');
```
