### ISSUE TITLE
Breaking change: treat concise line starting with ${ as a dynamic tag name

### ISSUE THREAD

**Issue by patrick-steele-idem** [marko-js/marko#425]
Currently, `htmljs-parser` switches into HTML parsing mode when the first character of a concise line is `$`. This was a deliberate decision at the time, but it results in unwanted differences between the HTML and concise syntax. Currently, in order to have a dynamic tag name, the HTML syntax must be used. We want to fix that.

Given the following template:

```
${isInline ? 'span' : 'div'} - Hello World
```

Given a value of `true` for `isInline`.

Old output:

```html
span - Hello World
```

Expected new output:

```html
<span>Hello World</span>
```

**Comment by patrick-steele-idem** [comment]
TODO: Output warning in old parser used by Marko v3. Something similar to:

```
WARNING!!
The behavior of `${` at the start of a line in concise parsing mode will
be changing in Marko v4. To avoid problems in the future, you should
make the following change:

OLD: ${foo}
NEW: - ${foo}

See: https://github.com/marko-js/marko/issues/425
```

**Comment by Hesulan** [comment]
@patrick-steele-idem It seems that this currently coerces non-string values, such as `undefined`, `null`, and `{}`, into `<undefined></undefined>`, `<null></null>`, and `<[object Object]></[object Object]>`. Should it throw an error instead?
