### ISSUE TITLE
Remove deprecated `async` events

### ISSUE THREAD

**Issue by austinkelleher** [marko-js/marko#426]
There are several instances of `TODO: remove deprecated event` comments related to `asyncFragmentFinish`, `asyncFragmentBegin`, `asyncFragmentBeforeRender`, and `asyncFragmentClientReorder`. Should these be removed in v4?

/cc @patrick-steele-idem @mlrawlings

**Comment by patrick-steele-idem** [comment]
Yes, I think they should be. If you want to remove that code and update the `ROADMAP.md` file with those additional breaking changes that would be appreciated. Thanks!

**Comment by austinkelleher** [comment]
Sounds good.

**Comment by mlrawlings** [comment]
@patrick-steele-idem @kprakasam I believe this will require an update to ebay's sitespeed module.  Switching to the new events will be compatible with v3/v4, but not v2.
