### ISSUE TITLE
Add convenience method to create template-based renderer

### ISSUE THREAD

**Issue by philidem** [marko-js/marko#45]
Most renderers look similar to this:
```javascript
var template = require('marko').load(require.resolve('./template.marko'));
module.exports = function(input, out) {
    template.render(input, out);
};
```

Add support for these convenient alternatives:
```javascript
module.exports = require('marko').renderer(require.resolve('./template.marko'));
```

```javascript
module.exports = require('marko').renderer(
    require.resolve('./template.marko'),
    function(input) {
        return {
            ..
        }
    });
```

NOTE: Lazily load the template that is provided and then store reference to loaded template.

**Comment by patrick-steele-idem** [comment]
Great suggestion! I'll be glad to see less boilerplate.

**Comment by patrick-steele-idem** [comment]
For Marko Widgets users this is mostly a non-issue. To avoid adding complexity I propose we scrap this idea. Please feel free to reopen if you disagree :)
