### ISSUE TITLE
Deprecate the layout taglib

### ISSUE THREAD

**Issue by patrick-steele-idem** [marko-js/marko#452]
**Old:**

`./layouts/main/template.marko`:

```html
<!doctype>
<html>
<body>
    <layout-placeholder name="body">
        Default body content
    </layout-placeholder>
</body>
</html>
```

`page.marko`:

```html
<layout-use('./layouts/main/template.marko')>
    <layout-put into="body">
        Hello World
    </layout-put>
</layout-use>
```

**New:**

`./layouts/main/template.marko`:

```html
<!doctype>
<html>
<body>
    <if(data.body)>
        <include(data.body)/>
    </if>
    <else>
        Default body content
    </else>
</body>
</html>
```

`page.marko`:

```html
<include('./layouts/main/template.marko')>
    <@body>
        Hello World
    </@body>
</include>
```

**Comment by JosselinTD** [comment]
A little command to automatically change the layout-put in <@> :
```for file in `find \`pwd\` -name *.marko`; do cat $file | tr '\n' '\f' | perl -pe 's/<layout-put into="([a-zA-Z]*)">(((?!<\/layout-put>).)*)<\/layout-put>/<@\1>\2<\/@\1>/g' | tr '\f' '\n' > "$file"2 && mv "$file"2 $file; done```

**Comment by PierBover** [comment]
Does this mean the package marko-layout is not needed?
