### ISSUE TITLE
Add support for root <style> in single-file component

### ISSUE THREAD

**Issue by patrick-steele-idem** [marko-js/marko#456]
Given:

_src/components/my-component/index.marko:_

```xml
<script>
module.exports = {
    handleButtonClick() {
    }
}
</script>

<style lang="less">
.foo {
}
</style>

<div class="foo">
</div>
```

The `<style>` code should be pulled out into `src/components/my-component/index.marko.less` at compile-time. The `lang` attribute should be used to determine the file extension and the default `lang` should be `css`.

The generated file should then be imported in the compiled template so that it will automatically be picked up by the bundler:

```
require('./index.marko.less');

// ...
```

**Comment by tinovyatkin** [comment]
`include` or new `import` syntax within this `<style>` will be very good addition too! As well as an API for tag renderer to append anything to this, like `out.styles.append('.test-rule { color: red }')`
