### ISSUE TITLE
Marko not work with pm2

### ISSUE THREAD

**Issue by khmelevskii** [marko-js/marko#460]
```
    {
      "name": "test",
      "script": "./src/test",
      "instances": 1,
      "exec_mode": "cluster",
      "watch": true,
      "env": {
        "INTERVAL" : 60000,
        "HOST": "127.0.0.1",
        "PORT": 14211
      }
    },
```

i have error: `Error: Cannot find module 'marko'`

**Comment by Hesulan** [comment]
@khmelevskii Works for me. Are you still having this problem? If so, could you give more details?

**Comment by SebastiaandenBoer** [comment]
I just experienced the same problem. No problems when starting the application with `node app.js`, but with pm2, the HTML does not get rendered anymore. Google Chrome doesn't even render the HTML, but simply displays the raw HTML instead.

If you need, I could provide a more accurate description of what is happening, but please specify what kind of details you would want.

**Comment by patrick-steele-idem** [comment]
@SebastiaandenBoer I think your issue is separate. I think you are forgetting to set the `Content-Type` header to ensure that the browser knows how to interpret the response from the server. You should be doing something similar to the following in your page controller:

```javascript
res.set({ 'content-type': 'text/html; charset=utf-8' });
```

**Comment by SebastiaandenBoer** [comment]
@patrick-steele-idem Although the `Content-Type` header was not the issue, I can now confirm that my problems were separate from the issue discussed in the original ticket. My apologies for the inconvenience.

**Comment by danrichman** [comment]
I've been using pm2 successfully with both Marko v3 and Marko v4 (latest beta) without any problems. No problems here.
