### ISSUE TITLE
emit attribute

### ISSUE THREAD

**Issue by mlrawlings** [marko-js/marko#463]
```html
<custom-component emit('event1', 'event2')/>
```

would be equivalent to:

```html
<custom-component on-event1('emit', 'event1') on-event2('emit', 'event2')/>
```

**Comment by mlrawlings** [comment]
@patrick-steele-idem I've updated this proposal to what we just discussed

**Comment by austinkelleher** [comment]
Without context, I don’t think it would be very clear what is happening here. Plus I don’t think it adds a lot of value. I see what the proposal is going for, but I just don’t think it’s worth having the somewhat ambiguous functionality. Even though the current status is slightly more verbose, it is much more clear.

**Comment by patrick-steele-idem** [comment]
Maybe `re-emit('click')` could be more clear?

**Comment by mlrawlings** [comment]
My desire for this stems from the verbosity that comes from building components that can be re-used across multiple projects.  

Let's take a shared button.  My ideal would be to take a `<button>` and just enhance it a bit.  Maybe all I do is add a `class`.  And then all other properties pass through:

**`<ui-button>`:**
```marko
style {
    .ui-btn { color: red; }
}

<button.ui-btn ${input}/>
```

As a user of the button, I would expect to be able to listen to an event:

```marko
<ui-button on-click('handleClick')/>
```

But events are not normal properties, so `<button.ui-btn ${input}/>` doesn't cover them.  Now I need to re-emit every possible event from the button in case a user might listen for them:

```marko
<button.ui-btn 
    on-mouseenter('emit', 'mouseenter')
    on-mouseover('emit', 'mouseover')
    on-mousemove('emit', 'mousemove')
    on-mousedown('emit', 'mousedown')
    on-mouseup('emit', 'mouseup')
    on-auxclick('emit', 'auxclick')
    on-click('emit', 'click')
    on-dblclick('emit', 'dblclick')
    on-contextmenu('emit', 'contextmenu')
    on-wheel('emit', 'wheel')
    on-mouseleave('emit', 'mouseleave')
    on-mouseout('emit', 'mouseout')
    on-select('emit', 'select')
    on-pointerlockchange('emit', 'pointerlockchange')
    on-pointerlockerror('emit', 'pointerlockerror)'
    ${input}/>
```

And that's just the mouse events.  

Is `emit`/`re-emit` much better?  Maybe not?

```marko
<button.ui-btn 
    re-emit(
       'mouseenter', 
       'mouseover', 
       'mousemove', 
       'mousedown', 
       'mouseup', 
       'auxclick', 
       'click', 
       'dblclick', 
       'contextmenu', 
       'wheel', 
       'mouseleave', 
       'mouseout', 
       'select', 
       'pointerlockchange', 
       'pointerlockerror'
    )
    ${input}/>
```

My ideal would be to allow all events to easily propagate, but there are limitations and performance concerns with doing that...
