### ISSUE TITLE
html tag expressions are compiled without parentheses

### ISSUE THREAD

**Issue by yomed** [marko-js/marko#465]
### Context
I am trying to use a dynamic expression to set an html tag. The compiled code seems to be slightly incorrect, resulting in mangled html.

My marko looks like (adding parenthesis here doesn't help):
```
<${data.type === 'primary' ? 'div' : 'span'}> 
```

### Expected Behavior
Compiled output should be
`out.w("<" + (data.type === "primary" ? "div" : "span") + ">");`

### Actual Behavior
Compiled output is:
`out.w("<" + data.type === "primary" ? "div" : "span" + ">");`

</details>

**Comment by mlrawlings** [comment]
@yomed if you need a temporary workaround:

```js
<${str(data.type === 'primary' ? 'div' : 'span')}> 
```
or
```js
<${(data.type === 'primary' ? 'div' : 'span').toString()}> 
```

**Comment by mlrawlings** [comment]
I have confirmed this is still an issue in v4 as well.

**Comment by mlrawlings** [comment]
Re-opening as the fix needs to be back-ported to v3.

**Comment by mlrawlings** [comment]
`marko@3.13.1` has been published with this fix.

**Comment by yomed** [comment]
@mlrawlings Thanks for the quick fix!
