### ISSUE TITLE
Improve test coverage

### ISSUE THREAD

**Issue by mlrawlings** [marko-js/marko#468]
This is an open-ended issue.

While code-coverage is not a perfect metric, it would be awesome to see our coverage reach 90% on this next release.  We use an autotests format for our tests, which make it really easy to add new tests, just copy a directory and modify it for the new test.  If you're interested in adding some tests and have questions, feel free to ask them here.

### Some high-impact places that could use better coverage:
- [ ] [runtime/dom.js](https://coveralls.io/builds/9270231/source?filename=runtime%2Fdom.js)
- [ ] preserved attributes when re-rendering in [widgets/Widget.js](https://coveralls.io/builds/9270231/source?filename=widgets%2FWidget.js#L578)
- [ ] rendering then using dom insertion methods when using the legacy widget api (`require('marko/widgets').defineComponent`) in [widgets/Widget.js](https://coveralls.io/builds/9270231/source?filename=widgets%2FWidget.js#L728)
- [ ] passing an object to `setState` in [widgets/Widget.js](https://coveralls.io/builds/9270231/source?filename=widgets%2FWidget.js#L340)
- [ ] a number of `builder` methods have no, or incomplete coverage in [compiler/Builder.js](https://coveralls.io/builds/9270231/source?filename=compiler%2FBuilder.js).  These tests could go in [test/autotests/codegen](https://github.com/marko-js/marko/tree/master/test/autotests/codegen).
- [ ] parsing a function expression in [compiler/util/parseJavaScript.js](https://coveralls.io/builds/9270231/source?filename=compiler%2Futil%2FparseJavaScript.js#L97)
- [ ] [compiler/taglib-loader/loader-taglib.js](https://coveralls.io/builds/9270231/source?filename=compiler%2Ftaglib-loader%2Floader-taglib.js)
-  [ ] error assertions (in many, _many_ locations)

### How to find other files that could use additional coverage:
- visit https://coveralls.io/github/marko-js/marko?branch=master
- scroll down to "Source Files on Master"
- sort by lines missed

![image](https://cloud.githubusercontent.com/assets/1958812/21169139/6cfff21a-c16e-11e6-864d-b20279e30354.png)

**Comment by DylanPiercey** [comment]
Much of this is outdated and/or addressed.
