### ISSUE TITLE
Compiler API: Add compileForBrowser and compileFileForBrowser methods

### ISSUE THREAD

**Issue by patrick-steele-idem** [marko-js/marko#472]
`output` should default to `vdom` when compiling for the browser. In addition, no metadata should be included.

**Comment by mlrawlings** [comment]
Should I turn metadata on by default for non browsers?

**Comment by patrick-steele-idem** [comment]
Yes. We'll need to update projects that call the compiler directly (e.g. `templating-benchmarks`) to use the *ForBrowser methods
