### ISSUE TITLE
Add marko-compiler-version to template.marko.js output

### ISSUE THREAD

**Issue by ramses0** [marko-js/marko#487]
### Description
```
var str = __helpers.s,
      ...
      cv = '4.0.1-beta4'
```

### Context

Sometimes it's difficult to determine *which* compiler version output the *.js on disk (ie- command line compiler, marko-loader, etc).  This is a possible enhancement to aid in debugging, perhaps sometimes you need bug reports of "send me template.marko and template.marko.js" and it'd be nice to know *how* template.marko.js was transformed.

Drawback is an increase in filesize per template.marko.js, over a project w/ 50 templates, could be ~500 bytes, although very likely they would gzip well since all would be identical.

**Comment by ramses0** [comment]
(in addition, add `--version | -v` support to `markoc` command)

**Comment by patrick-steele-idem** [comment]
I'm not opposed to this, but it is probably sufficient to add some extra metadata to the compiled template as a JavaScript comment such that it would be minified out in production. In addition, for Marko v4 we introduced support for inspectable metadata that gets added templates compiled for the server.

> (in addition, add `--version | -v` support to `markoc` command)

Can you open up a separate Github issue for that enhancement (this makes tracking progress easier)? Would you be interested in working on either of these enhancements?

**Comment by austinkelleher** [comment]
As we discussed a few days ago @patrick-steele-idem, we should also consider adding a note to the compiled output stating that it is compiled and to not edit it. e.g.

```js
// Compiled using marko@4.0.0-rc.5 - DO NOT EDIT
```

or

```js
// Compiled using markoc@4.0.0-rc.5 - DO NOT EDIT
```
