### ISSUE TITLE
Allow plain text parsing

### ISSUE THREAD

**Issue by eikaramba** [marko-js/marko#491]
## New Feature
Currently there is no easy way to use Marko for plain text parsing. 

### Description
Add non-renderable block to tell Marko to thread this block as text-only (still parsing variables and conditionals and such, just not forcing to transform html tags). 

### Context
The use case is for email rendering, where you probably want to render a html and text version. For example using [nodemailer ](https://github.com/nodemailer/nodemailer)> [node-email-templates](https://github.com/crocodilejs/node-email-templates) > [consolidate.js](https://github.com/tj/consolidate.js) will result in having problems to render the text version as marko will try to generate html tags out of the text sentences.

#### Option 1)
e.g. see this proposal https://github.com/marko-js/marko/issues/343
```
<marko-parser body='static-text'>
        Content
         More Content
        ${data.myVar}
</marko-parser>
```
Important: In this example the output should not include the <marko-parser> tag

#### Option 2)
Javascript call has a new attribute to specify whether the template should be parsed as text-only or with html (transformations)

**Comment by patrick-steele-idem** [comment]
The easiest way right now to achieve what you want is to register your own custom tag that is configured to have a body of "static-text". 

For example, you could register your own `<static-text>` tag:

_src/components/static-text/marko-tag.json:_

```json
{
  "body": "static-text"
}
```

```xml
<static-text>
        Content
         More Content
        ${data.myVar}
</static-text>
```

Does that work for you?

Related: https://github.com/marko-js/marko/issues/343

**Comment by patrick-steele-idem** [comment]
NOTE: If you want to recognize placeholders (i.e. `${...}`) then you should use `parsed-text` instead of `static-text`

**Comment by eikaramba** [comment]
Thanks for your quick response. Unfortunately i does not work. As soon as i'm using <static-text> in my template, the output is null (no error in console). I tried to move the components folder to different places, but nothing worked. Also i added a renderer.js or template.json but also... no luck. Maybe it has something to do how consolidate is calling Marko(`.load(options.filename, ContentAsStr, options`), although i would assume the actual folder lookup should not be affected by this.

**Comment by eikaramba** [comment]
currently my workaround is to use

```
<div marko-preserve-whitespace>
         Content
         More Content
        ${data.myVar}
</div>
```

and then manually removing both divs from the output string.

**Comment by patrick-steele-idem** [comment]
Which version of `marko` are you using? I'll add a test case

**Comment by eikaramba** [comment]
the latest from npm. 3.13.2

**Comment by patrick-steele-idem** [comment]
@eikaramba Sorry for the delayed response. I added a test case for what I was trying to explain. Please take a look at the following: https://github.com/marko-js/marko/tree/master/test/autotests/render/static-text-tag

The implementation for the `<static-text>` tag can be found in the following directory: https://github.com/marko-js/marko/tree/master/test/autotests/render/static-text-tag/components/static-text

NOTE: The test case was added to Marko v4 (master branch), but it should work the same in Marko v3

Does that clarify and does that solution work for you?

**Comment by eikaramba** [comment]
Perfect, now it works flawlessly. I guess the code-generator.js was the missing puzzle piece ;) Thx for the help and your (still very) quick response. Highly appreciated. And yes, it works for v3 too.
