### ISSUE TITLE
Feature suggestion: Macro Bodies

### ISSUE THREAD

**Issue by mindeavor** [marko-js/marko#503]
Might be related to #253

### Description

One of React / hyperscript's strongest ideas is the concept of "views as functions". Although I prefer Marko's "HTML before JS" approach (principle of least power), I think it could go a bit further with the first idea by adding body support to macros.

### The Problem

Currently if you have a list of content to map state onto, you have two options (as far as I know):

<details>
<summary>Option 1: Hard-code <b><i>(click me)</i></b></summary>

```html
<script>
module.exports = {
  onInput(attrs) {
    this.state = { stepsDone: [true, true] }
  }
}
</script>

<div class="challenge-editor">

  <ul>
    <li class={ done: state.stepsDone[0] }>First, do this.</li>

    <li class={ done: state.stepsDone[1] }>
      Then do this.<br/>
      Don't forget to also do this.
    </li>

    <li class={ done: state.stepsDone[2] }>Thirdly, do that.</li>
  </ul>
  ...
</div>
```
</details>

- **Pros:** Content is easily editable
- **Cons:** Repetition of view logic (actual use case has more). Easy to get indexes out of sync.

It's not terrible, but adding any more features would probably end up as a mess.

<details>
<summary>Option 2: Loop <b><i>(click me)</i></b></summary>

```html
<script>
module.exports = {
  onInput(attrs) {
    this.state = { done: [true, true] }
  }
}

var steps = [
  `First, do this.`,
  `Then do this.<br/>
   Don't forget to also do this.`,
   `Thirdly, do that.`
]
</script>

<div class="challenge-editor">

  <ul>
    <for(var i=0; i < steps.length; i++)>
      <li class={ done: state.done[i] }>$!{ steps[i] }</li>
    </for>
  </ul>
  ...
</div>
```
</details>

- **Pros:** No more duplicate logic! Easy to extend.
- **Cons:** Awkward to edit content. If not for ES6 string templates, it would be a nightmare.

In addition, creating a new component in this situation would be excessive, especially since it would only be used in this one component.

### The Solution

Macros *almost* offer the solution to the above problem – the missing piece is **content body**.

Given the feature, here's what the solution to the above problem might look like:

```html
<script>
module.exports = {
  onInput(attrs) {
    this.state = { stepsDone: [true, true] }
  }
}
</script>

<macro step(num)>
  <li class={ done: state.stepsDone[num] }>
    <macro-body />
  </li>
</macro>

<div class="challenge-editor">
  <ul>
    <step(0)>First, do this.</step>

    <step(1)>
      Then do this.<br/>
      Don't forget to also do this.
    </step>

    <step(2)>Thirdly, do that.</step>
  </ul>
  ...
</div>
```

- **Pros**: No duplicate view logic, *and* it's easy to edit! 💯 
- **Cons**: Need to write the feature. No cons from the user's perspective 👍 

Since it's a macro, this transformation would happen purely server-side, probably during compilation.

If you squint your eyes hard enough, you could also say the `<step>` macro is one of those *stateless functional components* React users love to rave about 😄 

### Is this something you're interested in working on?

Yes

**Comment by patrick-steele-idem** [comment]
Great minds think alike. That's already a feature of Marko exactly as you suggested :) See:

https://github.com/marko-js/marko/tree/master/test/autotests/render/macro-body

Specifically:

```xml
<macro alert(title)>
    <div>
        <h1>
            ${title}
        </h1>
        <p>
            <macro-body/>
        </p>
    </div>
</macro>

<alert title="My Alert">
    Something went wrong!
</alert>
```

Sorry for the lack of documentation! If you would be interested in improving the docs, here's the place to go: https://github.com/marko-js/marko/edit/master/docs/language-guide.md

**Comment by mindeavor** [comment]
Amazing! Yes, I'm interested in adding to the docs. Consider this issue assigned to me :)

**Comment by patrick-steele-idem** [comment]
Thanks for the PR to update the docs. Closing this issue now that the docs have been updated. Thanks, again!
