### ISSUE TITLE
node-require base class calling install() forces writeToDisk, exception on read-only systems

### ISSUE THREAD

**Issue by xaricx** [marko-js/marko#506]
### Context
In node-require.js, right before the module.exports, `install()` is called. Consequently, default options are used.
* This causes an exception to be thrown on read-only systems since the default option in the compiler is to writeToDisk. 
* This also results in `install()` potentially being called twice.

### Expected Behavior
`require("marko/node-require").install({compilerOptions: {writeToDisk: false}})` should result in a single call to `install()`, with the options specified.

### Actual Behavior
`require("marko/node-require").install({compilerOptions: {writeToDisk: false}})` calls `install()` twice: Once from the base class (just before the `module.exports` line) with no options, and a second time with the options specified.

### Possible Fix
Remove `install();` on line 134 of node-require.js. Note: With this fix, `require("marko/node-require")` will no longer by default call `install()`.

<details><summary>Additional Info</summary>

### Your Environment
* Version used: 4.0.0-beta.8
* node.js version: v6.9.1
* Operating System: Windows 10 x64

</details>

**Comment by Hesulan** [comment]
Related: #365

**Comment by patrick-steele-idem** [comment]
New version published with fix: `marko@4.0.0-beta.11`

Thanks for reporting the problem!
