### ISSUE TITLE
Input tag is being filled with undefined value when the component's state change.

### ISSUE THREAD

**Issue by juliocanares** [marko-js/marko#513]
### Context
I found what I think is a bug. When I change the state of my component and there is an input in the template, Marko fills it with an undefined value even if I don’t explicitly set the input’s value .

![image](https://cloud.githubusercontent.com/assets/5007653/21706817/dc09a5b2-d397-11e6-8df5-67627de085a7.png)

that’s my template markup

![image](https://cloud.githubusercontent.com/assets/5007653/21706827/f4a06b06-d397-11e6-8615-792ca4fbdb7e.png)

my component’s code

I am currently using `4.0.0-beta.5`

I updated to  `4.0.0-beta.8` and still getting that error

### Expected Behavior

Input's value shouldn't be set.

### Actual Behavior
Input's value is getting filled with an undefined value.

### Environment
* Version used: 4.0.0-beta.5 and 4.0.0-beta.8
* Environment: Chrome  55.0.2883.95 and node.js 7.3.0
* Operating System and version: macOS 10.12.2

**Comment by patrick-steele-idem** [comment]
Thanks for opening the issue. This has been fixed. Please see issue #509. If you upgrade to the latest beta you should be good to go
