### ISSUE TITLE
[v4] Marko treats es6 string templates as marko interpolation tags

### ISSUE THREAD

**Issue by mindeavor** [marko-js/marko#517]
### Context

```html
<script>
module.exports = {
  onInput(attrs) {
    var content = 'Hello there!'
    this.state = {
      text1: `Text 1: ${content}`,
      text2: 'Text 2: ' + content
    }
  }
}
</script>

<div>
  <h3>${state.text1}</h3>
  <h3>${state.text2}</h3>
</div>
```

### Expected Behavior

```html
<h3>Text 1: Hello there!</h3>
<h3>Text 2: Hello there!</h3>
```

### Actual Behavior

```html
<h3>Text 1: </h3>
<h3>Text 2: Hello there!</h3>
```

### Your Environment

* Version used: v4.0.0-beta.12

**Comment by patrick-steele-idem** [comment]
@mindeavor I would expect that to work since Marko shouldn't do anything special with the code inside the `<script>` block. Would you be interested in working on this?

**Comment by Hesulan** [comment]
Would adding `"body": "static-text"` in the `marko.json` fix that (similar to the [app-markdown](https://github.com/marko-js-samples/ui-components-playground/blob/master/src/components/app-markdown/marko-tag.json) sample component)?

**Comment by mindeavor** [comment]
I don't think I would have the time to dig into the codebase in the near future, no :(

**Comment by patrick-steele-idem** [comment]
@mindeavor No worries!

I think you are right, @Hesulan. Would you be interested in working on a fix?

**Comment by patrick-steele-idem** [comment]
Michael and I had a quick discussion and our conclusion was that we should update `htmljs-parser` to ignore Marko placeholders inside template literal strings in `parsed-text` mode.
