### ISSUE TITLE
Use "for of" instead of "for in" looping

### ISSUE THREAD

**Issue by aaronshaf** [marko-js/marko#519]
In ES6 "of" gives you the value and "in" gives you the key.

**Comment by patrick-steele-idem** [comment]
We've already deviated from JavaScript (in ways that I make more sense) and we would not want to introduce any breaking changes at this point. FYI, You can do the following if you want both the key/index and value when looping over the elements/properties of an `Array`/`Object`:

```xml
<for(colorIndex,color in ['red', 'green', 'blue'])>
</for>
```

That syntax works with objects too:

```xml
<for(colorName,colorHex in { red: '#f00', green: '#0f0', blue: '#00f' })>
</for>
```

If you still have suggestions/concerns, please let us know and happy to discuss some more, but closing issue for now. Thanks.
