### ISSUE TITLE
Unused file?

### ISSUE THREAD

**Issue by mlrawlings** [marko-js/marko#523]
It seems file at [/taglibs/core/util/parseJavaScriptIdentifier.js](https://github.com/marko-js/marko/blob/690c1d14333fcd9f7969dbbc1591fc538c2932c8/taglibs/core/util/parseJavaScriptIdentifier.js) does not appear to be [used](https://github.com/marko-js/marko/search?utf8=%E2%9C%93&q=parseJavaScriptIdentifier).

**Comment by patrick-steele-idem** [comment]
It was probably used at one point, but it looks safe to delete now. Please feel free.
