### ISSUE TITLE
[v4] The out should be passed to onInput(input, out)

### ISSUE THREAD

**Issue by patrick-steele-idem** [marko-js/marko#525]
The signature for `onInput` should be `onInput(input, out)`. It is currently `onInput(input)`.

**Comment by mlrawlings** [comment]
Closed via https://github.com/marko-js/marko/commit/2c04a4d916fb427e42ee923b3b66509bb26ac4f5

Note: When using [`setProps`](https://github.com/marko-js/marko/blob/master/widgets/Widget.js#L325-L346), `out` is not passed (nor was it passed to `getInitialState` in v3).

**Comment by patrick-steele-idem** [comment]
@mlrawlings I'm not seeing an issue related to `setProps`. Calling `setProps(newProps)` will cause the component to be rerendered with `newProps` as the input and a new `out` will be created to do the rerender and those things will be passed to `onInput()`. Am I misinterpreting your note?

**Comment by ianvonholt** [comment]
@patrick-steele-idem and @mlrawlings This reflects the behavior that was available in v3 with getInitialState and I don't see any problems with backwards compatibility. Thank You!
