### ISSUE TITLE
NPM package includes `~node_modules` and `~runtime`

### ISSUE THREAD

**Issue by Hesulan** [marko-js/marko#526]
Directories named `~node_modules` and `~runtime` seem to have been accidentally added to the NPM package starting from `4.0.0-beta.6`, bringing the `package.tgz` size from < 300 kB to > 3 MB. Still there as of `4.0.0-rc.0`.

/cc @patrick-steele-idem @mlrawlings

**Comment by patrick-steele-idem** [comment]
Thanks for letting us know. New version published with those directories removed: `v4.0.0-rc.1`

The new version also includes https://github.com/marko-js/marko/issues/525
