### ISSUE TITLE
Add support for exporting data from marko templates

### ISSUE THREAD

**Issue by Eldar-X** [marko-js/marko#538]
## Exporting data from template

I think it would be very nice feature if we can exporting data from template files because now marko files have much power and we can make logical operations some times we just want to export result for using it somewhere else.

### Example use case:

We have cms and we want define output fields for this template then in our admin page we want get all fields of selected template file for fill them.

**Comment by mlrawlings** [comment]
@Eldar-X Would this cover your use-case? https://github.com/marko-js/marko/blob/bce3836d099854f3aa9f2f48fffb470cd7a78399/docs/04-core-tags.md#export

I'm going to implement this in a bit unless you have some feedback.

**Comment by Eldar-X** [comment]
Looks like what i need.
Let's make some example something like this is working?
```
// foo.marko
<script>
var fields = {};
</script>

<div class="myField-1">
 <% fields["first"] = {
 name:"firstField",
 type:"textarea"
} %>
</div>

<div class="myField-2">
 <% fields["second"] = {
 name:"secondField",
 type:"datePicker"
} %>
</div>

export var info = {
 name: "Home Page",
fields: fields
}

// bar.js
const template = require('foo.marko');
console.log(template.info) // name: "Home Page", fields: { first, second }
```

**Comment by DylanPiercey** [comment]
@Eldar-X although I think top level export would be sweet, for now you can do this:

```marko
static exports.x = 1;

<div>Hi</div>
```

**Comment by DylanPiercey** [comment]
With Marko 5 you can use `esm` exports, eg

```marko
export const x = 1;
<div/>
```
