### ISSUE TITLE
Marko needs a new logo!

### ISSUE THREAD

**Issue by patrick-steele-idem** [marko-js/marko#54]
Let's create some logos for Marko!

I'll start things off with a really _rough_ sketch of an idea:

![marko-logo-small](https://cloud.githubusercontent.com/assets/978214/6374693/ce18ec78-bccf-11e4-968f-7c06ae73e8e6.jpg)

Please feel free to take that idea and make it better or come up with something completely different.

All logos submitted here will be assumed to be licensed as public domain / [CC0](http://creativecommons.org/about/cc0).

Contributors to the final logo will get credit on the main page and a custom printed T-Shirt with the logo on it!

**Comment by pdajlido** [comment]
![marko0](https://cloud.githubusercontent.com/assets/8730277/6872950/1f4f32d8-d4ad-11e4-9edd-4718197d4ba5.png)

**Comment by pdajlido** [comment]
![marko1](https://cloud.githubusercontent.com/assets/8730277/6872952/2807186e-d4ad-11e4-8d85-26981939383d.png)

**Comment by patrick-steele-idem** [comment]
@pdajlido I like the logo with the pink lettering because it is simpler. I like the visual elements added around the lettering, but what is the meaning of the lattice decoration?

Also, I think it works well if the graphic part of the logo could be used independent of the "Marko" text and for the graphic part to be easily recognizable and unique (if that makes sense).

**Comment by pdajlido** [comment]
:D these are the '< >'  it all can be customised I have .ai files saved

**Comment by patrick-steele-idem** [comment]
Instead of `><><` (which looks like two X's), I would lean more towards `<><>` since it matches how the characters would appear in an HTML tag. Maybe something can be done with a double diamond :)

**Comment by seangates** [comment]
Dumb, but worth the "idea".
![marko-logo](https://cloud.githubusercontent.com/assets/105656/6873249/9affb1fc-d474-11e4-8e5f-65e7e15a4aa5.png)

**Comment by pdajlido** [comment]
![marko3](https://cloud.githubusercontent.com/assets/8730277/6873580/9f302990-d4b1-11e4-8c19-1c3eadfd3823.png)

**Comment by philidem** [comment]
I like the upper-right "M" logo. Might want to create a companion logo that contains "Marko" as well. I do like the diamond concept.

**Comment by philidem** [comment]
I didn't see two "X"s at first but now that's all I see for "><><". Maybe "<><>" As @patrick-steele-idem suggested would be better.

**Comment by philidem** [comment]
@seangates Even "dumb" ideas can inspire something better! What is "Mark" though? Just kidding :)

**Comment by patrick-steele-idem** [comment]
![marko-logo-01](https://cloud.githubusercontent.com/assets/978214/6874018/bd5efd20-d479-11e4-9f0e-24ca36bfbc08.png)

**Comment by philidem** [comment]
@patrick-steele-idem Maybe ".Marko" instead of "Marko."

Or maybe ".marko" (lower case)

**Comment by seangates** [comment]
@philidem Yeah, I saw that as soon as I made it, but said, "What the heck? Worth a post."

**Comment by patrick-steele-idem** [comment]
![marko-logo-01](https://cloud.githubusercontent.com/assets/978214/6875756/1917e016-d487-11e4-9b7e-f7fdc7e6a75a.png)
![marko-logo-02](https://cloud.githubusercontent.com/assets/978214/6875757/19198b6e-d487-11e4-9bce-098856955d3d.png)

**Comment by pdajlido** [comment]
![marko2](https://cloud.githubusercontent.com/assets/8730277/6876374/2dc9b080-d4c7-11e4-8832-5a4347acf696.png)
Since Marko is a dudes name I gave him some personality

**Comment by patrick-steele-idem** [comment]
Hah, nice @pdajlido! I'm curious as to what others think of adding a character to the logo, but I might like it :) A logo with a character seems to have worked well for [Yeoman](http://yeoman.io/)

**Comment by patrick-steele-idem** [comment]
Also, for Marko Widgets you could modify the dude to be a mad scientist.

**Comment by pdajlido** [comment]
![marko4](https://cloud.githubusercontent.com/assets/8730277/6876740/de88c28c-d4ca-11e4-990f-ca09efb4e3d9.png)
Some Urban Style.

**Comment by pdajlido** [comment]
Alright time to leave Illustrator. Good night Gentleman!, I will be bugging you tomorrow since I haven't implementetd optimizer yet ;)

**Comment by patrick-steele-idem** [comment]
Thanks for the contributions, @pdajlido!

**Comment by patrick-steele-idem** [comment]
![marko-logo-03](https://cloud.githubusercontent.com/assets/978214/6877648/975279c6-d498-11e4-9b92-bfb4afaf571f.png)

**Comment by onemrkarthik** [comment]
![screen shot 2015-03-27 at 2 47 34 pm](https://cloud.githubusercontent.com/assets/7464488/6877671/72464764-d490-11e4-83b9-8d8fc7aedd66.png)

Maybe you could play around with the color...

**Comment by tindli** [comment]
![marko3](https://cloud.githubusercontent.com/assets/6454552/8861384/755b9178-318a-11e5-967a-4b8990787b94.png)

Some thoughts (additional love to detail required): 
* the brackets at the end should appear 3D "stacked"; meaning: tags can be wrapped... forming components
* the font should appear dynamic, "agile", quick and nice
* the subtext describes marko as template engine and binding (behavior) and gives an insight about how marko components are written

**Comment by patrick-steele-idem** [comment]
Hey folks, while we had a some great submissions we decided to get the help of some professionals. We started a logo contest on 99designs.com yesterday and are getting some great submissions:

**Comment by philidem** [comment]
Link to contest entries?

**Comment by patrick-steele-idem** [comment]
Accidentally pressed the wrong button... Comment updated with link to contest. Thanks.

**Comment by SirParadox** [comment]
Lol how about some fancy..

${marko}


   Ryan Pavely
    Net Access
    http://www.nac.net/

**Comment by tindli** [comment]
haha had a funny idea.... marko and an abstract grining face

![marko_face](https://cloud.githubusercontent.com/assets/6454552/9115315/b139b948-3c5e-11e5-9edd-0ec5a9e25110.png)

**Comment by patrick-steele-idem** [comment]
Hi folks,

We created two separate polls to help us choose a logo (99designs.com limits each poll to only 8 logos each):

Poll 1: https://99designs.com/logo-design/vote-d19zuf
Poll 2: https://99designs.com/logo-design/vote-3qyhyb 

Please vote! Thanks!

**Comment by patrick-steele-idem** [comment]
Hi folks,

Thank you all for the votes in the earlier polls! We have one more poll (last one, I promise). Please give your ratings for the last set of designs:

Final poll: https://99designs.com/logo-design/vote-bdarln

We will use the final poll to help select the winner. Thanks in advance!

**Comment by patrick-steele-idem** [comment]
Marko has a new logo!

![Marko Logo](https://cloud.githubusercontent.com/assets/978214/9265711/774768ca-41f4-11e5-81ee-8fff2cae7e9a.png)

**Comment by tindli** [comment]
Well deserved, congrats Marko!
