### ISSUE TITLE
How to disable "concise" defaultMode?

### ISSUE THREAD

**Issue by rgagnon24** [marko-js/marko#542]
I have a template that is in HTML format, but the parser is assuming concise mode, so warnings for issue 43 and 48 from htmljs-parser are now popping up in the console.

How do you disable concise mode if you do not use it?

**Comment by patrick-steele-idem** [comment]
You can immediately switch into HTML mode by using an HTML delimited block:

```html
--
This is all parsed as <strong>HTML<strong>!
--
```

Does that solve your issue?

**Comment by mlrawlings** [comment]
@patrick-steele-idem The parser allows disabling concise mode.  Do we (or can we) disable it for `.marko.html` and `.marko.xml` files?

**Comment by patrick-steele-idem** [comment]
We could disable concise mode for `.marko.html`, but I'm not sure we want to go there because it breaks syntax highlighting (unless we refactor our syntax highlighting bundles).

**Comment by rgagnon24** [comment]
I didn't know about wrapping with `--` as I couldn't find any documentation on that.  Thanks for the tip.  That should work, and probably much easier than figuring out how to change marko to pass the concise: false option to htmljs-parser

**Comment by patrick-steele-idem** [comment]
Sorry for the lack of docs on that @rgagnon24. We are completely reworking the docs for the Marko v4 release and things will be a lot more clear. Let us know if you have any questions, but closing this issue for now.
