### ISSUE TITLE
String interpolation not working in latest v3

### ISSUE THREAD

**Issue by scttdavs** [marko-js/marko#545]
### Context
Our template with string interpolation in the `<script>` tag is not working as it was before (in v3.9). See below for a simplified example.

### Expected Behavior
This template:
```html
<script>
    var url = "https://foobar.com?input=${'test'}";
</script>
```
should render as:
```js
function create(__helpers) {
  var str = __helpers.s,
      empty = __helpers.e,
      notEmpty = __helpers.ne,
      escapeXml = __helpers.x;

  return function render(data, out) {
    out.w("<script>\n    var url = \"https://foobar.com?input=test\";\n</script>");
  };
}

(module.exports = require("marko").c(__filename)).c(create);
```

### Actual Behavior
```js
function create(__helpers) {
  var str = __helpers.s,
      empty = __helpers.e,
      notEmpty = __helpers.ne,
      escapeXml = __helpers.x;

  return function render(data, out) {
    out.w("<script>\n    var url = \"https://foobar.com?input=${'test'}\";\n</script>");
  };
}

(module.exports = require("marko").c(__filename)).c(create);
```

### Possible Fix

Not a fix, but a clue: oddly, this template correctly renders the interpolation:
```html
<script>
    var url = "${'https://foobar.com?input='}${'test'}";
</script>
```
Result:
```js
function create(__helpers) {
  var str = __helpers.s,
      empty = __helpers.e,
      notEmpty = __helpers.ne,
      escapeXml = __helpers.x;

  return function render(data, out) {
    out.w("<script>\n    var url = \"https://foobar.com?input=test\";\n</script>");
  };
}

(module.exports = require("marko").c(__filename)).c(create);

```

### Your Environment

* Version used: 3.14.0
* Environment name and version (e.g. Chrome 39, node.js 5.4): node.js 4.4.5
* Operating System and version (desktop or mobile): desktop
* Link to your project:

### Steps to Reproduce

Just save a file with the above template and render with marko `markoc test.marko` and view the contents.

**Comment by patrick-steele-idem** [comment]
It looks like fixing one bug is causing another. The parser now tokenizes the content of script blocks and ignores string tokens to avoid issues with trying to do text replacement inside JavaScript strings. We might have to wait and see the impact on this change, but the correct thing to do is the following:

```html
<script>
    var url = ${JSON.stringify(getUrl(test))};
</script>
```

Technically, this bug fix was a breaking change, but I don't think we should go back to the old behavior just yet. Thoughts?

**Comment by scttdavs** [comment]
if it ignores string tokens, then why is it still replacing the strings in some situations (such as the one I gave above)? 

This is not a major bug for us, so we can change our templates to accommodate for it. It was just unexpected since even though we are typing js, it's still within the template and I'd expect the replacement to work the same.

**Comment by mlrawlings** [comment]
Maybe we should only be skipping template literals (`` `Hello ${name}` ``)?
