### ISSUE TITLE
Transclusion Scope on widgets

### ISSUE THREAD

**Issue by jasonmacdonald** [marko-js/marko#550]
This might be just me not fully understanding Widget scopes/states, or more likely it's working as intended, but if I have Widget (A) and Widget (B). Widget A uses Widget (B) in it's template and supplies some body content (template) for Widget B. The data scope is bound to Widget A for that body content and not Widget B (which actually renders it). 

Example

Widget A Template - data = 1
```
<widgetB data="2">
   <!-- trying to declare this inner content as a template 
   to be used to render the contents of Widget B -->
   <div>${data}</div>
</widgetB>
```

Widget B template - data = 2
```
<!--I want this to render the body declared in Widget A, but use the data scope of this Widget B-->
<div w-body></div>
```

This ends up rendering the value **1** in the div, not **2.**

What I was hoping was that the scope of WidgetB's data, value (**2**), would be supplied to the transcluded content. I suspect this is working as intended, but is there a way to get the result I was hoping for? 

What I'm trying to do is have widgetB  be able to declare a template to be used inside it's own template when rendered. Think of a tile list component, where I'm trying to supply a transcluded template to be used to render each tile when the tile list renders, rather than declaring the tile itself inside the tile list, for re-usability and flexibility. So each tiles data would be driven internal to Widget B, and I'm defining the template ${params} externally.

**Comment by jasonmacdonald** [comment]
I also tried using input.renderBody(out, WidgetB_data), inside WidgetB. But, that still seems to use WidgetA data.

**Comment by mlrawlings** [comment]
I also want to point out that we add one more layer on top of this for the await tag.  The await tag is used like:

```jsx
<await(value from promise)>
    ${value}
</await>
```

We transform this to the following in the [await transformer](https://github.com/marko-js/marko/blob/master/taglibs/async/await-tag-transformer.js#L28-L29):

```jsx
<await _var="value" _dataProvider="promise">
    ${value}
</await>
```

Then `{"name-from-attribute":"_var"}` is specified in the [`marko.json`](https://github.com/marko-js/marko/blob/master/taglibs/async/marko.json#L53-L55)

Which results in `value` (in this case) being made the second parameter to `input.renderBody`.  Then we just wait for the promise to resolve and [pass the result to `renderBody`](https://github.com/marko-js/marko/blob/master/taglibs/async/await-tag.js#L120).

**Comment by jasonmacdonald** [comment]
Thanks< mlrawlings! I'll give these a try!

**Comment by jasonmacdonald** [comment]
I think I might have a snag, all this assumes I'm only rendering the transcluded content once. But what I'm trying to do is the transcluded content template as an itemRenderer for a loop, basically.

something like this (very simplified)

WIdget
```
<tileList data="${some_array_of_items}">
    <div>${item}</div>
</tileList>
```

TileList
```
<div for(item in items)>
    <div w-body></div>
</div>
```

Seems if I manually call input.bodyRenderer() it would just repeat the same content. Maybe I'm approaching this wrong. I'm just trying to make a reusable tielist component for an image gallery, where the user of the component can easily define how the content is rendered by specifying the item renderer in the body. I know I could have them define a path to a template to be used for rendering, was just trying to avoid extra files.

**Comment by mlrawlings** [comment]
This should work:

```html
<div for(item in items)>
    <invoke data.renderBody(out, item)/>
</div>
```

**Comment by jasonmacdonald** [comment]
oh, let me try that! You're the best, mlrawlings! Cheers! Wish I knew more of these secrets :)

**Comment by jasonmacdonald** [comment]
Interesting. Marko doesn't seem to be parsing the for loop statement. WHen I look in the compiled file, it just leaves the forloop stuff untouched.

```
function(out, widget) {
        out.w('<div' +
          attr("id", widget.elId()) +
          attrs(_widgetAttrs(widget)) +
          '><div for(item in items)>' +
          escapeXml(item) +
          '</div></div>');
      });
```

I'm sure I've missed something, again :) Is Marko Widgets using a different version of Marko?

**Comment by jasonmacdonald** [comment]
Can Marko Widgets use Marko 4? NPM complains that Marko Widgets wants a Peer dependency for 3.0

**Comment by mlrawlings** [comment]
Marko 4 includes widgets, so you don't need `marko-widgets` anymore

**Comment by jasonmacdonald** [comment]
oh, really? Well, is Marko 4 accessible from NPM?

**Comment by jasonmacdonald** [comment]
ok, awesome. Got Marko 4 all set-up and things seems to be working, for the most part. One thing I can't seem to get to work anymore is the "var" part to add the extra variable to the renderBody.

I've tried adding it to the marko-taglib and also to the top of the component with...

```
exports.tag = {
    "var": "item"
}
```

BUt the compiled output doesn't seem to add the var anymore. I had it working in Marko 3. Did this part change? I can't find anything about how to do these configs in the [Roadmap page.](https://github.com/marko-js/marko/blob/v4.0.0-rc.8/ROADMAP.md).

I'm sorry for the all the questions. :(

**Comment by jasonmacdonald** [comment]
ok, after some trial and error, I was able to get the "var" to appear in the compiled output, but only if I added a marko-tag.json file to the "Widget" component directory, along side my component.js and index.html. I used the following JSON

```
{
  "var": "item"
}
```

No clue if this is correct way though. We used to be able to add these in the component file using an exports.tag, but that doesn't seem to work anymore. Kind of annoying to have to add another file to accomplish this.

I'm still a bit muddy on all these JSON files (marko-taglib.json vs marko-tag.json vs marko.json) and where exactly they are supposed to live. It seems I need to have a marko-tag.json somewhere high in the directory that defines the components directory defining "tags-dir": "./src/components" or nothing gets found.

I'm sure it's just me fumbling my way through this without docs :(

**Comment by patrick-steele-idem** [comment]
@jasonmacdonald Adding the `marko-tag.json` file as you did is the correct thing to do. We'll revisit the docs for v4 to make things more clear. Since we are completely reworking the documentation I'm going to go ahead and close this issue. In the meantime, please let us know if you have any specific questions...happy to help.
