### ISSUE TITLE
Components are being rendered with same id

### ISSUE THREAD

**Issue by juliocanares** [marko-js/marko#553]
I am getting the same id for all my rendered components and if I wanna get the state for one of those it always gives me the same result.

![](http://i.imgur.com/cG8dmT0.png)

This is my code

### account-purchase component

```html
<for(purchase in data.purchases)>
  <account-purchase-item item=purchase onChange('purchaseSelected')/>
</for>
```

```javascript
module.exports = {
  getTemplateData: function (state, input, out) {
    return input;
  }
};
```

### account-purchase-item component

```html
<button class='account-purchase-item' onClick('onClick')>
  <p class='code mb-5'>Pedido <span>${data.item.code}</span></p>
  <p class='date'>Comprado el ${data.item.$createdAt}</p>
  <span class='i-caret-right'></span>
</button>
```

```javascript
module.exports = {
  onInput: function (input) {
    this.state = {
      item: input.item
    }
  },
  getTemplateData: function (state, input, out) {
    return state;
  },
  onClick: function () {
    //always give me the same result
    console.log(this.state.item);
  }
};
```

**Comment by Hesulan** [comment]
Removing `onChange('purchaseSelected')` from the `account-purchase` template seems to fix this as a workaround.

I checked the v3 equivalent and it did the same thing, so this isn't a regression, but it does seem odd that attempting to assign event handlers to a nested widget from its parent template would interfere with ID assignment.
