### ISSUE TITLE
[v4.rc13] Unrecognized tag: picture

### ISSUE THREAD

**Issue by tinovyatkin** [marko-js/marko#574]
Compilation broken with error `Unrecognized tag: picture` while `picture` is certainly a standard HTML5 tag

**Comment by austinkelleher** [comment]
Thanks for reporting this issue. This is a result of: https://github.com/marko-js/marko/issues/560. I will have a fix up soon.

**Comment by austinkelleher** [comment]
This should be fixed now. A new version should be published later today.
