### ISSUE TITLE
[v4] Consider renaming `for` to `each`

### ISSUE THREAD

**Issue by gilbert** [marko-js/marko#577]
When users see `<for(var x in xs)>`, they think it's native JavaScript and try to do fancy ES6 stuff like destructuring.

Here's an actual attempt:

    <for(const [airport, { area, name, pos: { lat, lng } }] of Object.entries(geo.airports))>

I have two suggestions (not mutually-exclusive):

1. Rename `for` to `each` to avoid confusion
2. Give `for` native JS code support

This would be the last nail in the "uncanny JavaScript-like tags" coffin.

**Comment by mauricionr** [comment]
Or could be more vue like

for((key, value) in data)//object

And

for(item in data)//array

Thanks :)

**Comment by DylanPiercey** [comment]
We've switched up the for tag syntax keeping this in mind in https://github.com/marko-js/marko/pull/1238
