### ISSUE TITLE
Create a tag for data.renderBody(out);

### ISSUE THREAD

**Issue by tinovyatkin** [marko-js/marko#578]
Hello,

While refactoring for `rc14` I realise that new syntax for `data.renderBody` invocation must be like this:

```
$ if(data.renderBody) data.renderBody(out);
```
That's not looks very good inside a HTML like template. May be it's better to create a dedicated tag like `<tag-body-out />` for that purpose? It will be rendering for nothing or body... Simple and elegant?

**Comment by mlrawlings** [comment]
Good news: can already use the `include` tag for this

```html
<include(input.renderBody)/>
```

Include actually looks for a `renderBody` property if its an object, so this works as well:
```html
<include(input)/>
```

**Comment by tinovyatkin** [comment]
is `data` deprecated too and we should use `input` instead?

**Comment by mlrawlings** [comment]
Yeah, but `data` isn't going anywhere anytime soon and we won't be adding deprecation warnings for it right away either.

**Comment by mlrawlings** [comment]
But all the docs for Marko 4.0 will reference `input`
