### ISSUE TITLE
$escapeXml is not defined

### ISSUE THREAD

**Issue by tinovyatkin** [marko-js/marko#579]
Badly (confusing) written code result in even more confusing error message:

Code:
```
<a href="/vip/fasttrack/${airport.canonical}/"
               style="background-image: url(${asset(`${airport.icon}-square`, { path: 'logo/airports', type: 'png'})})">
               ${airport.name.en}
</a>
```
error:
```
$escapeXml is not defined
```
Rewriting the code above without using enclosed template literal fixes the problem:
```
<a href="/vip/fasttrack/${airport.canonical}/"
               style="background-image: url(${asset(airport.icon + '-square', { path: 'logo/airports', type: 'png'})})">
               ${airport.name.en}
</a>
```

**Comment by mlrawlings** [comment]
Is this still an issue?  We've since updated esprima which could potentially be related.  I'm going to close this, but comment here if it needs to be reopened.
