### ISSUE TITLE
[v4] virtualizeHTML requires the document.body be loaded

### ISSUE THREAD

**Issue by jasonmacdonald** [marko-js/marko#586]
Ran into this issue in IE where adding $!{htmlText} in a template, and rendering that template (not appending it), you can run into a condition where "doc.body" is undefined because IE has not yet loaded the body yet. Essentially, this means you cannot do any template rendering before the document is loaded. Seems to be fine in Chrome, or at least I was not able to replicate it.

This is the specific block where I was getting doc.body:
```
if (!range && doc.createRange) {
        range = doc.createRange();
        range.selectNode(doc.body);
    }
```

Is the expectation that we not do any pre-rendering before the DOM is loaded?

**Comment by mlrawlings** [comment]
@jasonmacdonald I realize this was opened a while ago.  Is this still an issue?  If so, could you provide some more details like a stack trace and maybe a bit more context?

**Comment by DylanPiercey** [comment]
Marko 4+ no longer uses `createRange`.
