### ISSUE TITLE
non-breaking spaces (& n b s p;) don't render correctly in v4 templates

### ISSUE THREAD

**Issue by smulder** [marko-js/marko#587]
### Context
placing non-breaking space (`&nbsp;`) in a template element renders out as `Â` on the browser (VDOM).

### Expected Behavior
should render simply as (`&nbsp;`)

### Actual Behavior
renders as `Â`.

<details><summary>Additional Info</summary>

```
< div class="cartCoupTitle" >
        ${coup.title}< br/ >
        < span class="cartCoupGUID" >${coup.GUID}< /span ><br/>
        < strong >Expires< /strong > &nbsp; &nbsp;${coup.expires}
< /div >
```

VDOM

``` marko_forEach(state.productCoupons, function(coup) { 
out.e("div", marko_attrs31, 2) 
.e("div", marko_attrs32, 7) 
.t(coup.title) .n(marko_node27) 
.e("span", marko_attrs34, 1) 
.t(coup.GUID)
 .n(marko_node28) 
.n(marko_node29)
 .t(" Â Â ") 
.t(coup.expires) 
.e("div", marko_attrs33, 1) 
.e("strong", null, 2) 
.t("$") 
.t(coup.authorizedPrice); }); 
```
</details>

**Comment by patrick-steele-idem** [comment]
Thanks for opening this bug report @smulder. We'll take a look.

**Comment by tigt** [comment]
This looks like the character encoding wasn’t set for the output HTML. [When the UTF-8 non-breaking space is interpreted as ISO-8859-1, it instead appears as Â.](https://stackoverflow.com/questions/1461907/html-encoding-issues-%C3%82-character-showing-up-instead-of-nbsp)

You can fix this by adding `<meta charset="utf-8">` in your `<head>`.

**Comment by DylanPiercey** [comment]
I have not been able to reproduce this issue myself and it's quite old at this point.

I believe @tigt is probably right. Happy to reopen the issue otherwise.
