### ISSUE TITLE
Async fragment rendering with marko

### ISSUE THREAD

**Issue by tindli** [marko-js/marko#59]
I have three points regarding progressive rendering of marko templates.

1. As out of order rendering requires JS on the client side, the docs should mention that as well (including the impact this has on on things like progressive enhancement etc.) The only mention of this that I have found is on the ebay tech blog article about progressive rendering. I might be missing something here; I made some thoughts, if out of order rendering could be achieved without the need of client side JS... unfortunately I did find a way to do so.... is this a point of interest for marko?

2. I wonder, if google does correct indexing with out-of order rendering, as A) JS is required and B) the initial HTML is rendered into a hidden div. Point A might be a no-issue, since google (and others?) now performs JS when requesting pages. If not, point B is critical because hidden content could be ignored/identified as lower priority (less relevant to a page) so pages might not be correctly indexed. If google runs JS and considers the page when it is fully loaded, point B might be a no-issue. Please provide some thoughts/practical experiences regarding A and B.

3. When running the examples on https://marko-progressive-rendering.herokuapp.com/?renderMode=progressive-in-order&jsLocation=middle everything is fine until you reload the iframe (hitting the inner refresh button on the page) in the chrome browser. Strangely, progressive rendering of async-elements only works when you move the mouse after refresh - Safari and Firefox render every chunk as soon as it arrives. Reloading the entire page in chrome shows the same effect while running the example in a separate window works fine (most of the time). I tested the behaviour with a bigger first chunk (additional textual data) but the data refuses to render until you move the mouse. It seems, that the browser ignores chunked responses and renders the content like a single chunk. I see the same behaviour on Mac and Linux. Does somebody know the reason and if this is a known/intended behaviour or a bug on the marko/chrome part?

**Comment by patrick-steele-idem** [comment]
Hey @tindli, I'm going through old issues to do some housecleaning. I am going to go ahead and close this issue. If you think that we need to improve the docs in various areas, I would recommend opening a Github issue for each proposal for better tracking purposes.

FYI, I actually haven't done any extensive tests to see how Google indexes pages with client-side reordering. I would be curious to know the answer to that :) However, we have aimed to only do out-of-order rendering for non-bots and browsers with JS enabled. For bots and non-JS users the recommendation has been to not enable client-side reordering (`client-reorder="false"`). Thanks!

**Comment by tindli** [comment]
hi @patrick-steele-idem thanks for looking into the issue - I am fine with closing it - if something pops up again, I will create a new issue.

Sadly, I have not done any further investigation towards indexing but as soon as I get more information, I will share it.
