### ISSUE TITLE
Support for scoped JavaScript variables

### ISSUE THREAD

**Issue by patrick-steele-idem** [marko-js/marko#590]
Marko v3 supports scoped vars:

```jsx
<var x=1 y=2>
  The `x` and `y` are scoped to this block.
</var>
```

We moved from `<var>` to `$ var` and need to rethink support for scoped variables in Marko v4.

**Comment by ramses0** [comment]
Strawman argument was for:

```
<scope>
   $ var x = 1
   $ var y = 2
   This is ${x}, ${y} valid.
</scope>
This is ${x}, ${y} undefined.
```

...compiling to an IIFE for scope protection, and using `$ ...` for JS execution.

Rationale is that a dangling `$ var x = ...` at the top of a file could have spooky action at a distance towards the bottom of the file, but if it were captured in some sort of `<scope> ...` block then the area required to analyze is much smaller.

**Comment by Hesulan** [comment]
A lot of tags generate nested functions, so with `$ var ...;` it's impossible to know where the scope begins or ends until you look at the compiled output - it could stop at the nearest parent tag, or extend all the way to the top-level render function. That *usually* doesn't matter, but it would be nice to have a more explicit way to handle variable scope.

I agree with using `$ ...;` for inline javascript, but things like tag scope need to be handled by the compiler. So here's my idea: The `<var>` tag could be reintroduced, with `<var ...></var>` compiling to an IIFE as before. However, self-closing `<var ... />` tags would now be *template*-scoped.

Example:
```html
<if(input.foo)>
  <var foo=input.foo /><!-- hoisted -->
  <var bar=input.bar><!-- scoped -->
    $ console.log(foo, bar);
  </var>
  <var foo=null /><!-- hoisted -->
</if>
$ console.log(foo); // input.foo ? null : undefined
$ console.log(bar); // ReferenceError
```
```js
var foo;
if (input.foo) {
  foo = input.foo;
  (function(){
    var bar = input.bar;
    console.log(foo, bar);
  })();
  foo = null;
}
console.log(foo); // input.foo ? null : undefined
console.log(bar); // ReferenceError
```

A name other than `<var>` could be used for backward-compatibility, but `v4` has already shipped without it, and I feel it would be fairly easy to explain that "`<var ... />` is now template-scoped".

**Comment by DylanPiercey** [comment]
@mlrawlings @austinkelleher @patrick-steele-idem

What if we simply wrap all tag creations in a block `{}` and users can use `$ const` and `$ let` to achieve this effect?

**Comment by mlrawlings** [comment]
@DylanPiercey I think using the block scoped `let` and `const` is the right thing to do.  In most cases you can think of each tag as a block.  As long as you don't shadow existing variables (which many people consider a bad practice anyway), this is fine.  Perhaps we can enforce this in the future.
