### ISSUE TITLE
Components no longer automatically add `index.marko` as a client-side dependency.

### ISSUE THREAD

**Issue by Hesulan** [marko-js/marko#598]
In `rc.17` and earlier, Marko would automatically add a widget's `index.marko` to the internal dependency array if needed. As of `rc.20`, the `<class { ... } />` tag adds the `index.marko` to the dependency list as expected, but if a `component.js` or `component-browser.js` is used instead then it will add that to the dependencies, but *not* the corresponding `index.marko`.

**Comment by mlrawlings** [comment]
@Hesulan Thanks for reporting! `marko@4.0.0-rc.21` has been published with the fix

**Comment by Hesulan** [comment]
@mlrawlings Looks like a `console.log` slipped through, and it's not marked as `latest-beta`. But other than that it works! :)
