### ISSUE TITLE
Avoid writing compiled template to disk on render

### ISSUE THREAD

**Issue by tunderdomb** [marko-js/marko#6]
I really like the idea of html templating, but I discovered an issue when I tried to use it in my usual dev flow.

As I understand: 
now the require-able templates are made possible through a temp file

```
fs.writeFileSync(tempFile, compiledSrc, {encoding: 'utf8'});
fs.renameSync(tempFile, targetFile);
return require(targetFile);
```

and although you can bust template cache with `unload(templatePath)`, this doesn't clear node's module cache. So every time you `require(targetFile)` it will return the same compiled template regardless your meddling with marko's cache. 
It's possible to clear node's cache with `delete require.cache["absolutePath"]` though, but manually it would be tedious to track every unneeded compiled template.

The problem this makes is during development when a file changes, I want to clear the cache so the engine can re-render the template, or refresh the browser for instance. 

I think writing the compiled template to disk should be a feature, or an option, rather than a byproduct of rendering. 

Is there a way not to write the compiled template directly to disk, but rather keep it only in memory?
I think it would be useful in development.

Thanks in advance!

**Comment by Solido** [comment]
Have to said that I'm really interested in this issue but I can't get it to work.

My workflow

adding this to the top of app.js

```javascript
var marko = require("marko")
require('marko/browser-refresh').enable()
require('marko/hot-reload').enable()

require('fs').watch('web/marko', function (event, filename) {
  if (/\.marko$/.test(filename)) {
    require('marko/hot-reload').handleFileModified(filename);
  }
});
```
At this point starting my app with iojs app.js doesn't serve the template anymore and got TypeError: Cannot read property 'pipe' of undefined, 

Then I npm install browser-refresh and browser-refresh-taglib and add <browser-refresh enabled="true" /> to my layout

```javascript
var server = app.listen(3000, function() {
    var host = server.address().address
    var port = server.address().port

    console.log('App listening at http://%s:%s', host, port)

    if (process.send) {
      process.send('online');
      console.log('Sending online message')
    }

})
```
Inside the listen of app.

Finally launching the command with browser-refresh 

```
[browser-refresh] App started (pid: 7888)
[browser-refresh] Waited 1500ms without receiving "online" from child process. Page refresh triggered over WebSockets co
nnection.
App listening at http://:::3000
Sending online message
[browser-refresh] Server is ready. Page refresh triggered over WebSockets connection.
::1
TypeError: Cannot read property 'pipe' of undefined
    at E:\JS.Next\app.js:71:27
    at Layer.handle [as handle_request] (E:\JS.Next\node_modules\express\lib\router\layer.js:82:5)
    at next (E:\JS.Next\node_modules\express\lib\router\route.js:110:13)
    at Route.dispatch (E:\JS.Next\node_modules\express\lib\router\route.js:91:3)
    at Layer.handle [as handle_request] (E:\JS.Next\node_modules\express\lib\router\layer.js:82:5)
    at E:\JS.Next\node_modules\express\lib\router\index.js:267:22
    at Function.proto.process_params (E:\JS.Next\node_modules\express\lib\router\index.js:321:12)
    at next (E:\JS.Next\node_modules\express\lib\router\index.js:261:10)
    at E:\JS.Next\node_modules\express-stormpath\lib\stormpath.js:171:7
    at E:\JS.Next\node_modules\express-stormpath\node_modules\async\lib\async.js:254:17
```
Also require('marko/browser-refresh').enable() is already calling hotreload.

I'm not sure where I miss the point in the setup !

**Comment by patrick-steele-idem** [comment]
I'll try to reproduce and get back to you.

On a related note, I recommend doing the following:

```javascript
var formulaTemplate = marko.load(require.resolve('./web/marko/formula.marko'))
app.get('/formula', function(req, res) {
  formulaTemplate.render({}, res)
})
```

The `stream()` method will unnecessarily produce an intermediate stream when it is more efficient to write to the existing `res` stream.

**Comment by patrick-steele-idem** [comment]
@Solido, I was not able to reproduce even after installing io.js (v1.0.2). What version of express and marko are you using. Do you have a simplified project that I could try?

**Comment by Solido** [comment]
It's a whole new project all packages are up to date on Windows.
Replacing pipe() solved the problem !
Thx Patrick

**Comment by Solido** [comment]
Hi Patrick, here's another beginner question,

I have a fragment that render properly when directly called.

For testing purpose I only use this code :

Hello ${data.name}!

<ul if="notEmpty(data.colors)">
  <li style="color: $color" for="color in data.colors">
    $color
  </li>
</ul>
<div else>
  No colors!
</div>


This fragment is then included in the main layout but when I render a page
that extend the layout the
$data fields are no more presents and the resulting html is different from
a direct call. How is that possible ?



2015-01-19 18:17 GMT+01:00 Patrick Steele-Idem <notifications@github.com>:

> @Solido <https://github.com/Solido>, I was not able to reproduce even
> after installing io.js (v1.0.2). What version of express and marko are you
> using. Do you have a simplified project that I could try?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/raptorjs/marko/issues/6#issuecomment-70528951>.
>



-- 
Robbie

**Comment by patrick-steele-idem** [comment]
Hi @Solido, I'll try to answer your question below, but I recommend joining the Marko Gitter chat room for more realtime help: https://gitter.im/raptorjs/marko

Gitter provides great desktop and mobile apps. Definitely recommend checking it out.

<hr>

With Marko you must explicitly pass along any required data to the other templates. Each template gets its own `data` variable.

You didn't share all of your code, but if you are using the `<layout-use>` tag then you can just pass along any data to the target template by doing something similar to the following:

```html
<use-layout template="path/to/some/layout.marko" some-data="foo">
  <!-- ... -->
</use-layout>
```

The target layout template can then access the data as shown below:

_path/to/some/layout.marko:_

```html
<div>
  $data.someData
</div>
```

Output:

```html
<div>foo</div>
```

There's also a feature to support "global" data that is automatically made available to all templates. This feature is supported, but it needs to be documented. The usage is shown below:

```javascript
var template = require('marko').load('template.marko');
template.render({
    $global: {  // $global is special
      someData: 'foo'
    }
  }
```

You can then access that data in any of your templates using `out.global`:

```html
<div>
  $out.global.someData
</div>
```
