### ISSUE TITLE
[Question] Await chain like promise chain

### ISSUE THREAD

**Issue by mauricionr** [marko-js/marko#600]
I got an situation here.

My team is using `await` in a page that we need to handle more then one Promise
They tried to use something like this

```HTML
<await(data from firstProvider)>
    <await(complementData from secondProvider)>
    </await>
</await>
```

They said to me they got some errors with nested `await` and i was thinking in two solutions for this scenario

I was thinking about wrap the Promises in an especifc provider and use `Promise.all(requests)`

or create a custom tag like this one `<await-all(data from [Promise1, Promise2, ....])</await-all>`

What is the best solution to implement something like this?

What do you think about it??

Thanks and i'm in love with marko :rocket:

**Comment by mlrawlings** [comment]
You should be able to nest `<await>` tags, but if you can run them in parallel, that's better to do anyway.  I believe `Promise.all` is your best bet.

**Comment by mauricionr** [comment]
```HTML
<var watcher=Promise.all([firstProvider(), secondProvider()] />
<await(response from watcher) ></await>
```

i will test this!

**Comment by mauricionr** [comment]
Here's my demo/test about this issue

https://github.com/mauricionr/marko-demo

```HTML
<var watchers=Promise.all([data.promise1, data.promise2]) />
```

the service 

```javascript
module.exports = () => {
    return new Promise((resolve, reject) => {
        request.get(config.categories, (error, response, body) => {
            setTimeout(() => {
                resolve(JSON.parse(body));
            }, 5000)
        })
    })
}
```
the controller

```javascript
module.exports = (req, res) => {
    template.render({
       name:'Mauricio Nunes dos reis',
       colors:['red', 'green', 'blue'],
       promise1:categorieService(),
       promise2:categorieService()
   }, res)
}
```

the view

```HTML
<!DOCTYPE html>
<html>
    <head>
        <meta charset="UTF-8">
        <title>Marko Demo</title>
    </head>
    <body>
        <h1>Marko Demo</h1>
        <h2>${data.name}</h2>
        <section>
            <ul>
                <li for(color in data.colors)>${color}</li>
            </ul>
        </section>
        <var watchers=Promise.all([data.promise1, data.promise2]) />
        <await(response from watchers) client-reorder=true>
            <await-placeholder>
                Loading data...
            </await-placeholder>
            <await-error>
                An error occurred!
            </await-error>
            <await-timeout>
                A timeout occurred!
            </await-timeout>

            <h3>Promise1</h3>
            <section>
                <ul>
                    <li for(cat in response[0])>${cat.name}</li>
                </ul>
            </section>
            <h3>Promise2</h3>
            <section>
                <ul>
                    <li for(cat2 in response[0])>${cat2.name}</li>
                </ul>
            </section>
        </await>
        <await-reorderer/>
    </body>
</html>
```

Works well :rocket: 

But i could not see the *Loading data* and i'm using the tag `await-placeholder`

Since i'm using `json-server` to fake and json api, i put an timeout to looks like the real world and could not see the loading.

Any guess?

**Comment by StarpTech** [comment]
Correct If iam wrong but you can only see it If you enable `client-reorder` for the await tag.

**Comment by mlrawlings** [comment]
@mauricionr Are you rendering this client-side or server-side?

**Comment by mauricionr** [comment]
@mlrawlings yes, but you can double check if really is server-side rendering here's the [demo](https://github.com/mauricionr/marko-demo)
