### ISSUE TITLE
[v4] expose component instance as a variable in the marko template

### ISSUE THREAD

**Issue by patrick-steele-idem** [marko-js/marko#601]
With Marko v4, we now create an instance of the UI component when rendering a UI component, but the UI component instance is not publicly exposed so it is not possible to call instance methods in the marko template code. This proposal introduces a new `component` variable that can be used to reference the UI component instance as shown below:

```jsx
class {
    getFullName() {
        return this.input.firstName + ' ' + this.input.lastName;
    }
}

<div>
    Hello ${component.getFullName()}!
</div>
```

Thoughts? Concerns?

👍  or 👎  ?

/cc @mlrawlings @austinkelleher @philidem @mindeavor @ramses0

**Comment by ramses0** [comment]
Biggest reason for this is parity with `onClick` which has access to the full data/state/input context.

index.marko-current
```
<div onClick('handleFoo')>click</div>
```

component.js:
```
module.exports = {
   handleFoo( e ) {
     alert( this.getFullName() );
   }
   getFullName() {
     return input.firstName + " " + input.lastName
   }
}
```

Compare the `-current` and `-proposed` convenience, debuggability, consistency, etc.

For some (many?) functions, eventually those component functions may move to a more structured project lib, but during initial development, having all functions available in `this.*` and `component.*` is extremely convenient.

index.marko-proposed
```
<div onClick('handleFoo')>${ component.getFullName() }</div>
$ console.log( component.getFullName() )
```

index.marko-current
```
import helper from './helper'
<div onClick('handleClick')>${ helper.getFullName( input, state ) }</div>
$ console.log( helper.getFullName( input, state ) )
```

component.js-current
```
import helper from './helper'
module.exports = {
   handleClick() {
     alert( helper.getFullName( input, state ) );
   }
}
```

**Comment by patrick-steele-idem** [comment]
Just to be clear @ramses0, you are in favor of this proposal as-is, correct?

**Comment by ramses0** [comment]
Yep... just pointing out why it's an improvement over the current options / alternatives.

`${ component.getFullName() }` would make me very happy. :-)

**Comment by mindeavor** [comment]
I think it makes sense to have as an option, and see no harm in adding it.

**Comment by austinkelleher** [comment]
I like this proposal too.

**Comment by patrick-steele-idem** [comment]
Thanks for the feedback. I will work on implementing this.
