### ISSUE TITLE
[v4] Add "use strict" to the top of all compiled templates

### ISSUE THREAD

**Issue by patrick-steele-idem** [marko-js/marko#602]
We want all compiled Marko templates to be loaded in strict mode to catch problems early. As an example, Marko uses `Object.freeze()` on the state object to prevent new properties from being added that won't be watched. Without strict mode adding properties will silently fail.

**Comment by mauricionr** [comment]
I have a question.

What about the templates that have `Class` like in marko widget?

Since The bodies of class declarations and class expressions are executed in strict mode.

Thanks!

reference:

https://developer.mozilla.org/en/docs/Web/JavaScript/Reference/Classes

**Comment by patrick-steele-idem** [comment]
Marko automatically transpiles the `class` syntax into an object declaration so that the compiled template will be ES5 compatible (assuming you aren't using other ES6 syntax). It produces something like the following:

_index.marko_

```jsx
class {
    foo() {

    }
    bar() {

    }
}

<div>
</div>
```

Compiled output:

```js
"use strict";
// ...
var marko_component = {
        foo: function() {},
        bar: function() {}
      }
// ...
```

**Comment by mauricionr** [comment]
Got it @patrick-steele-idem thanks!
