### ISSUE TITLE
[Question] Indentation in included files

### ISSUE THREAD

**Issue by fabien-lg** [marko-js/marko#603]
Hello,

I am using Marko (great tool by the way!) to generate XML.
I have a «root» .marko file and a few included files. I would like to keep the indentation in the rendered file for various reasons.

However, when I indent the xml tags in the included file, I have this error:
` Line has extra indentation at the beginning`

The root .marko file looks like this:
```
<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<myxml>
    <include("./myxml-include.marko", data)/>
</myxml>
```

And the included file (note the indentation):
```
    <SubObject>
        <Value>primary</Value>
    </SubObject>
```
Is there a way to remove this formatting rule?

Thanks!

**Comment by patrick-steele-idem** [comment]
Hey Fabien, sorry for the slow response. You can do the following to break out of concise syntax mode:

```
---
    <SubObject>
        <Value>primary</Value>
    </SubObject>
---
```

Does that work for you?

**Comment by fabien-lg** [comment]
Thanks, it's working!
