### ISSUE TITLE
Typo in error when parsing component class

### ISSUE THREAD

**Issue by edwarddamato** [marko-js/marko#605]
### Context
When a component `class` has a parsing issue, the exception thrown has a typo. Additionally, `Error:` is appended to the message twice.

### Expected Behavior
The error should read: `Unable to parse JavaScript for **component** class.`

### Actual Behavior
The error output is: `Unable to parse JavaScript for componnet class. Error: Error:`

### Possible Fix
Fix typo and remove `Error:`.

**Comment by edwarddamato** [comment]
Can tackle this issue if needed.

**Comment by austinkelleher** [comment]
A new version should be published later today. Thanks!
