### ISSUE TITLE
Bug: component IDs are not being assigned correctly when intermediate non-component is rendered

### ISSUE THREAD

**Issue by jasonmacdonald** [marko-js/marko#611]
I'm asking because I seem to constantly run into issues with child elements either getting the same ID as their parent, or a parent and then child, parent and than child, all being apart of the same array group which completes breaks render after an event.

I wish I had a simple example to show, but I always seem to run into this once I have a good number of components embedding components, and I can't quick figure out what is causing it.

As a quick sudo example, I have a list, which renders a card component for each item in the list, that card embeds an image widget. First render, everything works, but if anything happens that causes a rerender, images in the first row of cards disappear, then the second row on next, on and on. 

it looks like this in a template (but separate files)

```HTML
<list>
    <card>... <image />  </card>
</list>
````
NOTE: Each component listed above is in it's own file, just showing it all together for clarity

And I end up with something like
```HTML
<div class='list' id="1">
   <div class='card' id='1[0]'>
        <img id='1[1]'/>
   </div>
 <div class='card' id='1[2]'>
        <img id='1[3]'/>
   </div>
</div>
```
 I would expect I'm supposed to be getting images that have an id like 1[0][0] and 1[1][0]. But instead it seems to group parent and children in the same ID group, despite them being completely separate components with their own state. It seems whenever these ID's get mixed up, rendering updates starts doing very weird things.

I hope this makes sense. Here is a link to a pastebin of the output form my application where this is happening, incase that helps. http://pastebin.com/6T9mpVjY In the paste the figure tag is what is rendered by my image component

**Comment by jasonmacdonald** [comment]
Well, it seems all I have to do is make a post and I figure out what is causing it. It seems you can't use a self closing tag. If I use <component /> I get all the ID problems. If I use <component ></component > The images get the child ID's I would expect.

Is this a bug??

**Comment by patrick-steele-idem** [comment]
That would not be expected. Can you share a smaller example that I can use to reproduce?

**Comment by jasonmacdonald** [comment]
Well, I thought that was it, but I think it was a false positive. Still getting the same issue of parent and child components getting put into the same ID group. Trying to boil it down to a simple example.

**Comment by jasonmacdonald** [comment]
Ok, here is the simplest example I could put together.

index.html
```HTML
class {
    constructor(){
        this.state = {change:true}
    }
    doSomething(){
        this.state.change = !this.state.change
        console.log('state: ', this.state.change);
    }
}
<div>
    <my-list list=[1,2,3,4,5,6] >
        <card onClicked('doSomething') ></card>
    </my-list>
</div>
```

my-list/index.html
```HTML
<div>
    <for (item in input.list)>
        <include(data.renderBody) />
    </for>
</div>
```

card/index.html
```html
class {}
<div style="border: 1px solid black">
    <my-image />
    <br/>
    <button onClick('emit', 'clicked', true)>Click Me</button>
</div>
```

image/index.html
```HTML
class {}
<img src="http://placehold.it/300x200/" />
```


This is a contrived example, but if you run this in a browser (compiled) and click the button in a card, you'll see it pulls the image out of the parent, and sticks it as a sibling to the parent because of the ID's. If I remove the class{} definition from image, it doesn't assign an ID and works "sorta" properly, except that image is no longer a component.

**Comment by patrick-steele-idem** [comment]
Thanks for the code. I'll see if I can reproduce the issue as part of our test suite.

**Comment by jasonmacdonald** [comment]
Thanks, Patrick.  The other interesting thing is it doesn't pull them out all at once, but rather one at a time with each click. Each time it re-renders index, it pulls the next ID that's still a child out, then leaves the rest.

**Comment by patrick-steele-idem** [comment]
I'll keep investigating, but you can always assign your own IDs by providing a `key` attribute and that might alleviate some of the problems you are seeing. If there is a bug we definitely want to fix it though.

**Comment by patrick-steele-idem** [comment]
At first glance, I am not able to reproduce any issues. The IDs appear to be generated correctly and uniquely:

```html
<div id="s0">
    <div>
        <div style="border: 1px solid black" id="s0-0[0]"><img src="http://placehold.it/300x200/" id="s0-0[0]-c0"><br><button data-_onclick="emit s0-0[0] 0">Click Me</button></div>
        <div style="border: 1px solid black" id="s0-0[1]"><img src="http://placehold.it/300x200/" id="s0-0[1]-c0"><br><button data-_onclick="emit s0-0[1] 0">Click Me</button></div>
        <div style="border: 1px solid black" id="s0-0[2]"><img src="http://placehold.it/300x200/" id="s0-0[2]-c0"><br><button data-_onclick="emit s0-0[2] 0">Click Me</button></div>
        <div style="border: 1px solid black" id="s0-0[3]"><img src="http://placehold.it/300x200/" id="s0-0[3]-c0"><br><button data-_onclick="emit s0-0[3] 0">Click Me</button></div>
        <div style="border: 1px solid black" id="s0-0[4]"><img src="http://placehold.it/300x200/" id="s0-0[4]-c0"><br><button data-_onclick="emit s0-0[4] 0">Click Me</button></div>
        <div style="border: 1px solid black" id="s0-0[5]"><img src="http://placehold.it/300x200/" id="s0-0[5]-c0"><br><button data-_onclick="emit s0-0[5] 0">Click Me</button></div>
    </div>
</div>
```

Which version of `marko` are you using?

**Comment by jasonmacdonald** [comment]
Version 4.

**Comment by jasonmacdonald** [comment]
I'll try to put a full project up on Github. I just have to set-up a project with Webpack, etc. seperate from my current one.

But here is the output I get.

```html
<div id="b1">
    <div id="b1-0[0]">
        <div style="border: 1px solid black" id="b1-0[1]"><img src="http://placehold.it/300x200/" id="b1-0[2]"><br>
            <button>Click Me</button>
        </div>
        <div style="border: 1px solid black" id="b1-0[3]"><img src="http://placehold.it/300x200/" id="b1-0[4]"><br>
            <button>Click Me</button>
        </div>
        <div style="border: 1px solid black" id="b1-0[5]"><img src="http://placehold.it/300x200/" id="b1-0[6]"><br>
            <button>Click Me</button>
        </div>
        <div style="border: 1px solid black" id="b1-0[7]"><img src="http://placehold.it/300x200/" id="b1-0[8]"><br>
            <button>Click Me</button>
        </div>
        <div style="border: 1px solid black" id="b1-0[9]"><img src="http://placehold.it/300x200/" id="b1-0[10]"><br>
            <button>Click Me</button>
        </div>
        <div style="border: 1px solid black" id="b1-0[11]"><img src="http://placehold.it/300x200/" id="b1-0[12]"><br>
            <button>Click Me</button>
        </div>
    </div>
</div>

```

I don't know what could be causing the difference.

**Comment by jasonmacdonald** [comment]
Well, this might take me longer. I just tried to start a brand new project with a fresh set of npm installs and now it seems marko-loader doesn't work with webpack 2 under windows. File paths get stripped of slashes and webpack blows up with ` var e = new Error("Cannot find module \"C:UsersUserDesktopprojectsarchitecturemarko_test\testsrcindex.marko\""); `, so first I need to figure out what is going on there. /sigh

**Comment by jasonmacdonald** [comment]
Arrg, this makes no sense. Running Marko 4.0.0 and Marko-loader 1.2.0 works fine. Running 4.0.1 and Loader 1.2.0 works fine, Run 4.0.1 and Loader 1.3.0 and require paths break in Webpack. Yet when I look at the change set for both, they are only version number upgrades????

**Comment by jasonmacdonald** [comment]
Creating an issue over in Marko loader, 1.3.0 doesn't work on Windows. https://github.com/marko-js/marko-loader/issues/6

**Comment by jasonmacdonald** [comment]
Here's the example running: https://rawgit.com/jasonmacdonald/marko-test-webpack/master/index.html
And here's the test project that replicates it: https://github.com/jasonmacdonald/marko-test-webpack

Interesting note: If I use the extension ".marko", everything works fine. If I use ".html" though, I get the messed up ID's. So, it seems it has something to do with Marko parsing an HTML file differently than a Marko file?

**Comment by patrick-steele-idem** [comment]
Thanks for reporting the problem and creating the test project @jasonmacdonald ! Very helpful. The bug was that the component key being passed down to the nested component wasn't being cleared out so multiple components were receiving the same ID. Please let us know if you see any other issues.

The problem has been fixed. Please upgrade to `marko@4.1.0`
