### ISSUE TITLE
[V4] - destroyElRecursive is not a function when using result.replace after render

### ISSUE THREAD

**Issue by pcanella** [marko-js/marko#615]
### Context

I was working on a personal project and wanted to replace an existing rendered component with the newly rendered one using the following code:

```javascript
var $featured = document.querySelector('.featured_fish');
var featuredFish = require('../fh-featured-fish');

// featuredFish reference: 
//  https://gist.github.com/pcanella/da7eb300409034ed93c2ffe7525ed656

featuredFish.render(f).then(function(result){
        result.replace($featured);
});
```

Then, in console I get the following issue 

`Uncaught (in promise) TypeError: destroyElRecursive is not a function(…)beforeRemove @ bundle.js:3670replace @ bundle.js:3691(anonymous function) @ bundle.js:5274`

### Expected Behavior

Ideally, it should just replace the dom element, right?

### Actual Behavior

`Uncaught (in promise) TypeError: destroyElRecursive is not a function(…)beforeRemove @ bundle.js:3670replace @ bundle.js:3691(anonymous function) @ bundle.js:5274`

### Your Environment

* Version used: V4
* Environment name and version: Version 54.0.2840.71 (64-bit)
* Operating System and version (desktop or mobile): OS X on Chrome
* Link to your project: Not up yet, so I really don't have a repo at the moment...

### Stack Trace

`Uncaught (in promise) TypeError: destroyElRecursive is not a function(…)beforeRemove @ bundle.js:3670replace @ bundle.js:3691(anonymous function) @ bundle.js:5274`
</details>

**Comment by patrick-steele-idem** [comment]
Thanks for the bug report. I will try to reproduce

**Comment by patrick-steele-idem** [comment]
I am not able to reproduce the problem. Are you using Webpack? Might need to take a closer look to see what is wrong with your setup...

**Comment by pcanella** [comment]
@patrick-steele-idem ah! I am actually using browserify/markoify for this specific instance. This is my script I run before `app.js` runs

`"browserify -g markoify --extension='.marko' assets/js/main.js -o assets/js/bundle.js`

My "main.js" file just has some document level event binding (working on getting rid of that, but it doesn't really affect marko at all)

**Comment by mlrawlings** [comment]
@pcanella Is this still an issue for you?
