### ISSUE TITLE
Webpack integration tutorial not working

### ISSUE THREAD

**Issue by leili2017** [marko-js/marko#617]
## Bug Report
I started out following the webpack-marko integration tutorial on http://markojs.com/docs/webpack/
and got the error message "error in cannot find module 'marko/compiler' " even with webpack version 1.14.0.

### Context

![image](https://cloud.githubusercontent.com/assets/26175060/23806596/203176dc-0577-11e7-9360-70c1c5e68089.png)

### Possible Fix

<details><summary>Additional Info</summary>

### Your Environment

* Version used:
* Environment name and version (e.g. Chrome 39, node.js 5.4):
* Operating System and version (desktop or mobile):
* Link to your project:

### Steps to Reproduce

1. 
2. 
3. 
4. 

### Stack Trace

</details>

**Comment by jrop** [comment]
I think this is because `marko-loader` does not depend on the `marko` package.  If you install the marko package this should work:

```sh
npm install --save-dev marko
# or
yarn add --dev marko
```

**Comment by mlrawlings** [comment]
@leili2017 can you confirm that installing `marko` as @jrop suggested works?

**Comment by jrop** [comment]
To be clear, this is consistent behavior for any webpack `*-loader`: For example, when using the babel-loader, babel-core needs to be installed separately.

**Comment by wujjpp** [comment]
Try this , if you like [marko starter kit](https://github.com/wujjpp/marko-starter-kit)
