### ISSUE TITLE
[Question] how to increase default await timeout?

### ISSUE THREAD

**Issue by mauricionr** [marko-js/marko#621]
## Question

How to increase the default await time out?

### Context

i'm getting a lot's of timeout from await tag, i'm using marko `3.4.2`

How the best way to handle this?(Handle the error, notify user and try again)
Is possible increase the await-tag timeout for all await-tags?

### Actual Behavior
Async fragment failed. Exception: Error: Async fragment timed out after `10000ms` at Timeout._onTimeout (/var/app/current/node_modules/async-writer/src/AsyncStream.js:143:32) at tryOnTimeout (timers.js:224:11) at Timer.listOnTimeout (timers.js:198:5)

Async fragment failed (await-reorderer). Exception: Error: Async fragment failed. Exception: Error: Async fragment timed out after ` 10000ms` at Timeout._onTimeout (/var/app/current/node_modules/async-writer/src/AsyncStream.js:143:32) at tryOnTimeout (timers.js:224:11) at Timer.listOnTimeout (timers.js:198:5) at AsyncStream.error (/var/app/current/node_modules/async-writer/src/AsyncStream.js:365:13) at Timeout._onTimeout (/var/app/current/node_modules/async-writer/src/AsyncStream.js:143:26) at tryOnTimeout (timers.js:224:11) at Timer.listOnTimeout (timers.js:198:5)

Thanks

**Comment by Hesulan** [comment]
Use `<await(...) timeout=10000>`, where `10000` is the time in milliseconds, or `0` to disable the timeout entirely. It's currently not possible to change the default timeout for all await tags.

http://v3.markojs.com/docs/marko/async-taglib/

**Comment by mauricionr** [comment]
I would like to change the default timeout for all await-tag's

**Comment by Hesulan** [comment]
If anyone is interested in implementing this, here's where the default is currently hard-coded: https://github.com/marko-js/marko/blob/master/taglibs/async/await-tag.js#L149
