### ISSUE TITLE
how to print_r | dump a variable?

### ISSUE THREAD

**Issue by bonesoul** [marko-js/marko#622]
with nunjucks i can {{ var | dump }}, what is the equivalent for marko?

**Comment by seangates** [comment]
Maybe try: `<pre>${console.log(var)}</pre>`

**Comment by patrick-steele-idem** [comment]
I'm assuming you are using Marko v4 and if so the following works if you want to dump to the console output:

```
$ console.log('someVar:', someVar);
```

Or if you want to dump it to the browser as part of the HTML:

```
<pre>
  ${JSON.stringify(someVar)}
</pre>
```

`JSON.stringify` will only work if the object you want to dump doesn't have circular references. If that is the case, then you can use a Node.js builtin for dumping to a String:

```
import util from 'util';

<pre>
  ${util.inspect(someVar)}
</pre>
```

Hope that answers your question.

**Comment by patrick-steele-idem** [comment]
@seangates `console.log()` does not return a value so the `<pre>` tag will be empty, but the value will be written to the `console` at least :)

**Comment by seangates** [comment]
@patrick-steele-idem Yes, deleted my comment. ;-)
