### ISSUE TITLE
[Bug] Export Tag not in release but mentioned in documentation

### ISSUE THREAD

**Issue by jasonmacdonald** [marko-js/marko#627]
### Context
Documentation for 4.1.2 mentions [export tag](http://markojs.com/docs/core-tags/#codeampltexportgtcode )  but the tag does not appear to be in the current version. Looking in taglibs/core I do not see a taglib for export either.

### Expected Behavior
Using `export var route = '/about';` should export the value.

### Actual Behavior
Compiler throws an error `Unrecognized tag: export - More details: https://github.com/marko-js/marko/wiki/Error:-Unrecognized-Tag`

<details><summary>Additional Info</summary>

### Your Environment

* Version used: 4.1.2
* Node 6.10 + Webpack 2
* Windows

### Steps to Reproduce
1. Include export tag in template
2. Compile or run

### Stack Trace
`
ERROR in ./src/apps/demo/components/grid/index.html
Module build failed: Error: An error occurred while trying to compile template at path "\marko-comps\src\apps\demo\components\grid\index.html". Error(s) in template:
1) [src\apps\demo\components\grid\index.html:1:0] Unrecognized tag: export - More details: https://github.com/marko-js/marko/wiki/Error:-Unrecognized-Tag
    at handleErrors (...\marko-comps\node_modules\marko\compiler\Compiler.js:82:21)
    at Compiler.compile (...\marko-comps\node_modules\marko\compiler\Compiler.js:151:9)
    at _compile (...\marko-comps\node_modules\marko\compiler\index.js:89:33)
    at compile (...\marko-comps\node_modules\marko\compiler\index.js:103:12)
    at Object.compileForBrowser (...\marko-comps\node_modules\marko\compiler\index.js:114:12)
    at Object.module.exports (...\marko-comps\node_modules\marko-loader\src\index.js:10:38)
 @ ./src/apps/demo/component.js 16:13-52 27:39-78
 @ ./src/apps/demo/index.html
 @ ./index.js
 @ multi (webpack)-dev-server/client?http://localhost:8080 core-js/fn/promise ./index
`
</details>

**Comment by jasonmacdonald** [comment]
I also tried looking for any tests that reference "export", but I cannot find anything equivalent to the parseImport tests.

**Comment by jasonmacdonald** [comment]
It seems someone removed it from the Docs so I guess I'll close this. Too bad it's not actually in, would be a great feature.

**Comment by austinkelleher** [comment]
@jasonmacdonald The export tag is still a planned feature. We had received multiple questions about the fact that it was documented but not implemented, so I commented out the documentation until it is actually implemented.
