### ISSUE TITLE
Exporting a class from component-browser.js may have issues

### ISSUE THREAD

**Issue by patrick-steele-idem** [marko-js/marko#630]
From Gitter chat:

Eldar @Eldar-X Mar 24 10:47
@patrick-steele-idem in component-browser.js following not working

```js
module.exports = class {
    onCreate() {
        this.state = {
            count:0
        };
    }
    increment() {
        this.state.count++;
    }
}
```

But this is okay

```js
module.exports =  {
    onCreate() {
        this.state = {
            count:0
        };
    },
    increment() {
        this.state.count++;
    }
}
```

Error message:

```
TypeError: component.$__setCustomEvents is not a function
    at Function.ComponentDef.$__deserialize (https://localhost:3000/bundles/admin/news.js:3725:15)
    at https://localhost:3000/bundles/admin/news.js:3919:37
    at Array.forEach (native)
    at Object.initServerRendered [as concat] (https://localhost:3000/bundles/admin/news.js:3918:19)
    at https://localhost:3000/admin:2:99
    at https://localhost:3000/admin:2:275
```

**Comment by patrick-steele-idem** [comment]
I tested with the upcoming Marko v4.2.0 release and I am not able to reproduce.

@Eldar-X Can you provide more details on how to reproduce the problem you mentioned in Gitter? I'm closing the issue for now, but if it is still a problem please let me know.

**Comment by Eldar-X** [comment]
Looks like bug is fixed. I just reinstall all my modules and now everything work like expected

**Comment by ovidius72** [comment]
I'm getting this error: 

`Uncaught TypeError: component.$__setCustomEvents is not a function`

when using multi files structure for components and exporting as a class.  `module.exports = class {}.`
It works when a literal object is exported `module.exports = {}.`
 
marko version is  4.2.0
node: 6.10
