### ISSUE TITLE
Proposal: Allow explicitly imported UI components to be used as custom tags?

### ISSUE THREAD

**Issue by patrick-steele-idem** [marko-js/marko#632]
```marko
import Hello from './path/to/hello';

<Hello name="Frank"/>
```

In addition, we could also overload the `import` syntax to allow importing a UI component based on the tag name:

```marko
import Hello from <hello>;

<Hello name="Frank"/>
```

**Comment by mauricionr** [comment]
:+1:

**Comment by Hesulan** [comment]
Maybe something like `<taglib('./path/to/taglib') />` or `<marko-tag('./path/to/tag.marko') />`, to avoid overloading `import`?

**Comment by patrick-steele-idem** [comment]
@Hesulan you may be right. I'll throw out some other ideas:

```
import tag <hello> as Hello;
import tag <hello>; // if no "as" is specified then default to title case
```

**Comment by mindeavor** [comment]
What's the use case for this? Auto-detection has worked pretty well for me so far (that doesn't make me opposed to this though).

**Comment by ianvonholt** [comment]
I agree with @mindeavor that auto-detection has worked extremely well. 

Are you proposing this change instead of defining a `tags-dir` withn a `marko.json`?

**Comment by patrick-steele-idem** [comment]
Explicit importing of UI components for use as custom tags is not something we want to support. We are going to stick with implicit importing with `<include()>` being the best option for including dynamic components.
