### ISSUE TITLE
vdom issue ( I'm not sure if it is a BUG, but the vue's behavior is we wanted.)

### ISSUE THREAD

**Issue by wujjpp** [marko-js/marko#635]
## Bug Report
NOTE: I'm not sure if it is a BUG, but the vue's behavior is we wanted.

### Code

___/routes/index/index.marko___
```
<html>
  <head>
    <title>Welcome | Marko Demo</title>    
    <script src="https://unpkg.com/jquery"/>
    <script src="https://unpkg.com/easy-pie-chart/dist/jquery.easypiechart.min.js"/>
  </head>
  <body>
    <app-main/>
  </body>
</html>
```

___/routes/index/components/app-main/index.marko___
```
style {
  .chart {
    position: relative;
    display: inline-block;
    width: 110px;
    height: 110px;
    margin-top: 50px;
    margin-bottom: 50px;
    text-align: center;
  }
  .chart canvas {
    position: absolute;
    top: 0;
    left: 0;
  }
  .percent {
    display: inline-block;
    line-height: 110px;
    z-index: 2;
  }

  .percent:after {
    content: '%';
    margin-left: 0.1em;
    font-size: .8em;
  }
}

class {
    constructor() {
        this.state = { count:0 };
    }
    onMount(){
      $('.chart').easyPieChart({
        easing: 'easeOutBounce',
        onStep: function(from, to, percent) {
          $(this.el).find('.percent').text(Math.round(percent))
        }
      })
      this.chart = $('.chart').data('easyPieChart')
      this.chart.update(Math.round(Math.random() * 200 - 100))
    }

    inc() {
        this.state.count++
    }
    dec(){
      this.state.count--
    }

    updateChart(){
      this.chart.update(Math.round(Math.random() * 200 - 100))
    }
}
<div id="app">
  <div>
    <span>Count: ${state.count}</span>
    <button onClick("inc")>inc</button>
    <button onClick("dec")>dec</button>
    <span>--> Click the "+" or "-" button, will cause canvas(generated by easy pie chart plugin) be removed, vue doesn't has this issue</span>
  </div>
  <div>
    <span class="chart">
      <span class="percent"/>
    </span>
    <button onClick("updateChart")>Update chart</button>
  </div>
</div>

```
### Steps
After page loaded, the easyPieChart create a canvas inside `<span class="chart"><canvas ..... /></span>`, if you click `Update chart` button, the chart will be refreshed, all things goes well, but if you click `inc` or `dec` button, the canvas disappeared.  actually, we want canvas keep in document.

Vue has the right behavior(we wanted), I have created the same [demo app of vue version](https://jsfiddle.net/wujjpp/or132f6L/) 

Also, I have uploaded the [marko version of  demo app](https://github.com/wujjpp/marko-vdom-issue.git)

**Comment by mindeavor** [comment]
Try adding `no-update` to the chart div:

    <div class="chart" no-update />

**Comment by wujjpp** [comment]
@mindeavor Thanks for your reply, and fixed issue in this case.  but it cause `<span class="percent">${Math.round(state.percent)}</span>`  no longer to be updated.
Although, we can create special DOM structure to avoid the issue, but it make DOM structure more complex. Anyway, Thanks for your solution again.

___template.marko___
```
<div class="col-md-12">     
      <span class="chart" no-update>
        <span class="percent">${Math.round(state.percent)}</span>      
      </span>
      <span class="btn btn-default" onClick('updateChart')>Update chart</span>
</div>
```
___component.js___
```
export default class Test {
  onMount() {   
    $('.chart').easyPieChart({
      easing: 'easeOutBounce',
      onStep: function(from, to, percent) {
        //$(this.el).find('.percent').text(Math.round(percent))
      }
    })
    this.chart = $('.chart').data('easyPieChart');
    this.chart.update(this.state.percent)
  }
  updateChart() {   
    this.state.percent = Math.random() * 200 - 100
    this.chart.update(this.state.percent)
  }
```

**Comment by mindeavor** [comment]
The reason it was happening in the first place was because marko's vdom logic was causing your `chart` div to revert back to what you've written in the template.

If you still want to make use of `state.percent` (and thus marko's vdom), then this structure might work better for you:

```marko
<div class="col-md-12">     
      <span class="chart-wrapper">
        <span class="chart" no-update></span>
        <span class="percent">${Math.round(state.percent)}</span>      
      </span>
      <span class="btn btn-default" onClick('updateChart')>Update chart</span>
</div>
```

**Comment by wujjpp** [comment]
@mindeavor Correct, create special DOM structure for handling.

**Comment by wujjpp** [comment]
@mindeavor Another question: what's "input" and "state" used for? and what's the difference between them? like "props" and "state" in react?

**Comment by mindeavor** [comment]
> like "props" and "state" in react?

Yes, that's correct.

**Comment by wujjpp** [comment]
@mindeavor Thanks
