### ISSUE TITLE
component's instance are created out of normal way?

### ISSUE THREAD

**Issue by wujjpp** [marko-js/marko#638]
### Expected
I try to build Mixin  mechanism for enhancing marko component， unfortunately, it seems component instance was created out of normal way. 

### Code

[___mixins.js : L5 - L13___](https://github.com/wujjpp/marko-starter-kit/blob/master/src/core/mixins/mixins.js#L5-L13)

```
export default (...mixins) => {
  class MixedComponent {}
  for (let mixin of mixins) {
    for (let name of Object.keys(mixin)) {
      MixedComponent.prototype[name] = mixin[name]
    }
  }
  return MixedComponent
}
```

[___history-mixin.js : L1 - L6___](https://github.com/wujjpp/marko-starter-kit/blob/master/src/core/mixins/history-mixin.js#L1-L6)
```
export default {
  funcInMixin() {
    console.log('funcInMixin called')
  }
}
```

[___component.js : L5 - L23___](https://github.com/wujjpp/marko-starter-kit/blob/master/src/routes/mixin/components/app-main/component.js#L5-L23)
```
import {
  Mixins,
  HistoryMixin
} from '../../../../core/mixins'

var MixedBaseClass = Mixins(HistoryMixin)

class Bar extends MixedBaseClass {}

export default class MyClass extends MixedBaseClass {
  foo() {
    //the following 2 lines codes are working as expected.
    var bar = new Bar()
    bar.funcInMixin() //print 'funcInMixin called' in console

    // In fact,we want component instance has mixed function `funcInMixin`
    // Unfortunately `this.funcInMixin` is undefined, it caused unhandled exception
    this.funcInMixin()
  }
}
```

**Comment by patrick-steele-idem** [comment]
We need to make this more clear in the docs, but `extends` can not be used with component classes. The reason for this is that marko internally makes every UI component inherit from an internal `Component` class and you can't have multiple base classes. If you really want to do mixins then the following will work:

```js
class Component {
  foo() {
    //the following 2 lines codes are working as expected.
    var bar = new Bar()
    bar.funcInMixin() //print 'funcInMixin called' in console

    // In fact,we want component instance has mixed function `funcInMixin`
    // Unfortunately `this.funcInMixin` is undefined, it caused unhandled exception
    this.funcInMixin()
  }
}

var mixins = {
    funcInMixin() {
        // ...
    }
};

Object.assign(Component.prototype, mixins);

export default Component;
```

Does that work for you? I'm closing the issue, but please feel free to add more comments here if you still have concerns or questions.

**Comment by wujjpp** [comment]
@patrick-steele-idem Thanks for your help, it works. it looks like HOC

___foo-mixin.js___
```
export default {
  foo() {
    console.log('function called in foo mixin')
  }
}
```

___bar-mixin.js___
```
export default {
  bar() {
    console.log('function called in bar mixin')
  }
}
```
___mixins.js___
```
export default (...mixins) => (component) => {
  for (let mixin of mixins) {
    Object.assign(component.prototype, mixin)
  }
  return component
}
```
___component.js___
```
import {
  Mixins,
  FooMixin,
  BarMixin
} from '../../../../core/mixins'

class MyComponent {
  callFunc() {
    this.bar()
    this.foo()
  }
}

export default Mixins(FooMixin, BarMixin)(MyComponent)
```
