### ISSUE TITLE
"Search results" link on home page causes console error

### ISSUE THREAD

**Issue by codingthat** [marko-js/marko#639]
### Context

At markojs.com, clicking the tab next to "Color picker" gives a js error.

### Expected Behavior

Switch tabs.

### Actual Behavior

Error.

### Possible Fix

I'm totally new here.

<details><summary>Additional Info</summary>

### Your Environment

* Version used: n/a
* Environment name and version (e.g. Chrome 39, node.js 5.4): Chromium Version 56.0.2924.76 Built on Ubuntu , running on LinuxMint 18.1 (64-bit)
* Operating System and version (desktop or mobile): ibid
* Link to your project: n/a

### Steps to Reproduce
1. load markojs.com
2. open error console (clean at this point)
3. click said link

### Stack Trace

```
Uncaught Error: Not allowed
    at h.beginAsync (index-83c75fc1.js:63)
    at c.exports (index-83c75fc1.js:110)
    at index-83c75fc1.js:111
    at b.f (index-83c75fc1.js:71)
    at h._ (index-83c75fc1.js:111)
    at index-83c75fc1.js:112
    at b.f (index-83c75fc1.js:71)
    at g._.l.r.type (index-83c75fc1.js:112)
    at index-83c75fc1.js:55
    at index-83c75fc1.js:47
beginAsync @ index-83c75fc1.js:63
c.exports @ index-83c75fc1.js:110
(anonymous) @ index-83c75fc1.js:111
b.f @ index-83c75fc1.js:71
h._ @ index-83c75fc1.js:111
(anonymous) @ index-83c75fc1.js:112
b.f @ index-83c75fc1.js:71
g._.l.r.type @ index-83c75fc1.js:112
(anonymous) @ index-83c75fc1.js:55
(anonymous) @ index-83c75fc1.js:47
b._t @ index-83c75fc1.js:41
_S @ index-83c75fc1.js:47
update @ index-83c75fc1.js:47
h @ index-83c75fc1.js:41
f @ index-83c75fc1.js:41
(anonymous) @ index-83c75fc1.js:41
```

</details>

**Comment by patrick-steele-idem** [comment]
Thanks for reporting the problem with the website. We're investigating

**Comment by patrick-steele-idem** [comment]
This has been fixed. Thanks for reporting the problem!
