### ISSUE TITLE
Marko for mobile?

### ISSUE THREAD

**Issue by selforganized** [marko-js/marko#645]
Hi. Just read about Marko recently. Can Marko be used for mobile app development - does it have anything similar to React Native or Ionic?

**Comment by mauricionr** [comment]
I'm using marko for a progressive web app, so i guess marko can do it

marko <3

**Comment by selforganized** [comment]
Marko,

Can you talk a bit about how you do it? Do you use any other libraries/frameworks? Thanks.

**Comment by sebastianmacias** [comment]
@mauricionr if you have the time, a write up or a github starter repo would be really appreciated. 

Grouping efforts towards building something like https://github.com/nuxt/nuxt.js for marko would be great, I'm willing to contribute, however it seems like there are still a few missing pieces to the puzzle such as client side routing. So an example of a barebones PWA with client side routing and offline capabilities would make a good starting point.

**Comment by mauricionr** [comment]
I'm using the pwa [checklist](https://developers.google.com/web/progressive-web-apps/checklist) from google and the [sw-toolbox](https://github.com/GoogleChrome/sw-toolbox), and i'm not using client side routing.

@sebastianmacias @selforganized i will put the example in my repo :rocket:

**Comment by austinkelleher** [comment]
Marko does not currently have a framework with native bindings like React Native, but you can certainly create a static build of your app and use Phonegap etc.

Check out: [marko-phonegap](https://github.com/marko-js-samples/marko-phonegap)

**Comment by mauricionr** [comment]
@sebastianmacias @selforganized 

I started implement service worker in my demo at [PWA Road Show São Paulo](https://events.withgoogle.com/pwa-roadshow-latin-america/#content)

checkout of my [demo repo](https://github.com/mauricionr/marko-pwa) and [live demo](https://lit-headland-75537.herokuapp.com/)

![image](https://cloud.githubusercontent.com/assets/2263551/24765410/0d67703a-1ace-11e7-86b6-3b96f0693b65.png)


Hope this can help with PWA :rocket:

**Comment by patrick-steele-idem** [comment]
Another developer built a mobile app using Marko + [Framework7](https://framework7.io/): https://twitter.com/rtalwar26/status/847702923198963716

I haven't used Framework 7 myself but it looks promising. I installed the [ConfEngine](https://itunes.apple.com/in/app/confengine/id1010574267?mt=8) app built using Marko and Framework7 and looks very nice on my iPhone.

**Comment by sebastianmacias** [comment]
@mauricionr thanks! will be checking it out later this week

**Comment by mauricionr** [comment]
I will get some free time to improve them :)

**Comment by anupdineout** [comment]
Bro , I need Click side Routing mechanism for MarkoJS + Marko Widgets with SEO things .Please suggest me regarding

**Comment by patrick-steele-idem** [comment]
Doing some fall cleaning and closing this issue. Our focus is on building web applications and that includes desktop web applications and mobile applications. There are no plans to support native at this time. There are a variety of frameworks available for creating hybrid mobile apps that work with Marko:
- https://github.com/marko-js-samples/marko-f7
- https://github.com/marko-js-samples/marko-phonegap
