### ISSUE TITLE
Globals in server-rendered components

### ISSUE THREAD

**Issue by rubennorte** [marko-js/marko#646]
I'm testing Marko for server-side and client-side rendering and I've been looking for a way to define the global variables (`out.global`) when bootstrapping client-side components. Is it possible?

At the moment I'm just seeing that `input` and `state` are passed from backend to client, but global variables are left blank in the page (and I rather use specific globals in the client).

Sample code (using intentionally bad practices):

server:
```
<h1>${out.global.title}</h1>

...

template.stream({
  $global: {
    title: 'Foo'
  }
});
```

client:
```
import component from '...';
import markoComponents from 'marko/components';
markoComponents.init();

// How can I define $global?
```

Thanks for the hard work. It's amazing how simple it is to have universal components with Marko.

**Comment by patrick-steele-idem** [comment]
> It's amazing how simple it is to have universal components with Marko.

Thanks for the feedback!

Currently, the best option is to use a UI component to transfer the global variables to a shared module. Something like the following:

```marko
import myStore = from './path/to/my-store';

class {
    onInput(input, out) {
        this.someImportantData = out.global.someImportantData;
    }

    onMount() {
        myStore.setSomeImportantData(this.someImportantData);
    }
}

<div.top-level-ui-component>
</div>
```

Any other UI component or JavaScript module can do something similar to the following:

```marko
import myStore from './path/to/my-store';

$ var someImportantData = myStore.getSomeImportantData();
```

I'm thinking there might be value in some how marking certain globals as being serializable to the browser so that they will automatically show up in `out.global` on both the server and in the browser. I'm going to explore this option some more and try to put together a proposal that makes this intuitive.

**Comment by rubennorte** [comment]
I'm not sure if I got it right. From what I see you're suggesting using the `onInput` handler to assign the global values in the server to the component input so it's serialized in the HTML for the client. Then in the client, the `onMount` handler is called and the serialized input is put again in the store with the globals. Am I right?

Apart from being a little "hacky" IMO, my problem with that approach is that the thing I'm putting in globals are functions, not serializable values. For more context, they're a translation function (which already has the locale and the translations set for the current request) and a function to get urls (which rely on an internal mapping, e.g.: '/img/logo.png' => 'https://some-cdn.com/img/logo-v1234.png'), among other things. I use dependency injection a lot and I'd like to inject the client-side versions of those functions in the template.

I can come up with some hack to do this but I wanted to know if the library itself provided access to the `out` object being used in the client. Would you consider implementing it o accepting a PR that did that?

**Comment by patrick-steele-idem** [comment]
@rubennorte Would you be good with the following proposal:

```marko
class {
    get globals() {
        return ['title'];
    }
}

<div>
    Title: ${out.global.title}
</div>
```

Basically, the `globals` property on the component class definition would be used to specify the names of the global properties that should be serialized down to the browser. 

Look good? Any other ideas?

**Comment by gilbert** [comment]
@rubennorte Would this pattern work for you?

Idea: Define and include a `<global>` component that runs before any other component on the page:

```marko
class {
  onMount() {
    var global = {
      getImageUrl: (path) => `https://${ this.input.imageHost }/${ path }`
    }
    window.out = { global: global }
  }
}
```

**Comment by StarpTech** [comment]
@patrick-steele-idem I like your approach because we work with the same interface `out.global` but you always have to define which propertys are serialized to the browser right? It would be nice if we could work in the same way as on server side. "global" data shouldn't need manual adjustment.

```js
res.marko(template, {
    $global: {
      title: 'test',
      foo: {
        bar: 1,
        name: 'peter'
      }
    },
    $browserGlobals: ['title', 'foo.bar'] //{ title: 'test', foo: { bar: 1 } }
    $browserGlobals: ['!title'] //{ foo: { bar: 1 } }
})
``` 

```marko
<div>
    Title: ${out.global.title}
</div>
```

WDYT?

**Comment by rubennorte** [comment]
Sorry for the delay.

Before telling what my preference would be, take into account that I'm not using Marko in production, I'm still playing with it to evaluate if it fits my needs (my company's).

I think we should be able to pass top-level input and globals in the client initialization as we do with server-side rendering.

If in the server we do:

```javascript
template.stream({
  currentPage: 'Home page',
  $global: {
    staticUrl: () => { ... }
  }
});
```

We should be able to do so in the client:

```javascript
import component from '...';
import markoComponents from 'marko/components';
markoComponents.init({
  $input: {
    // Add variables to the serialized input
  },
  $replaceInput: {
    // Replace all serialized input
  },
  $global: {
    staticUrl: () => { ... } // client-side version
  },
  $replaceGlobal: {
    ...
  }
});
```

The problem with this approach, as far as I know, is that there's no guarantee that there will only be a single top-level component in the page, so passing these values to markoComponents.init could be problematic (although it'd solve my needs).

My use case is something like this (and it's already working with Nunjucks):

```javascript
$ const { staticUrl } = out.global;

<img src="${staticUrl('/img/logo.png')}">
```

@gilbert that pattern may work for me but I'd need many changes in my code to be able to import the function that resolves urls, as I rely a lot on dependency injection. The function that resolves urls is not so simple as appending the path to a variable CDN hostname, but all paths are mapped to a cache-friendly version. Also I don't think it's a good idea to use `out` as a global variable in `window`.

**Comment by rubennorte** [comment]
In case this weren't possible having a reference to the `out` variable used to initialize components would also be enough:

```javascript
import component from '...';
import markoComponents from 'marko/components';
Object.assign(markoComponents.out.$global, {
  // My global variables
});
markoComponents.init();
```

**Comment by patrick-steele-idem** [comment]
This should no longer be an issue now that we have support for [Serialized globals](http://markojs.com/docs/server-side-rendering/#serializing-globals). Also, `out.global` is also persisted across re-renders in the browser. Closing the issue, but please feel free to let us know if there are still concerns.

**Comment by rubennorte** [comment]
Serialized globals don't solve the problem of specifying non-serializable globals in the browser (e.g. functions), but I guess we'll have to use the mentioned hacks to solve that particular issue.

**Comment by BigFax** [comment]
Hi, I have a very similar problem #1447 after adding Marko as a client-side library.

I get the error `out.global.__ is not a function` for the line `${ out.global.__('title') }` because function `__` is not serialized to the browser. I would like to implement Marko client-side without the need to rewrite all my templates. 

**How can I do that ?**

Thank you in advance.

**Comment by DylanPiercey** [comment]
@BigFax what is the implementation of the `___` function?

**Comment by BigFax** [comment]
`__` is a function from `i18n` package : [here](https://github.com/mashpie/i18n-node/blob/master/i18n.js#L206)

**Comment by DylanPiercey** [comment]
@BigFax that module only works in nodejs. You’ll need to find an isomorphic i18n module that works in node and the browser.

**Comment by BigFax** [comment]
@DylanPiercey It is not possible to disable translation in the browser ?

**Comment by DylanPiercey** [comment]
It isn’t because any components with a `class` or `component.js` need to be able to be rerendered in the browser in order to update the dom. For example if you’ve got an `<if>` in your template it needs to be able to show the different blocks with the translated content.

**Comment by BigFax** [comment]
I have Marko as a server library which works fine on a big project with a lot of views.

To add JS on the project with Marko as a client library, I should modify all my templates and change some modules accordingly to make it works ?

**Comment by asieverding** [comment]
@BigFax have u solve this issue? I have the same issue and I am passing `req.__` from express to the $globals.

```js
$global: {
	i18n: res.__
}
```

In my marko component I can use `out.global.i18n('variable')` and it works! But also an error is thrown and the following components do not work.
