### ISSUE TITLE
The tag "await" does not support attribute "unless"

### ISSUE THREAD

**Issue by tinovyatkin** [marko-js/marko#650]
Should it?

**Comment by patrick-steele-idem** [comment]
Do you have a use case in mind? Maybe some sample code that might make the need more clear?

**Comment by tinovyatkin** [comment]
@patrick-steele-idem it's certainly not a problem to use `if(!` instead, I just was under impression that `unless` is some sort of global attribute like `if`...

**Comment by patrick-steele-idem** [comment]
Thanks for the clarification. A fix will go out with the next release.
