### ISSUE TITLE
Proposal: serialize only input and state on top-level server-rendered UI components

### ISSUE THREAD

**Issue by patrick-steele-idem** [marko-js/marko#651]
This proposal impacts how UI components are bootstrapped in the browser when the page is initially rendered on the server. This proposal improves performance on the server and it reduces the chances that a developer will run into problems related to serialization/deserialization of UI component `state`/`input`/properties when a page is rendered on the server. This proposal should maintain backwards compatibility in most cases, but there are a few caveats (see the Caveats section below).

# Current situation

Currently, each UI component rendered on the server will have its `state`, `input` and properties serialized down to the browser. This works and it is relatively fast, except there are a few issues:

- Not everything is serializable
- All `state`, `input` and properties for nested UI components can usually be derived from its top-level UI component so it is most likely redundant to serialize data associated with nested components (NOTE: Marko will dedupe objects/arrays but there is still excess serialization)

> Not everything is serializable

As an example, a reference to a UI component class is not serializable as JSON. The following will not work as expected:

```
import someModule from './foo';

<some-nested-component some-module=someModule />
```

The `some-module` attribute will result in a property being added to the `input` for `<some-nested-component>` but if `someModule` is a JavaScript module that has functions then those functions will not be included in the serialized `input` and `someModule` will _not_ be a reference to the `./foo` module when the UI component mounts in the browser.

# Proposal

Instead of serializing the `input`/properties/`state` of every UI component rendered on the server, only serialize the information associated with the top-level UI component(s) (excluding top-level "split UI components" that are not renderable in the browser).  In addition, a re-render of top-level UI components should be triggered when the top-level UI component boots in the browser. A "complete" re-render it is not actually necessary since there is no need to update the DOM in the browser (i.e., there is no reason to render any virtual DOM nodes when booting in the browser). It is, however, necessary to run through all of the rendering logic in order to determine which UI components need to be created and to determine their `input`/properties/`state`.

# Caveats

- If a nested UI component derives its props/state or generates input properties from anything other than passed in `input` (e.g. `this.locale = out.global.locale`)` then that information will not be available when the UI component mounts in the browser.

# Status

This has been mostly implemented on my machine and it is working well for the apps that I have tested so far. More testing and optimization still needs to be done.

-----

Thoughts? Concerns? Feedback?

**Comment by drewfish** [comment]
This proposal seem to be more secure too, since arbitrary properties will no longer be "leaked" to the browser.

**Comment by ianvonholt** [comment]
> If a nested UI component derives its props/state or generates input properties from anything other than passed in input (e.g. this.locale = out.global.locale)` then that information will not be available when the UI component mounts in the browser.

Does this now mean that accessing the out stream from `onInput` will no longer be serialized and sent to the browser for components?

**Comment by rubennorte** [comment]
@ianvonholt, we wouldn't need that hack if globals were also serialized and/or we could define the global object when initializing components in the browser. I created #646 specifically for that.
