### ISSUE TITLE
Bug: components implementing a `key` attribute break in Marko v4

### ISSUE THREAD

**Issue by gunjam** [marko-js/marko#654]
### Context
I have a couple of Marko 3 components that have a `key` attribute that after upgrading to marko 4 break the whole page when used.

I believe `key` is now a reserved attribute.

### Expected Behavior
Component works

### Actual Behavior
Page fails to render and the following error is logged: `Render error. Exception: Error: No component found`

### Possible Fix
Allow key if defined in marks-tag.json of component.

<details><summary>Additional Info</summary>

### Your Environment

* Version used: 4.2.4
* Environment name and version: node.js v7.8.0
* Operating System and version (desktop or mobile): mac OS Sierra

### Steps to Reproduce

1. Create component with defined `key` attribute
2. Use in a page
3. Everything breaks

### Stack Trace

</details>

**Comment by patrick-steele-idem** [comment]
The UI components compiler should ignore "key" attributes if the custom tag declares its own "key" attribute using `marko-tag.json`. There could still be some confusion to developers, but I think it's still the right thing to do.
