### ISSUE TITLE
Empty style tag leads to error

### ISSUE THREAD

**Issue by StarpTech** [marko-js/marko#658]
### Your Environment
    "lasso": "2.11.8"
    "lasso-autoprefixer": "2.0.0"
    "lasso-less": "2.4.3"
    "lasso-marko": "2.3.0"
    "marko": "4.1.1"
    "marko-widgets": "6.6.0"

Operating system: Windows 10
NodeJs: 6.10.2

### Steps to Reproduce
```js
style.less {
}

<div class="test">
</div>
```
when i remove the empty less section or insert one style it works again!
the parent element looks like

```js
<await(item from input.item )>
    <details item=item vHost=input.vHost />
</await>
```
### Stack Trace
```
Error: Render async fragment error (lasso-slot:head). Exception: Error: Error while writing bundle "details/lasso-less (head, css)" Error: Error:
Unrecognised input:
<div class="test">
```

**Comment by mlrawlings** [comment]
There's no point in adding a dependency if it doesn't contain anything, so I'll make the change to strip it out.


But I think we also need to make a change on the lasso side:
https://github.com/lasso-js/lasso/blob/01dde2dbae025762a98fc09e2306c249eeeb2c19/lib/dependencies/dependency-resource.js#L54-L56

If `code` is an empty string, it doesn't use it and instead tries to read from the filesystem.
