### ISSUE TITLE
Calling .render* on a component with 'key' attribute throws exception.

### ISSUE THREAD

**Issue by edwarddamato** [marko-js/marko#660]
### Context
Whilst trying to programmatically render components, one of the components started throwing an exception `Render error. Exception: Error: No component found`. After further investigation, I narrowed it down to whether any element within the component has a `for-key` or `key` attribute.

### Expected Behavior
The component should render as normal.

### Actual Behavior
With a `for-key` attribute, the following exception is thrown when `renderSync()` is called:
![image](https://cloud.githubusercontent.com/assets/19622548/24833117/5640d312-1c74-11e7-9825-7d9e549a5234.png)

With a `key` attribute, the following exception is thrown when `renderSync()` is called:
![image](https://cloud.githubusercontent.com/assets/19622548/24833126/7b45b43e-1c74-11e7-9083-af34dc8cb0d2.png)

<details><summary>Additional Info</summary>

### Your Environment
* Marko v4.2.6
* Chrome 57.0.2987.133 (64-bit), Node 6
* macOS Sierra 10.12.4

### Steps to Reproduce
I've created [a quick repository](https://github.com/edwarddamato/playground) where you can replicate this issue.

### Stack Trace
Stack traces provided above.

</details>

**Comment by patrick-steele-idem** [comment]
Can you please provide more of template for the UI component that is failing to render so that we can try to reproduce?

**Comment by patrick-steele-idem** [comment]
Currently, the `key` attribute is only applicable within the context of a UI component with a backing `class`. A quick fix would be the following:

```marko
class { }

<div>
  <label for-key="somekey">${input.label}</label>
  <input key="somekey" type="text" placeholder="some placeholder" />
</div>
```

We plan on revisiting this limitation in the future. I will leave the issue open.

**Comment by edwarddamato** [comment]
Yeah, that fixes it. I'll keep an eye on this. Thanks!

**Comment by mlrawlings** [comment]
This should be fixed in the latest beta (`npm i marko@beta`) which should go stable soon.
