### ISSUE TITLE
Component initialization code may end up in the wrong place

### ISSUE THREAD

**Issue by StarpTech** [marko-js/marko#661]
### Environment
Marko: 4.1.1
Node: 7.4.0
### Expected Behavior
Should only render the value.
### Actual Behavior
It renders javascript tag and the value.

### Steps to Reproduce

```marko
    <@title>
        <await(recipe from input.recipe)>
            ${recipe.name}
        </await>
    </@title>
```
will produce
```marko
<title>test&lt;script&gt;(function(){var w=window;w.$components=(w.$components||[]).concat({"w":[["s0",0,{},{"d":null,"b":null}],["s1",1,{"year":2017},{"d":null,"b":null}]],"t":["/recipe-detail$1.0.0/src/components/app-nav/index.marko","/recipe-detail$1.0.0/src/components/app-footer/index.marko"]})||w.$components})()&lt;/script&gt;</title>
```

**Comment by patrick-steele-idem** [comment]
Do you have a `<body>` on your page? Are you explicitly using the `<init-components/>` tag? I am not able to reproduce (unless I render UI components into the `<title>` tag).

**Comment by patrick-steele-idem** [comment]
Actually, I see the problem. It does look like a bug.
