### ISSUE TITLE
this.subscribeTo(document).on('click', (event)... firing immediately on onMount

### ISSUE THREAD

**Issue by basickarl** [marko-js/marko#662]
The following code fires immediately in Chrome when the component in question is rendered via a click event (I click a button, the onClick handler renders a component, in that components onMount I set a subscribe to the document click event, which is fired immediately in Chrome).

In FireFox the event is not fired immediately.

Chrome Version 57.0.2987.110 (64-bit)
FireFox 55.0a1 (2017-03-24) (64-bit)

```
onMount() {
  this.subscribeTo(document).on('click', (event) => {...});
}
```

To reproduce I've uploaded code to a development server I own.

https://bug.dev.instanty.io/

Clicking on the checkbox results in triggering a rendering of a component. Questions? Shoot!

**Comment by basickarl** [comment]
(The same address I linked also displays another weird bug, I'll file a separate bug report though for it)

**Comment by austinkelleher** [comment]
Hey, I realize this issue is pretty old. We are pruning our issue board. Are you still seeing this issue? Could you also provide a full code sample? Thanks!

**Comment by basickarl** [comment]
I'll reopen if it persists!
