### ISSUE TITLE
this.destroy() on parent causing weird UI glitches in Chrome

### ISSUE THREAD

**Issue by basickarl** [marko-js/marko#663]
In Chrome when triggering a this.destroy on a parent component (which has child components) results in unexpected UI "patches".

![screenshot from 2017-04-10 11 16 51](https://cloud.githubusercontent.com/assets/10507098/24862187/e3a5e070-1dfb-11e7-8897-352d27b24bba.png)

![screenshot from 2017-04-10 11 16 36](https://cloud.githubusercontent.com/assets/10507098/24862190/e577d05c-1dfb-11e7-8e49-e19bfe537330.png)

![screenshot from 2017-04-10 13 58 49](https://cloud.githubusercontent.com/assets/10507098/24862169/d2c476c2-1dfb-11e7-85fb-6877c6540971.png)

I've uploaded an example to my development server over at https://bug.dev.instanty.io/

I noticed that when I do not destroy the parent component the bug does not appear.

in the child component:
```
  destroySelf() {
    //this.destroy(); // <-- when this is uncommented, the bug does not appear, but the parent is also not destroyed
    this.emit('suicide'); // <-- parent is listening to this emit event
  }
```

in the parent component:
```
class {
  onMount() {
    console.log('* app-notification-text mounted');
    this.subscribeTo(this.getComponent('component')).on('suicide', () => { // <-- child component will emit suicide event
      this.destroy(); // <-- destroys both itself and child, bug will appear after this happens
    });
  }
  onDestroy() {
    console.log('* app-notification-text destroyed');
  }
}

<div style="position: absolute; width; 0em; height: 0em;">
	<include('src/client/components/app-notification', input) key="component"> <!-- <-- this is the child component -->
			<@body>
				$!{input.body}
			</@body>
	</include>
</div>
```

This only affects Chrome. the version I used is Version 57.0.2987.110 (64-bit). Tested in FireFox 55.0a1 (2017-03-24) (64-bit).

I am unsure if this is a Chrome bug, or if Marko is causing it. So I've issued two bug reports, here is the other one: https://bugs.chromium.org/p/chromium/issues/detail?id=709960

**Comment by austinkelleher** [comment]
Hey, I realize this issue is pretty old. We are pruning our issue board. Are you still seeing this issue? Thanks!

**Comment by basickarl** [comment]
@austinkelleher It's not actual atm, so I'll close it myself :) I'll reopen if it does become and issue again.
