### ISSUE TITLE
[docs] opening tag-brackets (`<`) being improperly converted to `&lt;`

### ISSUE THREAD

**Issue by noformnocontent** [marko-js/marko#664]
### Context
opening tag-brackets (`<`) being improperly converted to `&lt;`

[source](https://github.com/marko-js/marko/blob/master/docs/syntax.md#directives)
![source](https://cloud.githubusercontent.com/assets/23745012/24867738/79794f80-1e0e-11e7-9a2b-8ea816c9c5d5.png)

[rendered](http://markojs.com/docs/syntax/#directives)
![rendered](https://cloud.githubusercontent.com/assets/23745012/24867739/79ead6be-1e0e-11e7-9499-251eec545676.png)

### Expected Behavior
output:
``` marko
<strong if(true)>
    Marko is awesome
</strong>
```

### Actual Behavior
output:
``` marko
&lt;strong if(true)>
    Marko is awesome
&lt;/strong>
```

<details>
### Your Environment
* Version used: 4.2.7
* Environment name and version: Firefox 52, Chrome 57
* Operating System and version: Ubuntu 16.10
</details>

**Comment by patrick-steele-idem** [comment]
Not sure what happened there. I'm investigating.

**Comment by noformnocontent** [comment]
where can the latest rendered master be seen?

**Comment by patrick-steele-idem** [comment]
I'll be publishing a new version of the website soon after I investigate a few other issues that others have reported. You can also run the website locally: 

```
git clone https://github.com/marko-js/marko.git
cd marko
npm install
npm link

cd ..

git clone https://github.com/marko-js/markojs-website.git
cd markojs-website
npm install
npm link makro
npm start
```
