### ISSUE TITLE
Question: Recommended way to share common methods across Components?

### ISSUE THREAD

**Issue by jasonmacdonald** [marko-js/marko#665]
What is the recommended way to share common methods across widgets? Normally, I would extend a base class, but it seems this isn't possible since constructors are never called. 
 
I can't seem to find a clean way to extend ALL widgets with common functionality. Everything I try requires either mixing into the prototype of "class {}" or relying on doing composition within the onCreate method. Is there a better, cleaner, way to do this?

Side Note: My team is constantly fumbling with the class syntax in components because they are not real Classes. We are using es6 and Babel in our projects and Components are the one place that do not follow how real classes work. It's making things very confusing for our developers. Is there any way to use real classes with inheritance in Components? 

UPDATE: Sorry, I missed Patrick actually answered my side note in another ticket https://github.com/marko-js/marko/issues/619. Still, any examples of how to "nicely" mixin supporting methods?

**Comment by austinkelleher** [comment]
You can use mixins or move shared logic into JavaScript files that can be imported. See: https://github.com/marko-js/marko/issues/638
