### ISSUE TITLE
required property in marko-tag.json does not throw errors for child elements

### ISSUE THREAD

**Issue by gunjam** [marko-js/marko#671]
### Context
Setting `"required": true` on a child tag in the marko-tag.json file does not cause a component to throw an error when the required attribute is missing.

### Expected Behavior
The following test should pass:
```javascript
it('should error if you don\'t supply a item name attribute', () => {
  const templateSrc =
    `<summary>
       <@item name="Colour" value="Purple"/>
       <@item value="Dog"/>
     </summary>`;

  try {
    marko.load(templatePath, templateSrc, compilerOptions);
  } catch (err) {
    return assert(true);
  }

  assert(false, 'missing attribute "name" did not throw an error');
});
```

Example marko-tag.json:
```json
{
  "@items <item>[]": {
    "@name": {
      "required": true,
      "type": "string"
    },
    "@value": {
      "required": true,
      "type": "string"
    }
  }
}
```

### Actual Behavior
It fails

### Additional info
This test was passing in marko 3, started failing as I updated my project to marko 4.

**Comment by DylanPiercey** [comment]
These config options are now exposed as warnings.
