### ISSUE TITLE
Beta - Browser state serialization issue 

### ISSUE THREAD

**Issue by StarpTech** [marko-js/marko#677]
# Environment
Windows
NodeJs: v7.9.0
Marko: beta

The framework runtime variables in `out.global`
```
components:GlobalComponentsContext
uid: 1
```

are serialized to (in browser)
```
components: undefined
uid: NaN
```
when I access them in client side component. 

Another question is why they exists in the "user global" space ? This data should be land in a seperate namespace.

**Comment by StarpTech** [comment]
Found the issue here https://github.com/marko-js/marko/blob/845c177be67bce46cc55b1d64b7e451dfe5c01da/components/util-browser.js#L1 window.$MG (defaults) must be merged.

**Comment by patrick-steele-idem** [comment]
I believe this has been resolved. Closing the issue, but please feel free to add comments.

**Comment by StarpTech** [comment]
Hi, yes my PR was merged.
