### ISSUE TITLE
Tests fail on Windows

### ISSUE THREAD

**Issue by StarpTech** [marko-js/marko#679]
Windows 10
NodeJs: v7.9.0

## Steps
```
npm install
npm run test
```
### Output
https://gist.github.com/StarpTech/7766ed20349bc4096b647f1dbad2ab0c

**Comment by mlrawlings** [comment]
Looks like our [compare helper](https://github.com/marko-js/marko/blob/master/test/autotest.js#L32-L68) needs to be updated to normalize line-endings.

Windows uses `'\r\n'` where as Unix style OS (Linux, Mac) use `'\n'`.

**Comment by ajay2507** [comment]
@mlrawlings I am facing the same issue. how about using **process.platform** to check win or mac to fix this issue?. I can give it a try.

**Comment by DylanPiercey** [comment]
We do not currently have maintainers actively using windows and so it is not a high priority for the test suite to work on windows. (Obviously, Marko itself does need to).

If anyone wants to help us tackle this we'd certainly appreciate it, but as it stands we do not have any plans to address windows support for the test suite.
