### ISSUE TITLE
How to associate component controller with the template when using renderer (V4)

### ISSUE THREAD

**Issue by wangwb** [marko-js/marko#684]
### Question

I'm trying to use renderer to render one of my template like this:

```javascript
const template = require('./template')

module.exports = (input, out) => {
  // Do something else with the template, input or out
  template.render(input, out)
}
```

So is there a way I can associate my controller (`component.js` for example) to this certain template? Thanks a lot.

**Comment by mlrawlings** [comment]
An `index.marko` will automatically pick up a `component.js` in the same directory but for `.marko` files that have another name (like `template.marko`) the component file should have the same name prefix (like `template.component.js`).

See also: http://markojs.com/docs/components/#supporting-files
