### ISSUE TITLE
How to pass down reference from component.js (V4 Beta)

### ISSUE THREAD

**Issue by wangwb** [marko-js/marko#685]
### Question

Thank you so much for making components take reference in the latest beta version! But it seems like it only takes references from marko template (static). If I want to pass function reference from `component.js` down to child component, the child component still not able to receive the reference. I'm not sure if I'm using it correctly or not. Could you share some working demos to demonstrate passing reference from `component.js` down please? Thanks again!

**Comment by patrick-steele-idem** [comment]
When rendering on the server, the top-level UI component cannot have function references. Marko serializes the data for the top-level UI components rendered on the server. If you have a reproducible test case to better illustrate your problem that would be helpful.

**Comment by wangwb** [comment]
Hi @patrick-steele-idem, thanks for the response. 

I was not able to reproduce this time, maybe I didn't use it correctly that time. But I did encounter a different problem. The references passed down does not able to recgonize the correct execution context. 

/test-component/index.marko
```html
<test-inner-component handler=component.handler />
```

/test-component/component.js
```javascript
module.exports = {
  onCreate () {
    this.value = 'value'
  },
  handler () {
    return this.value // or do anything with the current controller context
  }
}

```

/test-inner-component/index.marko
```html
<div>
  <button on-click('click')>Click</button>
</div>
```
/test-inner-component/component.marko
```javascript
module.exports = {
  click () {
    console.log(this.input.handler())
  }
}
```

Supposely, the console should have a log as `value` printed when I click the button in the `test-inner-component`. But it actually printed `undefined`. 

I even tried to bind context for the function reference in `test-component` at `onCreate`, `onInput` or `onMount` like `this.handler = this.handler.bind(this)`. None of them actually work. 

Could you advise how this `pass reference` suppose to work? Does it only suppose to work without any context? 

Another use case I can think of is to pass marko component into another component, but that leads to another question I created: https://github.com/marko-js/marko/issues/684. How can I pass in a fully functional component (with template and controller) into another component? The only way I'm aware of it to pass in something like this: `require('./a-component.marko')`, but how can I associate a controller with that template? 

Sorry for the long question and thank you for the help.

**Comment by ianvonholt** [comment]
@wangwb 

You are going to need to bind the particular functions as follows: 

`test-inner-component.marko`
```
class {
  onCreate (input) {
    this.parentHandler = input.handler
  }
  onClick (e, el) {
    this.parentHandler()
  }
}

<div>
  <button onClick("onClick")>Click</button>
</div>
```

`test-outer-component.marko`
```
class {
  onCreate (input) {
    this.state = {
        name: 'Parent Component'
    }
  }

  handlerFn () {
    console.log(this.state.name);
  }
}

<div>
    <test-inner-component handler=component.handlerFn.bind(component) />
</div>
```

I, personally, would take advantage of the NodeJS events to pass or set data, but passing a controlling function in this manner will alter the parent state from the child component as well.

**Comment by wangwb** [comment]
@ianvonholt Thank you so much for your response. It worked as what I expected!

I do agree that in some cases using events would be more appropriate. While a function does not necessarily change the state of parent. In some cases like having a really deep nested components chain, you need to pop and catch every single event in each layer with the event name which is string literal and it is really easy to make mistakes. In other cases like if the parent component wants the child component to be rendered with some other components dynamically, then having parent passes in a function to render components would be easier to implement then using events to communicate back and forth. 

Thanks again for your help.

**Comment by austinkelleher** [comment]
Let us know if you have any additional questions.
