### ISSUE TITLE
Proposal: Add support for marko.js for tag discovery

### ISSUE THREAD

**Issue by austinkelleher** [marko-js/marko#686]
When overriding tags, it would be nice be able to be able to inherit from the `marko.json` file.

## Proposed Solution

Add support for a `marko.js` file that will be used to resolve components. This can be used to override a `marko.json` etc.

Overriding `<await>` tag:

**/marko/taglibs/async/marko.json**
```json
{
    "<await>": {
        "renderer": "./await-tag",
        "@_var": "identifier",
        "@_dataProvider": "expression",
        "transformer": "./await-tag-transformer",
        "@timeout": "integer",
        ...
        ...
        ...
    }
}
```

**/my-await/my-await-tag.js**

```js
module.exports = function (input, out) {
  input.timeout = input.timeout || 20000;
  ...
};
```

**/my-await/marko.js**
```js
const markoAwaitTag = require('marko/taglibs/async/marko.json');

const myAwaitProps = Object.assign({
  renderer: './my-await-tag',
  transformer: './my-await-transfomer'
  // All other `<await>` properties should be inherited
}, markoAwaitTag['<await>']);

module.exports = {
    '<my-await>': myAwaitProps
};
```

**Comment by austinkelleher** [comment]
Another possible solution we discussed:

```json
{
  "<child-tag>": {
    "extends": "/path/to/parent-tag/marko.json",
    "renderer": "./child-tag"
  }
}
```

**Comment by DylanPiercey** [comment]
Since we now recommend using TypeScript for much of the utility of that `marko*.json` files provided I think adding a new feature like this is no longer needed.
