### ISSUE TITLE
Event listeners not working from components rendered using <include(input.renderBody)/>

### ISSUE THREAD

**Issue by austinkelleher** [marko-js/marko#693]
Events are not getting handled from components that are included using `<include(input.renderBody)/>`

Example: https://github.com/austinkelleher/marko-render-body-events-bug

**Comment by ianvonholt** [comment]
I actually started encountering this today and have provided an example:

https://github.com/ianvonholt/marko-widget-test/tree/4.4.2

It seems that the onMount of child components is not being executed at all, nor are events being assigned. 

If the parent component has no component logic, no `module.exports` or `class {}`, then it works just fine. 

I provided two examples one with the class logic, one without.

**Comment by patrick-steele-idem** [comment]
@ianvonholt This one is kind of interesting and I'm not sure there is a good way to avoid the problem. With `marko@4.3` we changed how the page boots in the browser after at it renders on the server (https://github.com/marko-js/marko/issues/651). The new behavior is that only the input/state for the top-level UI component is serialized down to the browser and the top-level UI component is re-rendered with the serialized `input`/`state` in the browser when the page loads. The problem in this case is that the `input` for the top-level UI component (`<header-bar>`) includes a `input.renderBody(out)` function that is not serializable down to the browser so when the top-level UI component is re-rendered it has no children and the page does not fully boot.

I have an idea that might work. I am thinking that if we detect that a top-level UI component has a non-serializable functions on its `input` then we will revert to the old behavior for that component.

**Comment by ianvonholt** [comment]
I've sat on this one for a couple days and I have to say that I have no definitive conclusion on my stance with this. I understand the performance gains with only having the input/state for the top-level UI component serialized down to the browser. However, this method makes the combination of components rather lacking. 

With the current behavior in `marko@4.3+`, each instance where a developer is going to want nested components to be different for every page will fail to fully boot. Unless, that is, the developer explicitly creates different variations of the parent component with the desired top level UI components, or the component is utilized just as a template. The former bloats the number of components while the latter would remove any sort of logic you may want to apply to the parent component.

**Comment by patrick-steele-idem** [comment]
@ianvonholt We ended up going with the following solution:

> I am thinking that if we detect that a top-level UI component has a non-serializable functions on its input then we will revert to the old behavior for that component.

This solved the problem in a transparent way with no code bloat.

New version published with fix: `marko@4.4.6`

We added some tests. Please let me know if you see any issues.

**Comment by ianvonholt** [comment]
@patrick-steele-idem I was just looking through the commit log, looks wonderful. 

I'll run it through some tests on my end and let you know if there are any problems.

**Comment by hedav85** [comment]
Hello,

for me the problem is still there. I use marko version 4.4.18. I have a container component with logic in a component.js and this component includes child components with their own logic.
The logic of the child components is not working since the container has the component.js.

For the inlcude I use `<include(data.template, {...}/>` instead of `<include(input.renderBody)/>`
The template is loaded via require `data.template = require('myTemplate')`.

**Comment by Joeao** [comment]
I'm also experiencing this issue on 4.4.19:
```javascript
// modal.marko
class {
    destroy() {
        this.el.destroy();
    }
}

<div class="modal-dialog">
    <div class="modal-content ">
        <include(input.body)/>
    </div>
</div>

```
```javascript
// modalContents.marko
class {
    userSettings(e, el) {
    	// do something
    }
}

<include('../modal.marko')>
	<@body>
		<li class="link" on-click('userSettings')>
			<p>User Settings</p>
		</li>
	</@body>
</include>
```

Getting`Uncaught ReferenceError: __component is not defined` @  `onclick: __component.d("userSettings")`. 

Removing the `on-click` binding makes the error disappear.
