### ISSUE TITLE
I want to know about client side routing for PWA in Marko JS and Marko Widget like React Router

### ISSUE THREAD

**Issue by anupdineout** [marko-js/marko#700]
Documentation is not proper , We are developing Progressive Web App .  we need client side Routing Mechanism like Iron Router or react Router and Ember Routing  .

**Comment by mauricionr** [comment]
Check out https://github.com/marko-js/marko/issues/645

**Comment by anupdineout** [comment]
Hey @mauricionr  , Marko 4.*
We have developed webiste and mobile website using Marko 3.* and Marko Widget . Can you suggest We want to upgrade to Marko 4 . Like Marko start providing state  in Marko 4 . Please suggest me regarding this

**Comment by anupdineout** [comment]
@gilbert

**Comment by patrick-steele-idem** [comment]
I see client-side routing and scoped CSS as two gaps that we should fill (whether it be with a new marko-specific solution or integrating a third-party solution). We will be tackling the scoped CSS this sprint and we plan to do some more research and investigation for the client-side routing piece. In the meantime, maybe check out the following library for client-side routing: https://github.com/FormidableLabs/redux-little-router

With the approach that `redux-little-router` provides, there would not necessarily need to be any direct integration of the routing library with the view library (although they do provide React helpers). Seems like a promising approach, but I have not tried that library myself.

**Comment by anupdineout** [comment]
@patrick-steele-idem  : Can you suggest me  for Marko 4  , We are using marko 3.3 and marko widget . I want to upgrade for marko 4 . In Marko 4 u r proving state View architecture , We can eliminate Marko Widgets ?

**Comment by mauricionr** [comment]
@anupdineout this issue https://github.com/marko-js/marko/issues/626 has good stuff about markov3 and markov4

**Comment by patrick-steele-idem** [comment]
@anupdineout Here are some resources for moving from Marko v3 to Marko v4:

- [ROADMAP.md](https://github.com/marko-js/marko/blob/ed6f06a7af8f991cc0735e1366a9737e65e74a92/ROADMAP.md) (may be slightly inaccurate)
- [Migration guide](https://gist.github.com/ianvonholt/9f700ec9a6def8655179b46f9f294e61) by @ianvonholt 
- [Medium Article: Marko 4.0 is here](https://medium.com/@mlrawlings/marko-4-0-is-here-837884c5f60d)

**Comment by patrick-steele-idem** [comment]
@anupdineout 

> In Marko 4 u r proving state View architecture , We can eliminate Marko Widgets ?

Marko Widgets was merged into Marko and that has made things a lot more seamless.

**Comment by anupdineout** [comment]
@patrick-steele-idem  any suggestion for Progressive Web app in Marko Js for Mobile website . Can you provide any documenation  or git demo project .

**Comment by mauricionr** [comment]
i'm following lighthouse 2.0 for best practices on PWA

`npm install -g lighthouse`

**Comment by anupdineout** [comment]
I dont know , @patrick-steele-idem  , https://github.com/FormidableLabs/redux-little-router  does not provide support for MarkoJS

**Comment by mauricionr** [comment]
have you seen this one @anupdineout https://github.com/charlieduong94/marko-path-router ?

**Comment by anupdineout** [comment]
@mauricionr  @patrick-steele-idem  Can you help me to use es6 in MarkoJS 4.

**Comment by anupdineout** [comment]
@mauricionr  @patrick-steele-idem  

https://github.com/charlieduong94/marko-path-router ?
I checked this , its not working for me  . I need Client Side routing , otherwise , I need to switch the Technology from Marko4 to React . Please Suggest

**Comment by mauricionr** [comment]
Why is not working for you?

**Comment by charlieduong94** [comment]
Hello @anupdineout, I would be happy to help you get `marko-path-router` set up. Please create an issue on my repo detailing the problems you are having so that we can work through them together.

**Comment by anupdineout** [comment]
@charlieduong94  Thanks for reverting back . Thats was some issue with KOA Aysnc setup . Now working for me
