### ISSUE TITLE
marko 4.4 webpack Error: Cannot find module "."

### ISSUE THREAD

**Issue by arthurchenn** [marko-js/marko#702]
everything worked fine up until upgrading to marko 4.4.0, when building with webpack, this error cropped up
`var markoCompiler = !(function webpackMissingModule() { var e = new Error("Cannot find module \".\""); e.code = 'MODULE_NOT_FOUND'; throw e; }());`
Downgrading to marko 4.3.1 could fix the problem.
What's wrong? please!

**Comment by patrick-steele-idem** [comment]
I was not able to reproduce the issue using the [marko-webpack](https://github.com/marko-js-samples/marko-webpack) sample app. I tried using both `webpack@1` and `webpack@2` and I also used `npm@5`. Could you provide a sample app to reproduce the problem or more details on your setup?

**Comment by arthurchenn** [comment]
I added a github project to reproduce the issue
[https://github.com/arthurchenn/markoissue702](url)

**Comment by patrick-steele-idem** [comment]
Thanks for providing the project, @arthurchenn!

@austinkelleher, can you please take a look at the provided project  to reproduce the problem? Thanks

**Comment by arthurchenn** [comment]
Upgrading to node 8 and npm5 doesn't help.

**Comment by arthurchenn** [comment]
Any progress? @austinkelleher

**Comment by austinkelleher** [comment]
Hey @arthurchenn. Sorry for the late response. I'll look into it today.

**Comment by arthurchenn** [comment]
@austinkelleher , thank you for the fix, it works perfectly!
