### ISSUE TITLE
Marko >= 4.4.3 is not installing correctly with newly released npm@5

### ISSUE THREAD

**Issue by tinovyatkin** [marko-js/marko#703]
Seems to be related with #702 as error is the same

**Comment by tinovyatkin** [comment]
staying at `4.4.2` solves the problem

**Comment by patrick-steele-idem** [comment]
We'll investigate. Thanks for reporting the problem.

**Comment by patrick-steele-idem** [comment]
I'm not able to reproduce the issue using the [marko-webpack](https://github.com/marko-js-samples/marko-webpack). I tried using both `webpack@1` and `webpack@2` and I also used `npm@5`. Could you provide a sample app to reproduce the problem or more details on your setup?

**Comment by nahtnam** [comment]
Installing `4.4.5` works fine for me with `npm@5`.

**Comment by tinovyatkin** [comment]
Can't reproduce that on node 8 with NPM5 and `4.4.6`, so, it was either my misconfiguration or something already fixed. Will close the issue, thank you!
