### ISSUE TITLE
[help-wanted] Configuring Marko with Webpack for Electron

### ISSUE THREAD

**Issue by Heziode** [marko-js/marko#704]
Hi,

I try to create an [Electron](https://electron.atom.io/) boilerplate for [Marko](http://markojs.com/) using [Webpack](https://webpack.js.org/). When I launch app, template are not rendered and source it's displayed instead.

I would like someone help me or explain me how to fix this.

Repository: [electron-marko-boilerplate](https://github.com/Heziode/electron-marko-boilerplate)

**Comment by Heziode** [comment]
I don't undersant why I've this instead of compiled source:

![electron-marko-boilerplate-issue](https://cloud.githubusercontent.com/assets/16735076/26760082/204403ce-4910-11e7-9ab2-62d15ce89591.png)

If instead of **include** I write a simple page like this:
```html
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">

    <title>Markostractions</title>
  </head>
  <body>
	  <app/>
    <script src="../../../static/bundle.js"></script>
  </body>
</html>
```

This work (except APP which is not rendered).

**Comment by DylanPiercey** [comment]
@Heziode I understand this is a bit late, but `marko-loader` now automatically detects the webpack target which may resolve your issue.

You can also force Marko to initialize in the browser by using:
```js
require('marko/components').init();
```

Please let me know if this works for you!

**Comment by Heziode** [comment]
@DylanPiercey After testing what you tell, it still does not work.

**Comment by DylanPiercey** [comment]
This is not an area we are actively exploring. It is possible this now works with modern plugins. Happy to help anyone with specific issues using the updated tooling 😄
