### ISSUE TITLE
Add Option to make Browser-Refresh Quiet

### ISSUE THREAD

**Issue by nahtnam** [marko-js/marko#709]
## New Feature
Add an option (`quiet`, or `silent`) that will stop console outputs.
### Description

Add the option somewhere like: `require('marko/browser-refresh').enable({ quiet: true });`, that will stop console.logs like the following from being printed.
```
[marko/hot-reload] File modified: /Users/nahtnam/Desktop/testing/app/templates/hello/index.marko
```
### Context

I am working on a site and my console output every time my server restarts is bloated. To reduce clutter it would be great to have a quiet option that would only print if there is an error or warning.
### Possible Implementation
N/A
### Open Questions
N/A
### Is this something you're interested in working on?
No

**Comment by austinkelleher** [comment]
I think this is fair. Would you be interested in working on this? I think `silent` would be a good option for this. `silent` should be set to `false` by default.

**Comment by nahtnam** [comment]
I could try, but someone would have to go over the code since I have almost no experience with Marko.

**Comment by austinkelleher** [comment]
@nahtnam I would be more than happy to help you implement this feature. We love to welcome new contributors.

First off, you will need to add the `silent` option to the `enable` function: https://github.com/marko-js/marko/blob/fe60da9c111ae60613e567ab957b47e9b77cebea/src/browser-refresh.js#L4

As I said before, the `silent` option should default to `false`.

You will need to pass the options to the `hotReload.handleFileModified(...)` function call. The `hotReload` module can be found here: https://github.com/marko-js/marko/blob/master/src/hot-reload.js#L127. From there it's as simple as only running the `console.log` statements if `silent` is not `falsy`.

If you would like to work on this, or have any additional questions let me know! We'd love to get your help.

**Comment by patrick-steele-idem** [comment]
@nahtnam Contributions are greatly appreciated and we are happy to answer any questions you might have related to this proposed change. I also agree it would be a good addition.

**Comment by patrick-steele-idem** [comment]
@nahtnam here's the link to the contributors guide: https://github.com/marko-js/marko/blob/master/.github/CONTRIBUTING.md

All of the latest code is on master. You would want to fork the repo and create a new branch from master to implement the new feature and then submit a pull request using your new branch as the source.

**Comment by nahtnam** [comment]
@patrick-steele-idem @austinkelleher Thanks for your comments. I think I know how to do it. My only question is:

Here: https://github.com/nahtnam/marko/blob/master/src/hot-reload.js#L38 I will add a `option` parameter which will check is `silent` is defined (defaults to false). Do I add that option to the `runtime` variable so the silent option can be accessed in the other functions?

**Comment by austinkelleher** [comment]
@nahtnam Great to hear that you will work on it! You do not need to add the option to `runtime`.

**Comment by nahtnam** [comment]
I still need to finish the checklist but its a start.
