### ISSUE TITLE
Breaking change in patch version 4.4.8

### ISSUE THREAD

**Issue by tinovyatkin** [marko-js/marko#713]
Hello,

Is there a way to switch off breaking change in latest patch version of Marko? I mean this one: https://github.com/marko-js/marko/wiki/Error:-Dynamic-root-HTML-element-id-attribute

**Comment by austinkelleher** [comment]
I apologize. This change should only be applied to UI components. I will revert the change, publish a new version without it, then work on making the appropriate changes. I'm going to leave this issue open for now. Thanks.

**Comment by austinkelleher** [comment]
Published `marko@4.4.9` with the revert. Once again, I apologize for the inconvenience.

**Comment by tinovyatkin** [comment]
Thank you for fast fix!

**Comment by austinkelleher** [comment]
Real fix published in `marko@4.4.12`.
