### ISSUE TITLE
Browser-Refresh and Hot-Reload Called Several Times Automatically

### ISSUE THREAD

**Issue by nahtnam** [marko-js/marko#718]
## Bug Report
I've noticed that when I call `require('marko/browser-refresh').enable({ silent: true });` and `require('marko/node-require').install()`, hot-reload/browser-refresh is enabled several times. It should only be enabled once when I call `require('marko/browser-refresh').enable({ silent: true });`.
### Context

I am working on a framework using Marko and wanted to enable live-reloading. Part of it is to enable the silent flag. I found that there were still logs being added and I soon found debugged and found out that hot-reload was being enabled 3-4 times.
### Expected Behavior

Browser-Refresh and Hot-Reload should only be enabled once, when I manually do it.
### Actual Behavior

It is enabled 3-4 times.
### Possible Fix

I think I've found out how to fix it. Number one, when you enable `browser-refresh`, it should not set the env variables, as with `hot-reload`, [here](https://github.com/marko-js/marko/blob/master/src/hot-reload.js#L51) and [here](https://github.com/marko-js/marko/blob/master/src/browser-refresh.js#L19). Then wrap [this](https://github.com/marko-js/marko/blob/master/src/index.js#L11) in an if statement like the one a few lines above.

I have tested the changes, and they work but I do not know what the implications are of others using the framework.
### Your Environment

* Version used: 4.4.7
* Environment name and version (e.g. Chrome 39, node.js 5.4): Chrome 58, Node 7.10
* Operating System and version (desktop or mobile): MacOS Sierra
* Link to your project: N/A (yet)

### Steps to Reproduce

Not relevant?

### Stack Trace

N/A
</details>

**Comment by DylanPiercey** [comment]
This is fixed in Marko 5
