### ISSUE TITLE
Add a Code of Conduct

### ISSUE THREAD

**Issue by newyork-anthonyng** [marko-js/marko#721]
## New Feature
Add a `Code of Conduct`.

### Description

I was reading the [2017 Open Source Survey](http://opensourcesurvey.org/2017/) and thought that a Code of Conduct would be helpful for this project.

### Context

> Documentation helps create inclusive communities. Documentation that clearly explains a project's processes, such as contributing guides and codes of conduct, is valued more by groups that are underrepresented in open source, like women.
>
> [2017 Open Source Survey](http://opensourcesurvey.org/2017/)

### Possible Fix

<details><summary>Additional Info</summary>

### Your Environment

* Version used:
* Environment name and version (e.g. Chrome 39, node.js 5.4):
* Operating System and version (desktop or mobile):
* Link to your project:

### Steps to Reproduce

1. 
2. 
3. 
4. 

### Stack Trace

</details>

**Comment by patrick-steele-idem** [comment]
Thanks for bringing this up @newyork-anthonyng. I do think this is something we need to introduce to make it clear that this project aims to have an inclusive community and to avoid any issues in the future. 

Is there a particular Code of Conduct that you think stands out?

**Comment by newyork-anthonyng** [comment]
@patrick-steele-idem 
I saw two templates that look promising.

## 1. TODO Group
The first [template](http://todogroup.org/opencodeofconduct/) is from the [TODO group](http://todogroup.org/members/), an open group of companies who run open source programs (of which eBay is a member). I came upon this template on [Facebook’s Open Source Code of Conduct](https://code.facebook.com/pages/876921332402685/open-source-code-of-conduct).

However, the work on updating their Code of Conduct has been [discontinued](http://todogroup.org/blog/followup-open-code-of-conduct/). They recommend you adopt other code's of conduct, including the second on my list...

## 2. Contributor Covenant
[Contributor Covenant](http://contributor-covenant.org/)'s Code of Conduct has been used by over 15,000 open source projects, including `Atom`, `Angular`, `Babel`, `Swift`, and `Yarn`. 

It is a [living document](http://contributor-covenant.org/version/1/4/) and their [repo](https://github.com/ContributorCovenant/contributor_covenant) seems active. I would recommend this one. Let me know what your thoughts are.
