### ISSUE TITLE
[Question] Markojs and SailsJS

### ISSUE THREAD

**Issue by mauricionr** [marko-js/marko#723]
how to implement markojs and sailsjs?

Thanks guys!

**Comment by ianvonholt** [comment]
If I'm not mistaken, SailsJS uses Consolidate.JS to help Express with it's view engine.

The caveat here is that [consolidate.js](https://github.com/tj/consolidate.js) only currently supports Marko 3. There is a [pull request](https://github.com/tj/consolidate.js/pull/281) to update the library, but it seems that project is a bit behind. 

See: http://sailsjs.com/documentation/concepts/views/view-engines
And: https://github.com/tj/consolidate.js/blob/master/Readme.md#api

You may be able to tweak the handling of the view engine by using custom configuration parameters that load in the MarkoJS express module.

**Comment by mauricionr** [comment]
thanks @ianvonholt i will try it

**Comment by austinkelleher** [comment]
@mauricionr Did you ever get this working? If so, would you be interested in providing some documentation? Thanks!

**Comment by mauricionr** [comment]
sorry @austinkelleher, i could no test it yet :disappointed:

**Comment by DylanPiercey** [comment]
Going to close this for now since it looks like support got added for `Marko4` in `consolidate.js`. @mauricionr please comment back if it doesn't work out and we can try to help you further 🙂.

**Comment by mauricionr** [comment]
Thanks @DylanPiercey
