### ISSUE TITLE
intercommunication between parent and child component while using Marko path router and renderSync

### ISSUE THREAD

**Issue by anupdineout** [marko-js/marko#725]
import store from '../../store';
//var store = require('../../store');
//var counter = require('../counter');
import homeComponent from '../home';
import notFoundComponent from '../noFound';
import listingComponent from '../listing';
import {Router} from 'marko-path-router';

class {
  onCreate () {
    this.state = {
      currentRoute: "/"
    }
  }
  onMount() {
    store.subscribe(() => {
        this.forceUpdate();
    });
    const self = this
    const state = self.state
    const routes = [
      { path: '/', component: homeComponent },
      { path: '/**', component: notFoundComponent },
      { path: '/listing', component: listingComponent }
    ]
    const render = homeComponent.renderSync({
      routes: routes,
      initialRoute: state.currentRoute,
      value : store.getState().value
    })

    const router = this.router = render
      .appendTo(this.getEl('router-container'))
      .getComponent()

    state.currentRoute = router.currentRoute

    router.on('update', () => {
      state.currentRoute = router.currentRoute
    })
  }
  onInput (input) {
    let state = this.state
    state.currentRoute = input.currentRoute || state.currentRoute
    state.activeItem = input.activeItem || state.activeItem
  },
  dispatch(type) {
    console.log("dispatch : ", type)
      store.dispatch({ type: type });
  }
}

<div>
  <router-link.btn path='/listing' rel="nofollow"> Go to users </router-link>
  <div class ="app-content" key='router-container' on-increment('dispatch', 'INCREMENT')
        on-decrement('dispatch', 'DECREMENT') no-update> 
  </div>      
</div>

on-decrement('dispatch', 'DECREMENT')  and on-increment('dispatch', 'INCREMENT') not working

child component emit data : 
class {
    onCreate (){
        console.log("home input --- : ",this.input)
    }
    onInput (){
        console.log("home input --- : ",this.input)
    }
    increment(delta, event, el) {
        console.log("increment : ")
        this.emit('increment');
    }
    decrement() {
        this.emit('decrement');
    }

    incrementIfOdd() {
        if (this.input.value % 2 !== 0) {
            this.increment();
        }
    }

    incrementAsync() {
        setTimeout(() => {
            this.increment();
        }, 1000);
    }
}

**Comment by charlieduong94** [comment]
You should probably move this issue over [here](https://github.com/charlieduong94/marko-path-router). But to answer your question, you should use either an [SAV architecture](https://github.com/marko-js-samples/todomvc-marko-lasso-express) with a singleton app instance that all child components can import/require or use something like [redux](https://github.com/reactjs/redux).

**Comment by anupdineout** [comment]
I need client side routing mechanism using single app component through that I can navigate to different route  .and I want to send info to parent using emit .. but marko path router not providing this

**Comment by austinkelleher** [comment]
I'm going to go ahead and close this issue as it seems related to [marko-path-router](https://github.com/charlieduong94/marko-path-router) and is not specific to Marko. Let us know if you have any other questions. Thanks.
