### ISSUE TITLE
Urgent : Request for Demo sample Project for PWA using marko4 & Redux & marko-path-router & Webpack

### ISSUE THREAD

**Issue by anupdineout** [marko-js/marko#726]
Request for Demo sample Project for PWA using Markojs 4 && client side routing - marko-path-router (Client side Router) , Redux , Webpack 

Markojs is very new framework , Difficult to find issue solution on stackoverflow etc  . So I request to upload one sample project using these all step

**Comment by mlrawlings** [comment]
Our plan for the future of [`marko-starter`](https://github.com/marko-js/marko-starter) (which you'll typically use through the [`marko create`](https://github.com/marko-js/marko-devtools#create) command) is for you to get a basic PWA out of the box.  So stay tuned for that.

However, a PWA is really just a term for an app that makes use of a lot of the new technologies that are available in the browser and these are totally [unrelated to what view library you use](https://addyosmani.com/blog/getting-started-with-progressive-web-apps/).  So take a look at the resources available on PWA's and most of it will apply to building an app with marko as well.

**Comment by austinkelleher** [comment]
I'm going to go ahead and close this out since it is very specific technologies together in one sample app. We have samples of each of these technologies here: 

http://markojs.com/docs/server-integrations-overview/
http://markojs.com/docs/framework-integrations-overview/

**Comment by austinkelleher** [comment]
Let us know if you have any specific questions. Thanks!
