### ISSUE TITLE
Is lasso support for Service worker and precache sw-tool support during lasso bundling ?? #205

### ISSUE THREAD

**Issue by anupdineout** [marko-js/marko#727]
Webpack supports for service worker and sw-precache and sw-toolbox ...

Precache static resources so they work offline .

Handle versioning, redirects, etc.

Collection of helpers for writing your Service Worker
Caching strategies for dynamic content
Mapping caching strategies to application paths
Used extensively by sw-precache

**Comment by anupdineout** [comment]
Waiting for your reply for this  @austinkelleher @patrick-steele-idem

**Comment by anupdineout** [comment]
waiting for ur reply .. !!

**Comment by mlrawlings** [comment]
@anupdineout We don't as of yet have any examples or resources for service-workers + marko/lasso.  But you can probably expect some related stuff in the near future.

However most of this stuff is pretty separate from the view library you are using.  `sw-precache` which you mentioned is a standalone library.  Others have written integrations which make it a _little_ easier to use with various libraries, but you can definitely use the module directly.

If you end up writing a lasso plugin for `sw-precache`, let us know with a PR to the [plugin list](https://github.com/lasso-js/lasso#available-plugins)!
