### ISSUE TITLE
custom tag with renderer.js file does not load styles

### ISSUE THREAD

**Issue by loopArray** [marko-js/marko#730]
### Context

I created a custom tag and the directory structure is as follows:
```
- custom
  -- marko-tag.json
  -- renderer.js
  -- Template.marko
  -- Template.style.less
```
renderer.js content as follows:
```
var template = require('./Template.marko');
exports.renderer = function render(input, context) {
    ....
    ....
}
```
Template.marko.js is automatically generated when developing and the last lines are as follows:
```
marko_template.meta = {
    deps: [
      "./Template.style.less"
    ],
    tags: [
      "marko/src/taglibs\\core\\include-tag"
    ]
  };
```
using this custom tag in other places does not refer to this Template.style.less file.
but, when  I modify the file structure like this:
```
- custom
  -- marko-tag.json
  -- index.marko
  -- style.less
```
There is no such problem and the style file is also generated.

### Your Environment

* Version used: marko@4.4.11
* Environment name and version (e.g. Chrome 39, node.js 5.4): chrome 59, node.js 6
* Operating System and version (desktop or mobile): windows 7

**Comment by mlrawlings** [comment]
You'll need to export the template's metadata or the template itself from the renderer since it becomes the entry point.

```js
exports.meta = template.meta;
// or
exports.template = template;
```

However, while the `renderer` is supported, it's intended more for "advanced" tags like the [`await tag`](https://github.com/marko-js/marko/blob/master/src/taglibs/async/await-tag.js#L65). We recommend using the `index.marko` naming convention so the template is the entry point and importing any functions to manipulate the input data.

**Comment by loopArray** [comment]
Thank's for your reply.
But if so, how do I define attributes in index.marko? I'm writing a sample:
 index.marko
```
$ {
  var sideWidth = 260;
  var wrapStyle = {};
  var mainStyle = {};
  var sideStyle = {};

  if (input.wrapWidth || input.sideWidth) {
      sideWidth       = input.sideWidth || sideWidth;
      sideStyle.width = sideWidth * 1;
      wrapStyle[input.wrapWidth ? 'width': ''] = input.wrapWidth;

      mainStyle.paddingLeft = sideWidth * 1 + 10;
  }

}
<div style=wrapStyle >
...
...
</div>
```
marko-tag.json
```
{
    "@side": "string",
    "@main": "string",
    "@sideWidth": "string",
    "@wrapWidth": "string",
    "@content": "string",
    "@*": "string"
}
```
Such use as this:
```
<Content wrapWidth="1200" sideWidth="320">
</Content>
```
Is it a good idea to write in index.marko?

**Comment by mlrawlings** [comment]
I would probably do something like this:

```marko
import getStyles from './get-styles';

$ var styles = getStyles(input);

<div style=styles.wrap>
    ...
</div>
```

**Comment by loopArray** [comment]
I don't think there's anything better than that.
thank's.
