### ISSUE TITLE
marko widget init with wepack on client side in marko widget + marko v3

### ISSUE THREAD

**Issue by anupdineout** [marko-js/marko#738]
I am facing issue while init marko widget on client side with wepack  . with lasso its working , But I am changing to webpack . Please help me about this .

**Comment by mauricionr** [comment]
I got a question, Why not marko4?

**Comment by anupdineout** [comment]
@mauricionr  @patrick-steele-idem  .. We are already production live with Marko v3 + marko widget . Currently we changing our bundling tool due to some issue . Want to use webpack . Please suggest client side init of marko widget for webpack , its not working for me . after 3 month , we r planning to move on marko v4 .  Production Live on  www.dineout.co.in .

**Comment by austinkelleher** [comment]
Are you still experiencing any issues? Please provide additional details if so. Thanks.

**Comment by DylanPiercey** [comment]
@mauricionr I am going to close this issue for now, please let me know if your issue has not been resolved.

One thing I will add is that you can force Marko to initialize (when using webpack) by using:

```js
require('marko/components').init();
```
