### ISSUE TITLE
IE 10 throws an undefined error looking for Map in helper-forEachProperty.js

### ISSUE THREAD

**Issue by smulder** [marko-js/marko#739]
### Context
When loading a component wrapped in a lasso-async loader IE was throwing a Map ins undefined error.

### Expected Behavior
No error, and correct graceful degradation

### Actual Behavior
SCRIPT5009: 'Map' is undefined

### Possible Fix
} else if (o.forEach && typeof Map && o instanceof Map) {

<details><summary>Additional Info</summary>

### Your Environment
* Version used: Marko 4.4.13
* Environment name and version (e.g. Chrome 39, node.js 5.4): IE 10
* Operating System and version (desktop or mobile): Windows 8
* Link to your project:

### Stack Trace

</details>

**Comment by austinkelleher** [comment]
@smulder I just opened PR #740. Waiting for review and I'll merge/publish a new version. I don't have a Windows machine, so I cannot test on IE. Let me know if this fix works for you.

**Comment by austinkelleher** [comment]
Published `marko@4.4.15` with this fix. Let me know if you see any other issues. Thanks!
