### ISSUE TITLE
Append params to resources

### ISSUE THREAD

**Issue by design-media** [marko-js/marko#743]
Similar to urlPrefix, there should be a config to append a string to each resource.

For example, add to each resource (CSS, JS), a GET parameter when requesting the resource:
` <link rel="stylesheet" href="%CDN_URL%/static/page.css?%PARAM%=%VALUE%"> `
...
` <script src="%CDN_URL%/static/page.js?%PARAM%=%VALUE%"></script> `

It's very useful for cache busting, versioning, data center selection, etc.

**Comment by patrick-steele-idem** [comment]
Are you using Lasso or Webpack? If you are using Lasso then Lasso is generating the HTML code for the `<link>` and `<script>` tags (not Marko).

**Comment by design-media** [comment]
I'm using lasso.

**Comment by design-media** [comment]
I've also raised an issue in lassojs project https://github.com/lasso-js/lasso/issues/206
