### ISSUE TITLE
"mount" is first event emitted on browser?

### ISSUE THREAD

**Issue by newyork-anthonyng** [marko-js/marko#744]
## Bug Report
The [documentation](http://markojs.com/docs/components/#codeonmountcode) says that `mount` is the first event that is emitted on the browser for a server-rendered component.

The illustration on the website also makes it seem like `mount` is called first on the browser, and then `render` afterwards.

![screen shot 2017-06-22 at 8 16 55 pm](https://user-images.githubusercontent.com/14035529/27465544-0ccec7de-5789-11e7-8501-cb619b90dfdd.png)

However, it looks like `render` is the first event emitted on the browser.

### Context

I was going through this [issue](https://github.com/marko-js-samples/marko-redux/issues/1) from the [marko-redux](https://github.com/marko-js-samples/marko-redux) repository. I was trying to create an example of server-side rendering using `redux`. I was relying on the life-cycle illustration and ran into issues.
My inline JavaScript code was relying on things I thought would have already been initialized inside `onMount`.

### Expected Behavior

Please see this [repo](https://github.com/newyork-anthonyng/marko-lifecycle) that I created using `marko-starter`. I added a `console.log` to the `onCreate`, `onInput`, `onRender`, and `onMount` events.

On the server-side, I expected the order of the `console.log` to be:
```
1. Create
2. Input
3. Render
```

On the browser, I expected the order of the `console.log` to be:
```
1. Mount
2. Render
```

### Actual Behavior

The server-side events fired in the order I expected.
![screen shot 2017-06-22 at 8 13 47 pm](https://user-images.githubusercontent.com/14035529/27465469-8df4326e-5788-11e7-9432-0162fffcb6ed.png)
However on the browser, the `render` event fired off first.
![screen shot 2017-06-22 at 8 13 40 pm](https://user-images.githubusercontent.com/14035529/27465497-b04458f8-5788-11e7-9003-2ea79f3a8814.png)

I'm not sure if I'm misunderstanding the documentation, or if this is a bug. I'm a newbie to Marko, so any info would be greatly appreciated 👍 

### Possible Fix

<details><summary>Additional Info</summary>

### Your Environment

* Version used:
* Environment name and version (e.g. Chrome 39, node.js 5.4):
* Operating System and version (desktop or mobile):
* Link to your project:

### Steps to Reproduce

1. Go to this [repository](https://github.com/newyork-anthonyng/marko-lifecycle)
2. Run `npm start`
3. Look at the `console.log`s in your terminal
4. On your browser, go to `localhost:8080` and view the `console.log`s

### Stack Trace

</details>

**Comment by patrick-steele-idem** [comment]
We actually made some changes as part of the `marko@4.4` release that impacted the lifecycle methods and how the UI component tree was mounted in the browser when initially rendered on the server. Previously, the lifecycle events were as described in the docs, but now marko will do a "lightweight re-render" (the DOM is not actually updated) to rebuild the UI component tree in the browser. We need to revisit the docs. 

Also, I think the following is a better diagram for the lifecycle events:
![marko-lifecycle](https://user-images.githubusercontent.com/978214/27465873-8830ff14-5793-11e7-87bb-bc327add664c.png)

[PDF version](https://github.com/marko-js/marko/files/1096705/marko-lifecycle.pdf)

**Comment by newyork-anthonyng** [comment]
@patrick-steele-idem Thanks for the quick reply. This explains the weirdness I was seeing.

As for the docs, is the only thing that needs to be updated the [section](http://markojs.com/docs/components/#codeonmountcode) concerning `onMount`? I can create a PR to update it to include a description of the "lightweight re-render".

**Comment by DylanPiercey** [comment]
The documentation is now updated.
