### ISSUE TITLE
Lost `out.global` data when calling `this.forceUpdate()`

### ISSUE THREAD

**Issue by kpping** [marko-js/marko#748]
I have used server side rendering with express and set global data like this:

```javascript
router.get('/', (req, res) => {
    res.marko(template, {
        $global: {
            foobar: 'foobar'
        }
    });
});
```

Then I used it in component like this:

```marko
class {
    onMount() {
        this.forceUpdate();
    }
}

<h1>${ out.global.foobar }</h1>
```

What I expect:

```marko
<h1 id="s0">foobar</h1>
```

But actual is:
```marko
<h1 id="s0"></h1>
```

Is this an expected behavior ? If so, how can I maintain the passed data from server ?

Thank you.

**Comment by kpping** [comment]
What I do for workaround:

``` marko
class {
    onCreate() {
        this.state = {
            foobar: ''
        }
    }

    onInput(input, out) {
        this.state.foobar = out.global.foobar;
    }
}

<h1>${ state.foobar }</h1>
```

**Comment by patrick-steele-idem** [comment]
Unfortunately, we can't just serialize everything in `out.global` to the browser. Instead, you must explicitly tell Marko which globals to serialize. Please see: [markojs.com - Server-side Rendering - Serializing globals](http://markojs.com/docs/server-side-rendering/#serializing-globals)

Let us know if that resolves your issue.

**Comment by kpping** [comment]
Thank you for the answer . It's clear enough. It solved my problem. 😄
