### ISSUE TITLE
[Proposal] Inner components

### ISSUE THREAD

**Issue by patrick-steele-idem** [marko-js/marko#752]
Example usage:

```marko
component greeting {
  <div>
    Hello ${input.name}!
  </div>
}

<greeting name="Frank" />
<greeting name="Jane" />
```

Why is this helpful? We can replace macros with inner components for improved clarity. In addition, inner components are real components that are more powerful. Inner components could also have `class` and `style` that could eventually be split out into a separate `.marko` file if needed with minimal code changes:

```marko
component toggle-button {
  class {
    onClick() {
    }
  }
  <button.toggle-button ...>
    ...
  </button>
}

<toggle-button label="Click Me" />
```

# Open questions

## Local variables for inner components?

If a UI component is imported it can be assigned to a local variable:

```marko
import MyButton from './my-button.marko';
<my-form button-template=MyButton />
```

How could this be done for inner components? Maybe create a variable with tag converted to title case?:

```marko
component my-button {
  <button></button>
}

<my-form button-template=MyButton />
```

Or maybe just stick with title case throughout?

**Comment by ianvonholt** [comment]
Is this just a cleaner way to do inline components, rather than split them into full fledged .marko files?

If so, is there any inherit benefit to this approach over just making a .marko file component?

**Comment by DylanPiercey** [comment]
The Marko 6 API is going in a different direction.
