### ISSUE TITLE
Module fs not found when on require('zerorpc')

### ISSUE THREAD

**Issue by BryceHR** [marko-js/marko#753]
### Context

App was created using marko-devtools : marko create xxx

in component.js
```
var pubsub = require('raptor-Pubsub');
var zpc = require('zerorpc');
module.exports = class {...

```

### Actual Behavior

```
Render async fragment error (lasso-slot:head). Exception: Error: Failed to walk dependency [require: ./component]. Dependency chain: [require: C:\Users\Bryce\Desktop\remoteTerminal\src\components\app-terminaltab\index.marko] → [require: ../app-terminal] → [require: C:\Users\Bryce\Desktop\remoteTerminal\src\components\app-terminal\index.marko] → [require: ./component]. Cause: Error: Module not found: fs (from "src\components\app-terminal" and referenced in "src\components\app-terminal\component.js")
```

### Possible Fix

<details><summary>Additional Info</summary>

### Your Environment

* Version used:
* Environment name and version (e.g. Chrome 39, node.js 5.4):
* Operating System and version (desktop or mobile):
* Link to your project:

### Steps to Reproduce

1. 
2. 
3. 
4. 

### Stack Trace

</details>

**Comment by mlrawlings** [comment]
It looks like `zerorpc` is designed to run in node only, not the browser.  From the site (emphasis mine):
> zerorpc is a light-weight, reliable and language-agnostic library for distributed communication **between server-side processes**.
