### ISSUE TITLE
<var> element is interpreted as a tag

### ISSUE THREAD

**Issue by vp2177** [marko-js/marko#763]
### Context

Trying to use `<var>` elements in my template

### Expected Behavior

Not a major thing but should work 

### Actual Behavior

It is apparently interpreted as the `var` tag which I didn't find mentioned in the docs

### Possible Fix

Potentially just document `var`?

<details><summary>Additional Info</summary>

### Your Environment

* Version used: 4.4.18
* Environment name and version (e.g. Chrome 39, node.js 5.4): -
* Operating System and version (desktop or mobile): 
* Link to your project:

### Steps to Reproduce

1. `<var>a</var>`
2. 
3. 
4. 

### Stack Trace

</details>

**Comment by austinkelleher** [comment]
Hey, thanks for the report. That is correct, `<var>` is currently compiled down to a JavaScript `var`. It is deprecated in Marko v4 and it will be removed in Marko v5. We had it documented, but removed the documentation to discourage people from using this method. In Marko v4, we've replaced the `<var>` tag with an alternative to adding arbitrary JavaScript code to your template using `$`:

```marko
$ var name = 'John';

<div>${name}</div>
```

Multiple statements:

```marko
$ {
  var name = 'John';
  console.log('Name: ', name);
}

<div>${name}</div>
```

**Comment by vp2177** [comment]
Yes I was trying to output the HTML `<var>` element.

Looks like that will be possible with v5, thank you.

**Comment by patrick-steele-idem** [comment]
As a workaround to output `<var>` you can do the following:

```marko
<${'var'} foo='bar' />
```

Output:

```html
<var foo="bar"></var>
```
