### ISSUE TITLE
Question - include in component/script

### ISSUE THREAD

**Issue by cameronbraid** [marko-js/marko#766]
I would like to be able to use the **include** tag function form a component, like the following 

custom-tag.marko
```
class {
  onMount() {
    var content = include(this.input.content)
    require("someApi").show(content)
 }
}
<span>
<include(input.body)/>
</span>
```

page.marko
```
<custom-tag>
  <@content><b>welcome</b></@content>
  <@body> Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed et pellentesque erat. Maecenas vitae ultricies ipsum. Sed sed enim fermentum, suscipit odio ac, pellentesque augue</@body>
</custom-tag>
```

At the moment there is no way to call the **include** function from code, but I need to do the following 

custom-tag.marko
```
class {
  onMount() {
    var content = this.getEl("content").innerHTML
    require("someApi").show(content)
 }
}
<span>
<include(input.body)/>
<span key='content' style='display:none'><include(input.content)/></span>
</span>
```

**Comment by DylanPiercey** [comment]
You can currently pass the renderBody (in your case `input.content`) to `require("someApi").show` which can then use an `<include` tag in it's renderer. I don't think you should need this ability inside of a component since it only makes sense for rendering.
