### ISSUE TITLE
Auto-upgrade component

### ISSUE THREAD

**Issue by mlrawlings** [marko-js/marko#770]
### Description & Context

There are certain properties that only work within the context of a component.  The following will fail:
```marko
<div key="foo"/>
```
However adding an empty class allows it work:
```marko
class {}
<div key="foo"/>
```

It would be nice to have marko just "upgrade" the component and act as if there were an empty `class{}` instead of throwing an error.

### Attributes

- [ ] `key` and `*:key`
- [ ] `on-*()` and `emit()` see #463 

### Is this something you're interested in working on?

Yes

**Comment by mlrawlings** [comment]
This should actually upgrade to a "split" component.  The equivalent of having a `component-browser.js` that exports an empty object.

**Comment by Joeao** [comment]
Somewhat relevant, not sure if it's worth opening another issue as it may be intended behaviour.
Just having:
```html
<div id="foo"></div>
```
with no `class {}` will result in the component not being accessible through `.getComponent()`. Your proposition would fix this issue.

**Comment by mlrawlings** [comment]
The latest beta version makes every template a component.
