### ISSUE TITLE
Syntax error undetected on single file component

### ISSUE THREAD

**Issue by Joeao** [marko-js/marko#774]
### Context
A single space as seen below causes the `__component` attribute to be null on a rendered component element.
```javascript
class {
    showBackdrop() {
        Velocity(document.querySelectorAll('.modal-backdrop.in'), {
            opacity: [0.5,0]
        });
    }
}
 // Single space here
<div class=["modal", "remove", "in", input.class]>
    <div class="modal-dialog ">
        <div class="modal-content ">
            <include(input.body)/>
        </div>
    </div>
</div>
```

### Expected Behavior
An error/warning would be shown when building, either stating that the component is incomplete or that there is a syntax error.

### Actual Behavior
The `__component` attribute of the Component object will be `null` rather than `undefined` and the component will not append.

<details><summary>Additional Info</summary>

### Your Environment
* Version used: 4.4.19
* Environment name and version (e.g. Chrome 39, node.js 5.4): Chromium V59.0.3071.109. Node 6.11
* Operating System and version (desktop or mobile): Ubuntu 16.04

### Steps to Reproduce
1. Clone [Start Demo](https://github.com/marko-js-samples/marko-starter-demo) or any repo with a single file component
2. Remove style attributes from component, so you're left with class followed by HTML
3. Add a space in the line between the class and the HTML
4. Load page - component won't be loaded

</details>

**Comment by cameronbraid** [comment]
I had a similar issue today..

```
class {

}
 <div>space before div</div>
```

No error was reported, and the component was not rendered

**Comment by DylanPiercey** [comment]
This now throws an error during compile.
