### ISSUE TITLE
Question: this.state is undefined - websocket.onmessage

### ISSUE THREAD

**Issue by fmpwizard** [marko-js/marko#777]
I'm writing a simple chat component that uses websocket for communication, js is:

```
export default class {
 ...
  onInput(input) {
    this.state = {
      messages: ['diego']
    }
  }
  onMsg(evt) {
    const messages = evt.data.split('\n')
    Logger.info('item ', messages)
    Logger.info('state ', this.state)
  }
 ... // more stuff here
  onMount() {
    this.conn = new WebSocket('ws://<ip:port>/api/pages/ws')
    this.conn.onclose = this.onClose
    this.conn.onmessage = this.onMsg
  }
```

I can establish the ws connection, but when the onMsg function is called, state is undefined. I think this is because `this` isn't the component any more, but how do I change this code so that when ws calls the onmessage callback, marko knows that it should use the `this` from the component?

The line `Logger.info('item ', messages)` prints the msg I got from the server.

Thanks

**Comment by mauricionr** [comment]
maybe `this.conn.onmessage = this.onMsg.bind(this)` ?

**Comment by fmpwizard** [comment]
yes! thank you!

**Comment by Joeao** [comment]
@fmpwizard you should close this issue if it's resolved. Also I advise you use Stackoverflow or head to this project's gitter channel to ask questions which aren't related to bugs or feature requests as it makes things easier for the developers of this wonderful project

**Comment by fmpwizard** [comment]
sure, thank! I'll ask on Stackoverflow next time
