### ISSUE TITLE
Documentation for @ tags is lacking

### ISSUE THREAD

**Issue by patrick-steele-idem** [marko-js/marko#787]
## Relevant Gitter discussion:

@mccarvell Aug 05 10:03

> I am using Marko server side with Node. If I have a parent template that has a line like this:
```marko
<@name>Greg</@name>
````
> In a child template I would expect these to have the same output but they do not:

```marko
<include(input.name)/> //works
${input.name} //does not work
```

> What difference am I missing? Are these supposed to be interchangable?

## Answer in Gitter discussion

Patrick Steele-Idem @patrick-steele-idem 09:43

> @mccarvell When using an `@` tag you have to use `<include>` to render the nested content since since `@` tags result in an input object with `name` property with an object value that has  a `renderBody()` function similar to the following:

```js
{
  name: {
    renderBody: function(out) {
      out.t('Greg');
    }
  }
}
```

> If you just want to pass string data you would do the following:

```marko
<my-custom-tag name="Greg" />
```

> Which would result in the following `input` object being passed to the custom tag:

```js
{
  name: 'Greg'
}
```

> The benefit of the `@` tag is that the callee can choose when and where to invoke the function to actual render out the nested HTML content. Just think of `@` tags as being used to pass complex HTML content while attributes are used to pass JavaScript values (strings, numbers, booleans, objects, etc.)

**Comment by oldcai** [comment]
1. Is there a way to iterate all the attributes of a @ tag? That would be more flexible when we passing attributes to a child tag.

2. If we only need to define some of the tag types not recognized by marko automatically (like arrays) in `marko-tag.json`, it would be awesome.
