### ISSUE TITLE
Allow await tag without a var

### ISSUE THREAD

**Issue by austinkelleher** [marko-js/marko#788]
Currently we require that each `<await>` has a `var` and a `from`:

```marko
<await(p from Promise.resolve())/>
```

Since JavaScript allows the following:

```js
await Promise.resolve()
```

We should also allow it in Marko without requiring a var with the returned data:

```marko
<await(Promise.resolve())/>
```

**Comment by patrick-steele-idem** [comment]
Do you have a use case in mind?

**Comment by austin-rausch** [comment]
+1 for consistency between JS and Marko

**Comment by ulivz** [comment]
Nice! we are using this way in our client code to initialize our `fetch`.

**Comment by DylanPiercey** [comment]
This is now supported.
