### ISSUE TITLE
[Docs] Add docs for boolean attributes

### ISSUE THREAD

**Issue by patrick-steele-idem** [marko-js/marko#800]
- `<input type="checkbox" checked=true>`  → `<input type="checkbox" checked>`
- `<input type="checkbox" checked=false>`  → `<input type="checkbox">`

See: http://markojs.com/try-online/?file=%2Fmarko-language-guide%2Fcomponents%2Fattributes%2Fboolean.marko&gist=

**Comment by ulivz** [comment]
Nice 👍

**Comment by patrick-steele-idem** [comment]
@riktimmondal I know docs may be less exciting than working on code, but would you be interested in taking on a small task to add some missing documentation? If so, it would be greatly appreciated if you could submit a PR to the following file to include some of the information above: https://github.com/marko-js/marko/blob/master/docs/syntax.md
