### ISSUE TITLE
Syntax to define the template of a component

### ISSUE THREAD

**Issue by Gillespie59** [marko-js/marko#805]
Even if I am not a big fan of this syntax, I understand why we need to add the extra --- before a template when we do not have a root element. But... :D I spent 20 minutes on this error, only because i have few empty spaces before my root element :s

![image](https://user-images.githubusercontent.com/555768/29370983-51d6ace0-82a7-11e7-9cad-1156517e4421.png)

**Comment by patrick-steele-idem** [comment]
@Gillespie59 Thanks for opening the GitHub issue!

@austinkelleher Do you mind taking a look at this?

**Comment by austinkelleher** [comment]
Hey, @Gillespie59! Sorry that you had trouble debugging this!

So I assume you had something like this (starting in concise mode)?

```marko
script
 Test
```

Ultimately, in concise mode, indentation is important, so having a leading space without a double dash will cause the parser to behave differently.

For example, you will also see the same error in a scenario like this:

```marko
// HTML `script` tags only allow text content
script
    p - This is not allowed
```

We need to do a better job at describing compile time errors. I think we should add a new GitHub wiki page to the Marko parser ([`htmljs-parser`](https://github.com/marko-js/htmljs-parser/)) that describes each error that can be thrown by the parser. Then we can update each of the error messages thrown by the parser with a link to the wiki page which will contain examples of the errors.

Any thoughts?

**Comment by Gillespie59** [comment]
In fact when I saw this error message in my console, I understood it quickly. So I added the double dash, and everything was working. But I wanted to understand why... because my HTML was self-sufficient i thought, and few minutes after, I found these extra spaces... :D 

```html
<div id="background">
    <div id="result">${state.formula}</div>
    <calculator formula=state.formula on-update('update') />
</div>
```

Do you have any reason not to use the standard `template` HTML tag ?

**Comment by patrick-steele-idem** [comment]
Typing on phone, but just wanted to say that we chose not to hijack any standard HTML tags in Marko. We want the standard <template> tag to render as <template>.

**Comment by patrick-steele-idem** [comment]
Suppose to be the following but apparently I can't edit a comment on mobile: We want the standard template tag to render as template.

**Comment by Gillespie59** [comment]
mm I understand why it is complicated to find a solution :D. I think that's the reason Angular has created the ng-template directive.

**Comment by patrick-steele-idem** [comment]
We also aim to avoid all boilerplate and to also avoid any references to "Marko" in your view code to keep Marko only working behind the scenes.

**Comment by austinkelleher** [comment]
I'm going to go ahead and close this out. Please let us know if you have any additional questions.
