### ISSUE TITLE
[Proposal] Do not render ID attributes for keyed elements

### ISSUE THREAD

**Issue by patrick-steele-idem** [marko-js/marko#819]
Currently, when doing the following:

```marko
class { ... }

<div key="root"></div>
```

Marko will output something similar to the following:

```html
<div id="s0-root"></div>
```

We do this because we know that the browser will index nodes with IDs and we can use `document.getElementById('s0-root')` to get the DOM element. However, we want to get away from using IDs to do keyed matching to improve server-side rendering performance to avoid issues with users assigning duplicate IDs (which result in strange behavior when doing DOM diffing/patching). We also want to assign keys at compile time to elements and UI components to improve DOM diffing and patching.

# Solution

The solution is to maintain our own index of DOM nodes to add DOM nodes into the index when a VDOM node is converted over to a real DOM node. The key will be a property of the VDOM node. In addition, in the browser we can use a special wrapper VDOM node to mark the boundary of a UI component. That is, every UI component will be wrapped in a VDOM node that will not map to a real DOM node. In addition, we will remove nodes out of the index when we discard a DOM node during DOM diffing/patch or when a UI component is explicitly destroyed (we already walk the DOM in both cases).

We do not need to pass key information down for UI components that will be re-rendered in the browser. For split UI components that will not be rendered in the browser will need to store the keys in the DOM (e.g. `data-markoid`).

We should see improved performance on both the server and in the browser.

Tasks:

- [ ] Store keyed lookups with the component

**Comment by fierysunset** [comment]
I'm all for this of course, as IDs in our app, created based on keys explicitly set, are definitely ballooning out in length. However, the piece we'll have to watch out for is the issue as mentioned in https://github.com/marko-js/marko/issues/822 with a missing ID will be a lot harder to debug without the explicit IDs. We need to ensure that dynamically created IDs are _always_ present in the markup.
