### ISSUE TITLE
[Docs] 404 when typing in http://markojs.com/docs/

### ISSUE THREAD

**Issue by danmarshall** [marko-js/marko#820]
### Context
While reading the **excellent 👍** docs, I wanted to go to the documentation home page. I just hacked the url to http://markojs.com/docs/

### Expected Behavior
Go to documentation home page

### Actual Behavior
404

### Possible Fix
Perhaps you could redirect /docs/ to /docs/introduction-overview/ 

### Your Environment
The web

### Steps to Reproduce
1. Try to visit http://markojs.com/docs/

**Comment by austinkelleher** [comment]
Hey @danmarshall. Thanks for the report. I agree that the behavior is incorrect. We are using https://github.com/marko-js/marko-starter with the website and it currently does not support client redirects. This is something we've been talking about supporting. I opened https://github.com/marko-js/marko-starter/issues/12 to track this issue.
