### ISSUE TITLE
Webpack build throws warning when target is NODE

### ISSUE THREAD

**Issue by jasonmacdonald** [marko-js/marko#823]
### Context
When compiling marko for server side rendering with Webpack, it throws a warning of...

```
(undefined) /.../node_modules/marko/src/runtime/dependencies/index.js
38:41-48 Critical dependency: require function is used in a way in which dependencies cannot be statically extracted
```
NOTE: This does not appear to break functionality, but does cause the warning.

### Expected Behavior
Shouldn't be included by Webpack build.

### Actual Behavior
Is included by Webpack.

### Possible Fix
Current fix is to use the ContextReplacementPlugin to basically tell Webpack to ignore the file by supplying what should be run at runtime. This is just faked, since Marko does not use the file at runtime from what I can tell.

NOTE: You will also need to set the env variable `BUNDLE` to `true`, this is not documented anywhere I can find, but Webpack will blow-up without it! Also, you need to set the options for marko-loader to have `target` equal to `server` - also not documented anywhere, and frankly confusing. Why do you need `target NODE` for webpack and `target server` for the marko-loader, why not just use Webpacks target? (https://github.com/marko-js/marko-loader/issues/18)
```
{
    module: {
        rules: [
            {
                test: /\.marko|\.html$/,
                exclude: /node_modules/,
                use: [
                    {
                        loader: 'marko-loader',
                        options: {target: 'server'} // need to set this or marko loader won't compile for server
                    }
                ]
            }]
   },
    plugins: [
        // required for marko server side build to work:  this should really be documented
        new webpack.DefinePlugin({'process.env': {'BUNDLE': '"true"'}}),

        // gets rid of warning from webpack about require not being statically resolved. 
        //new webpack.ContextReplacementPlugin(/runtime\/dependencies/, /runtime\/dependencies/)
    ]
})
```

### Your Environment

* Version used: 4.4.26
* Environment name and version (e.g. Chrome 39, node.js 5.4): Node 7.10.1
* Operating System and version (desktop or mobile): MacOS Seirra
* Link to your project:

### Steps to Reproduce

1. Create a project which uses Babel and Webpack to compile server side
2. Choose target in Webpack to be "node"
3. Try to build

### Stack Trace

```
(undefined) ...node_modules/marko/src/runtime/dependencies/index.js
38:41-48 Critical dependency: require function is used in a way in which dependencies cannot be statically extracted
at CommonJsRequireContextDependency.getWarnings (...node_modules/webpack/lib/dependencies/CommonJsRequireContextDependency.js:27:4)
at Compilation.reportDependencyErrorsAndWarnings (...node_modules/webpack/lib/Compilation.js:694:24)
at Compilation.finish (...node_modules/webpack/lib/Compilation.js:552:9)
at applyPluginsParallel.err (...node_modules/webpack/lib/Compiler.js:512:17)
at ...node_modules/tapable/lib/Tapable.js:289:11
at _addModuleChain (...node_modules/webpack/lib/Compilation.js:498:11)
at processModuleDependencies.err (.../node_modules/webpack/lib/Compilation.js:468:14)
at _combinedTickCallback (internal/process/next_tick.js:73:7)
at process._tickCallback (internal/process/next_tick.js:104:9)
```
</details>

**Comment by jasonmacdonald** [comment]
I tried to follow the code to figure out exactly where this is getting included, but unfortunately debugging during a Webpack build is very difficult. This does not happen if the target is set to "web", but then of course Marko includes code that has "window" in it and therefore won't run on the server.

**Comment by DylanPiercey** [comment]
@jasonmacdonald this issue is because there are actually some Marko templates that need to be compiled in the Marko package (inside your node_modules).

If you change your Marko-loader's exclude option to look like this:

```js
{
      test: /\.marko|\.html$/,
      exclude: /node_modules(?!\/marko)/,
      loader: 'marko-loader',
      options: { target: 'server' }
}
```

It should work. 😀

**Comment by jasonmacdonald** [comment]
@DylanPiercey Unfortunately, you still get the error even with the exclude.

**Comment by mlrawlings** [comment]
It might be that when `BUNDLE` is true we should exclude the dependency metadata and related code.  This would be making the assumption that if you're bundling your server code you're also bundling your client code and therefore all the dependency stuff was handled at build time.

**Comment by jasonmacdonald** [comment]
NOTE: my fix of using `ContextReplacementPlugin` has stopped working and the warning has returned. :( Only way I seem to avoid it is if I set externals for all of marko, but then the server side build requires marko to be installed on the server, rather than a single bundle. I'll keep digging.

**Comment by DylanPiercey** [comment]
Fixed in newer `@marko/webpack` releases.
