### ISSUE TITLE
Preserve attribute names in custom tags

### ISSUE THREAD

**Issue by rubennorte** [marko-js/marko#824]
### Context
I have a template that accepts any HTML attribute from its parents this way:

```
$ const { src, ...attrs } = input;
<img src=src ${attrs} />
```

The problem is that Marko is automatically converting those attribute names to camelCase:

```
<my-img src="..." data-prop="value" />
=> <img src="..." dataProp="value" />
```

I'm trying to configure that behaviour using a `marko.json` file but it's not working as expected (I'm placing the `marko.json` file in the `components/` directory where the template is):

```json
{
  "<*>": {
    "@*": {
      "preserve-name": true
    }
  }
}
```

### Expected Behavior

It should preserve the attributes:

```
<my-img src="..." data-prop="value" />
=> <img src="..." data-prop="value" />
```

### Actual Behavior

It's ignoring the `marko.json` file:

```
<my-img src="..." data-prop="value" />
=> <img src="..." dataProp="value" />
```

As a workaround I'm doing:

```
<my-img src="..." ${{ 'data-prop': 'value' }} />
=> <img src="..." data-prop="value" />
```

### Your Environment

* Node.js 6.11 in Alpine Linux (Docker)

**Comment by mawrkus** [comment]
Hi,

I've been able to make it work with this config under Marko 4.16.3:

```json
{
  "tags": {
    "*": {
      "@data-qa": {
        "type": "string",
        "preserve-name": true,  
        "remove-dashes": false
      }
    }
  }
}
```

**Comment by Arti360** [comment]
> Hi,
> 
> I've been able to make it work with this config under Marko 4.16.3:
> 
> ```json
> {
>   "tags": {
>     "*": {
>       "@data-qa": {
>         "type": "string",
>         "preserve-name": true,  
>         "remove-dashes": false
>       }
>     }
>   }
> }
> ```

Hi!
This also works under Marko 4.7.5

Thanks for the solution!
