### ISSUE TITLE
Proposal for Scoped CSS and client side routing 

### ISSUE THREAD

**Issue by anupdineout** [marko-js/marko#825]
When we can expect scooped css and client side routing for marko v4

**Comment by austinkelleher** [comment]
Hey @anupdineout. We've been discussing scoped CSS in #666. We do not have an officially supported Marko router yet, but https://github.com/charlieduong94/marko-path-router supports client side routing and there are a few projects that are using it. 

We do not have an exact timeline of when to expect scoped CSS or a officially supported router right now. Hopefully in the coming months. Scoped CSS is one of our priorities. Definitely follow the thread in #666 if you're interested or have some ideas of your own.

I'm going to close this for now, but feel free to ask additional questions if you have them. Thanks!
