### ISSUE TITLE
Deprecate component.elId and component.getElId

### ISSUE THREAD

**Issue by mlrawlings** [marko-js/marko#843]
We have two component methods (`component.elId` and `component.getElId`) that do the same thing and were in some cases used within templates along side `key` to create scoped component ids before `:key` was introduced.

```marko
<label for=component.getElId('name')>Name</label>
<input key="name"/>
```

Because `key` no longer creates an `id` on the element, this would break with the new behavior.  We have preserved this behavior in #840, but would like to move users away from this with a deprecation warning.  The most straight-forward path is to rename the function.

@patrick-steele-idem has thrown out the following possible alternatives:
- `component.uniqueId(scopedId)`
- `component.uid(scopedId)`

**Comment by patrick-steele-idem** [comment]
`component.uid(scopedId)` feels a little more cryptic. I'm leaning towards `component.uniqueId(scopedId)`. Thoughts?

**Comment by austinkelleher** [comment]
I don't like `uid` either. It reminds me of a uuid, which it is not. I like `uniqueId(...)` too.

**Comment by mlrawlings** [comment]
Blocked by #871

**Comment by DylanPiercey** [comment]
This was deprecated in #916.
