### ISSUE TITLE
Manually triggering .marko template to compile - problem with include paths

### ISSUE THREAD

**Issue by sirceljm** [marko-js/marko#846]
Hi,

I am using the https://github.com/marko-js-samples/marko-webpack to experiment.

I am trying to compile the tree of .marko templates to one compiled file to be used with AWS Lambda. I managed to bundle all precompiled index.marko.js files into one with webpack and it seems to be working fine. The problem I have right now is, that I get errors if I try to manually trigger compilation of the main template with this code:

```
require('marko/compiler').configure({ requireTemplates: true });
require('marko/node-require');

require.extensions['.marko'](module, "./src/pages/home/template.marko");
``` 

It complains: Error: Cannot find module 'src/layouts/default' 
However if I use <include("./src/layouts/default")> instead of <include("src/layouts/default")> it compiles but then the webpack bundle has problems with paths.

If I try to compile by running the server.js everything works fine.

Is there an extra step that I should do or does there exist another way to manually compile .marko template to .marko.js?

**Comment by patrick-steele-idem** [comment]
@sirceljm Michael Rawlings (@mlrawlings) introduced support for precompiling `.marko` files to `.js` files so that the Node.js require hook would not need to be used in production. I'm not sure if the work is completely done, but we aim to support the following via the [Marko CLI](https://github.com/marko-js/marko-cli)

```
marko compile src/
```

Please give that a try. I will sync up with Michael tomorrow to figure out where we are with support for precompiling templates.

@mlrawlings can you please put the finishing touches on support for pre-compilation (including documentation)?

**Comment by patrick-steele-idem** [comment]
FYI, here is the code for the `marko compile` command if you want to take a closer look: https://github.com/marko-js/marko-cli/blob/master/src/commands/compile/run.js

**Comment by patrick-steele-idem** [comment]
Regarding the webpack specific issue. I'm not as familiar with Webpack, but you will need to configure Webpack if you want to change how modules are resolved. The default Webpack config will allow relative paths and for non-relative paths Webpack will look for a corresponding module in your `node_modules` directory. Please see: https://webpack.js.org/concepts/module-resolution/

**Comment by mlrawlings** [comment]
Regarding the `Cannot find module` error:

In that project, webpack is configured to [resolve modules from the root of the project](https://github.com/marko-js-samples/marko-webpack/blob/master/webpack.config.js#L15).  The same behavior is made available in Node using [`app-module-path`](https://github.com/marko-js-samples/marko-webpack/blob/master/server.js#L1).  You'll need to add that line to your compile script if you want to use paths that resolve from the root of the project.

**Comment by austinkelleher** [comment]
I'm going to close this issue out because I think this is already fixed with `marko-cli`. Please feel free to re-open this issue or ask additional questions if necessary.
