### ISSUE TITLE
Use mocha-puppeteer for browser tests

### ISSUE THREAD

**Issue by austinkelleher** [marko-js/marko#851]
Right now we are using `mocha-phantomjs` for browser tests. We should switch to [mocha-puppeteer](https://github.com/charlieduong94/mocha-puppeteer/). [Puppeteer]() only supports Node 6+, so this means we will either have to:

1. Drop support for Node 4
2. Only run Puppeteer tests locally and run the mocha-phantomjs tests in the CI

When we finally replace mocha-phantomjs, we will have to implement stronger linting rules for our projects to ensure that we do not introduce ES6 code into files that can be run in the browser. phantomjs does not support ES6, so currently when we use ES6 in our browser code, the browser tests will break.

**Comment by DylanPiercey** [comment]
Closing this since we switched to jsdom.
