### ISSUE TITLE
Templates rendered with Node API don't include style dependencies

### ISSUE THREAD

**Issue by fineline** [marko-js/marko#857]
### Context
Trying to render a template with a style dependency to a string

### Steps to Reproduce
* Make a template with a separate style.css file

```
--src
----index.marko
----style.css
```

* Render in node script with renderToString

```javascript
const pageTmpl = require('./src/index')
const html = pageTmpl.renderToString()
```

### Expected Behavior
Rendered template includes styles from `styles.css`

### Actual Behavior
Rendered template does not include styles from `styles.css`

### Further info

I also tried including further nested components in `src/components` which had their own `styles.css` - same outcome, no styles rendered.

In a debugger, I can see that pageTmpl.meta.deps[0] is "./styles.css". But can't see how to get this dependency included in the rendered output.

### Your Environment
* marko v 4.4.28
* node v 7.6.0
* osx 10.12.6

**Comment by austinkelleher** [comment]
This is because Marko requires that a module bundler is used to bundle assets that are sent to the browser. See [`marko-express`](https://github.com/marko-js-samples/marko-express) as an example.

**Comment by austinkelleher** [comment]
Please feel free to ask any additional questions that you may have!

**Comment by fineline** [comment]
Thanks. I'm trying to render a styled Marko template to a static HTML page string suitable for viewing with JS disabled (e.g. email templates). I had thought renderToString() sounded like the right API endpoint and it does indeed produce the right output, but without styles - I'm not really sure what it's intended for any more. I shall continue to investigate Lasso to see if I can figure out the necessary pipeline.

**Comment by Robula** [comment]
@fineline Did you figure this out? I too am using Marko for templating only on the server. I am NOT passing a HTML string to a browser, so I'm certain that I don't require a module bundler. Correct me if I am wrong.

**Comment by andresilvasantos** [comment]
Interested as well.

**Comment by davidmurdoch** [comment]
@austinkelleher, marko docs state that `These blocks add global css to the page.` but they don't, at least not when using using the string render. Can we not use marko and its stream rendering to send a javascript-less SSR page to the browser?

**Comment by strogonoff** [comment]
Curious as well. Does it make it infeasible to use Marko to build fully static sites?

**Comment by DylanPiercey** [comment]
@strogonoff you definitely can, and with its islands approach is works pretty well. The standard approach is to take an existing server rendering setup and render all pages and dump the html to disk. We have a tool (https://github.com/marko-js/ssr-to-html) that does this. Here's an example project using it: https://github.com/DylanPiercey/marko-vite-fastify-ssg
