### ISSUE TITLE
Language Server

### ISSUE THREAD

**Issue by mlrawlings** [marko-js/marko#859]
We should create a language server to support our advanced editor features across multiple editors

**Comment by patrick-steele-idem** [comment]
Proposed features:
- Auto completion
- Code linting
- Hover docs
- Find references
- Go to definition
- Refactoring:
 - Tag names
- Extract "class" to a separate file
- Jump to symbols in a `.marko` file (methods, sections)
- Pretty printing
- ...what else?

**Comment by MaxMilton** [comment]
That would be amazing. I'm happy to help with it implemented in a VS Code extension :)

For reference here's the Vue equivalent:
Lang server: https://github.com/vuejs/vetur/tree/master/server
VS Code extension: https://github.com/vuejs/vetur

**Comment by austinkelleher** [comment]
@MaxMilton Thanks for your interest! @CestDiego is currently working on this and we should have this project open sourced in the near future. I'm sure that there will be additional features that you could help with if you want 👍 👍

**Comment by CestDiego** [comment]
So far we've got go to definition and jump to symbols in a marko file (only on the template ones) The tricky part about this is going to have multi-language-support

**Comment by DylanPiercey** [comment]
@CestDiego got this started 😄. Lets track future features over [here](https://github.com/marko-js/marko-language-server).
