### ISSUE TITLE
How to bundle Marko runtime with Lasso into a separate file?

### ISSUE THREAD

**Issue by kwep** [marko-js/marko#863]
I'm building a multi-page web app and I would like to bundle only the required Marko templates and scripts for a given page and all the runtime into a separate file using Lasso. So basically what I'm trying to do is to generate one `runtime.js` with all the shared code and one additional js file per page with the page specific components.

So far I managed to achieve this by giving every `lasso-page` a proper name, and defining a `bundles` section for Lasso:

```javascript
bundles: [
  {
    name: 'runtime',
    dependencies: [
      { path: 'require: marko/components', recurseInto: 'all' },
      { path: 'require: marko/index-browser', recurseInto: 'all' },
      { path: 'require: raptor-util/inherit', recurseInto: 'all' },
      { path: 'require: raptor-util/extend', recurseInto: 'all' },
      { path: 'require: raptor-util/copyProps', recurseInto: 'all' }
    ]
  }
]

```

Despite it's clunkiness it works sort of but I don't seem to find a way to include the Marko browser runtime located below `marko/[src|dist]/runtime` as it's cannot be referenced directly outside of the module.

Is there a way to achieve this?

**Comment by mlrawlings** [comment]
@kwep Take a look at https://github.com/lasso-js/lasso#code-splitting ...does that do what you need?

**Comment by DylanPiercey** [comment]
@kwep going to close this issue for now but please feel free to leave a message in the Gitter or comment back if you have any other questions or @mlrawlings solution did not solve your problem.
