### ISSUE TITLE
Child components are failing inside <await>

### ISSUE THREAD

**Issue by Acanguven** [marko-js/marko#864]
### Context
I am trying to build a component with await. But whenever I use await I am getting an error log on console and all child component methods are failing. But it still renders.

index.marko
```
class {
  onCreate(){
    this.state = {}
  }
}

<html-container>
  <@title>${input.currentPage}</@title>
  <@body-content>
    <header-component/>
    <await(boutiqeTabList from data.boutiqueTabsProvider)>
      <await-error>:(</await-error>
      <boutique-list-tabs tabs=boutiqeTabList.tabs/>
      <boutique-list-items/>
    </await>
  </@body-content>
</html-container>
```

boutique-list-tabs.marko
```
class {
  changeTab(){
    console.log('c');
  }
}
<div.category-menu>
  <ul>
    <li for(tab in input.tabs | status-var=loop) on-click('changeTab', loop.getIndex())>
      <span class=(input.selectedIndex == loop.getIndex() && 'selected')>${tab.Name}</span>
    </li>
  </ul>
</div>
```

### Expected Behavior
Promise resolved and components mount successfully.

### Actual Behavior
> TypeError: Cannot read property 'tabs' of undefined.

 

- It only happens when I add class to component. 
- Whenever I make <await> top most element there is no error but on-click still not working.

Promise is being resolved with the exact data I need, it renders everything but there is a console error TypeError: Cannot read property 'tabs' of undefined. And on-click('changeTab', loop.getIndex()) not being called when I click the li.

### Stacktrace

> Await (data.boutiqueTabsProvider) failed. Error: TypeError: Cannot read property 'tabs' of undefined
>     at renderBody (http://localhost:8080/static/index/tymweb$1.0.0/src/routes/index/index.marko.js:55:43)
>     at safeRenderBody (http://localhost:8080/static/index/marko$4.4.28/src/taglibs/async/await-tag.js:13:9)
>     at renderBody (http://localhost:8080/static/index/marko$4.4.28/src/taglibs/async/await-tag.js:118:37)
>     at requestData (http://localhost:8080/static/index/marko$4.4.28/src/taglibs/async/await-tag.js:61:9)
>     at awaitTag (http://localhost:8080/static/index/marko$4.4.28/src/taglibs/async/await-tag.js:142:5)
>     at Object.renderBody (http://localhost:8080/static/index/tymweb$1.0.0/src/routes/index/index.marko.js:47:13)
>     at doInclude (http://localhost:8080/static/index/marko$4.4.28/src/taglibs/core/include-tag.js:13:31)
>     at includeTag (http://localhost:8080/static/index/marko$4.4.28/src/taglibs/core/include-tag.js:30:5)
>     at render (http://localhost:8080/static/index/tymweb$1.0.0/src/components/html-container/index.marko.js:50:3)
>     at renderCompontent (http://localhost:8080/static/index/marko$4.4.28/src/components/taglib/helpers/renderComponent.js:3:5)

```
await_tag({
    clientReorder: true,
    _dataProvider: data.boutiqueTabsProvider,
    _name: "data.boutiqueTabsProvider",
    renderPlaceholder: function renderBody(out) {
      out.w("...");
    },
    renderBody: function renderBody(out, boutiqeTabList) {
      boutique_list_tabs_tag({
          tabs: boutiqeTabList.tabs, //boutiqeTabList is undefined here
          selected: state.selectedTab
        }, out);

      boutique_list_items_tag({
          boutiques: boutiqeTabList.boutiques[0]
        }, out);
    }
  }, out);
```

**Comment by Acanguven** [comment]
I wanted to add a new information. Whenever  I wrap with <if> everything works fine, if there is no boutiqeTabList in the beginning why <await> renders its child components?

```
<await(boutiqeTabList from bProvider)>
     <await-placeholder>...</await-placeholder>
     <if(boutiqeTabList)>
        <boutique-list-tabs tabs=boutiqeTabList.tabs selected=state.selectedTab/>
        <boutique-list-items boutiques=boutiqeTabList.boutiques[0]/>
     </if>
</await>
```

**Comment by patrick-steele-idem** [comment]
Can you please let us know if the `4.5.0` release fixes this issue? There were related changes: https://github.com/marko-js/marko/blob/master/CHANGELOG.md#450

**Comment by Acanguven** [comment]
Problem solved, thank you!
