### ISSUE TITLE
Deprecate auto-patched express

### ISSUE THREAD

**Issue by mlrawlings** [marko-js/marko#869]
We currently support two ways of injecting `res.marko` into `express`.

Autopatch:
```js
require('marko/express')
var app = require('express')();
var template = require('./template.marko');
app.get('/', (req, res) => res.marko(template);
```

Middleware:
```js
var app = require('express')();
var markoExpress = require('marko/express');
var template = require('./template.marko');
app.use(markoExpress);
app.get('/', (req, res) => res.marko(template);
```

Let's deprecate the former (autopatch).

**Comment by patrick-steele-idem** [comment]
For further clarification:

If `res.marko()` is used and `app.use(markoExpress);` was not used to patch `res` then we should show a deprecation warning.

**Comment by ajay2507** [comment]
If the former is used, then we have to show the depreciation warning right?. Can I take this one?.
