### ISSUE TITLE
Parser support for attribute modifier syntax.

### ISSUE THREAD

**Issue by mlrawlings** [marko-js/marko#870]
### Description

I would like the parser to take an attribute like `id:scoped="123"` and produce something like:
```js
{
  name: "id",
  modifiers: ["scoped"],
  value: "123"
}
```

You should also be able to register transformers for a modifier.

### Why

We currently support attribute modifiers like `:scoped` and `:no-update`, but the attribute name includes the modifier and then it has to be stripped out at the transform stage. 

When registering a transformer for a modifier that can be used on any attribute, you have to check all attributes, it would be nice if marko did a bit of that work for you.

**Comment by DylanPiercey** [comment]
The current plan is to phase modifiers out of the language. Closing this issue for now.
