### ISSUE TITLE
Provide context object visible to any component in a subtree

### ISSUE THREAD

**Issue by mlrawlings** [marko-js/marko#872]
### Description

`context` would allow values to be implicitly passed to a component's entire subtree.

Given **`<parent>`**:
```marko
class {
  onCreate() {
    this.state = { message: 'Hello' };
    this.context = {
      setMessage: (message) => this.state.message = message
    };
  }
}

<child/>
<div.message>${state.message}</div>
```

**`<child>`**:
```marko
<grand-child/>
```

**`<grand-child>`**:
```marko
<great-grand-child/>
```

and **`<great-grand-child>`**:
```marko
class {
  updateMessage(event) {
    this.context.setMessage(e.target.value);
  }
}
<input on-input('updateMessage') />
```

Typing in the `<great-grand-child>` would cause the message in `<parent>` to update.

### Why

This is most useful to create components that work in concert with each other, but don't require an explicit wiring up from the user of the component.  

### Possible Implementation & Open Questions

@patrick-steele-idem  suggested using `Object.create` to create a prototype chain

It might be good to add a warning or totally prevent a context value being accessed by a component outside the same package where it was defined.  A component might put some value into context, but those values should only be available to other components in the same package.  They would not be available to an application or any other package which uses components that package.

**Comment by rubennorte** [comment]
I was about to open an issue asking to rename `out.global` as `context` so it would use a naming closer to other frameworks (React) and easier to understand when reading templates, so a big +1 to this.

**Comment by DylanPiercey** [comment]
This is now possible with https://github.com/marko-js/tags/tree/master/tags/context
