### ISSUE TITLE
How to upload assets for a component to a cdn

### ISSUE THREAD

**Issue by mauricionr** [marko-js/marko#885]
I'm using markojs components and i would like to upload the assets for each component to a cdn.

How to do it?

Thanks!

**Comment by jasonmacdonald** [comment]
Are you using a build pipeline like Webpack or Lasso? I imagine the solution will be highly dependent on which of those you are using to compile your JS. If this is purely server-side, then you will likely need to build an asset pipeline pass in (probably via the global `out` variable) to access the proper hostname for your assets.

**Comment by patrick-steele-idem** [comment]
Typically, once you run a build (either using Webpack or Lasso) you will get an output `static/` directory. You can then manually copy that directory to your CDN. At eBay we do it differently, during the Lasso build we use a Lasso plugin to automatically upload the files to our "Resource Server" that backs our CDN. See: https://github.com/lasso-js/lasso/issues/90

Is that what you are looking for?

**Comment by FiW** [comment]
You can see my fix for prefixUrl.
https://github.com/lasso-js/lasso/pull/241
Now urlPrefix can be full url (like cdn source)

**Comment by DylanPiercey** [comment]
I believe @patrick-steele-idem and @FiW have answered your question so I am going to close this for now. Feel free to leave another comment or ask us in the Gitter chat otherwise!
