### ISSUE TITLE
Use Angular 2 Template Syntax

### ISSUE THREAD

**Issue by aaronshaf** [marko-js/marko#89]
I suggest a new major version which uses Angular 2's new template syntax. Like Marko, this extends HTML well. I think this would quickly attract a wide set of people to the project!

**Comment by patrick-steele-idem** [comment]
Hi @aaronshaf, can you please be more specific on which aspects of the Angular 2 syntax interest you? Some of the syntax is related to event binding, one-way versus two-way data-binding, etc.

On a related note, this has been discussed in a few other issues, but longer term we are thinking about replacing the HTML parser with a new parser that can recognize types of attributes. With an HTML parser every attribute is a string regardless if it is quoted or not. Here's what we are thinking:

```xml
<my-component number=1/>
<my-component expression=(a + b)/>
<my-component string="hello"/>
<my-component string-concatenated=("hello"+a)/>
<my-component boolean=true/>
``` 

Thoughts?

**Comment by patrick-steele-idem** [comment]
Hi @aaronshaf, I decided to create a more formal proposal for introducing typed attributes. Please take a look at the following and provide feedback if you get a chance: https://github.com/raptorjs/marko/issues/90

**Comment by patrick-steele-idem** [comment]
Closing this issue in favor of the proposal for #90. We want to make Marko a more powerful blend of JavaScript and HTML by adopting JavaScript as the type for all HTML attributes.
