### ISSUE TITLE
Can not get "DOM element" or "id" in some case by getEl('xxx') and getElId('xxx')

### ISSUE THREAD

**Issue by wujjpp** [marko-js/marko#898]
### Details
![image](https://user-images.githubusercontent.com/14068989/31700020-234b2a9e-b3f9-11e7-9c43-f802635497b2.png)

Set key attribute on custom component with `<include>` tag, it will cause `getEl()` and `getElId()` return `undefiend`

Set key attribute on custom component without `<include>` tag, it will cause `getEl()` return `undefiend`

[src/routes/app/index.marko](https://github.com/wujjpp/isomorphic-marko/blob/issue-getEl/src/routes/issue-getEl/components/app/index.marko#L1-L13)

[src/routes/app/component.js](https://github.com/wujjpp/isomorphic-marko/blob/issue-getEl/src/routes/issue-getEl/components/app/component.js#L5-L34)

[src/routes/app-container/index.marko](https://github.com/wujjpp/isomorphic-marko/blob/issue-getEl/src/routes/issue-getEl/components/app-container/index.marko#L1-L3)

[src/routes/app-container/component.js](https://github.com/wujjpp/isomorphic-marko/blob/issue-getEl/src/routes/issue-getEl/components/app-container/component.js#L1-L5)

[src/routes/app-other/index.marko](https://github.com/wujjpp/isomorphic-marko/blob/issue-getEl/src/routes/issue-getEl/components/app-other/index.marko#L1-L3)

[src/routes/app-other/component.js](https://github.com/wujjpp/isomorphic-marko/blob/issue-getEl/src/routes/issue-getEl/components/app-other/component.js#L1-L5)

### Steps to Reproduce
You can verify this issue by checkout "issue-getEl" branch on [this repo](https://github.com/wujjpp/isomorphic-marko)

Maybe, it is similar to [#892](https://github.com/marko-js/marko/issues/892)

**Comment by patrick-steele-idem** [comment]
@wujjpp Does the following comment added to #892 resolve this issue?: https://github.com/marko-js/marko/issues/892#issuecomment-337774199

**Comment by wujjpp** [comment]
@patrick-steele-idem Thanks for your reply and it resolve this issue
Perfect design, it make more clear between component and element
Because of missing  change log and update marko to 4.5.1 directly, it cause some functions of our [main website](https://www.qixin.com) down.  Anyway I have fixed them.
Thanks again. 
BTW, please take note on [issue #897], I think “id” attr of DOM is necessary in some cases
