### ISSUE TITLE
Many "unexpected identifier" renderer errors don't print the identifier

### ISSUE THREAD

**Issue by brandones** [marko-js/marko#901]
### Details

I'm trying to debug javascript in my marko templates. Where node yields
```
> check = {
... foo: 'bar'
... baz: 'qux'
baz: 'qux'
^^^

SyntaxError: Unexpected identifier
```

The same error in a marko template yields

```
[marko-starter marko-starter-demo] Error building page /hello/:name. Error: Error: Render error. Exception: Error: An error occurred while trying to compile template at path "/Users/bistenes/Code/marko-starter-test/src/routes/hello/components/stop-watch/index.marko". Error(s) in template:
1) [src/routes/hello/components/stop-watch/index.marko:41:7] Unable to parse JavaScript for component class. Error: Line 41: Unexpected identifier

    at handleErrors (/Users/bistenes/Code/marko-starter-test/node_modules/marko/src/compiler/Compiler.js:82:21)
```

Where I've added
```
38   check() {
39     this.setState({
40       foo: 'bar'
41       baz: 'qux'
42     })
43   }
44 }
```

to `src/routes/hello/components/stop-watch/index.marko` after running `marko create`.

### Expected Behavior

"Unexpected identifier" errors should print the identifier.

### Actual Behavior

You sort of have to go off the line number it gives you, which seems to work in the default `marko-starter` app (the error above is indeed on line 41), as well as in my marko-express based app, but is broken in my actual marko-starter based app, where it shows `Error: Line 24: Unexpected identifier` for an error occurring on line 27-28. This makes debugging very challenging.

### Your Environment

* Environment name and version (e.g. Chrome 39, node.js 5.4): Node 8.6.0
* Operating System and version (desktop or mobile): MacOS 10.12.6
* Link to your project: https://github.com/brandones/marko-unexpected-identifier-bug

### Steps to Reproduce

See the above link.

### Stack Trace

</details>

**Comment by DylanPiercey** [comment]
This is definitely something I'd like to see as well. Although we currently don't have the bandwidth to tackle this we will keep this in mind. Another thing we'd like to see is [source maps](https://github.com/marko-js/marko/issues/868) and I feel that we would tackle these in tandem.

If you are interesting in adding this feature please don't hesitate to reach out as we'd be happy to help.

**Comment by DylanPiercey** [comment]
This is fixed with Marko 5
