### ISSUE TITLE
Question: Is there any way to use marko input validation programmatically?

### ISSUE THREAD

**Issue by jlopezxs** [marko-js/marko#905]
## Questions
I'm creating a small library of components and I want validation, cast and restricted values but I didn't found a nice way to do that.
Now in marko to validate input parameters I only found one method and is create an `marko.json` or `marko-tag.json`, exist other programmatic method?
And for restricted values there are any good practice or approach in Marko?

### Example of marko-tag.json
```
{
  "@style": "string",
  "@alignment": "string",
  "@style": "string",
  "@class": "string",
  "@tabs <tab>[]": {
    "@label": "string"
  }
}
```

Thanks!

**Comment by DylanPiercey** [comment]
Unfortunately right now there is no programatic way to do this and what you have done is correct. In the future we may toy around with allowing for types using flow and typescript within Marko components which I think would be a good solution here. We are a ways out from doing that but it is something that is on our radar with a potential future switch to Babylon as our js parser.

Future progress toward this will be tracked here https://github.com/marko-js/marko/issues/325

Thanks for creating the issue, feel free to ping me on Gitter or comment back if you have any other questions or concerns.
