### ISSUE TITLE
Changing state does not re-render loop

### ISSUE THREAD

**Issue by cmcarey** [marko-js/marko#907]
### Marko Version: x.x.x
4.5.4

### Details
Changing something within an object in a state does not cause it to re-render a loop that uses that variable from the state.

### Expected Behavior
My state is represented as:
```
state = {
  todos: [
    {
      done: false
    }
  ]
}
```
I would expect that modfying the done boolean through `this.state.todos[0].done = true;` would cause the for loop to re-render, as within it that boolean is called.

### Actual Behavior
It is not re-rendered.

### Your Environment
* Environment name and version (e.g. Chrome 39, node.js 5.4): Chrome 61.0.3163.100
* Operating System and version (desktop or mobile): macOS 10.12.4
* Link to your project: N/A

### Steps to Reproduce

Code:
```marko
class {
  onCreate() {
    this.state = {
      todos: [
        {
          done: false
        }
      ]
    };
  }
  handleCheck(index, e, el) {
    console.log("Checked: " + e.target.checked);
    this.state.todos[index].done = e.target.checked;
  }
}

html
  head
    title -- Loop testing
  body
    div.taskList
      div for(todo in state.todos | status-var=loop)
        $ console.log(todo)
        input type = "checkbox" on-change("handleCheck", loop.getIndex()) checked = todo.done
        p -- Checked: ${todo.done}
```
Run the above marko code, and check the checkbox.  I would expect that it change the text in the `p` tag to true, as well as printing the todo state to the console, and the state of the checkbox.  It prints the state of the checkbox proving that the event handler is called, but that is all.

### Stack Trace

N/A
</details>

**Comment by fogarasyroland** [comment]
Hy!

I think is not a bug. The todos array is a reference and state change not detected automaticly. You can try this:

```marko
handleCheck(index, e, el) {
    console.log("Checked: " + e.target.checked);
    this.state.todos[index].done = e.target.checked;
    this.setStateDirty('todos')
  }
```
More info: [this.state](https://markojs.com/docs/components/#codethisstatecode)

**Comment by DylanPiercey** [comment]
Thanks @fogarasyroland! That is correct, Marko will only determine if the state has changed via a shallow equality check. In this case you have to either explicitly re-assign `state.todos` to a new array by cloning it with `slice` or hint to Marko by using `setStateDirty` which I would recommend for performance.
