### ISSUE TITLE
JavaScript Error on Mobile Docs Site

### ISSUE THREAD

**Issue by eltimn** [marko-js/marko#909]
There's a JavaScript error on the docs site when clicking on the menu dropdown (hamburger icon) when viewed on small screens:

    docs-fcaf4305.js:14 Uncaught TypeError: Cannot read property '0' of null
    at d (docs-fcaf4305.js:14)
    at HTMLBodyElement.<anonymous> (docs-fcaf4305.js:14)

**Comment by austinkelleher** [comment]
Thanks for the report @eltimn. This looks like a bug in Marko. Will investigate.

**Comment by jlopezxs** [comment]
Yes is a bug in marko in the event-delegation component. The bug was added in version  `v4.5.0-beta.0` in `v4.4.28` works well

**Comment by patrick-steele-idem** [comment]
@austinkelleher Will you be publishing the fix?

**Comment by cravindra** [comment]
Hello.
 I'm facing a similar and possibly related issue. Binding an event using on-click throws an error in a component if the component is split component but works as expected if it not split.

Have created a MVP Express + Lasso + Marko app which reproduces this for illustration:
https://github.com/cravindra/marko-error-sample

Using @jlopezxs suggestion to downgrade to `4.4.28` worked but that made other features like using `*:scoped` on attributes stop working.

**Comment by austinkelleher** [comment]
Published `marko@4.5.6` with a fix. Let us know if you see any other issues.

**Comment by austinkelleher** [comment]
Also markojs.com on mobile is also fixed.

**Comment by cravindra** [comment]
Thanks for the quick fix @austinkelleher

**Comment by eltimn** [comment]
Excellent. Thanks.
