### ISSUE TITLE
componentsUtil.___componentLookup in marko/src/components/util.js ??

### ISSUE THREAD

**Issue by XianYeeXing** [marko-js/marko#911]
### Details
in **"marko/src/morphdom/index.js"** : **4**
```
var existingComponentLookup = componentsUtil.___componentLookup;
```
HOWEVER
**There seems NO ___componentLookup being exported from ""marko/src/components/util.js""**
(Perhaps It's just I've missed something ? )
 Any way, which likely causes the error I described in the last issue I opened 2 days ago since in **"marko/src/morphdom/index.js"** : **208**:
```
if ((matchingFromComponent = existingComponentLookup[componentForNode.id]) === undefined){...}
```
if componentsUtil.___componentLookup is not exported from **""marko/src/components/util.js""** then **existingComponentLookup** is **undefined**...

**Comment by austinkelleher** [comment]
Related: https://github.com/marko-js/marko/issues/908

**Comment by DylanPiercey** [comment]
Lets track this with browserify support (if we want to continue to support browserify) in #908.
