### ISSUE TITLE
Component lost the input.renderBody after internal state changed

### ISSUE THREAD

**Issue by fogarasyroland** [marko-js/marko#912]
### Details

I create a simple toggle button component and when active state change, the input.renderBody disappeare

## Context

- `src\routes\test\index.marko`

```marko
html
  head
  body
    toggle-button
      -- button label
```

- `src\components\toggle-button\index.marko`

```marko
class {
  onCreate(){
    this.state = {
      active: false
    }
  }
  toggle(evt){
    this.state.active = !this.state.active
    this.emit('change')
  }
  mousedown(evt){
    evt.preventDefault()
  }
}

div.toggle class={"toggle--active": state.active} onClick('toggle') onMouseDown('mousedown')
  include(input.renderBody)
```

### Expected Behavior

'button label' text stay there

### Actual Behavior

'button label' disappear

<details><summary>Additional Info</summary>

### Your Environment

* Environment name and version: Chrome 61, node v6.2.0
* Operating System and version: Win 10
</details>

**Comment by ovx** [comment]
Hey, any updates on this? It seems like this affects also `input` parameters (passed by <@param> tag) which get lost after state update. Is there a workaround for now?

**Comment by jesse1983** [comment]
Guys, I've a similar problem on another repo (marko-path-router):

https://github.com/charlieduong94/marko-path-router/issues/34

Maybe be same issue. Feel free for download this repo and test it.
