### ISSUE TITLE
Bizarre behavior using both layout and class in a top-level component

### ISSUE THREAD

**Issue by brandones** [marko-js/marko#913]
### Details

I'm trying to use both a layout and a class in a top-level marko component. When I do, I get strange behavior.

I've made a branch off of marko-express that exhibits four related errors (in four different commits, check out each one to take a look), see https://github.com/brandones/marko-express/tree/tlc-class-layout

### Expected Behavior

The top-level component should work like a normal component, as should layout.

### Actual Behavior

When a top-level component has a `class` and uses a layout,
- `out.global` seems to be empty
- layout doesn't receive things on `input`
- other components behave strangely (hard to explain, really... look at 011ff0e30121c4d030963cf985ab47642b0552a0 in the branch, the app-hello component, which appears normal for a moment but then gets its styling removed and becomes unresponsive)
- other incomprehensible errors come up, like `Uncaught Error: Cannot find module "process" from "/browser-refresh-taglib$1.1.0"` (I couldn't reproduce this in my sample, this is something I'm running into in a real project)
  
### Your Environment

* Environment name and version (e.g. Chrome 39, node.js 5.4): Chrome Version 61.0.3163.100 (Official Build) (64-bit)
* Operating System and version (desktop or mobile): MacOS 10.12.6
* Link to your project: https://github.com/brandones/marko-express/tree/tlc-class-layout

**Comment by garajo** [comment]
I think I just experienced the same thing in a `marko-cli` generated project. In my case I added a class definition in generated `src/routes/hello/index.marko`.

```
marko create project
echo -e "class {onMount(){console.log('foo')}}\n$(cat project/src/routes/hello/index.marko)" > project/src/routes/hello/index.marko
cd project/
npm start
```

visit http://localhost:8080/hello/marko , you'll see the styles are broken

**Comment by DylanPiercey** [comment]
This is now supported since #1428.
