### ISSUE TITLE
build script not used.

### ISSUE THREAD

**Issue by DylanPiercey** [marko-js/marko#915]
### Details
Currently the `npm run build` script is never used in the project (usage was removed [here](https://github.com/marko-js/marko/commit/14a0ab150b03282fc2f9e00f0aa97d254d2cb5bd).
Also it appears that the tests directory does not need to be built.

### Possible Fix
Recommend removing the `npm run build` script entirely. Might be worth renaming `npm run build-src` to `npm run build`.

**Comment by austinkelleher** [comment]
@patrick-steele-idem why was the build script execution removed from `test-ci`? If it is truly not needed there is [some code](https://github.com/marko-js/marko/blob/master/scripts/build.js#L43) in the build script that can be removed.
