### ISSUE TITLE
Promise support for lifecycle methods

### ISSUE THREAD

**Issue by bohdyone** [marko-js/marko#922]
### Description

Modify Marko to await (or promise chain) if a Promise is returned from a lifecycle method (e.g. onCreate)

### Why

It's useful to me because I'm loading initial state for my component from an async API and it's most convenient to do that from one of the lifecycle methods before initial rendering occurs. Currently the lifecycle methods don't wait on the promise returned, which means that I get exceptions while rendering because the initial object doesn't have the right "shape". The async tag allows a version of this use case, but it's not designed to populate state so far as I see.

### Possible Implementation & Open Questions

Could be tricky to implement without an async polyfill depending on Marko architecture.

Also worth considering if other such hooks also need to be modified with async support to allow for more flexibility. Some other frameworks like Aurelia already support this kind of use case.

### Is this something you're interested in working on?
Potentially yes, with some guidance.

**Comment by DylanPiercey** [comment]
@bohdyone typically when loading data like this you wan't to show some form of loading indicator instead of blocking the render.

If Marko were to support this feature then anytime a subtree were to be rendered you would effectively be blocking the render.

What I would recommend is using `onCreate` to trigger the data loading but use `state` to track once the loading has completed like so:

```marko
class {
  async onCreate() {
    this.state.loading = true;
    this.state.data = await load('./my-endpoint');
    this.state.loading = false;
  }
}

<div>
</div>
```

**Comment by bohdyone** [comment]
Hi,

It's not server-side, but the API I'm loading from is on local storage, so no loading indicator is needed. I take your point regarding alternative approaches to implementation, and I think it's right 99% of the time, but perhaps it's worth considering if there are some other use cases where this idea would make sense.

**Comment by ianvonholt** [comment]
@bohdyone 

If I understand correctly, you ware wanting to initialize state variables before the component is mounted in the browser, correct?

If so, you can still do this, but you're going to want to do it in the onRender() or onMount() functions to access the `window.localStorage` variable. 

`onCreate` will serialize the state variables on the server, so you have to create an empty object to store your live state objects.

```
class {
  onCreate (input) {
    console.log('onCreate Component')
    this.state = {
      localStorage: {},
      liveState: {}
    }
    this.intialLoad = false
  }

  async onRender (out) {
    // out.___document will only exist in the browser, otherwise the first initial render is on the server.
    if (out.hasOwnProperty('___document') && !this.initialLoad) {
      // This will render only in the browser
      await this.timeout(5000)
      this.state.localStorage = window.localStorage
      this.state.liveState = {
        one: 'one',
        two: 'two',
        three: 'three'
      }
      this.initialLoad = true
    }
    console.log('onRender Component')
  }

  timeout (ms) {
    return new Promise(resolve => setTimeout(resolve, ms));
  }

  onMount () {
    console.log('onMount Button Component')
    console.log(this.state.liveState)
  }
}

<div>
  Component
  $ var nState = state.liveState
  <if(nState.one)>
    ${nState.one}
  </if>
  <if(nState.two)>
    ${nState.two}
  </if>
</div>
```

If you test the above component, you'll see the `onRender()` function stall for 5 seconds, in newer browsers that support async await, and the `onMount()` function complete. After 5 seconds, the data loads and is displayed on the browser after the state has changed. 

This will allow you to write components that have a default loading state and transition into a fully loaded component. 

If you have a complex structure in a component, make sure that you use the `component.setStateDirty' function to update the component.

**Comment by DylanPiercey** [comment]
@bohdyone going to close this for now because of the ramifications of allowing for these async life cycle events. Feel free to ping me in Gitter or comment back if you have any other questions/concerns.
