### ISSUE TITLE
[Question] Is there a way to turn off escape?

### ISSUE THREAD

**Issue by dinfer** [marko-js/marko#928]
### Description
Is there a way to turn off escape? I just want to inflate some generated html code into the template. By the way, I'm using Node.js.

### Why
In some case. for example, generating markdown and transform it into html, insert the html into a template without escaping is necessary.

### Possible Implementation & Open Questions
Add an option "autoEscape" to turn on/off escape. By default, it should be true to keep compatible

**Comment by ianvonholt** [comment]
This already exists. See: https://markojs.com/docs/syntax/#text-replacement

You can use the following in your Marko templates:

```$!{htmlContent}```

**Comment by dinfer** [comment]
Thanks.
