### ISSUE TITLE
Compiler skip doctype element for client templates

### ISSUE THREAD

**Issue by westtrade** [marko-js/marko#930]
### Details

Compiler skip doctype element for client templates

**Template**

```html
<!DOCTYPE html>
<html lang="${ component.language }">
	<head>
		<title>${ component.title }</title>
	</head>
</html>
```

**Client template**
```js
 var data = input;
/// It started from html tag
  out.be("HTML", {
      lang: marko_str(component.language)
    }, "0", component);

  out.be("HEAD", null, "1", component);

  out.e("TITLE", null, "2", component, 1)
    .t(component.title);

  out.n(marko_node0, component);
```

I'm not sure that this is an important bug, but, as i think, there is may cause of  mismatching between the DOM tree and the virtual tree of component.

**Comment by DylanPiercey** [comment]
@westtrade it is not possible to change the DOCTYPE in the browser. This is why we are not representing it in the vdom. If you wish to diff the entire page you would render against `document.documentElement`.
