### ISSUE TITLE
Input field loses focus on input when wrapped in a layout

### ISSUE THREAD

**Issue by Hafas** [marko-js/marko#938]
### Details
When putting an `input` element in a layout component (e.g. with `include`) and updating the state `on-input`, the `input`-Element loses focus each time.

### Expected Behavior
The `input`-Element shouldn't lose focus `on-input`. (see https://hafas.github.io/marko-input-bug/dist/ok-example.html - Example does not use a layout.)

### Actual Behavior
The `input`-Element loses focus (see https://hafas.github.io/marko-input-bug/dist/not-ok-example.html)

### Steps to Reproduce
Source to the examples, here: https://github.com/Hafas/marko-input-bug

**Comment by DylanPiercey** [comment]
This was patched in #966.
