### ISSUE TITLE
Diff trying to remove last child in multi root components twice.

### ISSUE THREAD

**Issue by DylanPiercey** [marko-js/marko#939]
### Marko Version: x.x.x
4.6.0

### Details
Error when diffing while using multiple top level elements.

### Expected Behavior
The diff would succeed.

### Actual Behavior
The diffing algorithm can cause a node to be removed twice. Once by the component when it is [destroyed](https://github.com/marko-js/marko/blob/c9e7410ae1be142ed5b20a20f094c748135061b6/src/components/Component.js#L256) and again by morphdom [when it removes all detached nodes](https://github.com/marko-js/marko/blob/c9e7410ae1be142ed5b20a20f094c748135061b6/src/morphdom/index.js#L538).

This causes an error because we can't remove an element from the DOM twice.

### Possible Fix
Check to see if the element has been removed by the component before morphdom attempts to remove it.

Here is [the pr](https://github.com/marko-js/marko/pull/940) to resolve the issue.

**Comment by austinkelleher** [comment]
Fixed in `marko@4.7.1`
