### ISSUE TITLE
Conditional component rendering

### ISSUE THREAD

**Issue by ovidius72** [marko-js/marko#941]
Is it possible to render components conditionally and send down to the browser only the needed js code?
Suppose I have some components that only an administrator can see and interact with, i would like to do like so:

```js
//Server:

const indexTemplate = require('./index.marko');

let components= [];

app.get('/', (req, res) => {
  if(admin) {
     components.push(require('../my-component1'))
     components.push(require('../my-component2'))
  }
  data = {
    name: 'test',
    components,
  }
  res.marko(indexTemplate, data);
});  
```

```marko
//index.marko (indexTemplate)

<lasso-page/>
......
<body>
  <p>Test</p>
  <div if(data.components && data.components.length)>
    <div for(component in data.components)>
      <include(component)/>
    </div>
  </div>
</body>
```

I'm not sure if that's possible but the the above code is not working. If, instead of an array I send a single component it is rendered but the javascript code is not available.

**Comment by DylanPiercey** [comment]
@ovidius72 sorry for the late reply.

You have two options as far as I am aware:

1. You can send both templates down to the client and conditionally render them manually. (Require the templates in your index.marko).
2. You can do what you are doing now and programmatically add the correct components in the `dependencies` attribute of [lasso-page](https://github.com/lasso-js/lasso-marko-taglib#lasso-page) (probably what you were going for).
