### ISSUE TITLE
Is it possible to use Quasar Framework with MarkoJS?

### ISSUE THREAD

**Issue by paritosh149** [marko-js/marko#948]
I have used Quasar Framework with VueJS. I wish to use it with MarkoJS. Is it possible to use Quasar Framework with MarkoJS?

**Comment by MaxMilton** [comment]
Quasar is specific to Vue, so no you can't use it directly.

At this point in time there is no Vue single file components to Marko converter/compatability layer so there's no _easy_ way of loading vue components in Marko. That said the initial structure of Quasar is somewhat simple so you could port it to Marko if you so wish. A Vue to Marko component converter would be a cool thing too :wink:

**Comment by DylanPiercey** [comment]
I haven't taken a deep look at Quasar Framework however it looks like @MaxMilton is correct.
Closing this issue for now. Thanks!
