### ISSUE TITLE
Lose rendered elements when calling setStateDirty()

### ISSUE THREAD

**Issue by neunygph** [marko-js/marko#952]
I have a component with a list of images inside, in version 4.2.8 and below, when calling setStateDirty() it updated the image list by adding more element to the list and still keep rendered html inside element with "no-update" tag. When I updated to version 4.7.1 and above, I lost all rendered html inside element with "no-update" tag when calling setStateDirty(). I have  lasso v2.11.21 and lasso-marko v2.4.0.
For example I have the below template.
```
<for(item in data.folders.data)>
      <div id="item.id" no-update>
             <a href=""><img  src=//test.png></a>
      </div>
</for>
```
------rendered html before calling setStateDirty()
```
<div id="img1" >
       <a href=""><img src=//test1.png></a>
</div>
<div id="img2" >
       <a href=""><img  src=//test2.png></a>
</div>
```

-----rendered html after calling setStateDirty() in marko version 4.2.8
```
<div id="img1" >
       <a href=""><img  src=//test1.png></a>
</div>
<div id="img2" >
       <a href=""><img src=//test2.png></a>
</div>
<div id="img3" >
       <a href=""><img  src=//test3.png></a>
</div>
```
-----rendered html after calling setStateDirty() in marko version 4.7.1 and above
```
<div id="img1" >
     //empty here
</div>
<div id="img2" >
   //empty here
</div>
<div id="img3" >
       <a href=""><img  src=//test3.png></a>
</div>
```

In my component.js I have

```
module.exports = {
    onInput(input) {
        this.state = {
            count: input.count || 0,
            items: input.folders.data,
        };
    },

    onMount() {
        var widget = this;
        window.fetchUpdate = function fetchUpdate(data){
            if(data === undefined) return;
            data.data.forEach(function(item){
                widget.state.items.push(item)
            });
            widget.setStateDirty();
        };
    },

    onUpdate() {
        console.log('on update');
    },
};
```
Thank you !!!!

**Comment by austinkelleher** [comment]
@neunygph Can you try downgrading to `^4.4`? I'm pretty sure that this broke in 4.5. Thanks!

**Comment by neunygph** [comment]
Hi @austinkelleher ,

I keep having error on first page load with version > 4.2.8 and < 4.7.x
```
events.js:141
      throw er; // Unhandled 'error' event
      ^

Error: Render async fragment error (lasso-slot:body). Exception: Error: Async fragment (lasso-slot:body) timed out after 30000ms
    at null._onTimeout (/home/ubuntu/workspace/node_modules/marko/src/runtime/html/AsyncStream.js:173:32)
    at Timer.listOnTimeout (timers.js:92:15)
    at AsyncStream.error (/home/ubuntu/workspace/node_modules/marko/src/runtime/html/AsyncStream.js:411:13)
    at null.<anonymous> (/home/ubuntu/workspace/node_modules/marko/src/runtime/html/AsyncStream.js:173:26)
    at Timer.listOnTimeout (timers.js:92:15)
```
Thanks,

Phuong

**Comment by neunygph** [comment]
Hi @austinkelleher,

Any suggestion which version of marko, lasso and lasso-marko are stable and no setStateDirty bug.

Thanks,

**Comment by DylanPiercey** [comment]
@neunygph for now I would use `marko@4.4.28` and `lasso-marko@2.3.0`. I hope to have a fix for this and a couple other diffing bugs soon. Thanks for your patience!

**Comment by neunygph** [comment]
Thanks @DylanPiercey for looking into this, what about lasso, is there a specific version that I should use or the latest one should be fine ?

**Comment by DylanPiercey** [comment]
@neunygph the latest version of lasso should be fine to my knowledge.

**Comment by neunygph** [comment]
Oh ok, thanks Dylan.

Phuong Nguyen

**Comment by neunygph** [comment]
Hi, any update on this bug ?

Thanks,
