### ISSUE TITLE
Marko roadmap to native esmodules in Node

### ISSUE THREAD

**Issue by tinovyatkin** [marko-js/marko#953]
Current LTS version of Node is supporting es-modules loading with `--experimental-modules` flag and `.mjs` extension.
Marko since `4.x` is supporting a pseudo syntax of `import`, that converts in _very very old_ `var c = require`.
What is roadmap / strategy to start supporting ES modules and where that may happen?
At the moment, playing with something like:
```js
static {
  import { asset } from '../../../../shared/marko/asset'
  import { getFilteredOptions, stipOptionsStrings } from '../../../../data/helpers/transfer-options'
}
```
results in `.marko.js` file (that may not load modules due to different extension) like:
```js
// Compiled using marko@4.7.4 - DO NOT EDIT
"use strict";

var marko_template = module.exports = require("marko/src/html").t(__filename),
    marko_componentType = "/transfers.do$4.16.0/src/marko/inc/book-private/BookOptions.marko",
    components_helpers = require("marko/src/components/helpers"),
    marko_renderer = components_helpers.r,
    marko_defineComponent = components_helpers.c,
    marko_helpers = require("marko/src/runtime/html/helpers"),
    marko_str = marko_helpers.s,
    marko_forEachProp = require("marko/src/runtime/helper-forEachProperty"),
    marko_escapeXml = marko_helpers.x,
    marko_attr = marko_helpers.a,
    marko_classAttr = marko_helpers.ca;

import { asset } from '../../../../shared/marko/asset'
import { getFilteredOptions, stipOptionsStrings } from '../../../../data/helpers/transfer-options';
```
What is invalid due to `var` declaration above `import` and wrong extension.

Do you guys have a plan for "new" language feature or you will stick with Node 4.x / IE 9.x?

**Comment by tinovyatkin** [comment]
My proposal is - Marko may detect `--experimental-modules` in place and keep `import` as import and product `.marko.mjs` instead of `.js`.
Lovers of *latest and greatest* (as myself) will love you!

**Comment by tinovyatkin** [comment]
Producing `.mjs` will certainly be a good opportunity to start using `const`, real `await`, etc.

**Comment by tinovyatkin** [comment]
Sync feature detection is pretty straightforward too:

```js
const { NODE_OPTIONS = '' } = process.env;
console.log(
  'ES Modules supported:',
  [NODE_OPTIONS.split(/\s/), ...process.execArgv].includes(
    '--experimental-modules',
  ),
);
```

**Comment by DylanPiercey** [comment]
@tinovyatkin I agree this would be nice to have. Our team doesn't currently have the bandwidth to execute however we would be more than willing to provide support to anyone interested in implementing this feature.

Thanks for creating this issue, we'll be sure to track any progress here.

**Comment by DylanPiercey** [comment]
@tinovyatkin we are currently working switching our compiler to use babel which will come with this (and many other features) for free.

Going to close this issue as we are not likely to add this to the current v4 compiler.
