### ISSUE TITLE
Descriptions of Types in marko-tag.json Are Needed

### ISSUE THREAD

**Issue by oldcai** [marko-js/marko#962]
### Description
There are some advanced type definitions in the `marko-tag.josn` such as `"@checkboxes <checkbox>[]": {...}`, which I learned from [here](https://github.com/gunjam/govuk-elements-marko/blob/master/components/gov-checkboxes/marko-tag.json) without document.

### Why
Honest to say, it's very hard to find information about how to build reusable components (children tags or tag libs as you might call) when implementing UI components.
That might be a big reason why there aren't many component libraries for marko.
And in my option, it's thoughtful to put the descriptions of symbols into the documents, as they are not easy to search.

### Possible Implementation & Open Questions
Please give some documents about the marko-tag.json and more examples about making reusable components.

### Is this something you're interested in working on?
Yes, I need to get some more awesomeness from marko and can't find an easy way.

I believe marko would have a bright future and I'm working on a bootstrap UI component library for marko. But I have encountered many difficulties and it's not easy to find solutions.

**Comment by austinkelleher** [comment]
@oldcai I agree that the custom tag documentation is lacking. If you could help improve them, that would be awesome! The file you would want to improve is here: https://github.com/marko-js/marko/blob/master/docs/custom-tags.md

Let us know if you need any pointers. Thanks again.

**Comment by oldcai** [comment]
I'd love to, but I'm just at the very beginning of learning Marko. It would take time to have enough knowledge to document it well, but I'll try.

Could you give me some hints to the questions about @ tag listed in #787

**Comment by tigt** [comment]
It looks like at least some of your questions are now answered in [`marko.json` & `marko-tag.json` § Shorthands](https://markojs.com/docs/marko-json/#shorthands)

**Comment by DylanPiercey** [comment]
I believe the docs now cover all of this material.
