### ISSUE TITLE
template literals not polyifill

### ISSUE THREAD

**Issue by Charlang** [marko-js/marko#965]
## Bug Report
```js
var assignPropsFunction = `
    function ap_(p) {
        var s = document.currentScript;
        Object.assign(s.previousSibling, p);
        s.parentNode.removeChild(s);
    }
`.replace(/\s+/g, ' ').replace(/([\W]) (.)/g, '$1$2').replace(/(.) ([\W])/g, '$1$2').trim();
```

This piece of code was generate directly into output, and make IE not working

### Possible Fix

<details><summary>Additional Info</summary>

### Your Environment

* Environment name and version (e.g. Chrome 39, node.js 5.4):
* Operating System and version (desktop or mobile):
* Link to your project:

### Steps to Reproduce

1. 
2. 
3. 
4. 

### Stack Trace

</details>

**Comment by austinkelleher** [comment]
@Charlang Thanks for the report. This is a bug and I should have a fix up sometime this morning.

**Comment by austinkelleher** [comment]
@Charlang After looking at the code a bit more, I have a few questions:

1. Did you mean that `Object.assign` was getting sent down to the browser (not template literals)?

2. This code should only get sent to the browser if you're using a `html-element.json` to define an [HTML Custom Element](https://developer.mozilla.org/en-US/docs/Web/Web_Components/Custom_Elements). If so, custom elements are only supported in modern browsers, which also would include template literal support and `Object.assign` support. Are you using HTML Custom Elements?

Could you also send me an example of a component that is sending this code to the browser?

Thanks!

**Comment by Charlang** [comment]
For your question No.1,  looks like it's template literals issue: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Template_literals
For question No.2,  below is the generated code, looks like we are not using  HTML Custom Elements:
/**
 * Internal helper method to insert a script tag that assigns properties
 * to the dom node the precede it.
 */
var escapeScript = exports.xs;
var assignPropsFunction = `
    function ap_(p) {
        var s = document.currentScript;
        Object.assign(s.previousSibling, p);
        s.parentNode.removeChild(s);
    }
`.replace(/\s+/g, ' ').replace(/([\W]) (.)/g, '$1$2').replace(/(.) ([\W])/g, '$1$2').trim();
exports.p = function propsForPreviousNode(props, out) {
    var cspNonce = out.global.cspNonce;
    var nonceAttr = cspNonce ? ' nonce=' + JSON.stringify(cspNonce) : '';

    out.w('<script' + nonceAttr + '>');

    if (!out.global.assignPropsFunction) {
        out.w(assignPropsFunction);
        out.global.assignPropsFunction = true;
    }

    out.w('ap_(' + escapeScript(JSON.stringify(props)) + ');</script>');
};

**Comment by Charlang** [comment]
Hi Austin,

we just found the root cause, when we implement customer tag and using on UI Component, we have introduce `require('marko/dist/runtime/html/helpers').t; `by mistake, we should using `require('marko/dist/runtime/vdom/helpers').t;` instead.

Thanks.

**Comment by austinkelleher** [comment]
Glad you were able to work it out @Charlang. Let us know if you see any other issues.
