### ISSUE TITLE
Marko should not allow for passing data in string literals unless using template literals

### ISSUE THREAD

**Issue by austinkelleher** [marko-js/marko#970]
Currently in Mark you can do this:

```marko
$ var options = ['a', 'b', 'c']
<my-component options="${input.options}"/>
```

In Marko 5, the above should be treated as a the literal string "${input.options}" unless using template literals with back ticks, in which case the value would be caste to a stiring

```marko
$ var options = ['a', 'b', 'c']
<my-component options=`${input.options}`/>
```

**Comment by DylanPiercey** [comment]
This is now automatically migrated using the `marko migrate` cli command in `marko-cli`.
