### ISSUE TITLE
Is there anyway to log incorrect typing of a custom tag in template? 

### ISSUE THREAD

**Issue by LumpySpace** [marko-js/marko#972]
### Description
  I want that marco says me if I'm typing "<heder/>" instead of "<header/> tag, which I'm use as custom tag in my project and have a component "header.marco" in some directory 

### Why
It will help me to understand where I'm fucked up faster and to fix the bug faster as well 

### Possible Implementation & Open Questions
Something that will check the correct typing of custom tags and log it to the user 

### Is this something you're interested in working on?
Yes

**Comment by mlrawlings** [comment]
I'm not sure I understand what you're asking.  It sound like you're asking either to check attribute types or syntax errors.  Could you give an example template with what you're describing?

Marko already complains about unrecognized tags and syntax errors, but if you're taking about typed attributes that could be worthwhile.  It wouldn't be too hard to do some basic type checking for literal values, but we'd probably want to leverage typescript for anything more than that.  I haven't thought through what that would entail.

**Comment by DylanPiercey** [comment]
For reference here is what @mlrawlings was talking about: https://markojs.com/docs/custom-tags/#markojson-syntax

Closing this issue for now, but feel free to comment back if we've missed something.
