### ISSUE TITLE
compat layer bug with DOM events bound to root element

### ISSUE THREAD

**Issue by yomed** [marko-js/marko#974]
### Details

I am trying to build a component in v3, that will still work in v4. My component has DOM events bound to the root element like so:

```marko
<div w-bind w-on-some-event="handleEvent"/>
```

### Expected Behavior

The rendered HTML should end up with a marko key so that it can have DOM elements attached correctly. As is, this template works in v3, but not v4. If I add a `w-id`, it works in v4, but not v3 (which forbids using both `w-id` and `w-bind` on the same element.

### Actual Behavior

There is a js error in the browser. It fails on this part:
https://github.com/marko-js/marko/blob/eddbaaad86be8859935dfd9598429952c9424703/src/components/init-components-browser.js#L115-L124

The `eventEl` is `undefined` because the element does not have a corresponding key that it's looking for via `___keyedElements`.

<img width="478" alt="screen shot" src="https://user-images.githubusercontent.com/3595986/35069261-881c833c-fb8e-11e7-834c-15fb1aae0410.png">

### Possible Fix

One workaround is to attach the DOM events to an inner element, rather than the root element. However, this might not always be possible.

<details><summary>Additional Info</summary>

### Your Environment

* Environment name and version (e.g. Chrome 39, node.js 5.4):
* Operating System and version (desktop or mobile):

### Steps to Reproduce

1. Create template like above, compile in v4.
2. Check browser console

### Stack Trace

```
Uncaught TypeError: Cannot read property 'addEventListener' of undefined
    at addEventListenerHelper (init-components-browser.js:69)
    at addDOMEventListeners (init-components-browser.js:76)
    at init-components-browser.js:123
    at Array.forEach (<anonymous>)
    at initComponent (init-components-browser.js:115)
    at init-components-browser.js:261
    at Array.forEach (<anonymous>)
    at Object.initServerRendered [as concat] (init-components-browser.js:198)
```
</details>

**Comment by mlrawlings** [comment]
This should be fixed as of `4.9.0`
