### ISSUE TITLE
Add support for nextTick API

### ISSUE THREAD

**Issue by ulivz** [marko-js/marko#978]
## New Feature

Add nextTick API.

### Description

Add a nextTick API so that user can control the dom after setState.

### Why

We usually have a requirement at browser, in some conditions, we need to handle the DOM after changing some statex, such as focusing a input after open a modal. but due to batch update, now the dom would be empty so the code will throw exception.

And I found marko has used `setTimeout`(`src/runtime/nextTick-browser.js`) to exec the state batch update job, but I cannot find any callback after in batchUpdate `src/components/update-manager.js`.

Now I have a simple fix, add a extra flag and handle it with `onUpdate` hook, but this is not a best solution.

### Possible Implementation & Open Questions

At browser, provide a API like `this.nextTick(()=> { })` which will be run after next rendering finished.

### Is this something you're interested in working on?

Yes

**Comment by MaxMilton** [comment]
It would be nice. I find myself using the equvient with Vuejs from time to time.

For reference, here's the Vue implementation: <https://github.com/vuejs/vue/blob/dev/src/core/util/next-tick.js>.
And the Vue API documentation: <https://vuejs.org/v2/api/#Vue-nextTick>.

**Comment by jasonmacdonald** [comment]
Why can't you use the `onUpdate` callback? That is called after an update has happened. Maybe I'm missing something?

**Comment by mlrawlings** [comment]
Would `this.on('update', ()=> { })` do what you need?  Lifecycle events are just like any other event (but the also call methods like `onUpdate` as well).

**Comment by jasonmacdonald** [comment]
Thinking about this a bit more, is it a "global" hook you are looking for as opposed to something that runs at the updated component level like onUpdate?

**Comment by MaxMilton** [comment]
Nice one @mlrawlings ! We now have `once` too, so `this.once('update', ()=> {})` may actually be quite useful. In theory a true `nextTick` method should run the callback as soon possible, but this will just be called somewhere along the chain of other events for `onUpdate`, right?

Marko does have a`nextTick` module internally, so it may be worth exploring that option when necessary. The source is <https://github.com/marko-js/marko/blob/master/src/runtime/nextTick-browser.js>. I havn't tried it but I'm sure it's possible to import.

**Comment by DylanPiercey** [comment]
Using `once('update')` is equivalent to a `nextTick` API that we would expose.
