### ISSUE TITLE
Is there any plan to add support typescrip?

### ISSUE THREAD

**Issue by AlexStacker** [marko-js/marko#983]
### Description

typescript support for variable type development is very good, and `lasso` also supports the transform plugin, can support a single ts file in compontent through plug-in?
```
-|compontent
  |--click-count
       |-- compontent.ts
       |-- index.marko
       |-- style.less
```
Now can support TS in such a form? How to configure it? I think, with `tsc -w` or `tsc -p` to output `js` file is not too troublesome.

**Comment by DylanPiercey** [comment]
@AlexStacker it's definitely something we'd like to add and are tracking it [here](https://github.com/marko-js/marko/issues/325). Currently it is not a high priority though. If you have any further ideas please feel free to comment on #325.
