### ISSUE TITLE
`once` directive

### ISSUE THREAD

**Issue by scttdavs** [marko-js/marko#985]
### Description
Marko already supports the `on-<event>('someHandler')` directive, so also add a once directive: `once-<event>('someHandler')`

### Why
it would be useful in many scenarios where you only want to act on the first event, or you know you will only ever have one event, so remove the listener.

### Is this something you're interested in working on?
Sure

**Comment by austinkelleher** [comment]
I agree that we should implement this. We probably won't get to this right away. It would be great if you could help out!
