### ISSUE TITLE
Question - can no-update be used server side so that client side the DOM remains fixed

### ISSUE THREAD

**Issue by cameronbraid** [marko-js/marko#988]
Id like to implement a transformer or renderer (or both?)  that generates outputs a attribte containing html using out.write on the server but then the DOM is frozen so the client a) doesn't modify the dom, and b) doesn't need the HTML that the server had access to.

The idea in code would look like this :

`<ServerSideHtml html="some html"/>`

I can easily write a transformer like :

```
module.exports = function transform(el, context) {
  var builder = context.builder;
  if (el.hasAttribute("html")) {
    var html = el.getAttributeValue("html").value
    el.removeAttribute("h")
    var htmlNode = builder.htmlLiteral(html)
    el.replaceWith(htmlNode)
  }
}
```

Thinking I could possibly use the no-update attribute, however this means the html literal is now part of the compiled component, and therefore will end up on the client.

Another thought was using a renderer :

```
const onserver = require("onserver") // use package.json to return true for server, false for browser
module.exports = function transform(input, out) {
  if (onserver && input.html) {
    out.write(input.html)
    input.html = null /// remove this from the input object so it is not serialized to the client
  }
}
```

Though this doesn't work because the input is still serialised to the client which I am trying to avoid.

Is there any way ?

Thanks

Cameron

**Comment by cameronbraid** [comment]
I just had a thought... 

Could I generate different code in the transformer for server vs browser... have the server as I have done, and some how make the client version just strip out the html attribute.. But then how could I mark it to preserve the dom ?

**Comment by DylanPiercey** [comment]
`no-update` content is now preserved from server renders.
