### ISSUE TITLE
Add marko support to consolidate.js

### ISSUE THREAD

**Issue by patrick-steele-idem** [marko-js/marko#99]
While [consolidate.js](https://github.com/tj/consolidate.js/) doesn't support streaming, we should still add marko support for better visibility to this project.

I'm requesting help from the community in sending a Pull Request to the [consolidate.js](https://github.com/tj/consolidate.js/) project to add support for the marko template engine. Thanks in advance!

**Comment by seangates** [comment]
Is this all it takes? => https://github.com/tj/consolidate.js/pull/158/files

**Comment by patrick-steele-idem** [comment]
There are two issues with that PR:

- Issue 1) It doesn't cache the loaded template
- Issue 2) Marko needs both the template's source (as a string) and the  template's file system path.

__For issue 1:__ make sure you use the provided cache to cache the loaded marko template: https://github.com/gregwebs/consolidate.js/blob/8592fed81cd4483ff433b3fdc1d5ea190e004097/lib/consolidate.js#L525

__For issue 2:__  I believe the template's file system path is provided as `options.filename` based on the following line:
https://github.com/gregwebs/consolidate.js/blob/8592fed81cd4483ff433b3fdc1d5ea190e004097/lib/consolidate.js#L138

You can then use the marko [`load(templatePath, templateSrc)`](http://markojs.com/docs/marko/javascript-api/#loadtemplatepath-templatesrc-options--template) method to load the template:

```javascript
var template = marko.load(str, options.filename);
```

And then to render the loaded template:

```javascript
template.render(options, fn);
```

I don't like the Express view engine (see [Bypassing Express View Rendering for Speed and Modularity](https://strongloop.com/strongblog/bypassing-express-view-rendering-for-speed-and-modularity/) and I don't like `consolidate.js`, but for visibility to marko it is probably worthwhile to enable marko template rendering via consolidate.js... The biggest downside is that streaming/progressive HTML rendering won't work.

Thanks for looking into it @seangates!

**Comment by patrick-steele-idem** [comment]
See: https://github.com/tj/consolidate.js/pull/255

**Comment by bitinn** [comment]
@patrick-steele-idem Do you happen to know if we can disable cache (aka the generated .js files) when using `consolidate.js`?

I am interested in this because I use marko as a template language for static site generator `metalsmith`, but because marko is smart enough to generate js files, it prevents us from using a watcher to reload template just by running the build process again on template change.

Is there a solution for that?

ref:
- https://github.com/FWeinb/metalsmith-watch

**Comment by patrick-steele-idem** [comment]
@bitinn I've not used `metalsmith`, but loaded `.marko` templates are loaded and cached by the Node.js module loading system the same as normal `.js` modules. That is, they are cached in `require.cache` and deleting from `require.cache` will cause the template to be reloaded on the next `require()` of the template. `metalsmith-watch` supports a `invalidateCache` that might work. 

`marko` also supports a special `hot reload`: https://github.com/marko-js-samples/marko-hot-reload. You'll need to use your own file watcher to tell `marko` when a file is modified and `marko` will ensure that all templates automatically hot reload such that the next time they render they will be render based on the modified source.

Please let me know if you need more details @bitinn.

**Comment by bitinn** [comment]
@patrick-steele-idem Thx I did enable `invalidateCache`, it doesn't appear to find the right js `require.cache` to delete though. I need to figure out [why](https://github.com/FWeinb/metalsmith-watch/issues/36)...

**Comment by mlrawlings** [comment]
Closed via https://github.com/tj/consolidate.js/pull/255. Thanks @fabsrc!
