### ISSUE TITLE
Atom Language Marko Bugs

### ISSUE THREAD

**Issue by Eldar-X** [marko-js/marko#991]
1- In latest version of atom or atom-beta autocompleting of tags not listen of tag changes anymore.
2- When you have multiline js code in .marko files prettyprint adds some extra indentation to this code piece everytime you reformat code.

**Comment by Eldar-X** [comment]
3- Pretty print transforms ...data to ${data} which now deprecated.

**Comment by DylanPiercey** [comment]
@Eldar-X I think these pretty print issues have been fixed in https://github.com/marko-js/marko-prettyprint

If there is still some stuff missing would you mind creating an issue there?

Sorry for taking so long to respond, and thanks for creating the issue!
