### ISSUE TITLE
Tablib loader should throw if marko-tag.json renderer is not found

### ISSUE THREAD

**Issue by mlrawlings** [marko-js/marko#997]
### Details

With a `marko-tag.json` like the following, where the renderer is explicitly set to `index.marko`, if the `.marko` extension is not registered, the file will not be found and there is no error (except any errors caused by the custom tag not being found).
```json
{
   "renderer": "./index"
}
```

### Expected Behavior

The taglib loader should throw if an explicitly referenced file is not found.

### Actual Behavior

Silence

**Comment by tigt** [comment]
I’d like to try and fix this, but I’m curious about where in the Marko toolchain I should do the `fs.exists()` — my first guess is [`src/taglib/taglib-loader/loadTagFromProps.js`’s `renderer()` method](https://github.com/marko-js/marko/blob/ef45f053ef556c0c56f13673b754a19620e427e1/src/taglib/taglib-loader/loadTagFromProps.js#L349)?
